import { lib, game, ui, get, ai, _status } from '../../../../../../noname.js';
export { characterTitle };
var qmsgswkjsgj_span = 'cyber-neon-halo-flow';
// var qmsgswkjsgj_span = 'cyber-neon-text';
// var qmsgswkjsgj_shenci_span = 'champagne-gold-flow-text';
// var qmsgswkjsgj_shenci_span = 'molten-gold-flow-text';
// var qmsgswkjsgj_shenci_span = 'gold-flow-revamped-bright';
var qmsgswkjsgj_shenci_span = 'solid-gold-with-flow-halo';
// var sgsxjxfzmnl_span = 'sgsxjxfzmnl';
const characterTitle = {
	qmsgswkjsgj_re_xizhicai: "<span class = '" + qmsgswkjsgj_span + "'>负俗的夭才</span>",
	qmsgswkjsgj_re_liuxie: "<span class = '" + qmsgswkjsgj_span + "'>受困天子</span>",
	qmsgswkjsgj_shen_zhaoyun: "<span class = '" + qmsgswkjsgj_span + "'>神威如龙</span>",
	// qmsgswkjsgj_gui_xuyou:'<span class = \''+qmsgswkjsgj_span+'\'></span>',
	// qmsgswkjsgj_gui_zhaoyun:'<span class = \''+qmsgswkjsgj_span+'\'></span>',
	// qmsgswkjsgj_gui_sunquan:'<span class = \''+qmsgswkjsgj_span+'\'></span>',
	qmsgswkjsgj_shen_guojia: "<span class = '" + qmsgswkjsgj_span + "'>星月奇佐</span>",
	qmsgswkjsgj_re_sp_duyu: "<span class = '" + qmsgswkjsgj_span + "'>文成武德</span>",
	// qmsgswkjsgj_gui_liubei:'<span class = \''+qmsgswkjsgj_span+'\'></span>',
	qmsgswkjsgj_shen_zhugeliang: "<span class = '" + qmsgswkjsgj_span + "'>赤壁的妖术师</span>",
	// qmsgswkjsgj_gui_re_zhouyu:'<span class = \''+qmsgswkjsgj_span+'\'></span>',
	qmsgswkjsgj_sb_huangzhong: "<span class = '" + qmsgswkjsgj_span + "'>没金铩羽</span>",
	qmsgswkjsgj_re_yangbiao: "<span class = '" + qmsgswkjsgj_span + "'>德彰海内</span>",
	qmsgswkjsgj_re_luotong: "<span class = '" + qmsgswkjsgj_span + "'>力政人臣</span>",
	qmsgswkjsgj_re_liuyan: "<span class = '" + qmsgswkjsgj_span + "'>裂土之宗</span>",
	qmsgswkjsgj_re_lusu: "<span class = '" + qmsgswkjsgj_span + "'>独断的外交家</span>",
	qmsgswkjsgj_re_caorui: "<span class = '" + qmsgswkjsgj_span + "'>天资的明君</span>",
	qmsgswkjsgj_re_caiwenji: "<span class = '" + qmsgswkjsgj_span + "'>异乡的孤女</span>",
	qmsgswkjsgj_re_zhangxiu: "<span class = '" + qmsgswkjsgj_span + "'>北地枪王</span>",
	qmsgswkjsgj_re_fuhuanghou: "<span class = '" + qmsgswkjsgj_span + "'>孤注一掷</span>",
	qmsgswkjsgj_shen_ganning: "<span class = '" + qmsgswkjsgj_span + "'>江表之力牧</span>",
	qmsgswkjsgj_re_sunhanhua: "<span class = '" + qmsgswkjsgj_span + "'>挣绽的青莲</span>",
	qmsgswkjsgj_yingtian_simayi: "<span class = '" + qmsgswkjsgj_span + "'>三狼吞魏</span>",
	qmsgswkjsgj_re_shen_zhaoyun: "<span class = '" + qmsgswkjsgj_span + "'>天龙乘云</span>",

	qmsgswkjsgj_shen_lusu: "<span class = '" + qmsgswkjsgj_span + "'>兴吴之邓禹</span>",
	qmsgswkjsgj_re_sunquan: "<span class = '" + qmsgswkjsgj_span + "'>东吴大帝</span>",
	qmsgswkjsgj_shen_zhouyu: "<span class = '" + qmsgswkjsgj_span + "'>赤壁的火神</span>",
	qmsgswkjsgj_shen_xunyu: "<span class = '" + qmsgswkjsgj_span + "'>洞心先识</span>",
	qmsgswkjsgj_mb_luyusheng: "<span class = '" + qmsgswkjsgj_span + "'>义姑</span>",
	qmsgswkjsgj_shen_luxun: "<span class = '" + qmsgswkjsgj_span + "'>红莲业火</span>",
	qmsgswkjsgj_shen_caocao: "<span class = '" + qmsgswkjsgj_span + "'>超世之英杰</span>",
	qmsgswkjsgj_shen_lvbu: "<span class = '" + qmsgswkjsgj_span + "'>修罗之道</span>",
	qmsgswkjsgj_pot_weiyan: "<span class = '" + qmsgswkjsgj_span + "'>矜忠跨万山</span>",
	qmsgswkjsgj_pot_taishici: "<span class = '" + qmsgswkjsgj_span + "'>志踏天阶</span>",
	qmsgswkjsgj_re_caopi: "<span class = '" + qmsgswkjsgj_span + "'>霸业的继承者</span>",
	qmsgswkjsgj_re_shamoke: "<span class = '" + qmsgswkjsgj_span + "'>五奚蛮夷</span>",
	qmsgswkjsgj_re_peixiu: "<span class = '" + qmsgswkjsgj_span + "'>晋图开秘</span>",
	qmsgswkjsgj_re_shichangshi: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_zhangrang: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_zhaozhong: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_sunzhang: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_bilan: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_xiayun: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_hankui: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_lisong: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_duangui: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_guosheng: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_scs_gaowang: "<span class = '" + qmsgswkjsgj_span + "'>祸乱纲常</span>",
	qmsgswkjsgj_re_jushou: "<span class = '" + qmsgswkjsgj_span + "'>监军谋国</span>",
	qmsgswkjsgj_shen_huatuo: "<span class = '" + qmsgswkjsgj_span + "'>悬壶济世</span>",
	qmsgswkjsgj_pot_yuji: "<span class = '" + qmsgswkjsgj_span + "'>夙仙望道</span>",
	qmsgswkjsgj_re_mb_caomao: "<span class = '" + qmsgswkjsgj_span + "'>向死存魏</span>",
	qmsgswkjsgj_mengpo: "<span class = '" + qmsgswkjsgj_span + "'>忘川难断</span>",
	qmsgswkjsgj_shen_sunce: "<span class = '" + qmsgswkjsgj_span + "'>踞江鬼雄</span>",

	qmsgswkjsgj_mb_sunluyu: "<span class = '" + qmsgswkjsgj_span + "'>舍身饲虎</span>",
	qmsgswkjsgj_re_mb_zhangzhi: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_shen_taishici: "<span class = '" + qmsgswkjsgj_span + "'>义信天武</span>",
	qmsgswkjsgj_yanxiang: "<span class = '" + qmsgswkjsgj_span + "'>明尚夙达</span>",

	qmsgswkjsgj_re_zhangxuan: "<span class = '" + qmsgswkjsgj_span + "'>玉宇嫁蔷</span>",
	qmsgswkjsgj_re_chenshi: "<span class = '" + qmsgswkjsgj_span + "'>裨将可期</span>",
	qmsgswkjsgj_re_dc_tengfanglan: "<span class = '" + qmsgswkjsgj_span + "'>铃兰零落</span>",
	qmsgswkjsgj_re_zhenghun: "<span class = '" + qmsgswkjsgj_span + "'>民安寇灭</span>",
	qmsgswkjsgj_re_re_liuzan: "<span class = '" + qmsgswkjsgj_span + "'>啸天亢声</span>",
	qmsgswkjsgj_re_wupu: "<span class = '" + qmsgswkjsgj_span + "'>健体养魄</span>",
	qmsgswkjsgj_re_ruanyu: "<span class = '" + qmsgswkjsgj_span + "'>清谈高论</span>",
	qmsgswkjsgj_re_dc_duyu: "<span class = '" + qmsgswkjsgj_span + "'>文成武德</span>",
	qmsgswkjsgj_re_star_caoren: "<span class = '" + qmsgswkjsgj_span + "'>伏波四方</span>",
	qmsgswkjsgj_re_dc_xiahouhui: "<span class = '" + qmsgswkjsgj_span + "'>雅有识度</span>",
	qmsgswkjsgj_re_panghong: "<span class = '" + qmsgswkjsgj_span + "'>针砭时弊</span>",
	qmsgswkjsgj_re_zhujianping: "<span class = '" + qmsgswkjsgj_span + "'>识面知秋</span>",
	qmsgswkjsgj_re_guotiying: "<span class = '" + qmsgswkjsgj_span + "'>逆运定势</span>",
	qmsgswkjsgj_re_caofang: "<span class = '" + qmsgswkjsgj_span + "'>迷瞑终觉</span>",
	qmsgswkjsgj_re_guozhao: "<span class = '" + qmsgswkjsgj_span + "'>碧海青天</span>",
	qmsgswkjsgj_re_caomao: "<span class = '" + qmsgswkjsgj_span + "'>霸业的终耀</span>",

	// 后续批次（新增，称号待补充）
	qmsgswkjsgj_re_yue_caiwenji: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_dc_liuba: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_zhugejin: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_yuanyin: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_sp_zhenji: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_liushan: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_caojinyu: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_yue_zhouyu: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_bolingyun: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_v_zhangliao: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_sb_simayi: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_guanning: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_pangfengyi: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_guanyu: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_machao: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_xusheng: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_pot_guoyuan: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_pot_xinxianying: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_pot_dongzhao: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_simahui: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_o_sunquan: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_jsrg_guozhao: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_re_wn_zhanghe: "<span class = '" + qmsgswkjsgj_span + "'></span>",

	// 神批次（新增，称号待补充）
	qmsgswkjsgj_shen_pangtong: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_shen_zhangliao: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_shen_liubei: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_shen_guanyu: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_shen_lvmeng: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_mb_shen_jiangwei: "<span class = '" + qmsgswkjsgj_span + "'></span>",

	// plus 批次（新增，称号待补充）
	qmsgswkjsgj_plus_shen_guojia: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_plusplus_shen_guojia: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_plus_shen_xunyu: "<span class = '" + qmsgswkjsgj_span + "'></span>",
	qmsgswkjsgj_plus_shen_zhouyu: "<span class = '" + qmsgswkjsgj_span + "'></span>",

	qmsgswkjsgj_shenci_wu_zhugeliang: "<span class = '" + qmsgswkjsgj_shenci_span + "'>忠武良弼</span>",
	qmsgswkjsgj_shenci_re_duyu: "<span class = '" + qmsgswkjsgj_shenci_span + "'>文成武德</span>",
	qmsgswkjsgj_shenci_wu_luxun: "<span class = '" + qmsgswkjsgj_shenci_span + "'>释武怀儒</span>",
	qmsgswkjsgj_shenci_sb_caopi: "<span class = '" + qmsgswkjsgj_shenci_span + "'>魏文帝</span>",
	qmsgswkjsgj_shenci_re_sunhanhua: "<span class = '" + qmsgswkjsgj_shenci_span + "'>威灵尽显</span>",
	qmsgswkjsgj_shenci_dc_zhouxuān: "<span class = '" + qmsgswkjsgj_shenci_span + "'>夜华青乌</span>",
	qmsgswkjsgj_shenci_caomao: "<span class = '" + qmsgswkjsgj_shenci_span + "'>霸业的终耀</span>",
	qmsgswkjsgj_shenci_pot_yuji: "<span class = '" + qmsgswkjsgj_shenci_span + "'>夙仙望道</span>",

	// 神赐批次（新增，称号待补充）
	qmsgswkjsgj_shenci_wu_huangfusong: "<span class = '" + qmsgswkjsgj_shenci_span + "'></span>",
	qmsgswkjsgj_shenci_wu_guanyu: "<span class = '" + qmsgswkjsgj_shenci_span + "'></span>",
	qmsgswkjsgj_shenci_bolingyun: "<span class = '" + qmsgswkjsgj_shenci_span + "'></span>",
	qmsgswkjsgj_shenci_simahui: "<span class = '" + qmsgswkjsgj_shenci_span + "'></span>",
	qmsgswkjsgj_shenci_eu_kaisa: "<span class = '" + qmsgswkjsgj_shenci_span + "'></span>",

};
