import { lib, game, ui, get, ai, _status } from '../../../../../../noname.js';
export { character };

/** @type { importCharacterConfig['character'] } */
const character = {


	qmsgswkjsgj_re_xizhicai: ['male', 'wei', 3, ['qmsgswkjsgj_xianfu', 'tiandu', 'qmsgswkjsgj_chouce'], ['rankAdd:legend', 'rankS:ap', 'linkTo:xizhicai', 'YB_mjz:xizhicai', 'tempname:xizhicai']],
	qmsgswkjsgj_re_liuxie: ['male', 'qun', 3, ['qmsgswkjsgj_tianming', 'qmsgswkjsgj_mizhao', 'twzhuiting'], ['rankAdd:epic', 'rankS:a', 'linkTo:liuxie', 'YB_mjz:liuxie', 'tempname:liuxie']],
	qmsgswkjsgj_shen_zhaoyun: ['male', 'shen', 2, ['qmsgswkjsgj_juejing', 'relonghun'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_zhaoyun', 'YB_mjz:shen_zhaoyun', 'tempname:shen_zhaoyun', 'shu']],
	// qmsgswkjsgj_gui_xuyou:['male','YB_gui',4,['nzry_chenglve','nzry_shicai','nzry_cunmu','boss_baolian'],['rankAdd:legend','rankS:s','linkTo:xuyou','YB_mjz:xuyou','tempname:xuyou']],
	// qmsgswkjsgj_gui_zhaoyun:['male','YB_gui',4,['longdan','boss_baolian'],['rankAdd:rare','rankS:b','linkTo:zhaoyun','YB_mjz:zhaoyun','tempname:zhaoyun']],
	// qmsgswkjsgj_gui_sunquan:['male','YB_gui',4,['zhiheng','jiuyuan','boss_taiping'],['rankAdd:epic','rankS:a','linkTo:sunquan','YB_mjz:sunquan','tempname:sunquan']],
	qmsgswkjsgj_shen_guojia: ['male', 'shen', 3, ['qmsgswkjsgj_reshuishi', 'stianyi', 'resghuishi', 'tiandu', 'yiji'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_guojia', 'YB_mjz:shen_guojia', 'tempname:shen_guojia', 'wei']],
	qmsgswkjsgj_re_sp_duyu: ['male', 'qun', 4, ['qmsgswkjsgj_spwuku', 'qmsgswkjsgj_spsanchen'], ['rankAdd:legend', 'rankS:ap', 'linkTo:sp_duyu', 'YB_mjz:sp_duyu', 'tempname:sp_duyu']],
	// qmsgswkjsgj_gui_liubei:['male','YB_gui',4,['rende','jijiang','boss_taiping'],['rankAdd:rare','rankS:a','linkTo:liubei','YB_mjz:liubei','tempname:liubei']],
	// qmsgswkjsgj_gui_re_zhouyu:['male','YB_gui',3,['reyingzi','refanjian','boss_baolian'],['rankAdd:rare','rankS:a','linkTo:re_zhouyu','YB_mjz:re_zhouyu','tempname:re_zhouyu']],
	qmsgswkjsgj_shen_zhugeliang: ['male', 'shen', 3, ['qixing', 'qmsgswkjsgj_kuangfeng', 'qmsgswkjsgj_dawu', 'qmsgswkjsgj_guanxing'], ['rankAdd:eqic', 'rankS:a', 'linkTo:shen_zhugeliang', 'YB_mjz:shen_zhugeliang', 'tempname:shen_zhugeliang', 'shu', 'name:诸葛|亮']],
	qmsgswkjsgj_sb_huangzhong: ['male', 'shu', 4, ['qmsgswkjsgj_sbliegong'], ['rankAdd:legend', 'rankS:s', 'linkTo:sb_huangzhong', 'YB_mjz:sb_huangzhong', 'tempname:sb_huangzhong']],
	qmsgswkjsgj_re_yangbiao: ['male', 'qun', 3, ['qmsgswkjsgj_zhaohan', 'qmsgswkjsgj_rangjie', 'qmsgswkjsgj_yizheng'], ['rankAdd:legend', 'rankS:s', 'linkTo:yangbiao', 'YB_mjz:yangbiao', 'tempname:yangbiao']],
	qmsgswkjsgj_re_luotong: ['male', 'wu', 4, ['qmsgswkjsgj_qinzheng'], ['rankAdd:legend', 'rankS:s', 'linkTo:luotong', 'YB_mjz:luotong', 'tempname:luotong']],
	qmsgswkjsgj_re_liuyan: ['male', 'qun', 3, ['qmsgswkjsgj_tushe', 'qmsgswkjsgj_limu', 'qmsgswkjsgj_pianan'], ['rankAdd:legend', 'rankS:s', 'linkTo:liuyan', 'YB_mjz:liuyan', 'tempname:liuyan']],
	qmsgswkjsgj_re_lusu: ['male', 'wu', 3, ['qmsgswkjsgj_haoshi', 'dimeng'], ['rankAdd:legend', 'rankS:s', 'linkTo:re_lusu', 'YB_mjz:re_lusu', 'tempname:re_lusu']],
	qmsgswkjsgj_re_caorui: ['male', 'wei', 3, ['huituo', 'qmsgswkjsgj_mingjian', 'xingshuai'], ['rankAdd:legend', 'rankS:s', 'linkTo:caorui', 'YB_mjz:caorui', 'tempname:caorui', 'zhu']],
	qmsgswkjsgj_re_caiwenji: ['female', 'qun', 3, ['qmsgswkjsgj_beige', 'duanchang'], ['rankAdd:legend', 'rankS:s', 'linkTo:re_caiwenji', 'YB_mjz:re_caiwenji', 'tempname:re_caiwenji', 'name:蔡|琰']],
	qmsgswkjsgj_re_zhangxiu: ['male', 'qun', 4, ['qmsgswkjsgj_xiongluan', 'drlt_congjian'], ['rankAdd:epic', 'rankS:b', 'linkTo:zhangxiu', 'YB_mjz:zhangxiu', 'tempname:zhangxiu']],
	qmsgswkjsgj_re_fuhuanghou: ['female', 'qun', 3, ['qmsgswkjsgj_zhuikong', 'oldqiuyuan'], ['rankAdd:legend', 'rankS:s', 'linkTo:fuhuanghou', 'YB_mjz:fuhuanghou', 'tempname:fuhuanghou']],
	qmsgswkjsgj_shen_ganning: ['male', 'shen', '3/6', ['qmsgswkjsgj_poxi', 'qmsgswkjsgj_jieying', 'qixi'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_ganning', 'YB_mjz:shen_ganning', 'tempname:shen_ganning', 'wu']],
	qmsgswkjsgj_re_sunhanhua: ['female', 'wu', 3, ['qmsgswkjsgj_chongxu', 'qmsgswkjsgj_miaojian', 'qmsgswkjsgj_shhlianhua'], ['rankAdd:legend', 'rankS:s', 'linkTo:sunhanhua', 'YB_mjz:sunhanhua', 'tempname:sunhanhua']],
	// qmsgswkjsgj_yingtian_simayi:{
	// 	sex: "male",
	// 	group: "shen",
	// 	hp: 4,
	// 	skills: ["qmsgswkjsgj_jilin", "yingyou", "yingtian"],
	// 	groupInGuozhan: "wei",
	// 	names: "司马|懿",
	// 	linkTo:'new_simayi',
	// 	YB_mjz:'new_simayi',
	// },
	qmsgswkjsgj_yingtian_simayi: ['male', 'shen', 4, ['qmsgswkjsgj_jilin', 'yingyou', 'yingtian'], ['rankAdd:legend', 'rankS:s', 'linkTo:new_simayi', 'YB_mjz:new_simayi', 'tempname:new_simayi']],
	qmsgswkjsgj_re_shen_zhaoyun: ['male', 'shen', 2, ['qmsgswkjsgj_rejuejing', 'relonghun', 'longdan', 'new_yajiao'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_zhaoyun', 'YB_mjz:shen_zhaoyun', 'tempname:shen_zhaoyun', 'shu']],
	qmsgswkjsgj_shen_lusu: ['male', 'shen', 3, ['qmsgswkjsgj_tamo', 'qmsgswkjsgj_dingzhou', 'qmsgswkjsgj_zhimeng', 'haoshi', 'dimeng'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_lusu', 'YB_mjz:shen_lusu', 'tempname:shen_lusu', 'wu']],
	qmsgswkjsgj_re_sunquan: ['male', 'wu', 4, ['qmsgswkjsgj_rezhiheng', 'qmsgswkjsgj_rejiuyuan'], ['rankAdd:legend', 'rankS:s', 'linkTo:re_sunquan', 'YB_mjz:re_sunquan', 'tempname:re_sunquan']],
	qmsgswkjsgj_shen_zhouyu: ['male', 'shen', 4, ['qmsgswkjsgj_qinyin', 'qmsgswkjsgj_yeyan', 'reyingzi', 'qmsgswkjsgj_refanjian'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_zhouyu', 'YB_mjz:shen_zhouyu', 'tempname:shen_zhouyu', 'wu']],
	qmsgswkjsgj_shen_xunyu: ['male', 'shen', 3, ['qmsgswkjsgj_tianzuo', 'qmsgswkjsgj_lingce', 'qmsgswkjsgj_dinghan', 'qmsgswkjsgj_shenquhu', 'rejieming'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_xunyu', 'YB_mjz:shen_xunyu', 'tempname:re_xunyu', 'wei']],

	qmsgswkjsgj_shen_caocao: ['male', 'shen', 3, ['qmsgswkjsgj_guixin', 'qmsgswkjsgj_feiying', 'new_rejianxiong'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_caocao', 'YB_mjz:shen_caocao', 'tempname:shen_caocao', 'wei']],
	qmsgswkjsgj_shen_luxun: ['male', 'shen', 4, ['nzry_junlve', 'qmsgswkjsgj_nzry_cuike', 'nzry_dinghuo', 'qmsgswkjsgj_resbqianxun', 'qmsgswkjsgj_resblianying'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_luxun', 'YB_mjz:shen_luxun', 'tempname:shen_luxun', 'wu']],
	qmsgswkjsgj_shen_lvbu: ['male', 'shen', 5, ['qmsgswkjsgj_baonu', 'qmsgswkjsgj_wumou', 'qmsgswkjsgj_wuqian', 'qmsgswkjsgj_shenfen', 'qmsgswkjsgj_wushuang'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_lvbu', 'YB_mjz:shen_lvbu', 'tempname:shen_lvbu', 'qun']],

	// 星月界系列
	qmsgswkjsgj_re_caopi: ['male', 'wei', 3, ['qmsgswkjsgj_rexingshang', 'qmsgswkjsgj_refangzhu', 'qmsgswkjsgj_songwei'], ['zhu', 'rankAdd:rare', 'rankS:a', 'linkTo:re_caopi', 'YB_mjz:re_caopi', 'tempname:re_caopi']],
	qmsgswkjsgj_re_shamoke: ['male', 'shu', 4, ['qmsgswkjsgj_gzjili'], ['rankAdd:rare', 'rankS:a', 'linkTo:shamoke', 'YB_mjz:shamoke', 'tempname:shamoke']],
	// qmsgswkjsgj_re_peixiu:['male','qun',3,['qmsgswkjsgj_xingtu','qmsgswkjsgj_juezhi'],['rankAdd:legend','rankS:s','linkTo:peixiu','YB_mjz:peixiu','tempname:peixiu']],
	// qmsgswkjsgj_re_jushou:['male','qun','2/3/3',['qmsgswkjsgj_rejianying','dcshibei'],['rankAdd:legend','rankS:s','linkTo:re_jushou','YB_mjz:re_jushou','tempname:re_jushou']],

	qmsgswkjsgj_re_shichangshi: {
		sex: 'male',
		group: 'qun',
		hp: 1,
		skills: ['qmsgswkjsgj_mbdanggu', 'qmsgswkjsgj_mbmowang'],
		trashBin: ['sex:male_castrated'],
		names: '张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望',
		linkTo: 'shichangshi',
		YB_mjz: 'shichangshi',
		tempname: ['shichangshi'],
		rankAdd: 'legend',
		rankS: 's',
		// img:'extension/夜白神略/image/ybsl012/sgsxjxfzmnl_shichangshi.jpg',
	},
	qmsgswkjsgj_scs_zhangrang: ['male', 'qun', 0, ['qmsgswkjsgj_scstaoluan'], ['unseen', 'sex:male_castrated', 'tempname:scs_zhangrang', 'linkTo:scs_zhangrang', 'name:张|让', 'YB_mjz:scs_zhangrang']],
	qmsgswkjsgj_scs_zhaozhong: ['male', 'qun', 0, ['qmsgswkjsgj_scschiyan'], ['unseen', 'sex:male_castrated', 'tempname:scs_zhaozhong', 'linkTo:scs_zhaozhong', 'name:赵|忠', 'YB_mjz:scs_zhaozhong']],
	qmsgswkjsgj_scs_sunzhang: ['male', 'qun', 0, ['qmsgswkjsgj_scszimou'], ['unseen', 'sex:male_castrated', 'tempname:scs_sunzhang', 'linkTo:scs_sunzhang', 'name:孙|璋', 'YB_mjz:scs_sunzhang']],
	qmsgswkjsgj_scs_bilan: ['male', 'qun', 0, ['qmsgswkjsgj_scspicai'], ['unseen', 'sex:male_castrated', 'tempname:scs_bilan', 'linkTo:scs_bilan', 'name:毕|岚', 'YB_mjz:scs_bilan']],
	qmsgswkjsgj_scs_xiayun: ['male', 'qun', 0, ['qmsgswkjsgj_scsyaozhuo'], ['unseen', 'sex:male_castrated', 'tempname:scs_xiayun', 'linkTo:scs_xiayun', 'name:夏|恽', 'YB_mjz:scs_xiayun']],
	qmsgswkjsgj_scs_hankui: ['male', 'qun', 0, ['qmsgswkjsgj_scsxiaolu'], ['unseen', 'sex:male_castrated', 'tempname:scs_hankui', 'linkTo:scs_hankui', 'name:韩|悝', 'YB_mjz:scs_hankui']],
	qmsgswkjsgj_scs_lisong: ['male', 'qun', 0, ['qmsgswkjsgj_scskuiji'], ['unseen', 'sex:male_castrated', 'tempname:scs_lisong', 'linkTo:scs_lisong', 'name:栗|嵩', 'YB_mjz:scs_lisong']],
	qmsgswkjsgj_scs_duangui: ['male', 'qun', 0, ['qmsgswkjsgj_scschihe'], ['unseen', 'sex:male_castrated', 'tempname:scs_duangui', 'linkTo:scs_duangui', 'name:段|珪', 'YB_mjz:scs_duangui']],
	qmsgswkjsgj_scs_guosheng: ['male', 'qun', 0, ['qmsgswkjsgj_scsniqu'], ['unseen', 'sex:male_castrated', 'tempname:scs_guosheng', 'linkTo:scs_guosheng', 'name:郭|胜', 'YB_mjz:scs_guosheng']],
	qmsgswkjsgj_scs_gaowang: ['male', 'qun', 0, ['scsanruo'], ['unseen', 'sex:male_castrated', 'tempname:scs_gaowang', 'linkTo:scs_gaowang', 'name:高|望', 'YB_mjz:scs_gaowang']],

	// sgsxjxfzmnl_shichangshi_dead:{
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 1,
	// 	skills: ["qmsgswkjsgj_mbdanggu", "qmsgswkjsgj_mbmowang"],
	// 	trashBin: ["sex:male_castrated"],
	// 	names: "张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望",
	// 	linkTo:'shichangshi',
	// 	isUnseen:true,
	// },
	// sgsxjxfzmnl_scs_zhangrang_dead:['male','qun',0,['sgsxjxfzmnl_scstaoluan'],['unseen','sex:male_castrated','tempname:scs_zhangrang','linkTo:scs_zhangrang','name:张|让']],
	// sgsxjxfzmnl_scs_zhaozhong_dead:['male','qun',0,['sgsxjxfzmnl_scschiyan'],['unseen','sex:male_castrated','tempname:scs_zhaozhong','linkTo:scs_zhaozhong','name:赵|忠']],
	// sgsxjxfzmnl_scs_sunzhang_dead:['male','qun',0,['sgsxjxfzmnl_scszimou'],['unseen','sex:male_castrated','tempname:scs_sunzhang','linkTo:scs_sunzhang','name:孙|璋']],
	// sgsxjxfzmnl_scs_bilan_dead:['male','qun',0,['sgsxjxfzmnl_scspicai'],['unseen','sex:male_castrated','tempname:scs_bilan','linkTo:scs_bilan','name:毕|岚']],
	// sgsxjxfzmnl_scs_xiayun_dead:['male','qun',0,['sgsxjxfzmnl_scsyaozhuo'],['unseen','sex:male_castrated','tempname:scs_xiayun','linkTo:scs_xiayun','name:夏|恽']],
	// sgsxjxfzmnl_scs_hankui_dead:['male','qun',0,['sgsxjxfzmnl_scsxiaolu'],['unseen','sex:male_castrated','tempname:scs_hankui','linkTo:scs_hankui','name:韩|悝']],
	// sgsxjxfzmnl_scs_lisong_dead:['male','qun',0,['sgsxjxfzmnl_scskuiji'],['unseen','sex:male_castrated','tempname:scs_lisong','linkTo:scs_lisong','name:栗|嵩']],
	// sgsxjxfzmnl_scs_duangui_dead:['male','qun',0,['sgsxjxfzmnl_scschihe'],['unseen','sex:male_castrated','tempname:scs_duangui','linkTo:scs_duangui','name:段|珪']],
	// sgsxjxfzmnl_scs_guosheng_dead:['male','qun',0,['sgsxjxfzmnl_scsniqu'],['unseen','sex:male_castrated','tempname:scs_guosheng','linkTo:scs_guosheng','name:郭|胜']],
	// sgsxjxfzmnl_scs_gaowang_dead:['male','qun',0,['sgsxjxfzmnl_scsmiaoyu'],['unseen','sex:male_castrated','tempname:scs_gaowang','linkTo:scs_gaowang','name:高|望']],

	qmsgswkjsgj_shen_huatuo: ['male', 'shen', 3, ['qmsgswkjsgj_wuling', 'youyi', 'qmsgswkjsgj_qingnang', 'qmsgswkjsgj_jijiu'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_huatuo', 'YB_mjz:shen_huatuo', 'tempname:shen_huatuo', 'qun']],
	qmsgswkjsgj_re_mb_caomao: ['male', 'wei', 3, ['qmsgswkjsgj_mbqianlong', 'qmsgswkjsgj_mbweitong'], ['zhu', 'rankAdd:legend', 'rankS:s', 'linkTo:mb_caomao', 'YB_mjz:mb_caomao', 'tempname:mb_caomao']],
	qmsgswkjsgj_mengpo: ['female', 'YB_gui', 3, ['boss_shiyou', 'boss_wanghun', 'boss_wangshi', 'boss_aotang', 'qmsgswkjsgj_yunju'], ['rankAdd:legend', 'rankS:s', 'linkTo:boss_mengpo', 'YB_mjz:boss_mengpo', 'tempname:boss_mengpo', 'name:孟|姜女']],
	qmsgswkjsgj_shen_sunce: ['male', 'shen', '1/6', ['qmsgswkjsgj_yingba', 'qmsgswkjsgj_scfuhai', 'qmsgswkjsgj_pinghe', 'jiang', 'qmsgswkjsgj_shenhunzi'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_sunce', 'YB_mjz:shen_sunce', 'tempname:re_senben', 'wu']],
	qmsgswkjsgj_mb_sunluyu: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['qmsgswkjsgj_mbmeibu', 'qmsgswkjsgj_mbmumu'],
		dieAudios: ['sunluyu'],
		YB_mjz: 'mb_sunluyu',
		linkTo: 'mb_sunluyu',
		tempname: ['mb_sunluyu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_shen_taishici: {
		sex: 'male',
		group: 'shen',
		hp: 4,
		skills: ['qmsgswkjsgj_dulie', 'qmsgswkjsgj_tspowei', 'dangmo', 'qmsgswkjsgj_shentianyi', 'qmsgswkjsgj_shenhanzhan'],
		groupInGuozhan: 'wu',
		names: '太史|慈',
		YB_mjz: 'shen_taishici',
		linkTo: 'shen_taishici',
		tempname: ['re_taishici'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_yanxiang: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['qmsgswkjsgj_kujian', 'qmsgswkjsgj_ruilian'],
		dieAudios: ['tw_yanxiang'],
		YB_mjz: 'yanxiang',
		linkTo: 'yanxiang',
		tempname: ['yanxiang'],
		rankAdd: 'legend',
		rankS: 's',
	},

	qmsgswkjsgj_re_zhangxuan: {
		sex: 'female',
		group: 'wu',
		hp: 4,
		skills: ['tongli', 'qmsgswkjsgj_re_shezang'],
		YB_mjz: 'zhangxuan',
		linkTo: 'zhangxuan',
		tempname: ['zhangxuan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_chenshi: {
		sex: 'male',
		group: 'shu',
		hp: 4,
		skills: ['qmsgswkjsgj_re_qingbei'],
		YB_mjz: 'chenshi',
		linkTo: 'chenshi',
		tempname: ['chenshi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_dc_tengfanglan: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['qmsgswkjsgj_re_dcluochong', 'qmsgswkjsgj_re_dcaichen'],
		YB_mjz: 'dc_tengfanglan',
		linkTo: 'dc_tengfanglan',
		tempname: ['dc_tengfanglan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_zhenghun: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['dcqiangzhi', 'qmsgswkjsgj_re_dcpitian'],
		YB_mjz: 'zhenghun',
		linkTo: 'zhenghun',
		tempname: ['zhenghun'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_re_liuzan: {
		sex: 'male',
		group: 'wu',
		hp: 4,
		skills: ['qmsgswkjsgj_re_refenyin', 'qmsgswkjsgj_re_liji'],
		YB_mjz: 're_liuzan',
		linkTo: 're_liuzan',
		tempname: ['re_liuzan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_wupu: {
		sex: 'male',
		group: 'qun',
		hp: 4,
		skills: ['qmsgswkjsgj_re_dcduanti', 'qmsgswkjsgj_re_dcshicao'],
		YB_mjz: 'wupu',
		linkTo: 'wupu',
		tempname: ['wupu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_ruanyu: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['qmsgswkjsgj_re_xingzuo', 'qmsgswkjsgj_re_miaoxian'],
		YB_mjz: 'ruanyu',
		linkTo: 'ruanyu',
		tempname: ['ruanyu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_dc_duyu: {
		sex: 'male',
		group: 'wei',
		hp: 4,
		skills: ['qmsgswkjsgj_re_dcjianguo', 'qmsgswkjsgj_re_dcdyqingshi'],
		groupBorder: 'jin',
		YB_mjz: 'dc_duyu',
		linkTo: 'dc_duyu',
		tempname: ['dc_duyu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_star_caoren: {
		sex: 'male',
		group: 'wei',
		hp: 4,
		skills: ['qmsgswkjsgj_re_starsujun', 'qmsgswkjsgj_re_starlifeng'],
		YB_mjz: 'star_caoren',
		linkTo: 'star_caoren',
		tempname: ['star_caoren'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_dc_xiahouhui: {
		sex: 'female',
		group: 'wei',
		hp: 3,
		skills: ['qmsgswkjsgj_re_dcdujun', 'qmsgswkjsgj_re_dcjikun'],
		names: '夏侯|徽',
		YB_mjz: 'dc_xiahouhui',
		linkTo: 'dc_xiahouhui',
		tempname: ['dc_xiahouhui'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_panghong: {
		sex: 'male',
		group: 'shu',
		hp: 3,
		skills: ['qmsgswkjsgj_re_dcpingzhi', 'qmsgswkjsgj_re_dcgangjian'],
		YB_mjz: 'panghong',
		linkTo: 'panghong',
		tempname: ['panghong'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_zhujianping: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['qmsgswkjsgj_re_dcxiangmian', 'qmsgswkjsgj_re_dctianji'],
		YB_mjz: 'zhujianping',
		linkTo: 'zhujianping',
		tempname: ['zhujianping'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_guotiying: {
		sex: 'female',
		group: 'wei',
		hp: 3,
		skills: ['qmsgswkjsgj_re_dckanyu', 'qmsgswkjsgj_re_dczhee', 'tiandu'],
		YB_mjz: 'guotiying',
		linkTo: 'guotiying',
		tempname: ['guotiying'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_caofang: {
		sex: 'male',
		group: 'wei',
		hp: 4,
		skills: ['qmsgswkjsgj_re_dczhimin', 'qmsgswkjsgj_re_dcjujian'],
		isZhugong: true,
		YB_mjz: 'caofang',
		linkTo: 'caofang',
		tempname: ['caofang'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_guozhao: {
		sex: 'female',
		group: 'wei',
		hp: 3,
		skills: ['qmsgswkjsgj_re_pianchong', 'qmsgswkjsgj_re_zunwei'],
		YB_mjz: 'guozhao',
		linkTo: 'guozhao',
		tempname: ['guozhao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_caomao: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		maxHp: 4,
		skills: ['qmsgswkjsgj_re_qianlong', 'fensi', 'qmsgswkjsgj_re_juetao', 'qmsgswkjsgj_re_zhushi'],
		isZhugong: true,
		YB_mjz: 'caomao',
		linkTo: 'caomao',
		tempname: ['caomao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	qmsgswkjsgj_re_yue_caiwenji: ['female', 'qun', 3, ['qmsgswkjsgj_re_dcshuangjia', 'qmsgswkjsgj_re_dcbeifen'], ['rankAdd:legend', 'rankS:s', 'linkTo:yue_caiwenji', 'YB_mjz:yue_caiwenji', 'tempname:yue_caiwenji', 'name:蔡|琰']],
	qmsgswkjsgj_re_dc_liuba: ['male', 'qun', 3, ['qmsgswkjsgj_re_dczhubi', 'qmsgswkjsgj_re_dcliuzhuan'], ['rankAdd:legend', 'rankS:s', 'linkTo:dc_liuba', 'YB_mjz:dc_liuba', 'tempname:dc_liuba']],
	qmsgswkjsgj_re_zhugejin: ['male', 'wu', 3, ['qmsgswkjsgj_re_huanshi', 'qmsgswkjsgj_re_hongyuan', 'qmsgswkjsgj_re_mingzhe'], ['rankAdd:legend', 'rankS:s', 'linkTo:zhugejin', 'YB_mjz:zhugejin', 'tempname:zhugejin', 'name:诸葛|瑾']],
	qmsgswkjsgj_re_yuanyin:['male', 'qun', 3,['qmsgswkjsgj_re_dcmoshou', 'qmsgswkjsgj_re_dcyunjiu'], ['rankAdd:legend', 'rankS:s', 'linkTo:yuanyin', 'YB_mjz:yuanyin', 'tempname:yuanyin']],

	qmsgswkjsgj_re_sp_zhenji: ['female', 'qun', 3, ['qmsgswkjsgj_re_dcjijie', 'qmsgswkjsgj_re_dchuiji',], ['rankAdd:legend', 'rankS:s', 'linkTo:sp_zhenji', 'YB_mjz:sp_zhenji', 'tempname:sp_zhenji','name:甄|宓']],
	qmsgswkjsgj_re_liushan: ['male', 'shu', 3, ['qmsgswkjsgj_re_xiangle', 'qmsgswkjsgj_re_fangquan','olruoyu'], ['rankAdd:legend', 'rankS:s', 'linkTo:ol_liushan', 'YB_mjz:ol_liushan', 'tempname:ol_liushan']],
	qmsgswkjsgj_re_caojinyu: ['female', 'wei', 3, ['qmsgswkjsgj_re_yuqi', 'qmsgswkjsgj_re_shanshen', 'qmsgswkjsgj_re_xianjing'], ['rankAdd:legend', 'rankS:s', 'linkTo:caojinyu', 'YB_mjz:caojinyu', 'tempname:caojinyu']],
	qmsgswkjsgj_re_yue_zhouyu: ['male', 'wu', 3, ['qmsgswkjsgj_re_dcguyin', 'qmsgswkjsgj_re_dcpinglu'], ['rankAdd:legend', 'rankS:s', 'linkTo:yue_zhouyu', 'YB_mjz:yue_zhouyu', 'tempname:yue_zhouyu']],
	qmsgswkjsgj_re_bolingyun: ['female', 'wei', 3, ['qmsgswkjsgj_re_dclinghui', 'qmsgswkjsgj_re_dcxiace', 'qmsgswkjsgj_re_dcyuxin'], ['rankAdd:legend', 'rankS:s', 'linkTo:bolingyun', 'YB_mjz:bolingyun', 'tempname:bolingyun']],
	qmsgswkjsgj_re_v_zhangliao: ['male', 'qun', 4, ['qmsgswkjsgj_re_dcyuxi', 'qmsgswkjsgj_re_dcporong'], ['rankAdd:legend', 'rankS:s', 'linkTo:v_zhangliao', 'YB_mjz:v_zhangliao', 'tempname:v_zhangliao']],
	qmsgswkjsgj_re_sb_simayi: ['male', 'wei', 3, ['qmsgswkjsgj_re_dcsbquanmou', 'qmsgswkjsgj_re_dcsbpingliao'], ['rankAdd:legend', 'rankS:s', 'linkTo:sb_simayi', 'YB_mjz:sb_simayi', 'tempname:sb_simayi','name:司马|懿']],
	qmsgswkjsgj_re_guanning: ['male', 'qun', 3, ['qmsgswkjsgj_re_dunshi'], ['rankAdd:legend', 'rankS:s', 'linkTo:guanning', 'YB_mjz:guanning', 'tempname:guanning']],
	qmsgswkjsgj_re_pangfengyi: ['female', 'qun', 3, ['qmsgswkjsgj_re_dcyitong', 'qmsgswkjsgj_re_dcpeiniang'], ['rankAdd:legend', 'rankS:s', 'linkTo:pangfengyi', 'YB_mjz:pangfengyi', 'tempname:pangfengyi']],
	qmsgswkjsgj_re_machao: ['male', 'shu', 4, ['qmsgswkjsgj_re_tieji'], ['rankAdd:legend', 'rankS:s', 'linkTo:machao', 'YB_mjz:machao', 'tempname:machao']],
	qmsgswkjsgj_re_xusheng: ['male', 'wu', 4, ['qmsgswkjsgj_re_pojun'], ['rankAdd:legend', 'rankS:s', 'linkTo:re_xusheng', 'YB_mjz:re_xusheng', 'tempname:re_xusheng']],
	qmsgswkjsgj_re_pot_guoyuan: ['male', 'wei', 3, ['qmsgswkjsgj_re_mbqingdao', 'qmsgswkjsgj_re_mbxiugeng', 'qmsgswkjsgj_re_mbchenshe'], ['rankAdd:legend', 'rankS:s', 'linkTo:pot_guoyuan', 'YB_mjz:pot_guoyuan', 'tempname:pot_guoyuan']],
	qmsgswkjsgj_re_pot_xinxianying: ['female', 'wei', 3, ['qmsgswkjsgj_re_mbjiejie', 'qmsgswkjsgj_re_mbqingshi'], ['rankAdd:legend', 'rankS:s', 'linkTo:pot_xinxianying', 'YB_mjz:pot_xinxianying', 'tempname:pot_xinxianying']],
	qmsgswkjsgj_re_pot_dongzhao: ['male', 'wei', 3, ['qmsgswkjsgj_re_mbmiaolue', 'qmsgswkjsgj_re_mbyingjia'], ['rankAdd:legend', 'rankS:s', 'linkTo:pot_dongzhao', 'YB_mjz:pot_dongzhao', 'tempname:pot_dongzhao']],
	qmsgswkjsgj_re_simahui: ['male', 'qun', 3, ['qmsgswkjsgj_re_jianjie', "xinfu_chenghao", "xinfu_yinshi"], ['rankAdd:legend', 'rankS:s', 'linkTo:simahui', 'YB_mjz:simahui', 'tempname:simahui']],
	qmsgswkjsgj_re_o_sunquan: ['male', 'wu', 4, ['qmsgswkjsgj_mbshizhong', 'qmsgswkjsgj_mbcaowei'], ['rankAdd:legend', 'rankS:s', 'linkTo:o_sunquan', 'YB_mjz:o_sunquan', 'tempname:o_sunquan']],
	qmsgswkjsgj_re_jsrg_guozhao: ['female', 'wei', 3, ['qmsgswkjsgj_re_jsrgpianchong', 'qmsgswkjsgj_re_jsrgzunwei'], ['rankAdd:legend', 'rankS:s', 'linkTo:jsrg_guozhao', 'YB_mjz:jsrg_guozhao', 'tempname:jsrg_guozhao']],
	qmsgswkjsgj_re_wn_zhanghe: ['male', 'wei', 4, ['qmsgswkjsgj_re_wn_qiaobian'], ['rankAdd:legend', 'rankS:s', 'linkTo:wn_zhanghe', 'YB_mjz:wn_zhanghe', 'tempname:wn_zhanghe']],

	qmsgswkjsgj_shen_zhangliao: ['male', 'shen', 4, ['qmsgswkjsgj_drlt_tuxi', 'qmsgswkjsgj_drlt_duorui', 'qmsgswkjsgj_drlt_zhiti'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_zhangliao', 'YB_mjz:shen_zhangliao', 'tempname:shen_zhangliao', 'qun']],
	qmsgswkjsgj_shen_liubei: ['male', 'shen', 4, ['qmsgswkjsgj_nzry_rende', 'qmsgswkjsgj_nzry_longnu', 'qmsgswkjsgj_nzry_jieying'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_liubei', 'YB_mjz:shen_liubei', 'tempname:shen_liubei', 'shu']],
	qmsgswkjsgj_shen_guanyu: ['male', 'shen', 5, ['qmsgswkjsgj_shen_wusheng', 'qmsgswkjsgj_wushen', 'qmsgswkjsgj_wuhun'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_guanyu', 'YB_mjz:shen_guanyu', 'tempname:shen_guanyu', 'shu']],
	qmsgswkjsgj_shen_lvmeng: ['male', 'shen', 3, ['qmsgswkjsgj_shen_keji', 'qmsgswkjsgj_shelie', 'qmsgswkjsgj_gongxin'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_lvmeng', 'YB_mjz:shen_lvmeng', 'tempname:shen_lvmeng', 'wu']],
	qmsgswkjsgj_mb_shen_jiangwei:['male','shen',4,["qmsgswkjsgj_mbtiantao","qmsgswkjsgj_mbxinghun","qmsgswkjsgj_mbshenpei",'retiaoxin','qmsgswkjsgj_zhiji'],['rankAdd:legend', 'rankS:s', 'linkTo:mb_shen_jiangwei', 'YB_mjz:mb_shen_jiangwei', 'tempname:mb_shen_jiangwei', 'shu']],

	qmsgswkjsgj_mb_luyusheng: ['female', 'wu', 3, ['qmsgswkjsgj_mbrunwei', 'qmsgswkjsgj_mbshuanghuai'], ['rankAdd:legend', 'rankS:s', 'linkTo:mb_luyusheng', 'YB_mjz:mb_luyusheng', 'tempname:mb_luyusheng']],
	qmsgswkjsgj_pot_weiyan: ['male', 'shu', 4, ['qmsgswkjsgj_potzhongao', 'qmsgswkjsgj_potzhuangshi', 'qmsgswkjsgj_potyinzhan'], ['rankAdd:legend', 'rankS:s', 'linkTo:pot_weiyan', 'YB_mjz:pot_weiyan', 'tempname:pot_weiyan']],
	qmsgswkjsgj_pot_taishici: ['male', 'wu', 4, ['qmsgswkjsgj_pothanzhan', 'qmsgswkjsgj_potzhanlie', 'qmsgswkjsgj_potzhenfeng'], ['rankAdd:legend', 'rankS:s', 'linkTo:pot_taishici', 'YB_mjz:pot_taishici', 'tempname:pot_taishici']],
	qmsgswkjsgj_pot_yuji: ['male', 'qun', 3, ['qmsgswkjsgj_potfuji', 'qmsgswkjsgj_potdaozhuan'], ['rankAdd:legend', 'rankS:s', 'linkTo:pot_yuji', 'YB_mjz:pot_yuji', 'tempname:pot_yuji']],

	qmsgswkjsgj_shenci_wu_zhugeliang: ['male', 'shu', '4/7', ['qmsgswkjsgj_shenci_dcjincui', 'qmsgswkjsgj_shenci_dcqingshi', 'qmsgswkjsgj_shenci_dczhizhe'], ['rankAdd:legend', 'rankS:s', 'linkTo:wu_zhugeliang', 'YB_mjz:wu_zhugeliang', 'tempname:wu_zhugeliang']],
	qmsgswkjsgj_shenci_wu_luxun: ['male', 'wu', 4, ['qmsgswkjsgj_shenci_dcxiongmu', 'qmsgswkjsgj_shenci_dczhangcai', 'qmsgswkjsgj_shenci_dcruxian'], ['rankAdd:legend', 'rankS:s', 'linkTo:wu_luxun', 'YB_mjz:wu_luxun', 'tempname:wu_luxun']],
	qmsgswkjsgj_shenci_re_duyu: ['male', 'qun', 4, ['qmsgswkjsgj_shenci_spwuku', 'qmsgswkjsgj_shenci_spsanchen'], ['rankAdd:legend', 'rankS:s', 'linkTo:sp_duyu', 'YB_mjz:sp_duyu', 'tempname:sp_duyu']],
	qmsgswkjsgj_shenci_sb_caopi: ['male', 'wei', 3, ['qmsgswkjsgj_shenci_sbxingshang', 'qmsgswkjsgj_shenci_sbfangzhu', 'qmsgswkjsgj_shenci_sbsongwei'], ['zhu', 'rankAdd:legend', 'rankS:s', 'linkTo:sb_caopi', 'YB_mjz:sb_caopi', 'tempname:sb_caopi']],
	qmsgswkjsgj_shenci_re_sunhanhua: ['female', 'wu', 3, ['qmsgswkjsgj_shenci_chongxu', 'qmsgswkjsgj_shenci_miaojian', 'qmsgswkjsgj_shenci_shhlianhua'], ['rankAdd:legend', 'rankS:s', 'linkTo:sunhanhua', 'YB_mjz:sunhanhua', 'tempname:sunhanhua']],
	qmsgswkjsgj_shenci_dc_zhouxuān: ['male', 'wei', 3, ['qmsgswkjsgj_shenci_dcwumei', 'qmsgswkjsgj_shenci_dczhanmeng'], ['rankAdd:legend', 'rankS:s', 'linkTo:dc_zhouxuān', 'YB_mjz:dc_zhouxuān', 'tempname:dc_zhouxuān']],
	qmsgswkjsgj_shenci_caomao: ['male', 'wei', 3, ['qmsgswkjsgj_shenci_mbqianlong', 'qmsgswkjsgj_shenci_mbweitong'], ['zhu', 'rankAdd:legend', 'rankS:s', 'linkTo:mb_caomao', 'YB_mjz:mb_caomao', 'tempname:mb_caomao']],
	qmsgswkjsgj_shenci_pot_yuji: ['male', 'qun', 3, ['qmsgswkjsgj_shenci_potfuji', 'qmsgswkjsgj_shenci_potdaozhuan'], ['rankAdd:legend', 'rankS:s', 'linkTo:pot_yuji', 'YB_mjz:pot_yuji', 'tempname:pot_yuji']],

	qmsgswkjsgj_shenci_wu_huangfusong: ['male', 'qun', 4, ['qmsgswkjsgj_shenci_dcchaozhen', 'qmsgswkjsgj_shenci_dclianjie', 'qmsgswkjsgj_shenci_dcjiangxian'], ['rankAdd:legend', 'rankS:s', 'linkTo:wu_huangfusong', 'YB_mjz:wu_huangfusong', 'tempname:wu_huangfusong','name:皇甫|嵩']],
	qmsgswkjsgj_shenci_wu_guanyu: ['male', 'shu', 4, ['qmsgswkjsgj_shenci_dcjuewu', 'qmsgswkjsgj_shenci_dcwuyou', 'qmsgswkjsgj_shenci_dcyixian'], ['rankAdd:legend', 'rankS:s', 'linkTo:wu_guanyu', 'YB_mjz:wu_guanyu', 'tempname:wu_guanyu']],
	qmsgswkjsgj_shenci_bolingyun_x: ['female', 'wei', 3, ['qmsgswkjsgj_shenci_dclinghui', 'qmsgswkjsgj_shenci_dcxiace', 'qmsgswkjsgj_shenci_dcyuxin'], ['rankAdd:legend', 'rankS:s', 'linkTo:bolingyun', 'YB_mjz:bolingyun', 'tempname:bolingyun']],
	qmsgswkjsgj_shenci_simahui_x: ['male', 'qun', 3, ['qmsgswkjsgj_shenci_jianjie', 'qmsgswkjsgj_shenci_jianjie_huoji', 'qmsgswkjsgj_shenci_jianjie_lianhuan', 'qmsgswkjsgj_shenci_jianjie_yeyan', 'qmsgswkjsgj_shenci_yinshi', 'qmsgswkjsgj_shenci_chenghao'], ['rankAdd:legend', 'rankS:s', 'linkTo:simahui', 'YB_mjz:simahui', 'tempname:simahui']],
	qmsgswkjsgj_shenci_eu_kaisa_x: ['male', 'qun', 3, ['qmsgswkjsgj_shenci_eu_ducai', 'qmsgswkjsgj_shenci_eu_zhitong', 'qmsgswkjsgj_shenci_eu_jiquan'], ['rankAdd:legend', 'rankS:s', 'linkTo:eu_kaisa', 'YB_mjz:eu_kaisa', 'tempname:eu_kaisa']],

};
