import { lib, game, ui, get, ai, _status } from '../../../../../../noname.js';
export { translate };

const translate = {

	//-----------------------全民三国杀，我开局神郭嘉

	qmsgswkjsgj: '全民三国杀，我开局神郭嘉',
	qmsgswkjsgj_info: '全民三国杀，我开局神郭嘉<br>平台：番茄小说<br>作者：天一笙水',

	qmsgswkjsgj_zrlinan: '林安',

	qmsgswkjsgj_re_xizhicai: '星月界戏志才',
	qmsgswkjsgj_re_xizhicai_prefix: '星月|界',
	qmsgswkjsgj_xianfu: '先辅',
	qmsgswkjsgj_xianfu_info: '锁定技，游戏开始时，你选择一名其他角色，当其受到伤害后，你受到等量的伤害，当其回复体力后，你回复等量的体力。当先辅角色阵亡时，或回合开始时，你可以改变先辅目标。',
	qmsgswkjsgj_xianfu_append: '据作者口胡，这个伤害能发动“悲歌”。',
	qmsgswkjsgj_xianfu2: '先辅',
	qmsgswkjsgj_xianfu3: '先辅',
	tiandu_xizhicai: '天妒',
	tiandu_xizhicai_info: '此技能仅提供一条语音。',
	qmsgswkjsgj_chouce: '筹策',
	qmsgswkjsgj_chouce_info: `当你受到1点伤害后，你可以判定，若结果为：黑色，你可以移动场上一张牌或获得一名其他角色的一张手牌；红色，你选择一名角色，其摸一张牌，若其是${get.poptip('qmsgswkjsgj_xianfu')}选择的角色，改为其摸两张牌。若如此做，你可以将一张手牌交给任意角色。`,

	qmsgswkjsgj_re_liuxie: '星月界刘协',
	qmsgswkjsgj_re_liuxie_prefix: '星月|界',
	qmsgswkjsgj_tianming: '天命',
	qmsgswkjsgj_tianming_info: '当你成为【杀】的目标后，你可以摸两张牌。',
	qmsgswkjsgj_mizhao: '密诏', //【杀】或【火杀】或【雷杀】
	qmsgswkjsgj_mizhao_info: '出牌阶段限一次，你可以将所有手牌交给一名其他角色。若如此做，你令该角色与你指定的另一名有手牌的角色拼点，视为拼点赢的角色对没赢的角色使用一张雷/火/普通【杀】。',

	qmsgswkjsgj_shen_zhaoyun: '星月神赵云',
	qmsgswkjsgj_shen_zhaoyun_prefix: '星月|神',
	qmsgswkjsgj_juejing: '绝境',
	qmsgswkjsgj_juejing_info: '锁定技。①你的手牌上限+2。②当你进入或脱离濒死状态时，你摸一张牌。③摸牌阶段，你令额定摸牌数+X（X为你已损失的体力值）。',
	qmsgswkjsgj_juejing_append: '二代神赵云和三代神赵云取长补短的缝合品',
	// qmsgswkjsgj_longhun: '龙魂',
	// qmsgswkjsgj_longhun_info: '你可以将同花色的一至两张牌按下列规则使用或打出：红桃当【桃】，方块当火【杀】，梅花当【闪】，黑桃当普【无懈可击】。若你以此法转化了两张：红色牌，则此牌回复值或伤害值+1；黑色牌，则你弃置当前回合角色一张牌。',

	qmsgswkjsgj_gui_xuyou: '白无常赐福许攸',
	qmsgswkjsgj_gui_xuyou_prefix: '白无常赐福',

	qmsgswkjsgj_gui_zhaoyun: '白无常赐福赵云',
	qmsgswkjsgj_gui_zhaoyun_prefix: '白无常赐福',

	qmsgswkjsgj_gui_sunquan: '黑无常赐福孙权',
	qmsgswkjsgj_gui_sunquan_prefix: '黑无常赐福',
	//神鬼赐福
	qmsgswkjsgj_taiping: "太平",
	qmsgswkjsgj_taiping_info: "锁定技，摸牌阶段摸牌时，你的摸牌数量+2。",
	qmsgswkjsgj_taiping_append: "黑无常赐福。",
	qmsgswkjsgj_baolian:'暴敛',
	qmsgswkjsgj_baolian_info: "锁定技，结束阶段，你摸两张牌。",
	qmsgswkjsgj_baolian_append: "白无常赐福。",

	qmsgswkjsgj_shen_guojia: '星月神郭嘉',
	qmsgswkjsgj_shen_guojia_prefix: '星月|神',
	qmsgswkjsgj_reshuishi: '慧识',
	qmsgswkjsgj_reshuishi_info: '出牌阶段限一次。若你的体力上限小于10，你可进行判定。若判定结果与本次发动技能时的其他判定结果的花色均不相同且你的体力上限小于10，则你加1点体力上限，且可以重复此流程。然后你将所有位于处理区的判定牌交给一名角色。若其手牌数为全场最多，则你减1点体力上限。（全民三国杀我开局神郭嘉的慧识。据作者剧情实战，天妒回收后不计入已判定）',

	qmsgswkjsgj_re_sp_duyu: '星月界杜预',
	qmsgswkjsgj_re_sp_duyu_prefix: '星月|界',
	qmsgswkjsgj_spwuku: '武库',
	qmsgswkjsgj_spwuku_info: '锁定技，当有角色使用装备牌时，则你获得一个“武库”。',
	qmsgswkjsgj_spsanchen: '三陈',
	qmsgswkjsgj_spsanchen_info: `觉醒技，若你的“武库”数大于2，则你加1点体力上限并回复1点体力，然后获得${get.poptip('spmiewu')}。`,

	qmsgswkjsgj_gui_liubei: '黑无常赐福刘备',
	qmsgswkjsgj_gui_liubei_prefix: '黑无常赐福',

	qmsgswkjsgj_gui_re_zhouyu: '白无常赐福界周瑜',
	qmsgswkjsgj_gui_re_zhouyu_prefix: '白无常赐福',

	qmsgswkjsgj_shen_zhugeliang: '星月神诸葛亮',
	qmsgswkjsgj_shen_zhugeliang_prefix: '星月|神',
	qmsgswkjsgj_kuangfeng: '狂风',
	qmsgswkjsgj_kuangfeng2: '狂风',
	qmsgswkjsgj_kuangfeng2_bg: '风',
	qmsgswkjsgj_kuangfeng3: '狂风',
	qmsgswkjsgj_kuangfeng_info: '结束阶段，你可以弃置一张“星”并指定一名角色：直到你的下结束阶段开始时，该角色受到火焰伤害时，此伤害+1，且该角色收到的所有非属性伤害均视为火属性伤害。',
	qmsgswkjsgj_dawu: '大雾',
	qmsgswkjsgj_dawu2_bg: '雾',
	qmsgswkjsgj_dawu2: '大雾',
	qmsgswkjsgj_dawu3: '大雾',
	qmsgswkjsgj_dawu_info: '结束阶段，你可以弃置X张“星”并指定等量的角色：直到你的下结束阶段开始时，当这些角色受到非雷电伤害时，防止此伤害。',
	qmsgswkjsgj_guanxing: '观星',
	qmsgswkjsgj_guanxing_info: '准备阶段，你可以观看牌堆顶的七张牌，然后将其中一张扣置于你的武将牌上称为“星”，然后将其中任意数量的牌置于牌堆顶，将其余的牌置于牌堆底。',

	qmsgswkjsgj_sb_huangzhong: '星月谋黄忠',
	qmsgswkjsgj_sb_huangzhong_prefix: '星月|谋',
	qmsgswkjsgj_sbliegong: '烈弓',
	qmsgswkjsgj_sbliegong_info: '①你使用【杀】可以选择你距离不大于此【杀】点数的角色为目标。②当你使用牌时，或成为其他角色使用牌的目标后，你记录此牌的花色。③当你使用【杀】或伤害锦囊指定唯一目标后，若你〖烈弓②〗的记录不为空，则你可亮出牌堆顶的X张牌（X为你〖烈弓②〗记录过的花色数-1），令此牌的伤害值基数+Y（Y为亮出牌中被〖烈弓②〗记录过花色的牌的数量），且目标角色不能使用〖烈弓②〗记录过花色的牌响应此牌。此牌使用结算结束后，你清除〖烈弓②〗的记录。',

	qmsgswkjsgj_re_yangbiao: '星月界杨彪',
	qmsgswkjsgj_re_yangbiao_prefix: '星月|界',
	qmsgswkjsgj_zhaohan: '昭汉',
	qmsgswkjsgj_zhaohan_info: '锁定技，游戏开始后的前四个准备阶段，你加1点体力上限并回复1点体力。之后的三个准备阶段，你受到1点无来源伤害。',
	qmsgswkjsgj_rangjie: '让节',
	qmsgswkjsgj_rangjie_info: '当你受到1点伤害后，你可以选择一项并令一名角色摸一张牌：1.移动场上一张牌；2.从牌堆获得一张你指定类型的牌。',
	qmsgswkjsgj_yizheng: '义争',
	qmsgswkjsgj_yizheng_info: '出牌阶段限一次，你可以与一名角色拼点：若你赢，跳过其下个摸牌阶段；若你没赢，你受到其对你造成的1点伤害。',
	qmsgswkjsgj_yizhengplus:'义争',
	qmsgswkjsgj_yizhengplus_info: '出牌阶段限一次，你可以与一名角色拼点：若你没输，跳过其下个摸牌阶段；若你输，你受到其对你造成的一点伤害。若你没有因此受到伤害，你视为未发动此技能。',
	// 义争：出牌阶段限一次，你可以与一名角色拼点：若你没输，跳过其下个摸牌阶段；若你输，你受到其对你造成的一点伤害。若你没有因此受到伤害，你视为未发动此技能。
	//已经是懒得整理的玩意了……

	qmsgswkjsgj_re_luotong: '星月界骆统',
	qmsgswkjsgj_re_luotong_prefix: '星月|界',
	qmsgswkjsgj_qinzheng: '勤政',
	qmsgswkjsgj_qinzheng_info: '锁定技，你每使用或打出：两张牌时，你随机从牌堆或弃牌堆获得一张【杀】或【闪】或【桃】或【酒】；五张牌时，你随机从牌堆或弃牌堆获得一张【决斗】或【过河拆桥】；八张牌时，你随机从牌堆或弃牌堆获得一张【无中生有】或【顺手牵羊】。',

	qmsgswkjsgj_re_liuyan: '星月界刘焉',
	qmsgswkjsgj_re_liuyan_prefix: '星月|界',
	qmsgswkjsgj_tushe: '图射',
	qmsgswkjsgj_tushe_info: '当你使用牌指定目标后，若你没有基本牌，则你可以摸X张牌。（X为此牌指定的目标数）',
	qmsgswkjsgj_limu: '立牧',
	qmsgswkjsgj_limu_info: '出牌阶段，你可以将一张红牌当做【乐不思蜀】对自己使用，然后回复1点体力。若你的判定区内有牌，你对攻击范围内的其他角色使用牌便没有次数和距离限制，且可以将一种花色的所有手牌当普通杀使用，出牌阶段每种花色限一次。',
	// qmsgswkjsgj_limu_append:'暂定每回合每种花色限一次。看后面作者怎么解释吧。',
	qmsgswkjsgj_limu_sha: '立牧',
	qmsgswkjsgj_limu_sha_info: '将一种花色的所有手牌当普通【杀】使用，出牌阶段每种花色限一次',
	qmsgswkjsgj_pianan: '偏安',
	qmsgswkjsgj_pianan_info: '锁定技，当你受到伤害时，若你的判定区有牌，你弃置其中一张，防止此伤害。',

	qmsgswkjsgj_re_lusu: '星月界鲁肃',
	qmsgswkjsgj_re_lusu_prefix: '星月|界',
	qmsgswkjsgj_haoshi: '好施',
	qmsgswkjsgj_haoshi_info: '摸牌阶段，你可以多摸两张牌，然后若你的手牌数大于5，则你可以将一半的手牌（向下取整）交给一名其他角色，然后直到你的回合开始，当你成为【杀】或普通锦囊牌的目标后，其可将一张手牌交给你。',

	qmsgswkjsgj_re_caiwenji: '星月界蔡文姬',
	qmsgswkjsgj_re_caiwenji_prefix: '星月|界',
	qmsgswkjsgj_beige: '悲歌',
	qmsgswkjsgj_beige_info: '当有角色受到【杀】造成的伤害后，你可以弃一张牌，若此牌花色为：♥该角色回复X点体力(X为伤害点数)；♦︎该角色摸三张牌；♣伤害来源弃三张牌；♠伤害来源将其武将牌翻面。',

	qmsgswkjsgj_re_caorui: '星月界曹叡',
	qmsgswkjsgj_re_caorui_prefix: '星月|界',
	qmsgswkjsgj_mingjian: '明鉴',
	qmsgswkjsgj_mingjian_info: '出牌阶段开始时，你可以将所有手牌交给一名其他角色，然后你结束此阶段，其执行一个额外的出牌阶段，本出牌阶段其可以多使用一张【杀】。若如此做，直到该角色下个回合结束，其手牌上限+1。',
	//作者描述原文一塌糊涂，正好现在的剧情，这个曹叡登场了，我看看剧情里是什么结算，然后好根据作者口胡调整描述

	qmsgswkjsgj_re_zhangxiu: '星月界张绣',
	qmsgswkjsgj_re_zhangxiu_prefix: '星月|界',
	qmsgswkjsgj_xiongluan: '雄乱',
	qmsgswkjsgj_xiongluan_info: '限定技，出牌阶段，你可以废除你的判定区和装备区，然后指定一名其他角色。直到回合结束，你对其使用牌无距离和次数限制，其不能使用和打出手牌。你每废除一个装备栏，可以摸一张牌。',
	qmsgswkjsgj_xiongluanplus: '雄乱',
	qmsgswkjsgj_xiongluanplus_info: '限定技，出牌阶段，你可以废除你的判定区和装备区，然后指定一名其他角色。直到回合结束，你对其使用牌无距离和次数限制，其不能使用和打出手牌且非锁定技失效。你每废除一个装备栏，可以摸一张牌。',

	qmsgswkjsgj_re_fuhuanghou: '星月界伏皇后',
	qmsgswkjsgj_re_fuhuanghou_prefix: '星月|界',
	qmsgswkjsgj_zhuikong: '惴恐',
	qmsgswkjsgj_zhuikong_info: '其他角色的回合开始时，若你已受伤，你可以与该角色拼点。若你赢，该角色跳过本回合的出牌阶段。若你没赢，你获得其的拼点牌，然后其视为对你使用一张【杀】。',

	qmsgswkjsgj_shen_ganning: '星月神甘宁',
	qmsgswkjsgj_shen_ganning_prefix: '星月|神',
	qmsgswkjsgj_poxi: '魄袭',
	qmsgswkjsgj_poxi_info: '出牌阶段限一次，你可以观看一名其他角色的手牌，然后你可以弃置你与其手里共计四张牌。若如此做，根据此次弃置你的牌数量执行以下效果：零张，体力上限减1；一张，你本回合手牌上限-1；三张，你回复1点体力；四张，你摸五张牌。',
	qmsgswkjsgj_jieying: '劫营',
	qmsgswkjsgj_jieying_info: '回合开始时，若全场没有“营”，你获得一个“营”标记。结束阶段，你可以将“营”置于一名其他角色的武将牌旁；有“营”的角色摸牌阶段多摸一张牌、出牌阶段可多使用一张【杀】、手牌上限+1。有“营”的其他角色回合结束后，移去“营”，然后你获得其所有牌。',

	qmsgswkjsgj_re_sunhanhua: '星月界孙寒华',
	qmsgswkjsgj_re_sunhanhua_prefix: '星月|界',
	qmsgswkjsgj_chongxu: '冲虚',
	qmsgswkjsgj_chongxu_info: '出牌阶段限一次，你可以随机演奏一首音乐，并根据完成度来获得相应的分数（至多五分）。然后你可修改〖妙剑〗或〖莲华〗（消耗2分），并使用剩余的分数进行摸牌（每张1分）。',
	qmsgswkjsgj_miaojian: '妙剑',
	qmsgswkjsgj_miaojian_info: '出牌阶段限一次，你可以将一张基本牌当作刺【杀】使用，该刺【杀】不计入次数限制。',
	qmsgswkjsgj_miaojian1: '妙剑·改',
	qmsgswkjsgj_miaojian1_info: '出牌阶段限一次，你可以视为使用一张刺【杀】，该刺【杀】不计入次数限制。',
	qmsgswkjsgj_miaojian2: '妙剑·极',
	qmsgswkjsgj_miaojian2_info: '出牌阶段限一次，你可以视为使用一张刺【杀】，该刺【杀】不计入次数限制且无距离限制。',
	qmsgswkjsgj_shhlianhua: '莲华',
	qmsgswkjsgj_shhlianhua_info: '你成为其他角色【杀】的目标后，你摸一张牌，然后进行一次判定，若结果为黑桃，则取消之。',
	qmsgswkjsgj_shhlianhua1: '莲华·改',
	qmsgswkjsgj_shhlianhua1_info: '你成为其他角色【杀】的目标后，你摸一张牌，除非该角色弃置一张牌，否则取消之，然后进行一次判定，若结果为黑桃，则取消之。',
	qmsgswkjsgj_shhlianhua2: '莲华·极',
	qmsgswkjsgj_shhlianhua2_info: '你成为其他角色【杀】的目标后，你摸一张牌，除非该角色弃置一张牌，否则取消之，然后进行一次判定，若结果为黑色，则取消之。',

	qmsgswkjsgj_yingtian_simayi: '星月应天神司马懿',
	qmsgswkjsgj_yingtian_simayi_prefix: '星月|应天|神',
	qmsgswkjsgj_jilin: '戢鳞',
	qmsgswkjsgj_jilin_info: '①游戏开始时，你将牌堆顶三张牌暗置于你的武将牌上，称为“志”。②当你成为其他角色使用牌的目标时，你可以明置一张暗置的“志”令此牌对你无效。③回合开始时，你可用任意张手牌替换等量暗置的“志”。',

	qmsgswkjsgj_re_shen_zhaoyun: '星月界神赵云',
	qmsgswkjsgj_re_shen_zhaoyun_prefix: '星月|界|神',
	qmsgswkjsgj_rejuejing: '绝境',
	qmsgswkjsgj_rejuejing_info: '锁定技，你的手牌上限+2。你进入或脱离濒死状态时，你摸两张牌。摸牌阶段，你令额定摸牌数+X（X为你已损失的体力值）。',

	qmsgswkjsgj_shen_lusu: '星月神鲁肃',
	qmsgswkjsgj_shen_lusu_prefix: '星月|神',
	qmsgswkjsgj_tamo: '榻谟',
	qmsgswkjsgj_tamo_info: '游戏开始时，你可以重新分配所有角色的座次。',
	qmsgswkjsgj_tamo_faq: 'FAQ',
	qmsgswkjsgj_tamo_faq_info: '<br><li>Q：在一号位不为主公的情况下，〖榻谟〗如何结算？</li><li>A：该角色可以正常进行座次交换。若受此技能影响导致一号位角色发生了变化，则以排列后的一号位角色为起始角色开始本局游戏。</li>',
	qmsgswkjsgj_dingzhou: '定州',
	qmsgswkjsgj_dingzhou_info: '出牌阶段限一次，玩家交给一名角色一张牌 ，然后玩家获得其场上的所有牌。',
	//也不知道作者抽啥风，不说你，说玩家
	qmsgswkjsgj_zhimeng: '智盟',
	qmsgswkjsgj_zhimeng_info: '玩家的回合结束后，玩家可以选择一名其他角色，玩家与其交换手牌。',
	qmsgswkjsgj_dimengplus: '缔盟',
	qmsgswkjsgj_dimengplus_info: '出牌阶段限一次，你可以令两名其他角色交换手牌。',

	qmsgswkjsgj_re_sunquan: '星月界孙权',
	qmsgswkjsgj_re_sunquan_prefix: '星月|界',
	qmsgswkjsgj_rezhiheng: '制衡',
	qmsgswkjsgj_rezhiheng_info: '出牌阶段限一次，你可以摸X+1张牌，然后弃置X张牌。（X为你的牌数量。）',
	qmsgswkjsgj_rejiuyuan: '救援',
	qmsgswkjsgj_rejiuyuan_info: '主公技，当其他吴势力角色回复体力时，其可以改为令你回复1点体力，然后其摸一张牌。',

	qmsgswkjsgj_shen_zhouyu: '星月神周瑜',
	qmsgswkjsgj_shen_zhouyu_prefix: '星月|神',
	qmsgswkjsgj_qinyin: '琴音',
	qmsgswkjsgj_qinyin_info: '弃牌阶段结束时，你可以选择一项：1.令你选择的任意名角色各回复1点体力；2.令你选择的任意角色各失去1点体力或对其各造成一点伤害。',
	qmsgswkjsgj_yeyan: '业炎',
	qmsgswkjsgj_yeyan_info: '出牌阶段限一次，你可以选择至多三名角色，对这些角色造成共计至多3点火焰伤害（若你将对一名角色分配2点或更多火焰伤害，你须先弃置四张花色各不相同的手牌）。',
	qmsgswkjsgj_refanjian: '反间',
	qmsgswkjsgj_refanjian_info: '出牌阶段限一次，你可以展示一张手牌并交给一名其他角色，令其展示所有手牌，然后你选择一项：1.弃置其与此牌花色相同的所有牌；2.令其失去1点体力或对其造成1点伤害。',
	qmsgswkjsgj_refanjian_card: '弃牌',
	qmsgswkjsgj_refanjian_hp: '失去体力',

	qmsgswkjsgj_shen_xunyu: '星月神荀彧',
	qmsgswkjsgj_shen_xunyu_prefix: '星月|神',
	qmsgswkjsgj_tianzuo: '天佐',
	qmsgswkjsgj_tianzuo_info: `锁定技。①游戏开始时，你将十六张${get.poptip('qizhengxiangsheng')}加入牌堆。②${get.poptip('qizhengxiangsheng')}对你无效。③出牌阶段限一次，你可视为使用一张${get.poptip('qizhengxiangsheng')}。`,
	qmsgswkjsgj_lingce: '灵策',
	qmsgswkjsgj_lingce_info: `锁定技。当有${get.poptip('qizhengxiangsheng')}或智囊或〖定汉①〗记录过的锦囊牌被使用时，则你摸一张牌。你以此法摸的牌，不计入手牌上限。`,
	qmsgswkjsgj_dinghan: '定汉',
	qmsgswkjsgj_dinghan_info: '①当你成为未记录过的普通锦囊牌的目标时，或有未记录过的延时锦囊牌进入你的判定区时，你记录此牌名并取消之。②准备阶段或你受到一点伤害后，你可在〖定汉①〗的记录中添加或减少一种锦囊牌的牌名。',
	//这里作者把准备阶段写成了回合开始，我懒得多改代码，就帮他改过来了
	qmsgswkjsgj_shenquhu: '驱虎',
	qmsgswkjsgj_shenquhu_info: '出牌阶段限一次，你可以与一名角色拼点：若你赢，你令该角色对其攻击范围内的另一名角色造成1点伤害；若你没赢，其对你造成1点伤害。',

	// qmsgswkjsgj_shenxing:'神性',
	// qmsgswkjsgj_shenxing_info:`每轮游戏开始时，若你没有装备${get.poptip("mb_qingnangshu")}，你可将${get.poptip("mb_qingnangshu")}置入你的装备区。${get.poptip("mb_qingnangshu")}离开你的装备区时，立刻销毁。`,
	// qmsgswkjsgj_shenxing2:'神性',
	// qmsgswkjsgj_shenxing2_info:`每轮游戏开始时，若你没有装备${get.poptip("qmsgswkjsgj_chuanguoyuxi")}，你可将${get.poptip("mb_qingnangshu")}置入你的装备区。${get.poptip("mb_qingnangshu")}离开你的装备区时，立刻销毁。`,
	// qmsgswkjsgj_shenxing3:'神性',
	// qmsgswkjsgj_shenxing3_info:`每轮游戏开始时，若你没有装备${get.poptip("muniu")}，你可将${get.poptip("muniu")}置入你的装备区。${get.poptip("muniu")}离开你的装备区时，立刻销毁。`,
	// //某一章开始，改为获得并使用，为了配合杜预叠标记
	// qmsgswkjsgj_chuanguoyuxi:'传国玉玺',
	// qmsgswkjsgj_chuanguoyuxi_info:'锁定技，弃牌阶段开始时，你摸一张牌且手牌上限永久+2。',
	// qmsgswkjsgj_chuanguoyuxi_bg: "玺",
	// // mb_chuanguoyuxi_info: "锁定技，弃牌阶段开始时，你摸一张牌且手牌上限永久+2，然后若你不为主公，你失去1点体力。",
	// qmsgswkjsgj_chuanguoyuxi_append: '<span style="font-family: yuanli">受命于天，既寿永昌！</span>',
	// qmsgswkjsgj_chuanguoyuxi_skill: "传国玉玺",
	// qmsgswkjsgj_chuanguoyuxi_skill_info: "锁定技，弃牌阶段开始时，你摸一张牌且手牌上限永久+2。",

	// qmsgswkjsgj_zhenshen:'真神',
	// qmsgswkjsgj_zhenshen_info:'非神势力角色改变你横置或翻面状态时，取消之。',
	// // qmsgswkjsgj_zhenshen_info:'非神武将无法影响你的神将状态，包括但不限于：技能失效，翻面，封锁手牌……',
	// qmsgswkjsgj_zhenshen_append:'无语',
	//我可不什么都惯着这作者

	qmsgswkjsgj_shen_luxun: '星月神陆逊',
	qmsgswkjsgj_shen_luxun_prefix: '星月|神',
	qmsgswkjsgj_resbqianxun: '谦逊',
	qmsgswkjsgj_resbqianxun_info: '当一张锦囊对你生效时，你可以将任意张手牌 扣置于武将牌上，若如此做，回合结束时，你获得武将牌上的所有牌。',
	qmsgswkjsgj_resblianying: '连营',
	qmsgswkjsgj_resblianying_info: '当你失去最后的手牌时，你可以摸一张牌。每回合结束时，你可观看牌堆顶的X张牌，然后将这些牌交给任意角色（X为你本回合失去的牌数，且至多为5）',
	qmsgswkjsgj_nzry_cuike: '摧克',
	qmsgswkjsgj_nzry_cuike_info: '出牌阶段，若“军略”标记的数量为奇数，你可以对一名角色造成1点伤害；若“军略”标记的数量为偶数，你可以横置一名角色并弃置其区域内的一张牌。然后，若“军略”标记的数量超过7个，你可以移去全部“军略”标记并对所有其他角色造成1点伤害。',
	qmsgswkjsgj_nzry_cuike_append: '一切以作者口胡（实战）为准',

	qmsgswkjsgj_shen_caocao: '星月神曹操',
	qmsgswkjsgj_shen_caocao_prefix: '星月|神',
	qmsgswkjsgj_guixin: '归心',
	qmsgswkjsgj_guixin_info: '当你受到一点伤害后，你可以获得每名其他角色区域里的一张牌或摸一张牌。',
	qmsgswkjsgj_guixin_append: '拷打作者。描述不严谨。实际上应该说是：<br>当你受到一点伤害后，你可以获得每名其他角色区域里的一张牌，你可以放弃获得该角色的牌，然后摸一张牌。',
	qmsgswkjsgj_feiying: '飞影',
	qmsgswkjsgj_feiying_info: '锁定技，其他角色计算与你的距离+1，你计算与其他角色的距离-1。',

	qmsgswkjsgj_shen_lvbu: '星月神吕布',
	qmsgswkjsgj_shen_lvbu_prefix: '星月|神',
	qmsgswkjsgj_shenfen: '神愤',
	qmsgswkjsgj_shenfen_info: '出牌阶段限一次，你可以弃置6枚“暴怒”标记，对任意其他角色各造成1点伤害。然后这些角色先各弃置其装备区里的牌，再各弃置六张手牌。',
	qmsgswkjsgj_baonu: '狂暴',
	qmsgswkjsgj_baonu_info: '锁定技，游戏开始时，你获得4枚“暴怒”标记；锁定技，当你造成/受到1点伤害后，你获得1枚“暴怒”标记。',
	qmsgswkjsgj_wumou: '无谋',
	qmsgswkjsgj_wumou_info: '锁定技，当你使用普通锦囊牌时，你选择一项：1.弃置1枚“暴怒”标记；2.失去1点体力。然后你摸一张牌。',
	qmsgswkjsgj_wuqian: '无前',
	qmsgswkjsgj_wuqian_info: `出牌阶段，你可以弃置2枚“暴怒”标记并选择一名本回合内未选择过的其他角色，然后直到回合结束，你对该角色使用牌没有次数限制，且令其防具无效。`,
	qmsgswkjsgj_wushuang: '无双',
	qmsgswkjsgj_wushuang_info: '锁定技。①你使用的【杀】需两张【闪】才能抵消；与你进行【决斗】的角色每次需要打出两张【杀】。②每回合限一次，当你使用【杀】或【决斗】造成伤害时，此伤害+1。',

	qmsgswkjsgj_re_caopi: '星月界曹丕',
	qmsgswkjsgj_re_caopi_prefix: '星月|界',
	qmsgswkjsgj_rexingshang: '行殇',
	qmsgswkjsgj_rexingshang_info: '当其他角色死亡后，你可以获得其所有牌并回复一点体力。',
	qmsgswkjsgj_refangzhu: '放逐',
	qmsgswkjsgj_refangzhu_info: '当你受到1点伤害后，你可以选择令一名其他角色：摸X张牌并将武将牌翻面，或弃置X张牌并失去1点体力。（X为你已损失的体力值）',
	qmsgswkjsgj_songwei: '颂威',
	qmsgswkjsgj_songwei_info: '主公技，其他魏势力的角色的判定牌结果为黑色且生效后，你可以摸一张牌。',

	qmsgswkjsgj_re_shamoke: '星月界沙摩柯',
	qmsgswkjsgj_re_shamoke_prefix: '星月|界',
	qmsgswkjsgj_gzjili: '蒺藜',
	qmsgswkjsgj_gzjili_info: '当你于一回合内使用或打出第X张牌时，你可以摸X张你指定类型的牌（X为你的攻击范围）。',

	qmsgswkjsgj_re_peixiu: '星月界裴秀',
	qmsgswkjsgj_re_peixiu_prefix: '星月|界',
	qmsgswkjsgj_xingtu: '行图',
	qmsgswkjsgj_xingtu1: '倍数',
	qmsgswkjsgj_xingtu2: '约数',
	qmsgswkjsgj_xingtu_info: '锁定技。你失去牌时，若此牌的点数是X的约数或倍数，你摸一张牌且此牌无次数限制（X为你失去的上一张牌的点数）。',
	qmsgswkjsgj_xingtu_append: '作者说等以后需要的时候改改。',
	// qmsgswkjsgj_xingtu_append:'MD若制作者，谁教你这么突破的？',
	// qmsgswkjsgj_xingtu_info: "锁定技。你使用点数为X的倍数的牌无次数限制，你使用点数为X的约数的牌时摸一张牌（X为你本局游戏使用的上一张牌的点数）。",
	qmsgswkjsgj_juezhi: '爵制',
	qmsgswkjsgj_juezhi_info: '出牌阶段，你可以弃置至少两张牌，然后从牌堆中获得一张点数为Y的牌（Y为这些牌的点数和对13取余，余数为0时可以指定任意点数且额外获得一张）。',

	qmsgswkjsgj_re_shichangshi: '星月界十常侍',
	qmsgswkjsgj_re_shichangshi_prefix: '星月|界',
	qmsgswkjsgj_mbdanggu: '党锢',
	qmsgswkjsgj_mbdanggu_info: '锁定技。①游戏开始时，你获得十张“常侍”牌，然后你进行一次结党。②当你修整结束后，你进行一次结党并摸两张牌。③若你有亮出的“常侍”牌，你视为拥有这些牌的技能。（全民三国杀我开局神郭嘉的十常侍专用）',
	qmsgswkjsgj_mbdanggu_faq: '关于结党',
	qmsgswkjsgj_mbdanggu_faq_info: '<br>系统随机选择一张未亮出过的“常侍”牌，然后选择四张未亮出过的“常侍”牌。你观看前者，然后从后者中选择一名认可前者的“常侍”牌。然后若此时不为双将模式，你将这两张武将牌作为你的武将牌（不移除原有技能）；否则你获得这两张武将牌上的技能。',
	qmsgswkjsgj_mbdanggu_faq2: '关于认可',
	qmsgswkjsgj_mbdanggu_faq2_info: '<br>双向不认可常侍为固定组合：<br><li>郭胜、段珪<br><li>韩悝、毕岚<br>单向不认可常侍为系统随机分配。<br>每次结党至多存在一张不认可主将的常侍牌，且若此次结党仅有一张常侍牌，则不会存在不认可情况。',
	//殁亡貌似没变化
	//谁说的没变化？检测的目标常侍牌都变了
	qmsgswkjsgj_mbmowang: '殁亡',
	qmsgswkjsgj_mbmowang_info: '锁定技。①当你死亡前，若你有未亮出的“常侍”牌且体力上限大于0，你将死亡改为修整至你的下个回合开始前，然后你复原武将牌，且不于此次死亡事件中进行展示身份牌、检测游戏胜利条件与执行奖惩的流程。②回合结束后，你死亡。（全民三国杀我开局神郭嘉的十常侍专用）',
	qmsgswkjsgj_mbmowang_faq: '关于修整',
	qmsgswkjsgj_mbmowang_faq_info: '<br>将武将牌移出游戏（视为你存活）。当该角色修整结束，其移回游戏。',
	qmsgswkjsgj_scs_zhangrang: '星月张让',
	qmsgswkjsgj_scs_zhangrang_prefix: '星月',
	qmsgswkjsgj_scstaoluan: '滔乱',
	qmsgswkjsgj_scstaoluan_info: '出牌阶段限一次。你可以视为使用任意一种基本牌或普通锦囊牌。',
	qmsgswkjsgj_scs_zhaozhong: '星月赵忠',
	qmsgswkjsgj_scs_zhaozhong_prefix: '星月',
	qmsgswkjsgj_scschiyan: '鸱咽',
	qmsgswkjsgj_scschiyan_info: '①当你使用【杀】指定目标后，你可以将其的两张牌置于其武将牌上，然后其于当前回合结束时获得这些牌。②当你因执行【杀】的效果对一名角色造成伤害时，若该角色的手牌数和装备区内的牌数均不大于你，此伤害+1。',
	qmsgswkjsgj_scs_sunzhang: '星月孙璋',
	qmsgswkjsgj_scs_sunzhang_prefix: '星月',
	qmsgswkjsgj_scszimou: '自谋',
	qmsgswkjsgj_scszimou_info: '锁定技。出牌阶段，当你使用第一/二/三张牌时，你从牌堆中获得一张【酒】/【杀】/【决斗】。',
	qmsgswkjsgj_scs_bilan: '星月毕岚',
	qmsgswkjsgj_scs_bilan_prefix: '星月',
	qmsgswkjsgj_scspicai: '庀材',
	qmsgswkjsgj_scspicai_info: '出牌阶段限一次。你可进行判定牌不置入弃牌堆的判定。若判定结果与本次发动技能时的其他判定结果的数字均不相同，则你可以重复此流程。然后你将所有位于处理区的判定牌交给一名角色。',
	qmsgswkjsgj_scs_xiayun: '星月夏恽',
	qmsgswkjsgj_scs_xiayun_prefix: '星月',
	qmsgswkjsgj_scsyaozhuo: '谣诼',
	qmsgswkjsgj_scsyaozhuo_info: '出牌阶段限一次。你可以与一名角色拼点，若你没输，其跳过下一个摸牌阶段。',
	//不知道赢和没输有啥区别
	qmsgswkjsgj_scs_hankui: '星月韩悝',
	qmsgswkjsgj_scs_hankui_prefix: '星月',
	qmsgswkjsgj_scsxiaolu: '宵赂',
	qmsgswkjsgj_scsxiaolu_info: '出牌阶段限一次。你可以摸四张牌，然后选择一项：1.弃置四张手牌；2.将四张手牌交给一名其他角色。',
	qmsgswkjsgj_scs_lisong: '星月栗嵩',
	qmsgswkjsgj_scs_lisong_prefix: '星月',
	qmsgswkjsgj_scskuiji: '窥机',
	qmsgswkjsgj_scskuiji_info: '出牌阶段限一次。你可以观看一名其他角色的手牌，然后弃置你与其的共计四张牌。',
	//花色去掉了，手也去掉了……
	qmsgswkjsgj_scs_duangui: '星月段珪',
	qmsgswkjsgj_scs_duangui_prefix: '星月',
	qmsgswkjsgj_scschihe: '叱吓',
	qmsgswkjsgj_scschihe_info: '当你使用【杀】指定唯一目标后，你可亮出牌堆顶的三张牌，令此【杀】的伤害值基数+X（X为亮出牌中花色与此【杀】相同的牌数），且目标角色不能使用亮出牌包含的花色的牌响应此【杀】。',
	qmsgswkjsgj_scs_guosheng: '星月郭胜',
	qmsgswkjsgj_scs_guosheng_prefix: '星月',
	qmsgswkjsgj_scsniqu: '逆取',
	qmsgswkjsgj_scsniqu_info: '出牌阶段限一次。你可以对一名角色造成2点火焰伤害。',
	qmsgswkjsgj_scs_gaowang: '星月高望',
	qmsgswkjsgj_scs_gaowang_prefix: '星月',
	///其实没变化哒
	// qmsgswkjsgj_scsanruo: "安弱",
	// qmsgswkjsgj_scsanruo_info: "你可以将一张♥牌当【桃】、♦牌当火【杀】、♣牌当【闪】、♠牌当【无懈可击】使用。当你以此法使用或打出【杀】或【闪】时，你可以获得对方的一张牌；当你以此法使用【桃】时，你可以获得一名其他角色的一张牌；当你以此法使用【无懈可击】时，你可以获得此牌响应的普通锦囊牌的使用者的一张牌。",
	// qmsgswkjsgj_scsmiaoyu: "妙语",
	// qmsgswkjsgj_scsmiaoyu_info: "你可以将至多两张相同花色的牌按照以下规则使用或打出：♦牌当作火【杀】，♥牌当作【桃】，♣牌当作【闪】，♠牌当作【无懈可击】。若你以此法使用了两张红色牌，则此牌回复值或伤害值+1。若你以此法使用了两张黑色牌，则你弃置当前回合角色一张牌。",

	qmsgswkjsgj_re_jushou: '星月界沮授',
	qmsgswkjsgj_re_jushou_prefix: '星月|界',
	qmsgswkjsgj_rejianying: '渐营',
	qmsgswkjsgj_rejianying_info: '当你失去牌时，若此牌与你上一张失去的牌颜色或点数相同，泽尼可以摸一张牌。出牌阶段限一次，你可以将一张牌当做任意基本牌使用，且不计入次数限制。若你于此阶段内使用的上一张牌有花色，则此牌的花色视为上一张牌的花色。',
	// 矢北本质上是十周年矢北
	qmsgswkjsgj_shen_huatuo: '星月手杀神华佗',
	qmsgswkjsgj_shen_huatuo_prefix: '星月|手杀|神',
	qmsgswkjsgj_qingnang: '青囊',
	qmsgswkjsgj_qingnang_info: '出牌阶段限一次，你可以令一名角色回复一点体力。',
	qmsgswkjsgj_jijiu: '急救',
	qmsgswkjsgj_jijiu_info: '你于回合外可以将一张红色牌当【桃】使用，其他角色使用【桃】时，你摸一张牌。',

	qmsgswkjsgj_wuling_append: '最后一段的修改顺序我没写，懒',
	qmsgswkjsgj_wuling: '五灵',
	qmsgswkjsgj_wuling_info: `⓪你始终拥有“五灵”标记，并按照你指定的顺序获得“五禽戏”。①美轮游戏开始时限两次。你可以选择一名没有“${get.poptip({
		id: 'qmsgswkjsgj_wl_wuqinxi',
		name: '五禽戏',
		type: 'character',
		info: `“五禽戏”分为“虎、鹿、熊、猿、鹤”五个不同的效果：<span style='font-family: yuanli'>
				<br><li>虎：当你使用牌对目标角色造成伤害时，此伤害+1。
				<br><li>鹿：①当你获得此效果时，你回复2点体力并弃置判定区的所有牌。②你不能成为延时锦囊牌的目标。
				<br><li>熊：当你受到伤害时，此伤害-1。
				<br><li>猿：当你获得此效果时，你选择一名其他角色，获得其装备区里的牌。
				<br><li>鹤：当你获得此效果时，你摸五张牌。
			</span>`,
	})}”的角色，按照你选择的顺序向其传授“${get.poptip('qmsgswkjsgj_wl_wuqinxi')}”，且其获得如下效果：其获得你选择的第一种“${get.poptip('qmsgswkjsgj_wl_wuqinxi')}”的效果，并在其每个准备阶段移除当前“${get.poptip('qmsgswkjsgj_wl_wuqinxi')}”的效果并切换为下一种。`,
	//②出牌阶段，你可以重新调整拥有“五灵”标记角色后续未触发的“五禽戏”顺序。
	//当你死亡时，你令场上的角色失去你传授的“${get.poptip("qmsgswkjsgj_wl_wuqinxi")}”
	qmsgswkjsgj_wuling_wuqinxi: '五禽戏',
	get qmsgswkjsgj_wuling_wuqinxi_info() {
		return lib.poptip.getInfo('qmsgswkjsgj_wl_wuqinxi');
	},
	qmsgswkjsgj_youyi: '游医',
	qmsgswkjsgj_youyi_info: '①弃牌阶段结束时，你可以将所有于此阶段弃置的牌置入仁区。②出牌阶段限一次。你可以将仁区的所有牌置入弃牌堆，令所有角色各回复1点体力。',
	qmsgswkjsgj_wuqinxi_hu: '虎',
	qmsgswkjsgj_wuqinxi_hu_bg: '虎',
	qmsgswkjsgj_wuqinxi_hu_info: '当你使用牌对目标角色造成伤害时，此伤害+1。',
	qmsgswkjsgj_wuqinxi_hu_append: '作者原文是：你使用牌对目标角色造成伤害时，令此牌对其中一个目标造成的伤害值+1。',
	//我的【评价是：云玩家还想吃这碗饭
	qmsgswkjsgj_wuqinxi_lu: '鹿',
	qmsgswkjsgj_wuqinxi_lu_bg: '鹿',
	qmsgswkjsgj_wuqinxi_lu_info: '①当你获得此效果时，你回复2点体力并弃置判定区的所有牌。②你不能成为延时锦囊牌的目标。',
	qmsgswkjsgj_wuqinxi_xiong: '熊',
	qmsgswkjsgj_wuqinxi_xiong_bg: '熊',
	qmsgswkjsgj_wuqinxi_xiong_info: '当你受到伤害时，此伤害-1。',
	qmsgswkjsgj_wuqinxi_yuan: '猿',
	qmsgswkjsgj_wuqinxi_yuan_bg: '猿',
	qmsgswkjsgj_wuqinxi_yuan_info: '当你获得此效果时，你选择一名其他角色，获得其装备区里的牌。',
	qmsgswkjsgj_wuqinxi_he: '鹤',
	qmsgswkjsgj_wuqinxi_he_bg: '鹤',
	qmsgswkjsgj_wuqinxi_he_info: '当你获得此效果时，你摸五张牌。',

	qmsgswkjsgj_re_mb_caomao: '星月界曹髦',
	qmsgswkjsgj_re_mb_caomao_prefix: '星月|界',
	qmsgswkjsgj_mbqianlong: '潜龙',
	qmsgswkjsgj_mbqianlong_info: `${get.poptip('rule_chihengji')}。①游戏开始时，你获得20枚“道心”标记。②当你得到牌后/受到1点伤害后/造成1点伤害后，你获得5/15/15枚“道心”（上限为99枚）。③若你的“道心”数不小于25/50/75/99，你视为拥有${get.poptip('qmsgswkjsgj_mbcmqingzheng')}/${get.poptip('qmsgswkjsgj_mbcmjiushi')}/${get.poptip('qmsgswkjsgj_mbcmfangzhu')}/${get.poptip('qmsgswkjsgj_mbjuejin')}。`,
	qmsgswkjsgj_mbcmqingzheng: '清正',
	qmsgswkjsgj_mbcmqingzheng_info: `${get.poptip('rule_chihengji')}。出牌阶段开始时，你可以弃置一种花色的所有手牌，并观看一名有手牌的其他角色的手牌，你弃置其中一种花色的所有牌。然后对其造成1点伤害。`,
	qmsgswkjsgj_mbcmjiushi: '酒诗',
	qmsgswkjsgj_mbcmjiushi_info: `${get.poptip('rule_chihengji')}。①当你需要使用【酒】时，若你的武将牌正面向上，你可以翻面，视为使用一张【酒】。②当你受到伤害后，若你武将牌背面朝上且未因此次伤害发动过〖酒诗〗，你可以翻面。③当你翻面后，你获得牌堆里的一张锦囊牌。`,
	qmsgswkjsgj_mbcmfangzhu: '放逐',
	qmsgswkjsgj_mbcmfangzhu_info: `${get.poptip('rule_chihengji')}。出牌阶段限一次，你可以选择一名其他角色，选择一项：⒈令其不能使用手牌中的一种类型牌直到其回合结束；⒉令其所有非Charlotte技能失效直到其回合结束。`,
	qmsgswkjsgj_mbjuejin: '决进',
	qmsgswkjsgj_mbjuejin_info: `${get.poptip('rule_chihengji')}，限定技。出牌阶段，你可以令所有角色依次将体力调整至1并获得X点护甲（X为一名角色以此法减少的体力值且你以此法获得的护甲数额外+2）。然后你将牌堆、弃牌堆、场上及所有角色手牌中的【闪】、【桃】和【酒】移出游戏且增加全局技能“${get.poptip({
		id: 'juejin_xiangsicunwei',
		name: '向死存魏',
		type: 'character',
		info: '当有牌进入弃牌堆后，系统将这些牌中的【闪】、【桃】和【酒】移出游戏。',
	})}”。（全民三国杀我开局神郭嘉的界曹髦）`,
	qmsgswkjsgj_mbweitong: '卫统',
	qmsgswkjsgj_mbweitong_info: `${get.poptip('rule_chihengji')}，主公技。游戏开始时，若你有${get.poptip('qmsgswkjsgj_mbqianlong')}，你改为获得60点道心值（全民三国杀我开局神郭嘉的界曹髦）。`,

	qmsgswkjsgj_mengpo_ab: '星月孟婆',
	qmsgswkjsgj_mengpo: '星月孟婆·孟姜女',
	qmsgswkjsgj_mengpo_prefix: '星月',

	// qmsgswkjsgj_shiyou: "拾忧",
	// qmsgswkjsgj_shiyou_info: "其他角色于弃牌阶段弃置的牌进入弃牌堆前，你可以选择其中任意张花色各不相同的牌获得之。",
	// qmsgswkjsgj_wanghun: "忘魂",
	// qmsgswkjsgj_wanghun_info: "锁定技，你死亡时，令随机两名敌方角色各随机失去一个技能（主公技除外），并在牌堆中加入2张回魂。(回魂只能在挑战模式出现)",
	// qmsgswkjsgj_wangshi: "往事",
	// qmsgswkjsgj_wangshi_info: "锁定技，你存活时，敌方角色的回合开始时，令其于本回合不能使用或打出随机一种类型的牌（基本、锦囊、装备）。",
	// qmsgswkjsgj_aotang:'熬汤',
	// qmsgswkjsgj_aotang_info:'孟婆回合开始时随机使一名敌方角色遗忘所有武将技能，持续至孟婆下回合开始。',
	qmsgswkjsgj_yunju: '云飓',
	qmsgswkjsgj_yunju_info: '锁定技，敌方角色的回合结束时随机弃置一张手牌。',

	qmsgswkjsgj_shen_sunce: '星月神孙策',
	qmsgswkjsgj_shen_sunce_prefix: '星月|神',
	qmsgswkjsgj_yingba: '英霸',
	qmsgswkjsgj_yingba_info: '①出牌阶段限两次，你可令一名其他角色减少1点体力上限并获得“平定”标记，然后你减少1点体力上限。②你对拥有“平定”标记的角色使用牌没有距离限制和次数限制。',
	qmsgswkjsgj_scfuhai: '覆海',
	qmsgswkjsgj_scfuhai_info: '锁定技。①当你使用牌指定目标后，若目标角色有“平定”标记，则其不可响应此牌，然后你摸一张牌。此牌结算后，你可以移除其“平定”标记，并恢复X点体力上限。②拥有“平定”标记的角色死亡时，你增加X点体力上限并摸X张牌。（X为其拥有的“平定”标记数）。',
	qmsgswkjsgj_pinghe: '冯河',
	qmsgswkjsgj_pinghe_info: '锁定技。①你的手牌上限基数等于你已损失的体力值+3。②当你受到其他角色造成的伤害时，若你有牌且你的体力上限大于1，则你防止此伤害，减1点体力上限并可将一张手牌交给一名其他角色。然后若你拥有〖英霸〗，则伤害来源获得一个“平定”标记。',
	qmsgswkjsgj_shenhunzi: '魂姿',
	qmsgswkjsgj_shenhunzi_info: `锁定技，游戏开始时，你获得${get.poptip('qmsgswkjsgj_shenyingzi')}和${get.poptip('qmsgswkjsgj_shenyinghun')}`,
	qmsgswkjsgj_shenyingzi: '英姿',
	qmsgswkjsgj_shenyingzi_info: `锁定技，摸牌阶段，你多摸一张牌。`,
	qmsgswkjsgj_shenyinghun: '英魂',
	qmsgswkjsgj_shenyinghun_info: `准备阶段，若你已受伤，你可以选择一名其他角色并选择一项：1.令其摸Y张牌；2.令其弃置Y张牌。（Y为你已损失的体力值）`,
	qmsgswkjsgj_shenjiang: '激昂',

	qmsgswkjsgj_mb_sunluyu: '星月手杀界孙鲁育',
	qmsgswkjsgj_mb_sunluyu_prefix: '星月|手杀|界',
	qmsgswkjsgj_mbmumu: '穆穆',
	qmsgswkjsgj_mbmumu_info: '出牌阶段开始时，你可以选择一项：1.弃置一名其他角色的一张牌；2.获得场上的一张防具牌。',
	qmsgswkjsgj_mbmeibu: '魅步',
	qmsgswkjsgj_mbmeibu_info: `其他角色的出牌阶段开始时，你可以令该角色于本回合内获得${get.poptip('qmsgswkjsgj_mbzhixi')}，本回合其与你的距离视为1。`,
	qmsgswkjsgj_mbzhixi: '止息',
	qmsgswkjsgj_mbzhixi_info: '锁定技。出牌阶段，你使用牌时需弃置一张手牌，若你于此阶段使用过的牌数不小于X，你不能使用牌（X为你的体力值）；当你使用锦囊牌时，你结束此阶段；你使用装备牌后，本回合手牌上限-1。',

	qmsgswkjsgj_re_mb_zhangzhi: '星月界书张芝',
	qmsgswkjsgj_re_mb_zhangzhi_prefix: '星月|界|书',
	qmsgswkjsgj_mbshiju: '势举',
	qmsgswkjsgj_mbshiju_info: `锁定技，你使用牌结算结束后，若此牌与上一张被使用的牌：类别相同，你获得牌堆顶的一张牌；颜色相同，你获得牌堆底的一张牌；${get.poptip('rule_chengshi')}：若牌名也相同，你升级或刷新${get.poptip('mbkubai')}。`,

	qmsgswkjsgj_shen_taishici: '星月神太史慈',
	qmsgswkjsgj_shen_taishici_prefix: '星月|神',
	qmsgswkjsgj_dulie: '笃烈',
	qmsgswkjsgj_dulie_info: '锁定技。当你成为【杀】的目标时，你进行判定。若结果为红色，则取消此目标。',
	qmsgswkjsgj_tspowei: '破围',
	qmsgswkjsgj_tspowei_info: `使命技。①游戏开始时，你令所有其他角色获得一个“围”，你对有“围”的角色使用【杀】没有距离限制。②一名角色受到伤害后，你可以移去其“围”。③回合开始时，你可重新分配场上的“围”标记。④一名其他角色的回合开始时，若其有“围”，则你可以选择一项：⒈对其造成1点伤害。⒉你获得其一张手牌。背水，你视为在其攻击范围内直到回合结束。⑤使命：回合开始时，若场上“围”标记数不大于X（X为你的体力上限），则你获得技能${get.poptip('qmsgswkjsgj_shenzhu')}。⑥失败：当你进入濒死状态时，你将体力值回复至上限。`,
	qmsgswkjsgj_shenzhu: '神著',
	qmsgswkjsgj_shenzhu_info: '锁定技，当你使用【杀】结算结束后，你选择一项：①摸一张牌，且本回合使用【杀】的次数上限+1。②摸X张牌，且本回合不能再使用【杀】（X为你的体力上限）。',
	// qmsgswkjsgj_dangmo: "荡魔",
	// qmsgswkjsgj_dangmo_info: "当你于出牌阶段内使用第一张【杀】选择目标后，你可以为此牌增加至多X个目标（X为你的体力上限）。",
	qmsgswkjsgj_shentianyi: '天义',
	qmsgswkjsgj_shentianyi2: '天义',
	qmsgswkjsgj_shentianyi_info: '出牌阶段限一次，你可以和一名其他角色拼点。若你赢，你获得以下技能效果直到回合结束：你使用【杀】没有距离限制；可额外使用一张【杀】；使用【杀】时可额外指定一个目标。',
	qmsgswkjsgj_shenhanzhan: '酣战',
	qmsgswkjsgj_shenhanzhan_info: '①当你发起拼点时，或成为拼点的目标时，你可以令对方选择拼点牌的方式改为随机选择一张手牌。②当你拼点结束后，你可以获得本次拼点的拼点牌中点数最大的牌。',

	qmsgswkjsgj_yanxiang: '星月界阎象',
	qmsgswkjsgj_yanxiang_prefix: '星月|界',
	qmsgswkjsgj_kujian: '苦谏',
	qmsgswkjsgj_kujian_info: '出牌阶段限一次，你可以将任意张手牌称为“谏”并交给一名其他角色，然后你获得以下效果：其他角色失去“谏”后，若为因使用或打出而失去，你与其各摸两张牌。“谏”牌不计入手牌上限。',
	qmsgswkjsgj_ruilian: '睿敛',
	qmsgswkjsgj_ruilian_info: '每轮开始时，你可以选择一名角色。你与其回合结束时，你可以选择一种类别，你与其各从弃牌堆中获得一张此类别的牌。',

	qmsgswkjsgj_mb_luyusheng: '星月界势陆郁生',
	qmsgswkjsgj_mb_luyusheng_prefix: '星月|界|势',
	qmsgswkjsgj_mbrunwei: '润微',
	qmsgswkjsgj_mbrunwei_info: '出牌阶段限一次，你可以展示牌堆顶至多五张牌，令一名角色获得其中一种颜色的所有牌。若如此做，你失去X张牌后（X为其因此获得的牌数），该技能可以再次发动。',
	qmsgswkjsgj_mbshuanghuai: '霜怀',
	qmsgswkjsgj_mbshuanghuai_info: '每回合限一次，当与你距离1以内的角色受到伤害时，你可以选择一项：防止此伤害；令其从弃牌堆中获得一张【桃】。若该角色与你上一次发动时相同，你与其各摸一张牌。',
	qmsgswkjsgj_mbshuanghuaiplus: '霜怀',
	qmsgswkjsgj_mbshuanghuaiplus_info: '每回合限一次，当有角色受到伤害时，你可以选择一项：防止此伤害；令其从弃牌堆中获得一张【桃】。若该角色与你上一次发动时相同，你与其各摸一张牌。',
	//啊？

	qmsgswkjsgj_pot_weiyan: '星月界势魏延',
	qmsgswkjsgj_pot_weiyan_prefix: '星月|界|势',
	qmsgswkjsgj_potzhongao: '忠傲',
	qmsgswkjsgj_potzhongao_info: `使命技，①游戏开始时，你获得${get.poptip('qmsgswkjsgj_potkuanggu')}。②成功：你杀死一名角色后，升级〖狂骨〗，然后若你本阶段使用的牌数：小于因〖壮誓〗弃置的牌数，摸一张牌；小于因〖壮誓〗失去的体力值，回复1点体力（体力值已满则改为摸一张牌）。③失败：你进入濒死，或你未于出牌阶段开始时执行〖壮誓〗，失去〖壮誓〗并获得${get.poptip('kunfenx')}。（全民三国杀我开局神郭嘉）`,
	qmsgswkjsgj_potzhuangshi: '壮誓',
	qmsgswkjsgj_potzhuangshi_info: '出牌阶段开始时，你可以执行任意项：1.弃置任意张手牌，令你此阶段使用的前等量+1张牌无距离限制且不可被响应；2.失去任意点体力，令你此阶段使用的前等量+1张牌不计入次数限制。',
	qmsgswkjsgj_potzhuangshi_tag: '已选择弃置',
	qmsgswkjsgj_potyinzhan: '饮战',
	qmsgswkjsgj_potyinzhan_info: `锁定技，你对一名角色造成伤害时，若：1.你的体力值小于等于其，此伤害+1；2.你的牌数小于等于其，你于此牌结算结束后弃置其一张牌；${get.poptip('rule_chengshi')}：你回复1点体力，获得其弃置的牌。`,
	qmsgswkjsgj_potkuanggu: '狂骨',
	qmsgswkjsgj_potkuanggu_info: '你对一名角色造成1点伤害后，可以选择一项：1.回复1点体力；2.摸一张牌。',
	qmsgswkjsgj_potkuanggu_pot_weiyan_achieve: '狂骨·二级',
	qmsgswkjsgj_potkuanggu_pot_weiyan_achieve_info: `你对一名角色造成1点伤害后，可以选择一项：1.回复1点体力；2.摸一张牌；3.${get.poptip('rule_beishui')}：弃置一张牌并令你此阶段使用【杀】的次数+1。`,

	qmsgswkjsgj_pot_taishici: '星月界势太史慈',
	qmsgswkjsgj_pot_taishici_prefix: '星月|界|势',
	qmsgswkjsgj_pothanzhan: '酣战',
	qmsgswkjsgj_pothanzhan_info: '出牌阶段限一次，你可以选择一名其他角色，你将手牌数摸至X张（X为你的体力上限且至多摸5张），然后你视为对其使用一张【决斗】。',
	qmsgswkjsgj_potzhanlie: '战烈',
	qmsgswkjsgj_potzhanlie_info: '每名角色回合中的杀进入弃牌堆时，若此牌在弃牌堆内，你获得1个“烈”标记，你至多拥有6个“烈”标记。你的出牌阶段结束时，你可移除任意数量的“烈”标记，视为使用一张无次数限制的【杀】并选择以下选项中的至多X项（X为你本次移除的标记数）：1.此【杀】目标+1；2.此【杀】基础伤害值+1；3.此【杀】需额外弃置一张牌方可响应。4.此【杀】结算结束后你摸两张牌。',
	qmsgswkjsgj_potzhenfeng: '振锋',
	qmsgswkjsgj_potzhenfeng_info: '限定技，出牌阶段或当你进入濒死状态时，你可以选择一项：①回复2点体力；②膝盖战烈的你的出牌阶段结束时为每名角色出牌阶段结束时，直到你的下个回合开始。',
	qmsgswkjsgj_potzhenfeng_append: '本体战烈改不了。<br>其实也不是不能改，只是会显得我有大病',
	//②修改〖酣战〗和〖战烈〗描述中的“X”为当前体力值、已损失体力值、场上人数中的一项（拥有对应技能方可选择）

	qmsgswkjsgj_pot_yuji: '星月界势于吉',
	qmsgswkjsgj_pot_yuji_prefix: '星月|界|势',
	qmsgswkjsgj_potfuji: '符济',
	qmsgswkjsgj_potfuji_info: '出牌阶段限一次，你可以展示至多X张牌并交给任意角色，称为“符济”（X为场上角色数）。其角色使用“符济”牌时获得一张与“符济”牌花色相同的牌；然后若此牌为：【杀】，此牌造成的伤害+1；【闪】，结算完毕后其摸一张牌；【桃】，回复数值+1；【酒】，其可弃置场上一张牌。然后若你的手牌数为全场最低，则你摸一张牌，且你使用的下一张【杀】【闪】【桃】【酒】视为拥有对应效果直到你的下个回合开始（可叠加）。',
	qmsgswkjsgj_potdaozhuan: '道转',
	qmsgswkjsgj_potdaozhuan_info: '每回合每种牌名限一次限一次，你可以将你或者当前回合角色的一张牌置入弃牌堆，视为使用一张基本牌。若当前回合角色因此失去了牌，则本回合此技能失效。',

	//界新杀武将
	qmsgswkjsgj_re_zhangxuan: '星月界张嫙',
	qmsgswkjsgj_re_zhangxuan_prefix: '星月|界',
	// tongli: "同礼",//小说提及，同礼没变化。
	// //tongli_info:'当你于出牌阶段内不因〖同礼〗而使用基本牌或普通锦囊牌指定第一个目标后，若你手牌中的花色数和你于本阶段内不因〖同礼〗而使用过的牌数相等，则你可以于此牌结算结束后依次视为对此牌的所有目标使用X张名称和属性相同的牌（X为你手牌中的花色数）。',
	// tongli_info: "当你于出牌阶段内使用基本牌或普通锦囊牌指定第一个目标后，若你手牌中的花色数和你于本阶段内使用过的牌数相等，则你可以令此牌额外结算X次（X为你手牌中的花色数）。",
	qmsgswkjsgj_re_shezang: '奢葬',
	qmsgswkjsgj_re_shezang_info: '当有角色进入濒死状态时，你可以从牌堆中获得每种花色的牌各一张。',

	qmsgswkjsgj_re_chenshi: '星月界陈式',
	qmsgswkjsgj_re_chenshi_prefix: '星月|界',
	qmsgswkjsgj_re_qingbei: '擎北',
	qmsgswkjsgj_re_qingbei_info: '①每轮开始时，你可以选择任意种花色，你不能于本轮内使用这些花色的牌。②你使用牌结算结束后，你摸X张牌（X为你本轮〖擎北①〗选择的花色数+1）。',

	qmsgswkjsgj_re_dc_tengfanglan: '星月界滕芳兰',
	qmsgswkjsgj_re_dc_tengfanglan_prefix: '星月|界',
	qmsgswkjsgj_re_dcluochong: '落宠',
	qmsgswkjsgj_re_dcluochong_info: '每轮开始时，你可以弃置任意名角色区域里的共计至多[4]张牌。（全民三国杀我开局神郭嘉）',
	qmsgswkjsgj_re_dcaichen: '哀尘',
	qmsgswkjsgj_re_dcaichen_info: '锁定技。当你每次发动〖落宠〗弃置你区域内的牌后，你摸两张牌；你跳过弃牌阶段。（全民三国杀我开局神郭嘉）',
	qmsgswkjsgj_re_dcluochongplus: '落宠',
	qmsgswkjsgj_re_dcluochongplus_info: '每轮开始时，你可以弃置任意名角色区域里的共计至多[5]张牌。（全民三国杀我开局神郭嘉）',
	qmsgswkjsgj_re_dcaichenplus: '哀尘',
	qmsgswkjsgj_re_dcaichenplus_info: '锁定技。当你每次发动〖落宠〗弃置你区域内的1张牌后，你摸两张牌；你跳过弃牌阶段。（全民三国杀我开局神郭嘉）',
	//还能补强？

	qmsgswkjsgj_re_zhenghun: '星月界郑浑',
	qmsgswkjsgj_re_zhenghun_prefix: '星月界',
	// qmsgswkjsgj_re_dcqiangzhi: "强峙",//原文提及，没变化
	// qmsgswkjsgj_re_dcqiangzhi_info: "出牌阶段限一次。你可以弃置你和一名其他角色的共计三张牌。然后若你与其之中有角色因此失去了三张牌，该角色对另一名角色造成1点伤害。",
	qmsgswkjsgj_re_dcpitian: '辟田',
	qmsgswkjsgj_re_dcpitian_info: '①当你的一张牌被弃置后，或当你受到一点伤害后，你的手牌上限+1。②结束阶段，若你的手牌数小于手牌上限，你可以摸至手牌上限。',
	qmsgswkjsgj_re_dcqiangzhiplus: "强峙",//后文提及，有补强
	qmsgswkjsgj_re_dcqiangzhiplus_info: "出牌阶段限两次。你可以弃置你和一名其他角色的共计三张牌。然后若你与其之中有角色因此失去了三张牌，该角色对另一名角色造成1点伤害。",
	//还能补强也是醉了

	qmsgswkjsgj_re_re_liuzan: '星月界留赞',
	qmsgswkjsgj_re_re_liuzan_prefix: '星月|界',
	qmsgswkjsgj_re_refenyin: '奋音',
	qmsgswkjsgj_re_refenyin_info: '锁定技，你的回合内，当一张牌进入弃牌堆后，若本回合内没有过与此牌点数相同的卡牌进入过弃牌堆，则你摸一张牌。（全民三国杀我开局神郭嘉）',
	qmsgswkjsgj_re_liji: '力激',
	qmsgswkjsgj_re_liji_info: '出牌阶段限X+1次，你可以弃置一张牌并对一名其他角色造成1点伤害。（X为本回合内进入过弃牌堆的卡牌数除以3，向下取整）（全民三国杀我开局神郭嘉）',

	qmsgswkjsgj_re_wupu: '星月界吴普',
	qmsgswkjsgj_re_wupu_prefix: '星月|界',
	qmsgswkjsgj_re_dcduanti: '锻体',
	qmsgswkjsgj_re_dcduanti_info: '锁定技。每失去三张牌后，你回复一点体力并增加一点体力上限（至多+10）。',
	qmsgswkjsgj_re_dcshicao: '识草',
	qmsgswkjsgj_re_dcshicao_info: '出牌阶段，你可以声明一种类型，然后选择从牌堆顶或牌堆底摸一张牌。若此牌类型与你声明的类型不同，你观看牌堆另一端的三张牌，此技能本回合失效。',

	qmsgswkjsgj_re_ruanyu: '星月界阮瑀',
	qmsgswkjsgj_re_ruanyu_prefix: '星月|界',
	qmsgswkjsgj_re_xingzuo: '兴作',
	qmsgswkjsgj_re_xingzuo2: '兴作',
	qmsgswkjsgj_re_xingzuo_info: '出牌阶段限一次，你可观看牌堆底的五张牌并用任意张手牌替换其中等量的牌。若如此做，结束阶段，你可令一名角色用所有手牌替换牌堆底的五张牌。',
	qmsgswkjsgj_re_miaoxian: '妙弦',
	qmsgswkjsgj_re_miaoxian_info: '若你的手牌中仅有一张黑色牌，你可将此牌当作任意一张锦囊牌或基本牌使用；若你的手牌中仅有一张红色牌，你使用或打出此牌时摸一张牌，此牌无距离和次数限制且无法被响应。',

	qmsgswkjsgj_re_dc_duyu: '星月界杜预',
	qmsgswkjsgj_re_dc_duyu_prefix: '星月|界',
	qmsgswkjsgj_re_dcjianguo: '谏国',
	qmsgswkjsgj_re_dcjianguo_info: '出牌阶段各限一次。你可以选择一名角色并选择一项：1.令其弃置一半的手牌，若其弃置的牌数量小于你的体力值，你对其造成一点伤害；2.令其摸等同于手牌数一半的牌，若其摸牌数量大于等于你的体力值，你回复一点体力。（均向上取整）',
	qmsgswkjsgj_re_dcdyqingshi: '倾势',
	qmsgswkjsgj_re_dcdyqingshi_info: '当你于回合内使用牌后，若此牌为你本回合使用的第X张牌，你可以对一名角色造成1点伤害（X为你的手牌数）。',

	qmsgswkjsgj_re_star_caoren: '星月界星曹仁',
	qmsgswkjsgj_re_star_caoren_prefix: '星月|界|星',
	qmsgswkjsgj_re_starsujun: '肃军',
	qmsgswkjsgj_re_starsujun_info: '游戏开始时或你手牌数变动后，若你手牌中的基本牌和非基本牌的牌数相等，你可以摸两张牌。',
	qmsgswkjsgj_re_starlifeng: '砺锋',
	qmsgswkjsgj_re_starlifeng_info: '你可以将一张本回合未有角色使用过的花色的手牌当做无次数限制且不计入次数的【杀】或【无懈可击】使用。',

	qmsgswkjsgj_re_dc_xiahouhui: '星月界新杀夏侯徽',
	qmsgswkjsgj_re_dc_xiahouhui_prefix: '星月|界|新杀',
	qmsgswkjsgj_re_dcdujun: '笃君',
	qmsgswkjsgj_re_dcdujun_info: '游戏开始时，你选择一名其他角色，你不能响应其使用的牌。每回合限X次，你与其造成或受到1点伤害后，你可摸两张牌，然后（可以</小说里按照十周年描述写的，没加可以，这里应当可以>）将两张牌交给其他角色（X为你的体力上限）。',
	qmsgswkjsgj_re_dcjikun: '济困',
	qmsgswkjsgj_re_dcjikun_info: '每当你累计失去五张牌后，你可令一名角色获得其他角色的一张牌。',

	qmsgswkjsgj_re_panghong: '星月界庞宏',
	qmsgswkjsgj_re_panghong_prefix: '星月|界',
	qmsgswkjsgj_re_dcpingzhi: '评骘',
	qmsgswkjsgj_re_dcpingzhi_info: '转换技。出牌阶段限三次，你可观看一名角色的手牌并展示其中一张牌，阳：你弃置此牌，然后其视为对你使用一张【火攻】，若其未因此造成伤害则此技能视为未发动过；阴：然后你代替其使用此牌</据小说解释，本质上就算是那个人使用这张牌，这是盻睇吗>，若此牌造成伤害则此技能视为未发动过。',
	qmsgswkjsgj_re_dcgangjian: '刚简',
	qmsgswkjsgj_re_dcgangjian_info: '锁定技。每个回合结束时，你摸X张牌（X为本回合展示过的牌数至多为5）</作者又开始了，把展示牌堆的牌也计入其内了。云玩家写小说是这样的>。',

	qmsgswkjsgj_re_zhujianping: '星月界朱建平',
	qmsgswkjsgj_re_zhujianping_prefix: '星月|界',
	qmsgswkjsgj_re_dcxiangmian: '相面',
	qmsgswkjsgj_re_dcxiangmian_info: '出牌阶段限两次。你可以令一名其他角色判定，其获得以下效果：当其使用结果的花色的牌后，或当其使用X张牌后（X为结果的点数），其失去等同于其体力值的体力。',
	qmsgswkjsgj_re_dctianji: '天机',
	qmsgswkjsgj_re_dctianji_info: '锁定技。当判定牌生效后，你从牌堆或弃牌堆随机获得分别与该牌类型、花色和点数相同的牌各一张。',
	qmsgswkjsgj_re_dcxiangmianplus: '相面',
	qmsgswkjsgj_re_dcxiangmianplus_info: '出牌阶段限两次。你可以令一名其他角色判定，其获得以下效果：当其失去结果的花色的牌后，或当其失去X张牌后（X为结果的点数），其失去等同于其体力值的体力。',
	qmsgswkjsgj_re_dcxiangmianplusplus: '相面',
	qmsgswkjsgj_re_dcxiangmianplusplus_info: '出牌阶段限两次。你可以令一名其他角色判定，其获得以下效果：当其失去结果的花色的牌后，或当其失去点数不小于X的牌后（X为结果的点数），其失去等同于其体力值的体力。',
	//作者不动声色，直接改前文描述，如果不是后文实战发现不对劲，我都没发现
	//后文实战发现，对一个人发动两次后，会选择保留哪个结果。这个到时候也在代码里表现出来
	//不实现了

	qmsgswkjsgj_re_guotiying: '星月界郭缇萦',
	qmsgswkjsgj_re_guotiying_prefix: '星月|界',
	qmsgswkjsgj_re_dckanyu: '堪舆',
	qmsgswkjsgj_re_dckanyu_info: '一名角色进行判定或当你受到1点伤害后，你可观看牌堆顶与牌堆底各两张牌，然后可获得其中任意张牌，并将剩余牌以任意顺序放回。若你以此法获得牌，【闪电】对你的生效范围增加你所获得牌的花色点数组合。',
	qmsgswkjsgj_re_dczhee: '谪厄',
	qmsgswkjsgj_re_dczhee_info: '锁定技，游戏开始时/每回合结束时，你将牌堆/弃牌堆中的一张【闪电】置入一号位/当前回合角色的下家判定区。',
	// tiandu_qmsgswkjsgj_re_guotiying:'天妒',
	// tiandu_qmsgswkjsgj_re_guotiying_info:'星月界郭缇萦的语音',

	qmsgswkjsgj_re_caofang: '星月界曹芳',
	qmsgswkjsgj_re_caofang_prefix: '星月|界',
	qmsgswkjsgj_re_dczhimin: '置民',
	qmsgswkjsgj_re_dczhimin_tag: '民',
	qmsgswkjsgj_re_dczhimin_info: '锁定技。①每轮开始时或回合内限一次，你选择至多X名其他角色（X为你的体力上限），获得这些角色各自手牌中的随机一张点数最小的牌。②当你于你的回合外得到牌后，你将这些牌标记为“民”。③当你失去“民”后，你将手牌补至体力上限。',
	qmsgswkjsgj_re_dczhimin_append: '尚未实战，盲猜是每回合限一次，出牌阶段……',
	qmsgswkjsgj_re_dcjujian: '拒谏',
	qmsgswkjsgj_re_dcjujian_info: '主公技。出牌阶段每名角色限一次，你可以令一名其他魏势力角色1：摸一张牌；2：本轮内其使用的普通锦囊牌对你无效。',

	qmsgswkjsgj_re_guozhao: '星月界郭照',
	qmsgswkjsgj_re_guozhao_prefix: '星月|界',
	qmsgswkjsgj_re_pianchong: '偏宠',
	qmsgswkjsgj_re_pianchong_info: '每轮开始时或摸牌阶段开始时选择一项：1.你每失去一张红色牌时摸一张黑色牌，2.你每失去一张黑色牌时摸一张红色牌。摸牌阶段，你可以改为从牌堆获得红牌和黑牌各一张。',
	qmsgswkjsgj_re_zunwei: '尊位',
	qmsgswkjsgj_re_zunwei_backup: '尊位',
	qmsgswkjsgj_re_zunwei_info: "出牌阶段限一次，你可选择一项：①若你已受伤，则你可以选择一名体力值大于你的其他角色，你将体力值回复至X（X为你的体力上限与其体力值中的较小值）②选择一名手牌数大于你的其他角色，你将手牌数摸至与其相同（至多摸五张）③选择一名装备区内牌数大于你的其他角色。你令X=1。若你装备区内的('equip'+X)栏为空，则你使用牌堆中的一张副类别为('equip'+X)，且能对自己使用的装备牌。你令X+1。若X不大于5，且你装备区内的牌数仍小于目标角色，则你重复此流程。",
	qmsgswkjsgj_re_zunwei_append: '实际描述是先选目标再选效果。不过距离效果大差不差，就这么地了',

	qmsgswkjsgj_re_caomao: '星月界曹髦',
	qmsgswkjsgj_re_caomao_prefix: '星月|界',
	qmsgswkjsgj_re_qianlong: '潜龙',
	qmsgswkjsgj_re_qianlong_info: '当你受到伤害后，你可以亮出牌堆顶你的体力上限数张牌并获得其中的至多X张牌（X为你已损失的体力值）<小说主角特有的傲骨，不设下限>，然后将剩余的牌置于牌堆底。',
	// qmsgswkjsgj_re_fensi: "忿肆",
	// qmsgswkjsgj_re_fensi_info: "锁定技。准备阶段，你须选择一名体力值不小于你的角色并对其造成1点伤害，然后若你选择的角色不为你自己，则其视为对你使用一张【杀】。",
	qmsgswkjsgj_re_juetao: '决讨',
	qmsgswkjsgj_re_juetao_info: '出牌阶段开始时，若你的体力值为1，则你可以选择一名其他角色。你亮出牌堆底的一张牌，若此牌能被你使用，则你使用此牌并重复此流程直到出现不可使用的牌或其死亡（你与其以外的角色不是此牌的合法目标）。',
	qmsgswkjsgj_re_zhushi: '助势',
	qmsgswkjsgj_re_zhushi_info: '主公技。其他魏势力角色回复体力时，你可以摸一张牌。',

	qmsgswkjsgj_shen_pangtong: '星月神庞统',
	qmsgswkjsgj_shen_pangtong_prefix: '星月|神',
	// luansuo: "鸾锁",
	// luansuo_info: "锁定技。①你的回合内，所有角色不能弃置手牌。②回合开始时，所有角色的当前手牌视为【铁索连环】直到有与此牌对应花色的牌进入弃牌堆或回合结束。",
	// fengliao: "凤燎",
	// fengliao_info: "锁定技，转换技，你使用牌指定唯一目标后，阳：你令其摸一张牌；阴：你对其造成1点火焰伤害。",
	qmsgswkjsgj_kunyu: '鹍浴',
	qmsgswkjsgj_kunyu_info: '锁定技。②你死亡时，你将牌堆中的一张火属性伤害牌移出游戏，然后防止死亡并将体力回复至1点。',

	qmsgswkjsgj_re_yue_caiwenji: '星月界乐蔡琰',
	qmsgswkjsgj_re_yue_caiwenji_prefix: '星月|界|乐',
	qmsgswkjsgj_re_dcshuangjia: '霜笳',
	// qmsgswkjsgj_re_dcshuangjia_tag: "胡笳",
	qmsgswkjsgj_re_dcshuangjia_info: '锁定技。①每轮开始时，你的手牌增加“胡笳”标记。③其他角色至你的距离+X（X为你的“胡笳”数且至多为5）。',
	qmsgswkjsgj_re_dcbeifen: '悲愤',
	qmsgswkjsgj_re_dcbeifen_info: '锁定技。①当你失去牌后，若这些牌中有“胡笳”牌，你获得与该牌花色均不同的每种花色的牌各一张。②若你手牌中“胡笳”牌数小于不为“胡笳”牌的牌数，你使用牌无距离和次数限制。',

	qmsgswkjsgj_re_dc_liuba: '星月界刘巴',
	qmsgswkjsgj_re_dc_liuba_prefix: '星月|界',
	qmsgswkjsgj_re_dczhubi: '铸币',
	qmsgswkjsgj_re_dczhubi_info: '当有♦牌因弃置而进入弃牌堆后，你可以令一名角色从牌堆或弃牌堆获得一张【无中生有】，然后其可以将【无中生有】置于牌堆顶。',
	qmsgswkjsgj_re_dcliuzhuan: '流转',
	qmsgswkjsgj_re_dcliuzhuan_tag: "转",
	qmsgswkjsgj_re_dcliuzhuan_info: '锁定技，其他角色的回合内获得的牌无法对你使用，这些牌本回合进入弃牌堆后，你获得之<按照作者的解释，只是本回合不能对自己用，下回合是可以的。评价为：继承了新杀的描述含糊不清和云玩家的口胡>。',

	qmsgswkjsgj_re_zhugejin: '星月界诸葛瑾',
	qmsgswkjsgj_re_zhugejin_prefix: '星月|界',
	qmsgswkjsgj_re_huanshi: '缓释',
	qmsgswkjsgj_re_huanshi_info: '一名角色的判定牌生效前，你可令其观看你的手牌。若如此做，你打出一张牌代替之。',
	qmsgswkjsgj_re_hongyuan: '弘援',
	qmsgswkjsgj_re_hongyuan_info: '摸牌阶段，你可以少摸一张牌并指定至多两名其他角色。若如此做，这些角色各摸两张牌。',
	qmsgswkjsgj_re_mingzhe: '明哲',
	qmsgswkjsgj_re_mingzhe_info: '当你于回合外失去一张红色牌后，你可以摸两张牌。',

	qmsgswkjsgj_re_yuanyin: '星月界袁胤',
	qmsgswkjsgj_re_yuanyin_prefix: '星月|界',
	qmsgswkjsgj_re_dcmoshou: '墨守',
	qmsgswkjsgj_re_dcmoshou_info: '当你成为一名角色使用的黑色牌的目标后，你可以摸体力上限张牌。',
	qmsgswkjsgj_re_dcyunjiu: '运柩',
	qmsgswkjsgj_re_dcyunjiu_info: '一名角色死亡后，你可以加1点体力上限并回复1点体力，然后你可交给任意角色该角色死亡时弃置的牌。',

	qmsgswkjsgj_re_sp_zhenji: '星月界SP甄宓',
	qmsgswkjsgj_re_sp_zhenji_prefix: '星月|界|SP',
	qmsgswkjsgj_re_dcjijie: '己诫',
	qmsgswkjsgj_re_dcjijie_info: '锁定技。每回合每项各限X次（X为你的体力上限），其他角色于其回合外得到牌后/回复体力后，你摸等量的牌/回复等量的体力。',
	qmsgswkjsgj_re_dchuiji: '惠济',
	qmsgswkjsgj_re_dchuiji_info: '出牌阶段限一次。你可以令一名角色摸两张牌或从牌堆中使用一张你指定牌名的装备牌，然后若其手牌数不小于存活角色数，其视为使用一张【五谷丰登】。系统不于此牌使用准备工作结束时执行亮出牌堆顶的牌的动作，改为你令其将所有手牌置于处理区，然后令所有目标角色依次获得其中一张牌。当这些牌因执行【五谷丰登】的执行动作而置于弃牌堆后，你令其获得这些牌。',

	qmsgswkjsgj_mb_shen_jiangwei: '星月手杀神姜维', //血上限+1即5
	qmsgswkjsgj_mb_shen_jiangwei_prefix: '星月|手杀|神',
	qmsgswkjsgj_mbtiantao: '天涛',
	qmsgswkjsgj_mbtiantao_info: '锁定技，结束阶段，你选择一个区域并弃置其中所有牌，然后依次弃置任意名其他角色相同区域所有牌，因此弃置牌且未弃置【杀】的角色失去1点体力。',
	qmsgswkjsgj_mbxinghun: '星魂',
	qmsgswkjsgj_mbxinghun_info: '出牌阶段限一次，你可以观看牌堆顶9张牌，用任意张手牌与其中的等量张牌进行交换并任意排序，然后你令一名其他角色展示你的手牌与牌堆顶的共计9张牌，你对其依次使用其中的【杀】。',
	qmsgswkjsgj_mbshenpei: '神霈',
	qmsgswkjsgj_mbshenpei_info: `限定技，当你进入濒死状态时，你可以回复X点体力(X为你本局游戏进入过濒死状态的次数)，然后对一名角色造成等量点雷电伤害并获得${get.poptip('qmsgswkjsgj_mbhuitian')}。`,
	qmsgswkjsgj_mbhuitian: '回天',
	qmsgswkjsgj_mbhuitian_info: '一名角色的回合开始时，你可以摸两张牌并执行一个额外的回合。每轮开始时，若你发动过此技能超过9次，你死亡。',
	// qmsgswkjsgj_tiaoxin:'挑衅',
	// qmsgswkjsgj
	//同retiaoxin
	qmsgswkjsgj_zhiji: '志继',
	qmsgswkjsgj_zhiji_info: `觉醒技，准备阶段或结束阶段，若你没有手牌，你回复1点体力或摸两张牌，然后减1点体力上限，获得技能${get.poptip("qmsgswkjsgj_jwguanxing")}和${get.poptip("kongcheng")}。`,
	qmsgswkjsgj_jwguanxing: '观星',
	qmsgswkjsgj_jwguanxing_info: '准备阶段，你可以观看牌堆顶5张牌，然后将其中任意数量的牌置于牌堆顶，将其余的牌置于牌堆底。',

	qmsgswkjsgj_re_liushan: '星月界刘禅',
	qmsgswkjsgj_re_liushan_prefix: '星月|界',
	qmsgswkjsgj_re_xiangle: '享乐',
	qmsgswkjsgj_re_xiangle_info: '锁定技，你不能对其他角色使用【杀】，其他角色对你使用【杀】无效。',
	qmsgswkjsgj_re_fangquan: '放权',
	qmsgswkjsgj_re_fangquan_info: '弃牌阶段开始时，你可以弃置一张牌并令一名其他角色获得一个额外的回合。',
	// qmsgswkjsgj_re_ruoyu:'若愚',//同ol若愚
	// qmsgswkjsgj_re_ruoyu_info: `主公技，觉醒技，准备阶段，若你的体力是全场最少的(或之一)，你须增加1点体力上限并回复体力至3点，然后获得技能${get.poptip("rejijiang")}和${get.poptip("sishu")}。`,

	qmsgswkjsgj_re_caojinyu: '星月界曹金玉',
	qmsgswkjsgj_re_caojinyu_prefix: '星月|界',
	qmsgswkjsgj_re_yuqi: '隅泣',
	qmsgswkjsgj_re_yuqi_info: '每回合限<span class=YB_snowtext>2</span>次。当有角色受到1点伤害后，若你至其的距离不大于<span class=thundertext>1</span>，则你可以观看牌堆顶的<span class=firetext>3</span>张牌。你将其中至多<span class=greentext>0</span>张牌交给受伤角色，然后可以获得剩余牌中的至多<span class=yellowtext>2</span>张牌，并将其余牌以原顺序放回牌堆顶。（所有具有颜色的数字至多为体力上限）（全民三国杀我开局神郭嘉的界曹金玉）',
	qmsgswkjsgj_re_shanshen: '善身',
	qmsgswkjsgj_re_shanshen_info: '当有角色进入濒死状态时，你可令你的〖隅泣〗中的一个具有颜色的数字+2。然后若不是你令该角色进入濒死状态，且进入濒死状态的角色不为你，你回复1点体力。（全民三国杀我开局神郭嘉的界曹金玉）',
	qmsgswkjsgj_re_xianjing: '娴静',
	qmsgswkjsgj_re_xianjing_info: '准备阶段，你可令你的〖隅泣〗中的一个具有颜色的数字+1。若你的体力值等于体力上限，则你可以重复一次此流程。结束阶段，你可令你的〖隅泣〗中的一个具有颜色的数字+1。（全民三国杀我开局神郭嘉的界曹金玉）',

	qmsgswkjsgj_re_yue_zhouyu: '星月界乐周瑜',
	qmsgswkjsgj_re_yue_zhouyu_prefix: '星月|界|乐',
	qmsgswkjsgj_re_dcguyin_tag:'琴音',
	qmsgswkjsgj_re_dcguyin: '顾音',
	qmsgswkjsgj_re_dcguyin_info: '锁定技。①你的初始手牌数为0，其他角色的初始手牌数+1。②每轮开始时，所有人的手牌增加“琴音”标记，带有“琴音”标记的牌进入弃牌堆后，你摸一张牌。你没有手牌时，受到伤害-1。',
	qmsgswkjsgj_re_dcpinglu: '平虏',
	qmsgswkjsgj_re_dcpinglu_info: '出牌阶段，你可以获得攻击范围内所有其他角色各一张牌。若如此做，直到这些牌离开你的手牌区，本技能此阶段失效。',

	qmsgswkjsgj_re_bolingyun: '星月界柏灵筠',
	qmsgswkjsgj_re_bolingyun_prefix: '星月|界',
	qmsgswkjsgj_re_dclinghui: '灵慧',
	qmsgswkjsgj_re_dclinghui_info: '一名角色的结束阶段，若当前回合角色为你或本回合有角色受到过伤害，则你可以观看牌堆顶的X张牌（X为你的体力上限），然后你可以使用其中一张牌并获得其中一张剩余牌，然后将剩余牌以任意顺序放回牌堆顶。',
	qmsgswkjsgj_re_dcxiace: '黠策',
	qmsgswkjsgj_re_dcxiace_info: '当你造成/受到伤害后，你可以弃置一张牌并回复1点体力/令一名其他角色的非锁定技于本回合失效。',
	qmsgswkjsgj_re_dcyuxin: '御心',
	qmsgswkjsgj_re_dcyuxin_info: '限定技，一名角色进入濒死状态时，你可以令其将体力回复至3点。',

	qmsgswkjsgj_re_v_zhangliao: '星月界威张辽',
	qmsgswkjsgj_re_v_zhangliao_prefix: '星月|界|威',
	qmsgswkjsgj_re_dcyuxi: '驭袭',
	qmsgswkjsgj_re_dcyuxi_info: '当你造成或受到1点伤害时，你可以摸一张牌。你使用以此法获得的牌无次数限制。',
	qmsgswkjsgj_re_dcporong: '破戎',
	qmsgswkjsgj_re_dcporong_info: '连招技（非【杀】 + 【杀】）。你可以获得目标角色与其相邻角色的各一张牌，且此牌额外结算一次。',

	//神郭嘉再加强
	qmsgswkjsgj_plus_shen_guojia:'星月神神郭嘉',
	qmsgswkjsgj_plus_shen_guojia_prefix: '星月|神|神',
	qmsgswkjsgj_reshuishiplus: '慧识',
	qmsgswkjsgj_reshuishiplus_info: '出牌阶段限一次。若你的体力上限小于15，你可进行判定。若判定结果与本次发动技能时的其他判定结果的点数均不相同且你的体力上限小于15，则你加1点体力上限，且可以重复此流程。然后你将所有位于处理区的判定牌交给一名角色。若其手牌数为全场最多，则你减1点体力上限。（全民三国杀我开局神郭嘉的慧识。据作者剧情实战，天妒回收后不计入已判定）',
	qmsgswkjsgj_stianyiplus: '天翊',
	qmsgswkjsgj_stianyiplus_info: `觉醒技，若你受到伤害，你加2点体力上限并回复1点体力，然后令一名角色获得技能${get.poptip('qmsgswkjsgj_zuoxingplus')}。`,
	qmsgswkjsgj_zuoxingplus: '佐幸',
	qmsgswkjsgj_zuoxingplus2: '佐幸',
	qmsgswkjsgj_zuoxingplus_info: '每回合限一次，若令你获得〖佐幸〗的角色存活且体力上限大于1，则你可以令其减1点体力上限，并视为使用一张普通锦囊牌。',

	//神荀彧再加强
	qmsgswkjsgj_plus_shen_xunyu:'星月神神荀彧',
	qmsgswkjsgj_plus_shen_xunyu_prefix: '星月|神|神',
	qmsgswkjsgj_jiemingplus: '节命',
	qmsgswkjsgj_jiemingplus_info: '当你受到1点伤害时，你可以令一名角色摸X张牌，然后你摸一张牌（X为其体力上限且至多为5）。',
	qmsgswkjsgj_tianzuoplus: '天佐',
	qmsgswkjsgj_tianzuoplus_info: `锁定技。①游戏开始时，你将二十四张${get.poptip('qizhengxiangsheng')}加入牌堆。②${get.poptip('qizhengxiangsheng')}对你无效。③出牌阶段限一次，你可视为使用一张${get.poptip('qizhengxiangsheng')}。④当一名角色成为【奇正相生】的目标时，你可以查看其手牌，然后重新为其指定【正兵】或【奇兵】。`,

	qmsgswkjsgj_re_sb_simayi: '星月界新杀谋司马懿',
	qmsgswkjsgj_re_sb_simayi_prefix: '星月|界|新杀|谋',
	qmsgswkjsgj_re_dcsbquanmou: '权谋',
	qmsgswkjsgj_re_dcsbquanmou_info: '转换技。①游戏开始时，你可以转换此技能状态；②出牌阶段每名角色限一次，你可以令一名其他角色交给你一张牌。阳：当你于本阶段内下次对其造成伤害时，取消之；阴：当你于本阶段内下次对其造成伤害后，你可以选择至多X名其他角色，对这些角色依次造成1点伤害（X为你的体力上限）。（全民三国杀我开局神郭嘉）',
	qmsgswkjsgj_re_dcsbpingliao: '平辽',
	qmsgswkjsgj_re_dcsbpingliao_info: '锁定技。当你声明使用【杀】时，你令此【杀】的目标对其他角色不可见，且你令攻击范围内的其他角色依次选择是否打出一张基本牌。所有角色选择完成后，此牌的目标角色中没有以此法打出牌的角色本回合内无法使用或打出手牌；若有不为此牌目标的角色以此法打出了牌，则每有一名非目标打出一张基本牌，你摸两张牌且此阶段出【杀】次数+1。（全民三国杀我开局神郭嘉）（不支持其他版本的权谋）',

	qmsgswkjsgj_re_guanning: "星月界管宁",
	qmsgswkjsgj_re_guanning_prefix: "星月|界",
	qmsgswkjsgj_re_dunshi: "遁世",
	qmsgswkjsgj_re_dunshi_info: "每回合每种牌名限一次。你可以视为使用或打出一张【杀】/【闪】/【桃】/【酒】，然后当前回合角色于本回合内下一次造成伤害时，你选择两项：⒈防止此伤害。系统从技能名中包含“仁/义/礼/智/信”字样的技能中随机选择三个其未拥有的技能，然后你令当前回合角色获得其中一个技能。⒉从〖遁世〗中删除你本次使用或打出的牌并获得一个“席”。⒊减1点体力上限并摸X张牌（X为你的“席”数）。",

	qmsgswkjsgj_re_pangfengyi: "星月界庞凤衣",
	qmsgswkjsgj_re_pangfengyi_prefix: "星月|界",
	qmsgswkjsgj_re_dcyitong: "异瞳",
	qmsgswkjsgj_re_dcyitong_info: "锁定技。①游戏开始时，你记录一个花色。②〖异瞳〗记录花色的牌进入弃牌堆后，你从牌堆或弃牌堆获得与此花色不同的牌各一张。",
	qmsgswkjsgj_re_dcpeiniang: "醅酿",
	qmsgswkjsgj_re_dcpeiniang_info: "①你可以将〖异瞳〗记录花色的牌当作【酒】使用（无任何次数限制）。②其他角色处于濒死状态时，你可以对其使用【酒】（回复效果）。",

	//界关羽补强
	qmsgswkjsgj_re_guanyu: '星月界关羽',
	qmsgswkjsgj_re_guanyu_prefix: '星月|界',
	qmsgswkjsgj_re_wusheng:'武圣',
	qmsgswkjsgj_re_wusheng_info:'你可以将一张红色牌当无距离限制的【杀】使用或打出。',
	qmsgswkjsgj_re_yijue:'义绝',
	qmsgswkjsgj_re_yijue_info:'出牌阶段限一次，你可以弃置一名角色一张牌。若此牌为黑色，则其本回合非锁定技失效且不能使用或打出手牌，你对其使用的红桃【杀】伤害+1；若此牌为红色，则你获得之，然后你可令该角色回复1点体力。',

	//界马超补强
	qmsgswkjsgj_re_machao: '星月界马超',
	qmsgswkjsgj_re_machao_prefix: '星月|界',
	qmsgswkjsgj_re_tieji:'铁骑',
	qmsgswkjsgj_re_tieji_info:'当你使用【杀】指定目标后，你可令其直到其下个回合结束非锁定技失效，然后你进行判定，除非其弃置与结果花色相同的一张牌，否则其不能响应此杀。',//使用【闪】
	//没写抵消此杀，干脆让目标永久不能用闪吧，作者描述不规范背大锅
	//写起来太麻烦了，优化描述吧，仅不能响应此杀

	//界徐盛补强
	qmsgswkjsgj_re_xusheng: '星月界徐盛',
	qmsgswkjsgj_re_xusheng_prefix: '星月|界',
	qmsgswkjsgj_re_pojun:'破军',
	qmsgswkjsgj_re_pojun_info:'当你使用【杀】指定目标后，你可以将其的至多X张牌置于其武将牌上（X为其体力上限），然后其于当前回合结束时获得这些牌。当你使用【杀】对一名角色造成伤害时，若该角色的手牌数和装备区内的牌数均不大于你，则此伤害+1。',
	qmsgswkjsgj_re_pojun2:'破军',
	qmsgswkjsgj_re_pojun3:'破军',

	//神张辽
	qmsgswkjsgj_shen_zhangliao: '星月神张辽',
	qmsgswkjsgj_shen_zhangliao_prefix: '星月|神',
	qmsgswkjsgj_drlt_tuxi:'突袭',
	qmsgswkjsgj_drlt_tuxi_info:'摸牌阶段，你可以少摸任意张牌并获得等量其他角色的牌',
	qmsgswkjsgj_drlt_duorui:'夺锐',
	qmsgswkjsgj_drlt_duorui1:'夺锐',
	qmsgswkjsgj_drlt_duorui_info:'当你对一名其他角色造成伤害后，你可以废除其一个装备栏，然后选择该角色武将牌上的一个技能，令其此技能无效，且你获得该技能。',
	qmsgswkjsgj_drlt_zhiti:'止啼',
	qmsgswkjsgj_drlt_zhiti_info:'摸牌阶段你可以多摸X张牌（X为场上所有被废除的装备栏数），其他角色的弃牌阶段结束时，若其有被废除的装备栏，你可以弃置其等量张牌。其他角色有被废除的装备栏时，其不可响应你使用的牌。',

	//神刘备
	qmsgswkjsgj_shen_liubei: '星月神刘备',
	qmsgswkjsgj_shen_liubei_prefix: '星月|神',
	qmsgswkjsgj_nzry_rende:'仁德',
	qmsgswkjsgj_nzry_rende_info:'出牌阶段，你可以将任意张牌交给其他角色，然后你可以视为使用一张基本牌（无距离且不计入次数限制）',
	qmsgswkjsgj_nzry_longnu:'龙怒',
	qmsgswkjsgj_nzry_longnu_info:'转换技，出牌阶段限一次，阳：你可以失去1点体力并摸两张牌，然后本回合你的红色手牌均视为火【杀】且无距离和次数限制，你以此法造成伤害后，可以回复等量体力并摸等量张牌；阴：你可以减1点体力上限并摸两张牌，然后本回合你的锦囊牌均视为雷【杀】且无距离和次数限制，你以此法造成伤害后，可以增加等量体力上限并摸等量张牌。',
	qmsgswkjsgj_nzry_jieying:'结营',
	qmsgswkjsgj_nzry_jieying_info:'锁定技，你始终处于横置状态；你的手牌上限+4；准备阶段和结束阶段，你横置任意名其他角色。',

	qmsgswkjsgj_rejiemingplus:'节命',
	qmsgswkjsgj_rejiemingplus_info:'当你受到1点伤害后，你可以令一名角色摸两张牌。然后若其手牌数小于体力上限，则你摸一张牌。',

	//没错，界荀彧也有增强，虽然没有神荀彧那样，直接摸体力上限张牌，但也把摸牌数量增加到了三张，也是非常不错的提升了。
	//↑原文……
	//区区一个一笔带过的武将的补强我已经懒得整理了

	//神关羽
	qmsgswkjsgj_shen_guanyu: '星月神关羽',
	qmsgswkjsgj_shen_guanyu_prefix: '星月|神',
	qmsgswkjsgj_shen_wusheng:'武圣',
	qmsgswkjsgj_shen_wusheng_info:'你可以将一张牌当任意【杀】使用或打出；你使用方块【杀】无距离限制。',
	qmsgswkjsgj_wushen:'武神',
	qmsgswkjsgj_wushen_info:'锁定技，你的红桃手牌视为【杀】。你每阶段使用的第一张【杀】不可被响应。你使用红桃【杀】无距离和次数限制，且可以额外指定所有拥有“梦魇”标记的角色为目标。你对拥有“梦魇”标记的目标造成伤害后，你摸此【杀】造成伤害总数的牌。（全民三国杀我开局神郭嘉的神关羽，不适配其他梦魇标记）',
	qmsgswkjsgj_wuhun:'武魂',
	qmsgswkjsgj_wuhun_info:'当你受到1点伤害后，你令伤害来源获得1枚“梦魇”标记。当你对其他角色造成伤害后，你令其获得1枚“梦魇”标记。当你回复1点体力时，你可以移动1枚‘梦魇’标记。当你死亡时，你可以进行判定，若结果不为【桃】或【桃园结义】，你可以选择至少一名拥有“梦魇”标记的角色，令这些角色各自依次失去X点体力（X为其拥有的“梦魇”标记数）（全民三国杀我开局神郭嘉的神关羽，不适配其他梦魇标记）。',
	//【梦魇】：根据‘梦魇’标记数量，持有‘梦魇’标记的角色获得对应效果：1个，神关羽回合内非锁定技失效；3个，神关羽回合内所有技能失效；5个，非锁定技失效；7个，所有技能失效。
	//我：？？？这怎么实现

	//神吕蒙
	qmsgswkjsgj_shen_lvmeng: '星月神吕蒙',
	qmsgswkjsgj_shen_lvmeng_prefix: '星月|神',
	qmsgswkjsgj_shen_keji:'克己',
	qmsgswkjsgj_shen_keji_info:'你跳过弃牌阶段。',
	qmsgswkjsgj_shelie:'涉猎',
	qmsgswkjsgj_shelie_info:'涉准备阶段和结束阶段，你可以亮出牌堆顶的五张牌，然后获得其中每种花色的牌各一张。每回合结束时，若此回合内置入弃牌堆的牌包含四种花色，你可以获得一个额外回合。',
	qmsgswkjsgj_shelie_extra:'涉猎·额外',
	qmsgswkjsgj_gongxin:'攻心',
	qmsgswkjsgj_gongxin_info:'每名角色的出牌阶段限开始时，你可以观看该角色的手牌（你的出牌阶段开始时，修改为观看任意一名其他角色的手牌），然后你可以展示其中一种花色的牌，你可以获得其中任意张牌，弃置任意张牌，将剩余的牌以任意方式放在牌堆顶，然后你可以令其本回合无法使用和打出你展示花色对应颜色的牌。',


	//神郭嘉再再加强
	qmsgswkjsgj_plusplus_shen_guojia:'星月神神神郭嘉',
	qmsgswkjsgj_plusplus_shen_guojia_prefix: '星月|神|神|神',
	qmsgswkjsgj_reshuishiplusplus: '慧识',
	qmsgswkjsgj_reshuishiplusplus_info: '出牌阶段限一次。若你的体力上限小于18，你可进行判定。若判定结果与本次发动技能时的其他判定结果的点数均不相同且你的体力上限小于18，则你加1点体力上限，且可以重复此流程。然后你将所有位于处理区的判定牌交给一名角色。若其手牌数为全场最多，则你减1点体力上限。（全民三国杀我开局神郭嘉的慧识。据作者剧情实战，天妒回收后不计入已判定）',
	qmsgswkjsgj_stianyiplusplus: '天翊',
	qmsgswkjsgj_stianyiplusplus_info: `觉醒技，若你受到伤害，你加2点体力上限并回复1点体力，然后令一名角色获得技能${get.poptip('qmsgswkjsgj_zuoxingplusplus')}。`,
	qmsgswkjsgj_zuoxingplusplus: '佐幸',
	qmsgswkjsgj_zuoxingplusplus2: '佐幸',
	qmsgswkjsgj_zuoxingplusplus_info: '若令你获得〖佐幸〗的角色存活且体力上限大于1，则你可以令其减1点体力上限，并视为使用一张普通锦囊牌。',
	qmsgswkjsgj_resghuishiplusplus:'辉逝',
	qmsgswkjsgj_resghuishiplusplus_info:'出牌阶段限一次，你可以选择一名角色，若其：有未触发的觉醒技，则你选择其中一个觉醒技，然后该角色直接觉醒；没有未触发的觉醒技，其摸四张牌，增加2点体力上限。若如此做，你减2点体力上限。',

	qmsgswkjsgj_re_pot_guoyuan:'星月界势国渊',
	qmsgswkjsgj_re_pot_guoyuan_prefix: '星月|界|势',
	qmsgswkjsgj_re_mbqingdao:'清蹈',
	qmsgswkjsgj_re_mbqingdao_info: '当其他角色对你使用的卡牌结算结束后，若你因此牌受到伤害，你可以从牌堆或弃牌堆中获得一张【闪】并弃置一名角色区域里的一张牌；否则你可以从牌堆或弃牌堆中获得一张【杀】并使用一张手牌（无距离限制）。',
	qmsgswkjsgj_re_mbxiugeng:'休耕',
	qmsgswkjsgj_re_mbxiugeng_info: '准备阶段，你可以记录至多X名角色的手牌数（X为你的体力上限）。若如此做，这些角色的摸牌阶段开始时，若其手牌数：小于等于记录值，其摸两张牌；大于等于记录值，其手牌上限+1。',
	qmsgswkjsgj_re_mbchenshe:'陈赦',
	qmsgswkjsgj_re_mbchenshe_info:'当一名角色进入濒死状态时，你可以依次弃置其和伤害来源的各一张牌，若这些角色被弃置的牌颜色相同，则其回复体力至上限。',

	qmsgswkjsgj_re_pot_xinxianying:'星月界势辛宪英',
	qmsgswkjsgj_re_pot_xinxianying_prefix: '星月|界|势',
	qmsgswkjsgj_re_mbjiejie:'诫节',
	qmsgswkjsgj_re_mbjiejie_info:'每名角色的出牌阶段限一次，当前回合角色可以令你观看其手牌，然后你可以选择一种花色，若其手牌：1.包含此花色，其弃置所有不为此花色的手牌，本回合使用此花色的牌无次数限制；2.不含此花色，其从牌堆或弃牌堆中获得一张此花色的牌。然后你视为对其发动“清识”。每轮开始时，你选择一名角色，其出牌阶段开始时，你对其发动“诫节”。',
	qmsgswkjsgj_re_mbqingshi:'清识',
	qmsgswkjsgj_re_mbqingshi_info:'当你受到1点伤害后，你可以选择一名角色，然后若你与其阵营：相同，你与其各摸两张牌；不同，你弃置其三张牌。',

	qmsgswkjsgj_re_pot_dongzhao:'星月界势董昭',
	qmsgswkjsgj_re_pot_dongzhao_prefix: '星月|界|势',
	qmsgswkjsgj_re_mbmiaolue:'妙略',
	qmsgswkjsgj_re_mbmiaolue_info:'每轮开始时，你获得两张【瞒天过海】；当你受到1点伤害后，你可以摸两张牌并从牌堆或弃牌堆中获得一张智囊。',
	qmsgswkjsgj_re_mbyingjia:'迎驾',
	qmsgswkjsgj_re_mbyingjia_info:'一名角色的回合结束后，若你本回合使用了大于等于两张同名锦囊牌，你可以令一名角色执行一个额外的回合，此额外回合开始时，其摸两张牌。',

	qmsgswkjsgj_re_simahui:'星月界司马徽',
	qmsgswkjsgj_re_simahui_prefix: '星月|界',
	qmsgswkjsgj_re_jianjie: "荐杰",
	qmsgswkjsgj_re_jianjie_info: "①游戏开始时，你令一名其他角色获得“龙印”，然后令另一名其他角色获得“凤印”。②出牌阶段限一次。若当前回合不是你的第一个回合，则你可以移动场上的“龙印”或“凤印”。③拥有“龙印”或“凤印”的其他角色死亡时，你转移该角色的“龙印”和“凤印”。④拥有“龙印”/“凤印”的角色视为拥有〖火计〗/〖连环〗，且同时拥有这两种标记的角色视为拥有〖业炎〗。",

	//神周瑜补强
	qmsgswkjsgj_plusplus_shen_zhouyu:'星月神神周瑜',
	qmsgswkjsgj_plusplus_shen_zhouyu_prefix: '星月|神|神',
	qmsgswkjsgj_yeyanplus: '业炎',
	qmsgswkjsgj_yeyanplus_info: '出牌阶段限一次，你可以选择至多三名角色，对这些角色造成共计至多3点火焰伤害。',
	qmsgswkjsgj_reyingziplus: '英姿',
	qmsgswkjsgj_reyingziplus_info: '锁定技，摸牌阶段，你多摸X张牌；你的手牌上限为X（X为你的体力上限）。',
	qmsgswkjsgj_refanjianplus: '反间',
	qmsgswkjsgj_refanjianplus_info: '出牌阶段每名其他角色限一次，你可以展示一张手牌并交给一名其他角色，令其展示所有手牌，然后依次执行：1.弃置其与此牌花色相同的所有牌；2.令其失去1点体力或对其造成1点伤害。',
	qmsgswkjsgj_qinyinplus: '琴音',
	qmsgswkjsgj_qinyinplus_info: '准备阶段和结束阶段，你可以选择任意名角色各回复1点体力，然后选择其他任意名角色各失去1点体力或对其各造成一点伤害。',

	qmsgswkjsgj_re_o_sunquan:'星月界缘孙权',
	qmsgswkjsgj_re_o_sunquan_prefix: '星月|神赐|缘',
	qmsgswkjsgj_mbshizhong: "势众",
	qmsgswkjsgj_mbshizhong_info: "锁定技，你的第一个回合内造成伤害时将伤害值改为十万！结束阶段，你摸一张牌并展示所有手牌；准备阶段，你摸X张牌（X为你手牌中剩余以此法展示过的牌数），若X小于你上次以此法展示牌数，本回合你造成伤害时，将伤害值改为十万！",
	qmsgswkjsgj_mbcaowei: "操微",
	qmsgswkjsgj_mbcaowei_info: "锁定技，当你受到1点伤害后，你重铸至少一个类别的所有牌并摸X张牌（指一技能的X。跨技能的代数不在技能里标注而是在后文注解里写也是醉了）。",

	qmsgswkjsgj_re_jsrg_guozhao:'星月界合郭照',
	qmsgswkjsgj_re_jsrg_guozhao_prefix: '星月|神赐|合',
	qmsgswkjsgj_re_jsrgpianchong: "偏宠",
	qmsgswkjsgj_re_jsrgpianchong_info: "一名角色的结束阶段，你可以判定。若结果为红色/黑色，你摸此回合进入弃牌堆的红色/黑色牌数量的牌。",
	qmsgswkjsgj_re_jsrgzunwei: "尊位",
	qmsgswkjsgj_re_jsrgzunwei_info: "出牌阶段限一次。你可以选择一名其他角色并选择执行一项：1.将手牌数摸至与该角色相同；2.将其装备牌移至你的装备区；3.将体力值回复至与该角色相同。",

	qmsgswkjsgj_re_wn_zhanghe: "星月界渭南张郃",
	qmsgswkjsgj_re_wn_zhanghe_prefix: "星月|界|渭南",
	qmsgswkjsgj_re_wn_qiaobian: "巧变",
	qmsgswkjsgj_re_wn_qiaobian_info: "其他角色的准备阶段，你可以将一张牌置于武将牌上，称为“巧”。本回合其使用牌时，你展示一张“巧”，若这两张牌类型或花色或点数：相同，若此时在其出牌阶段内，结束此阶段；不同，你摸一张牌，其的结束阶段，你获得所有“巧”。",
	//魔炎

	//----------------神赐章节-----------------
	qmsgswkjsgj_shenci_wu_zhugeliang: '星月神赐武诸葛亮',
	qmsgswkjsgj_shenci_wu_zhugeliang_prefix: '星月|神赐|武',
	qmsgswkjsgj_shenci_dcjincui: '尽瘁',
	qmsgswkjsgj_shenci_dcjincui_info: '锁定技。①游戏开始时，你将手牌摸至七张。②准备阶段，你将体力值回复或失去至等同于牌堆和弃牌堆中点数为7的牌数（你的体力值最低因此调整至1）。然后你观看牌堆顶X张牌，将这些牌以任意顺序置于牌堆顶或牌堆底（X为你的体力值）。',
	qmsgswkjsgj_shenci_dcqingshi: '情势',
	qmsgswkjsgj_shenci_dcqingshi_info: '当你于出牌阶段使用牌时，若你手牌中有同名牌，你可以选择一项：1.令此牌对其中一个目标角色造成的伤害+1；2.令任意名角色各摸一张牌；3.摸X张牌，然后〖情势〗于本回合无效（X为你的体力值）。',
	qmsgswkjsgj_shenci_dczhizhe: '智哲',
	qmsgswkjsgj_shenci_dczhizhe_clear: 'invisible',
	qmsgswkjsgj_shenci_dczhizhe_info: '限定技。出牌阶段，你可以选择一张手牌并复制之。此牌进入弃牌堆时，你获得之，然后你本回合不能再使用或打出此牌。',
	qmsgswkjsgj_shenci_redczhizhe: '智哲',
	qmsgswkjsgj_shenci_redczhizhe_clear: 'invisible',
	qmsgswkjsgj_shenci_redczhizhe_info: '出牌阶段，若你没有“智哲”牌，你可以选择一张手牌并复制之。此牌进入弃牌堆时，你获得之，然后你本回合不能再使用或打出此牌。',

	qmsgswkjsgj_shenci_re_duyu: '星月神赐界杜预',
	qmsgswkjsgj_shenci_re_duyu_prefix: '星月|神赐|界',
	qmsgswkjsgj_shenci_spwuku: '武库',
	qmsgswkjsgj_shenci_spwuku_info: '锁定技，当有角色使用装备牌时，则你获得一个“武库”。你使用装备时，额外获得一个“武库”。',
	qmsgswkjsgj_shenci_spsanchen: '三陈',
	qmsgswkjsgj_shenci_spsanchen_info: `觉醒技，若你的“武库”数大于2，则你加1点体力上限并回复1点体力，然后获得${get.poptip('qmsgswkjsgj_shenci_spmiewu')}。`,
	qmsgswkjsgj_shenci_spmiewu: '灭吴',
	qmsgswkjsgj_shenci_spmiewu_info: '你可弃置一枚“武库”并将一张牌当做任意基本牌或锦囊牌使用，然后摸一张牌。',
	qmsgswkjsgj_shenci_spwukuplus: '武库',
	qmsgswkjsgj_shenci_spwukuplus_info: '锁定技，当有角色使用装备牌时，则你获得一个“武库”。你使用装备时，额外获得一个“武库”。准备阶段，你从牌堆和弃牌堆获得一件指定的装备并使用',

	qmsgswkjsgj_shenci_wu_luxun: '星月神赐武陆逊',
	qmsgswkjsgj_shenci_wu_luxun_prefix: '星月|神赐|武',
	qmsgswkjsgj_shenci_dcxiongmu: '雄幕',
	qmsgswkjsgj_shenci_dcxiongmu_tag: '雄幕',
	qmsgswkjsgj_shenci_dcxiongmu_info: '①每轮开始时，你可以摸体力上限数张牌，然后将任意张牌随机置入牌堆，从牌堆或弃牌堆中获得等量的点数为8的牌。玩家点数为8的牌不计入手牌上限。②玩家每回合受到第一次伤害时，免疫此伤害。。',
	qmsgswkjsgj_shenci_dczhangcai: '彰才',
	qmsgswkjsgj_shenci_dczhangcai_info: '当你失去一张点数为8的牌时，你可以摸X张牌（X为你手牌区里点数为8的牌数且至少为1）。',
	qmsgswkjsgj_shenci_dcruxian: '儒贤',
	qmsgswkjsgj_shenci_dcruxian_info: '限定技。出牌阶段，你可以令你〖彰才〗的点数限制取消，且摸牌数改为等同于你手牌区内与此牌点数相同的牌数且至少为1，直到你的下回合结束。',

	qmsgswkjsgj_shenci_sb_caopi: '星月神赐谋曹丕',
	qmsgswkjsgj_shenci_sb_caopi_prefix: '星月|神赐|谋',
	qmsgswkjsgj_shenci_sbxingshang: '行殇',
	qmsgswkjsgj_shenci_sbxingshang_info: '①当一名角色受到伤害后或死亡时，你获得2个“颂”标记。②出牌阶段限两次，你可以：选择一名角色，移去任意数量的“颂”令其执行对应的一个操作：1个，复原武将牌；2个，摸X张牌（X为本局已死亡角色数，至少为3）；3个，增加1点体力上限并回复一点体力，然后恢复被废除的装备栏（体力上限不大于12方可选择）；4个，追思一名未被追思过的已阵亡角色的武将牌上的技能，然后你失去“行殇”。',
	// sbxingshang_info: "①当一名角色受到伤害后或死亡时，你获得2个“颂”标记。②出牌阶段限两次，你可以：" + ["移去2个“颂”标记，令一名角色复原武将牌", "移去2个“颂”标记，令一名角色摸三张牌", "移去3个“颂”标记，令一名体力上限小于10的角色回复1点体力，增加1点体力上限，随机恢复一个已废除的装备栏", "移去4个“颂”标记，获得一名阵亡角色武将牌上的所有技能，然后你失去〖行殇〗〖放逐〗〖颂威〗"].map((str, index) => `${index + 1}.${str}`).join("；") + "。",
	qmsgswkjsgj_shenci_sbfangzhu: '放逐',
	qmsgswkjsgj_shenci_sbfangzhu_info: '出牌阶段限两次，你可以选择一名其他角色，移去任意数量的“颂”令其执行对应的一个操作：1个，你指定一种类型的牌，直到其下回合结束，其只能使用此类型的牌；2个，直到其下回合结束，其武将技能失效或不可响应另一名角色使用的牌；3个，其翻面。',
	// sbfangzhu_info: "出牌阶段限一次，你可以：" + ["移去2个“颂”标记，令一名其他角色于手牌中只能使用基本牌直到其回合结束", "移去6个“颂”标记，令一名其他角色于手牌中只能使用锦囊牌直到其回合结束", "移去8个“颂”标记，令一名其他角色于手牌中只能使用装备牌直到其回合结束", "移去6个“颂”标记，令一名其他角色的非Charlotte技能失效直到其回合结束", "移去4个“颂”标记，令一名其他角色不能响应另一名角色使用的牌直到其回合结束", "移去8个“颂”标记，令一名其他角色将武将牌翻面"].map((str, index) => `${index + 1}.${str}`).join("；") + "。",
	// sbfangzhu_info_doudizhu: "出牌阶段限一次，你可以：" + ["移去2个“颂”标记，令一名其他角色于手牌中只能使用基本牌直到其回合结束", "移去6个“颂”标记，令一名其他角色于手牌中只能使用锦囊牌直到其回合结束", "移去4个“颂”标记，令一名其他角色不能响应另一名角色使用的牌直到其回合结束"].map((str, index) => `${index + 1}.${str}`).join("；") + "。",
	qmsgswkjsgj_shenci_sbsongwei: '颂威',
	qmsgswkjsgj_shenci_sbsongwei_info: '主公技，出牌阶段开始时，你获得Y个“颂”标记（Y为本局游戏魏势力角色数的两倍）。每局游戏限一次，你可以于出牌阶段令一名其他魏势力角色失去其武将牌上的所有技能。',

	qmsgswkjsgj_shenci_re_sunhanhua: '星月神赐界孙寒华',
	qmsgswkjsgj_shenci_re_sunhanhua_prefix: '星月|神赐|界',
	qmsgswkjsgj_shenci_chongxu: '冲虚',
	qmsgswkjsgj_shenci_chongxu_info: '出牌阶段限一次，你可以集灵（至多七分），并根据分数：你可以修改〖妙剑〗或〖莲华〗（消耗2分），并使用剩余的分数进行摸牌（每张1分）。',
	qmsgswkjsgj_shenci_miaojian: '妙剑',
	qmsgswkjsgj_shenci_miaojian_info: '出牌阶段限一次，你可以视为使用一张刺【杀】，该刺【杀】不计入次数限制且无距离限制。',
	qmsgswkjsgj_shenci_miaojian1: '妙剑·改',
	qmsgswkjsgj_shenci_miaojian1_info: '出牌阶段限一次，你可以视为使用一张刺【杀】，该刺【杀】不计入次数限制且无距离限制。你的【杀】均可视为刺【杀】',
	qmsgswkjsgj_shenci_miaojian2: '妙剑·极',
	qmsgswkjsgj_shenci_miaojian2_info: '出牌阶段限一次，你可以视为使用一张刺【杀】，你的【杀】均可视为刺【杀】。刺【杀】无次数和距离限制。',
	qmsgswkjsgj_shenci_shhlianhua: '莲华',
	qmsgswkjsgj_shenci_shhlianhua_info: '你成为其他角色【杀】的目标后，你摸一张牌，除非该角色弃置一张牌，否则取消之，然后进行一次判定，若结果为黑桃，则取消之。',
	qmsgswkjsgj_shenci_shhlianhua1: '莲华·改',
	qmsgswkjsgj_shenci_shhlianhua1_info: '你成为其他角色【杀】的目标后，你摸一张牌，除非该角色弃置一张牌，否则取消之，然后进行一次判定，若结果为黑色，则取消之。',
	qmsgswkjsgj_shenci_shhlianhua2: '莲华·极',
	qmsgswkjsgj_shenci_shhlianhua2_info: '你成为其他角色牌的目标后，你可以摸一张牌，除非该角色弃置一张牌，否则取消之，然后进行一次判定，若结果不为红桃，则取消之。',
	//由于剧情里，孙寒华在对局中被神赐，已升级的技能仍然延续神赐之前的等级，因此这里以及界孙寒华尽量也要和本体孙寒华互通

	qmsgswkjsgj_shenci_dc_zhouxuān: '星月神赐周宣',
	qmsgswkjsgj_shenci_dc_zhouxuān_prefix: '星月|神赐',
	qmsgswkjsgj_shenci_dcwumei: '寤寐',
	qmsgswkjsgj_shenci_dcwumei_info: '每轮限一次。回合开始前，你可以令一名角色执行一个额外回合，此回合内，其造成的所有伤害+1。以此法进行的回合结束时，将场上所有角色的体力值改为此回合开始时的数值。',
	qmsgswkjsgj_shenci_dczhanmeng: '占梦',
	qmsgswkjsgj_shenci_dczhanmeng_info: '当你使用或打出牌时，你可以选择一项：1.上一回合内，若没有同名牌被使用过，你获得一张非伤害牌；2.下一回合内，当同名牌被使用后，你获得一张伤害牌；3.弃置一名其他角色两张牌，对其造成1点火焰伤害。',
	qmsgswkjsgj_shenci_dcwumeiplus: '寤寐',
	qmsgswkjsgj_shenci_dcwumeiplus_info: '每轮限一次。游戏开始时或回合开始前，你可以令一名角色执行一个额外回合，此回合内，其造成的所有伤害+1。以此法进行的回合结束时，将场上所有角色的体力值改为此回合开始时的数值。',

	qmsgswkjsgj_shenci_caomao: '星月神赐曹髦',
	qmsgswkjsgj_shenci_caomao_prefix: '星月|神赐',
	qmsgswkjsgj_shenci_mbqianlong: '潜龙',
	qmsgswkjsgj_shenci_mbqianlong_info: `${get.poptip('rule_chihengji')}。①游戏开始时，你获得30枚“道心”标记。②当你得到牌后/受到1点伤害后/造成1点伤害后，你获得10/20/20枚“道心”（上限为99枚）。③若你的“道心”数不小于20/40/60/80/99，你视为拥有${get.poptip('qmsgswkjsgj_shenci_mbcmqingzheng')}/${get.poptip('qmsgswkjsgj_shenci_mbcmjiushi')}/${get.poptip('qmsgswkjsgj_shenci_mbcmfangzhu')}/${get.poptip('qmsgswkjsgj_shenci_cmhuituo')}/${get.poptip('qmsgswkjsgj_shenci_mbjuejin')}。`,
	qmsgswkjsgj_shenci_mbcmqingzheng: '清正',
	qmsgswkjsgj_shenci_mbcmqingzheng_info: `${get.poptip('rule_chihengji')}。出牌阶段开始时，你可以弃置一张手牌，并观看一名有手牌的其他角色的手牌，你弃置其中一种花色的所有牌。然后对其造成1点伤害。`,
	qmsgswkjsgj_shenci_mbcmjiushi: '酒诗',
	qmsgswkjsgj_shenci_mbcmjiushi_info: `${get.poptip('rule_chihengji')}。①当你需要使用【酒】时，若你的武将牌正面向上，你可以翻面，视为使用一张【酒】。②当你受到伤害后，若你武将牌背面朝上且未因此次伤害发动过〖酒诗〗，你可以翻面。③当你翻面后，你获得牌堆或弃牌堆中的一张指定牌名的锦囊牌。`,
	qmsgswkjsgj_shenci_mbcmfangzhu: '放逐',
	qmsgswkjsgj_shenci_mbcmfangzhu_info: `${get.poptip('rule_chihengji')}。出牌阶段限两次，你可以选择一名其他角色，选择一项：⒈令其不能使用手牌中的一种类型牌直到其回合结束；⒉令其所有非Charlotte技能失效直到其回合结束；3.其翻面。`,
	qmsgswkjsgj_shenci_cmhuituo: '恢拓',
	qmsgswkjsgj_shenci_cmhuituo_info: `${get.poptip('rule_chihengji')}。当你受到1点伤害后，你可以令一名角色进行一次判定，若结果为红色，该角色回复X点体力；若结果为黑色，该角色摸X张牌。（X为此次伤害的伤害点数）`,
	qmsgswkjsgj_shenci_mbjuejin: '决进',
	qmsgswkjsgj_shenci_mbjuejin_info: `${get.poptip('rule_chihengji')}，限定技。出牌阶段，你可以令任意角色依次将体力调整至1并获得X点护甲（X为一名角色以此法减少的体力值且你以此法获得的护甲数额外+2）。然后你将牌堆、弃牌堆、场上及所有角色手牌中的【闪】、【桃】和【酒】移出游戏且增加全局技能“${get.poptip({
		id: 'juejin_xiangsicunwei',
		name: '向死存魏',
		type: 'character',
		info: '当有牌进入弃牌堆后，系统将这些牌中的【闪】、【桃】和【酒】移出游戏。',
	})}”，若你因此失去手牌，你可以摸等量的牌，并反转${get.poptip('qmsgswkjsgj_shenci_cmhuituo')}的判定效果。（全民三国杀我开局神郭嘉的神赐曹髦）`,
	qmsgswkjsgj_shenci_mbweitong: '卫统',
	qmsgswkjsgj_shenci_mbweitong_info: `${get.poptip('rule_chihengji')}，主公技。游戏开始时，若你有${get.poptip('qmsgswkjsgj_shenci_mbqianlong')}，你获得60点道心值；其他魏势力角色回复体力时，你可以摸一张牌（全民三国杀我开局神郭嘉的神赐曹髦）。`,

	qmsgswkjsgj_shenci_mbqianlongplus: '潜龙',
	qmsgswkjsgj_shenci_mbqianlongplus_info: `${get.poptip('rule_chihengji')}。①游戏开始时，你获得30枚“道心”标记。②当你得到牌后/受到1点伤害后/造成1点伤害后，你获得10/20/20枚“道心”（无上限）。③若你的“道心”数不小于20/40/60/80/99，你视为拥有${get.poptip('qmsgswkjsgj_shenci_mbcmqingzheng')}/${get.poptip('qmsgswkjsgj_shenci_mbcmjiushi')}/${get.poptip('qmsgswkjsgj_shenci_mbcmfangzhu')}/${get.poptip('qmsgswkjsgj_shenci_cmhuituo')}/${get.poptip('qmsgswkjsgj_shenci_mbjuejin')}。`,


	qmsgswkjsgj_shenci_pot_yuji: '星月神赐界势于吉',
	qmsgswkjsgj_shenci_pot_yuji_prefix: '星月|神赐|界|势',
	qmsgswkjsgj_shenci_potfuji: '符济',
	qmsgswkjsgj_shenci_potfuji_info: '每轮游戏开始时或出牌阶段限一次，你可以展示至多X张牌并交给任意角色，称为“符济”（X为场上角色数）。其角色使用“符济”牌时获得一张与“符济”牌花色相同的牌；然后若此牌为：【杀】，此牌造成的伤害+1；【闪】，结算完毕后其摸一张牌；【桃】，回复数值+1；【酒】，其可弃置场上一张牌。然后你摸一张牌，且直到下回合开始前，你使用的【杀】【闪】【桃】【酒】视为拥有对应效果（可叠加）。',
	//后面某一场战斗提及，持续时间到了下回合结束而不是下回合开始。又是一个补强，但那要改很多代码，我懒
	qmsgswkjsgj_shenci_potdaozhuan: '道转',
	qmsgswkjsgj_shenci_potdaozhuan_info: '每回合限X次，你可以将你或者当前回合角色的一张牌置入弃牌堆，视为使用一张基本牌。若当前回合角色是你，则你摸一张牌。（X为你的体力上限）',

	qmsgswkjsgj_shenci_wu_huangfusong: '星月神赐武皇甫嵩',
	qmsgswkjsgj_shenci_wu_huangfusong_prefix: '星月|神赐|武',
	qmsgswkjsgj_shenci_dcchaozhen: '朝镇',
	qmsgswkjsgj_shenci_dcchaozhen_info: '准备阶段或当你进入濒死状态时，你可以获得牌堆里或场上点数最小的牌，若此牌点数为A，你回复1点体力。',
	qmsgswkjsgj_shenci_dclianjie: '连捷',
	qmsgswkjsgj_shenci_dclianjie_info: '你使用手牌指定目标后，你可令一名角色将其一张点数最小的手牌置于牌堆底，若你无手牌或此牌点数不大于你的所有手牌，你将手牌摸至体力上限，以此法获得的牌本回合无距离和次数限制。',
	qmsgswkjsgj_shenci_dcjiangxian: '将贤',
	// qmsgswkjsgj_shenci_dcjiangxian_info: "限定技，出牌阶段，当你造成伤害时，你可以令此伤害+X（X为你本回合造成伤害的次数）。",//作者忘写了，你可以获得以下效果直到本回合结束：，也可能并非忘记而是单纯云，不做理会
	qmsgswkjsgj_shenci_dcjiangxian_info: '限定技，出牌阶段，你可以获得以下效果直到本回合结束：当你造成伤害时，可以此伤害+X（X为你本回合造成伤害的次数）。',
	//按照原著描述，下面的是正确结算，因此直接补齐。
	//按照原著描述，每次造成伤害都可以手动选择是否加伤

	qmsgswkjsgj_shenci_wu_guanyu: '星月神赐武关羽',
	qmsgswkjsgj_shenci_wu_guanyu_prefix: '星月|神赐|武',
	qmsgswkjsgj_shenci_dcjuewu: '绝武',
	qmsgswkjsgj_shenci_dcjuewu_two: '2点',
	qmsgswkjsgj_shenci_dcjuewu_info: `①你可以将一张点数为2的牌当任意伤害类牌使用（包括${get.poptip('shuiyanqijuny')}）。②当你得到其他角色区域内的牌后，你令这些牌的点数均视为2直到你失去这些牌。`,
	qmsgswkjsgj_shenci_dcwuyou: '武佑',
	qmsgswkjsgj_shenci_dcwuyou_info: '①每名角色的出牌阶段限两次。其可以交给你一张手牌，然后你可以从全部牌名中选择一个牌名并交给其一张手牌，令此牌的牌名与属性视为与你选择的相同（一名角色使用〖武佑〗转化的牌无距离且无任何次数限制）。',
	qmsgswkjsgj_shenci_dcyixian: '义贤',
	qmsgswkjsgj_shenci_dcyixian_info: '出牌阶段限一次，你可以选择一项：⒈获得场上的所有装备牌；⒉获得弃牌堆中的所有装备牌。然后你依次选择是否令被你以此法获得牌的角色摸X张牌并回复1点体力（X为其以此法失去的牌数）。',


	qmsgswkjsgj_shenci_bolingyun: '星月神赐界柏灵筠',
	qmsgswkjsgj_shenci_bolingyun_prefix: '星月|神赐|界',
	qmsgswkjsgj_shenci_dclinghui: '灵慧',
	qmsgswkjsgj_shenci_dclinghui_info: '一名角色的结束阶段，你可以观看牌堆顶的X张牌（X为你的体力上限），然后你可以使用其中任意张牌并获得剩余任意张牌，然后将其余牌以任意顺序放回牌堆顶。',
	qmsgswkjsgj_shenci_dcxiace: '黠策',
	qmsgswkjsgj_shenci_dcxiace_info: '当你受到1点伤害后，你可令一名其他角色技能失效直到其下回合结束；当你造成1点伤害后，你可以回复1点体力。',
	qmsgswkjsgj_shenci_dcyuxin: '御心',
	qmsgswkjsgj_shenci_dcyuxin_info: '每轮限一次，一名角色进入濒死状态时，你可以令其将体力回复至上限。',

	qmsgswkjsgj_shenci_simahui:'星月神赐司马徽',
	qmsgswkjsgj_shenci_simahui_prefix: '星月|神赐',
	qmsgswkjsgj_shenci_jianjie: "荐杰",
	qmsgswkjsgj_shenci_jianjie_info: "①你的第一个准备阶段开始时，你令至多两名其他角色获得“神赐龙印”，“神赐凤印”。②出牌阶段限一次或拥有“神赐龙印”或“神赐凤印”的其他角色死亡时，你可以移动场上的“神赐龙印”和“神赐凤印”。③拥有“神赐龙印”/“神赐凤印”的角色视为拥有〖火计〗/〖连环〗，且同时拥有这两种标记的角色视为拥有〖业炎〗。④每轮开始时或你的准备阶段，若场上没有“神赐龙印”，“神赐凤印”，你令至多两名角色获得“神赐龙印”和“神赐凤印”。",
	qmsgswkjsgj_shenci_jianjie_huoji: "火计",
	qmsgswkjsgj_shenci_jianjie_huoji_effect: "火计",
	qmsgswkjsgj_shenci_jianjie_huoji_info: "你可以将一张红色牌当作【火攻】使用，且你以此法使用【火攻】的作用效果改为“目标角色随机展示一张手牌A，然后你可以弃置一张与A颜色相同的牌，对目标造成1点火属性伤害”。",
	qmsgswkjsgj_shenci_jianjie_lianhuan: "连环",
	qmsgswkjsgj_shenci_jianjie_lianhuan_effect: "连环",
	qmsgswkjsgj_shenci_jianjie_lianhuan_info: "你可以将一张♣牌当作【铁索连环】使用或重铸，且你以此法使用【铁索连环】的目标数上限+1。",
	qmsgswkjsgj_shenci_jianjie_yeyan: "业炎",
	qmsgswkjsgj_shenci_jianjie_yeyan_info: "限定技。出牌阶段，你可以移去你所有的“神赐龙印”和“神赐凤印”，对一至三名角色造成至多共3点火焰伤害（你可以任意分配每名目标角色受到的伤害点数），若你将对一名角色分配2点或更多的火焰伤害，你须先弃置四张不同花色的手牌再失去3点体力。",
	qmsgswkjsgj_shenci_yinshi: "隐士",
	qmsgswkjsgj_shenci_yinshi_info: "锁定技，当你受到属性伤害或锦囊牌造成的伤害时，防止此伤害。",
	qmsgswkjsgj_shenci_chenghao: "称好",
	qmsgswkjsgj_shenci_chenghao_info: "当一名角色受到属性伤害时，你可以观看牌堆顶的X张牌并分配给任意角色。（X为横置的角色数量且包含该角色）",

	qmsgswkjsgj_shenci_eu_kaisa:'星月神赐欧陆凯撒',
	qmsgswkjsgj_shenci_eu_kaisa_prefix: '星月|神赐|欧陆',
	qmsgswkjsgj_shenci_eu_ducai: "独裁",
	qmsgswkjsgj_shenci_eu_ducai_info: `${get.poptip("rule_chihengji")}，你的回合内使用牌无距离次数限制，其他角色不能使用或打出牌且所有技能失效。`,
	qmsgswkjsgj_shenci_eu_zhitong: "治统",
	qmsgswkjsgj_shenci_eu_zhitong_info: "转换技，当你使用牌时，若目标包含，阳：自己，摸X张牌且回复1点体力；阴：其他角色，你获得其装备区所有牌或手牌区X张牌并对其造成1点伤害。（X为你的体力上限）",
	qmsgswkjsgj_shenci_eu_jiquan: "集权",
	qmsgswkjsgj_shenci_eu_jiquan_info: "主公技，锁定技，其他角色均视为西势力；西势力角色的回合开始时，你回复1点体力并摸两张牌。",
	//作者注解，可以触发集权，不改变原势力

};
