import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export { list }

const list = [
	['spade','5','guilongzhanyuedao'],
	['spade',2,'qimenbagua'],
	['club',2,'qimenbagua'],
	//['spade','5','juechenjinge_gai'],
	['spade','6','chixueqingfeng'],
	['diamond','12','xiuluolianyuji'],
	['diamond','4','xuwangzhimian'],
	['spade','2','longfenghemingjian'],
	['diamond','3','guofengyupao'],
	['diamond','3','qicaishenlu'],
	['heart','5','jinwuluorigong'],
	['diamond','5','xingtianpojunfu'],
	['club','12','lingsheji'],
	['spade','13','shanrangzhaoshu'],
	['heart','1','goujiangdesidai'],
	['diamond','13','niaobaidaowenha'],
	['spade','13','shenzhixiunvfu'],
	['club','5','gubuzifeng'],
	['diamond','7','gubuzifeng'],
	['club','13','yihuajiemu'],
	['club','12','yihuajiemu'],
	['heart','7','sadouchengbing'],
	['heart','8','sadouchengbing'],
	['heart','9','sadouchengbing'],
	['heart','11','sadouchengbing'],
	['diamond','12','wushuangfangtianji'],
	['spade','2','linglongshimandai'],
	['club','2','linglongshimandai'],
	['spade','2','hongmianbaihuapao'],
	['club','2','hongmianbaihuapao'],
	['diamond','5','shufazijinguan'],
	['heart','3','lianjunshengyan_gai'],
	['heart','4','lianjunshengyan_gai'],
	['heart','1','lianjunshengyan_gai']
]
