import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export {translate}

const translate = {
	sadouchengbing:'撒豆成兵',
	sadouchengbing_info:'出牌阶段对自己使用，若你的势力为“神”，摸X张牌；否则将你手牌补至X；（X为你的体力上限且至多为5）',
	yihuajiemu:'移花接木',
	yihuajiemu_info:'出牌阶段对一名有牌的其他角色使用，令其使用一张【杀】，或交给你两张牌',
	chiyanzhenhunqin:'赤焰镇魂琴',
	chiyanzhenhunqin_info:'锁定技，你造成的伤害均视为具有火属性',
	// juechenjinge_gai:'绝尘金戈',
	// juechenjinge_gai_append:'没写好，别私自加！',
	// juechenjinge_gai_info:'锁定技，其它角色计算与你的距离+2。没写好，别私自加！',
	// juechenjinge_gai_info_boss:'锁定技，其它角色计算与你的距离+2，敌方角色计算与己方其他角色距离+1。没写好，别私自加！',
	// juechenjinge_gai_info_guozhan:'锁定技，其它角色计算与你的距离+2，其它势力角色计算与己方势力的距离+1。没写好，别私自加！',
	xiuluolianyuji:'修罗炼狱戟',
	xiuluolianyuji_info:'你使用【杀】可以额外指定任意名攻击范围内的其他角色为目标；锁定技，你使用【杀】造成的伤害+1，然后令受到伤害的角色回复1点体力',
	longfenghemingjian:'鸾凤和鸣剑',
	longfenghemingjian_info:'你使用的【雷杀】或【火杀】指定目标后，可令对方选择弃置一张牌或令你摸一张牌',
	qicaishenlu:'七彩神鹿',
	qicaishenlu_info:'锁定技，你计算与其他角色的距离时-1，当你造成属性伤害时，你令此伤害+1。',
	boss_mengpohuihun:'回魂',
	boss_mengpohuihun_info:'若场上有角色在本局游戏中因孟婆的【忘魂】失去过技能，则令其恢复该技能；此牌进入弃牌堆后，会被销毁。',
	honghuangzhili:'洪荒之力',
	honghuangzhili_cbg:'洪',
	honghuangzhili_info:'若该角色的势力是神，你获得其一张牌，其【神裔】无效直到其下家的回合（这个下家是动态变化的，会随着一个人的死或者复活而变化）开始；若该角色的势力不是神，其翻面。',
	lingsheji:'灵蛇髻',
	lingsheji2:'灵蛇髻',
	shanrangzhaoshu:'禅让诏书',
	xingtianpojunfu:'刑天破军斧',
	noda_axe:'刑天破军斧',
	noda_axe2:'刑天破军斧',
	jinwuluorigong:'金乌落日弓',
	iwasawa_crowbow:'金乌落日弓',
	lingsheji_info:'出牌阶段结束时，你可选择：1.摸一张牌。2.将一张武将牌置于武将牌上，并于回合结束后获得此牌。',
	shanrangzhaoshu_info:'其他角色于回合外获得牌后，若是其本回合内第一次获得牌，则你可以选择一项：交给其一张牌，或令其交给你一张牌。',
	xingtianpojunfu_info:'当你于出牌阶段内使用牌指定唯一目标后，你可弃置两张牌。若如此做，其本回合内不能使用或打出牌且其防具技能无效。',
	jinwuluorigong_info:'当你于出牌阶段内一次性失去了两张以上的手牌后，你可以弃置一名其他角色等量的牌。',
	_TheDayIBecomeAGod:'神杀',
	thedayibecomeagod:'传承',
	thedayibecomeagod_info:'选择一名其他己方角色。若其势力非神，则改为神势力；若其势力为神，则将武将牌翻至正面，回复体力至体力上限，并将手牌摸至5 ',
	gubuzifeng:'故步自封',
	gubuzifeng_disable:'故步自封',
	gubuzifeng_info:'出牌阶段，对一名其他角色使用。其的一个随机技能失效直到其下个回合结束。',
	goujiangdesidai:'篝酱的丝带',
	goujiangdesidai_info:'锁定技，若你未拥有技能【纵丝】，则你视为拥有技能【纵丝】；若你拥有技能【纵丝】，则你将此技能改为「出牌阶段限两次」',
	goujiangdesidai_skill:'纵丝',
	niaobaidaowenha:'鸟白岛文蛤',
	niaobaidaowenha_skill:'鸟白岛文蛤',
	niaobaidaowenha_info:'当你减少1点体力上限后，你可令一名其他角色增加1点体力上限并回复1点体力。',
	niaobaidaowenha_skill_info:'当你减少1点体力上限后，你可令一名其他角色增加1点体力上限并回复1点体力。',
	shenzhixiunvfu:'神之修女服',
	shenzhixiunvfu_info:'没什么实际作用的衣服，仅仅是显得像个神而已。',
	lianjunshengyan_gai:'联军盛宴',
	lianjunshengyan_gai_info:'出牌阶段，对场上所有角色使用。你摸X张牌（X为存活角色数），其他角色依次选择回复1点体力或摸一张牌。',
	lianjunshengyan_gai_info_guozhan:'出牌阶段，对你和你选择的除你的势力外的一个势力的所有角色使用。若目标角色：为你，你选择摸Y张牌并回复X-Y点体力（X为该势力的角色数，Y∈[0,X]）；不为你，其摸一张牌，然后重置。',
}