import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export {translate}

const translate = {
	sadouchengbing:'撒豆成兵',
	sadouchengbing_info:'出牌阶段对自己使用，若你的势力为“神”，摸X张牌；否则将你手牌补至X；（X为你的体力上限且至多为5）',
	yihuajiemu:'移花接木',
	yihuajiemu_info:'出牌阶段对一名有牌的其他角色使用，令其使用一张【杀】，或交给你两张牌',
	chiyanzhenhunqin:'赤焰镇魂琴',
	chiyanzhenhunqin_info:'锁定技，你造成的伤害均视为具有火属性',
	// juechenjinge_gai:'绝尘金戈',
	// juechenjinge_gai_append:'没写好，别私自加！',
	// juechenjinge_gai_info:'锁定技，其它角色计算与你的距离+2。没写好，别私自加！',
	// juechenjinge_gai_info_boss:'锁定技，其它角色计算与你的距离+2，敌方角色计算与己方其他角色距离+1。没写好，别私自加！',
	// juechenjinge_gai_info_guozhan:'锁定技，其它角色计算与你的距离+2，其它势力角色计算与己方势力的距离+1。没写好，别私自加！',
	xiuluolianyuji:'修罗炼狱戟',
	xiuluolianyuji_info:'你使用【杀】可以额外指定任意名攻击范围内的其他角色为目标；锁定技，你使用【杀】造成的伤害+1，然后令受到伤害的角色回复1点体力',
	longfenghemingjian:'鸾凤和鸣剑',
	longfenghemingjian_info:'你使用的【雷杀】或【火杀】指定目标后，可令对方选择弃置一张牌或令你摸一张牌',
	qicaishenlu:'七彩神鹿',
	qicaishenlu_info:'锁定技，你计算与其他角色的距离时-1，当你造成属性伤害时，你令此伤害+1。',
	boss_mengpohuihun:'回魂',
	boss_mengpohuihun_info:'若场上有角色在本局游戏中因孟婆的【忘魂】失去过技能，则令其恢复该技能；此牌进入弃牌堆后，会被销毁。',
	honghuangzhili:'洪荒之力',
	honghuangzhili_cbg:'洪',
	honghuangzhili_info:'若该角色的势力是神，你获得其一张牌，其【神裔】无效直到其下家的回合（这个下家是动态变化的，会随着一个人的死或者复活而变化）开始；若该角色的势力不是神，其翻面。',
	lingsheji:'灵蛇髻',
	lingsheji2:'灵蛇髻',
	shanrangzhaoshu:'禅让诏书',
	xingtianpojunfu:'刑天破军斧',
	noda_axe:'刑天破军斧',
	noda_axe2:'刑天破军斧',
	jinwuluorigong:'金乌落日弓',
	iwasawa_crowbow:'金乌落日弓',
	lingsheji_info:'出牌阶段结束时，你可选择：1.摸一张牌。2.将一张武将牌置于武将牌上，并于回合结束后获得此牌。',
	shanrangzhaoshu_info:'其他角色于回合外获得牌后，若是其本回合内第一次获得牌，则你可以选择一项：交给其一张牌，或令其交给你一张牌。',
	xingtianpojunfu_info:'当你于出牌阶段内使用牌指定唯一目标后，你可弃置两张牌。若如此做，其本回合内不能使用或打出牌且其防具技能无效。',
	jinwuluorigong_info:'当你于出牌阶段内一次性失去了两张以上的手牌后，你可以弃置一名其他角色等量的牌。',
	_TheDayIBecomeAGod:'神杀',
	thedayibecomeagod:'传承',
	thedayibecomeagod_info:'选择一名其他己方角色。若其势力非神，则改为神势力；若其势力为神，则将武将牌翻至正面，回复体力至体力上限，并将手牌摸至五 ',
	gubuzifeng:'故步自封',
	gubuzifeng_disable:'故步自封',
	gubuzifeng_info:'出牌阶段，对一名其他角色使用。其的一个随机技能失效直到其下个回合结束。',
	goujiangdesidai:'篝酱的丝带',
	goujiangdesidai_info:'锁定技，若你未拥有技能【纵丝】，则你视为拥有技能【纵丝】；若你拥有技能【纵丝】，则你将此技能改为「出牌阶段限两次」',
	goujiangdesidai_skill:'纵丝',
	niaobaidaowenha:'鸟白岛文蛤',
	niaobaidaowenha_skill:'鸟白岛文蛤',
	niaobaidaowenha_info:'当你减少1点体力上限后，你可令一名其他角色增加1点体力上限并回复1点体力。',
	niaobaidaowenha_skill_info:'当你减少1点体力上限后，你可令一名其他角色增加1点体力上限并回复1点体力。',
	shenzhixiunvfu:'神之修女服',
	shenzhixiunvfu_info:'没什么实际作用的衣服，仅仅是显得像个神而已。',
	lianjunshengyan_gai:'联军盛宴',
	lianjunshengyan_gai_info:'出牌阶段，对场上所有角色使用。你摸X张牌（X为存活角色数），其他角色依次选择回复1点体力或摸一张牌。',
	lianjunshengyan_gai_info_guozhan:'出牌阶段，对你和你选择的除你的势力外的一个势力的所有角色使用。若目标角色：为你，你选择摸Y张牌并回复X-Y点体力（X为该势力的角色数，Y∈[0,X]）；不为你，其摸一张牌，然后重置。',
	zhu: "神",
	cai: "盟",
	zhong: "从",

	boss_chi: "魑",
	boss_mo: "魅",
	boss_wang: "魍",
	boss_liang: "魉",
	boss_niutou: "牛头",
	boss_mamian: "马面",
	boss_baiwuchang: "白无常",
	boss_heiwuchang: "黑无常",
	boss_luocha: "罗刹",
	boss_yecha: "夜叉",
	boss_zhuoguiquxie: "捉鬼驱邪",

	boss_nianshou: "年兽",
	boss_nianshou_heti: "年兽",
	boss_nianshou_jingjue: "警觉年兽",
	boss_nianshou_renxing: "任性年兽",
	boss_nianshou_baonu: "暴怒年兽",
	boss_nianshou_ruizhi: "睿智年兽",

	boss_huangyueying: "奇智女杰",
	boss_zhangchunhua: "冷血皇后",
	boss_dongzhuo: "乱世魔王",
	boss_lvbu1: "最强神话",
	boss_lvbu2: "暴怒战神",
	boss_lvbu3: "神鬼无前",
	boss_zhouyu: "赤壁火神",
	boss_pangtong: "涅槃凤雏",
	boss_zhugeliang: "祭风卧龙",
	boss_zhangjiao: "天公将军",
	boss_zuoci: "迷之仙人",
	boss_liubei: "蜀汉烈帝",
	boss_caiwenji: "异乡孤女",
	boss_huatuo: "药坛圣手",
	boss_zhenji: "洛水仙子",
	boss_diaochan: "绝代妖姬",
	boss_guojia: "世之奇士",
	boss_caocao: "魏武大帝",

	boss_chiyanshilian: "夏之试炼",
	boss_zhuque: "朱雀",
	boss_huoshenzhurong: "火神祝融",
	boss_yanling: "焰灵",
	boss_yandi: "炎帝",

	boss_hundun: "混沌",
	boss_qiongqi: "穷奇",
	boss_taowu: "梼杌",
	boss_taotie: "饕餮",
	boss_zhuyin: "烛阴",
	boss_xiangliu: "相柳",
	boss_zhuyan: "朱厌",
	boss_bifang: "毕方",
	boss_yingzhao: "英招",

	boss_yaoshou: "妖兽",
	boss_yaoshou_info: "锁定技，你与其他角色计算-2。",
	boss_duqu: "毒躯",
	boss_duqu_info: "锁定技，你受到伤害时，伤害来源获得1枚“蛇毒”标记；你自身不会拥有“蛇毒”标记；你的【桃】均视为【杀】。“蛇毒”标记：锁定技，拥有“蛇毒”标记的角色回合开始时，需要选择弃置X张牌或者失去X点体力，然后弃置一枚“蛇毒”标记（X为其拥有的“蛇毒”标记个数）。",
	boss_shedu: "蛇毒",
	boss_jiushou: "九首",
	boss_jiushou_info: "锁定技，你的手牌上限始终为9，你的出牌阶段开始时以及你的回合结束时，将手牌补至手牌上限，你始终跳过你的摸牌阶段。",
	boss_echou_switch: "恶臭",
	boss_echou: "恶臭",
	boss_echou_info: "体力值首次减少至一半或更少时激活此技能。锁定技，除你之外的其他角色使用【桃】或【酒】时，获得1枚“蛇毒”标记。",
	boss_bingxian: "兵燹",
	boss_bingxian_info: "锁定技，其他角色的回合结束时，若其回合内没有使用【杀】，则视为你对其使用一张【杀】。",
	boss_juyuan: "巨猿",
	boss_juyuan_info: "锁定技，你的体力上限+5，你的出牌阶段内，若你的体力少于上一次你的回合结束时的体力，则你本回合使用【杀】可额外指定1个目标。",
	boss_xushi_switch: "蓄势",
	boss_xushi: "蓄势",
	boss_xushi_info: "体力值首次减少至一半或更少时激活此技能。锁定技，你的出牌阶段结束时，你令自己翻面；当你的武将牌从背面翻至正面时，对所有其他角色造成随机1至2点伤害。",
	boss_zhaohuo: "兆火",
	boss_zhaohuo_info: "锁定技，你造成的所有伤害均视为火属性伤害；你的回合中，所有其他角色的防具牌无效；你免疫所有火属性伤害。",
	boss_honglianx: "红莲",
	boss_honglianx_info: "锁定技，你的红色牌不计入你的手牌上限；你的回合开始时，随机获得牌堆中0到3张红色牌，然后随机对3到0名其他角色各造成1点火属性伤害。",
	boss_yanyu: "炎狱",
	boss_yanyu_switch: "炎狱",
	boss_yanyu_info: "体力值首次减少至一半或更少时激活此技能。锁定技，其他角色回合开始时进行判定，若为红色则受到1点火属性伤害，并重复此过程（每个回合最多判定3次）。",
	boss_fengdong: "封冻",
	boss_fengdong_info: "锁定技，你的回合内，其他角色的非锁定技无效。",
	boss_xunyou: "巡游",
	boss_xunyou_info: "锁定技，其他角色回合开始时，你随机获得场上除你以外的一名角色区域内的一张牌，若你获得的是装备牌，则你使用之。",
	boss_sipu: "司圃",
	boss_sipu_switch: "司圃",
	boss_sipu_info: "体力值首次减少至一半或更少时激活此技能。锁定技，你的出牌阶段内，若你使用的牌数小于等于2张，其他角色无法使用或打出牌。",

	boss_wuzang: "无脏",
	boss_wuzang_info: "锁定技，摸牌阶段，你的摸牌基数改为X（X为你的体力值一半且至少为5）；你的手牌上限基数为0。",
	boss_xiangde: "相德",
	boss_xiangde_info: "锁定技，其他角色对你造成伤害时，若其装备区内有武器牌，此伤害+1。",
	boss_yinzei: "隐贼",
	boss_yinzei_switch: "隐贼",
	boss_yinzei_info: "体力值首次减少至一半或更少时激活此技能。锁定技，若你没有手牌，其他角色对你造成伤害后，随机弃置一张牌。",
	boss_zhue: "助恶",
	boss_zhue_info: "锁定技，每当一名其他角色造成伤害后，你与伤害来源各摸一张牌。",
	boss_futai: "复态",
	boss_futai_info: "锁定技，你的回合外，其他角色不能使用【桃】；你的回合开始时，你令所有角色回复1点体力。",
	boss_yandu: "厌笃",
	boss_yandu_switch: "厌笃",
	boss_yandu_info: "体力值首次减少至一半或更少时激活此技能。锁定技，其他角色回合结束后，若其未造成过伤害，你获得其一张牌。",
	boss_minwan: "冥顽",
	boss_minwan_info: "锁定技，当你于回合内使用牌对其他角色造成伤害后，你于此回合内使用牌只能指定你与这些角色为目标，且你每使用一张牌，摸一张牌。",
	boss_nitai: "拟态",
	boss_nitai_info: "锁定技，防止你于回合内受到的伤害；你于回合外受到火属性伤害+1。",
	boss_luanchang: "乱常",
	boss_luanchang_switch: "乱常",
	boss_luanchang_info: "体力值首次减少至一半或更少时激活此技能。锁定技，回合开始时，你视为使用【南蛮入侵】；回合结束时，你视为使用【万箭齐发】。",
	boss_tanyu: "贪欲",
	boss_tanyu_info: "锁定技，跳过你的弃牌阶段；结束阶段，若你的手牌数为全场最多，失去1点体力。",
	boss_cangmu: "藏目",
	boss_cangmu_info: "锁定技，你令摸牌阶段摸牌基数改为X（X为存活角色数）。",
	boss_jicai: "积财",
	boss_jicai_switch: "积财",
	boss_jicai_info: "体力值首次减少至一半或更少时激活此技能。锁定技，一名角色回复体力后，你与其各摸一张牌。",
	boss_xiongshou: "凶兽",
	boss_xiongshou_info: "锁定技，你使用【杀】对体力值小于你的角色造成的伤害+1；你与其他角色距离-1；你不能被翻面。",
	sadouchengbing: "撒豆成兵",
	sadouchengbing_info: "出牌阶段对自己使用，若你的势力为“神”，摸X张牌；否则将你手牌补至X；（X为你的体力上限且至多为5）。",
	yihuajiemu: "移花接木",
	yihuajiemu_info: "出牌阶段对一名有牌的其他角色使用，令其使用一张【杀】，或交给你两张牌。",
	chiyanzhenhunqin: "赤焰镇魂琴",
	chiyanzhenhunqin_info: "锁定技，你造成的伤害均视为具有火属性。",
	juechenjinge: "绝尘金戈",
	juechenjinge_info: "锁定技，敌方角色计算与己方其他角色距离+1。",
	xiuluolianyuji: "修罗炼狱戟",
	xiuluolianyuji_info: "你使用【杀】可以额外指定任意名攻击范围内的其他角色为目标；锁定技，你使用【杀】造成的伤害+1，然后令受到伤害的角色回复1点体力。",
	longfenghemingjian: "鸾凤和鸣剑",
	longfenghemingjian_info: "你使用的雷【杀】或火【杀】指定目标后，可令对方选择弃置一张牌或令你摸一张牌。",
	qicaishenlu: "七彩神鹿",
	qicaishenlu_info: "锁定技，你计算与其他角色的距离时-1，当你造成属性伤害时，你令此伤害+1。",
	boss_mengpohuihun: "回魂",
	boss_mengpohuihun_info: "若场上有角色在本局游戏中因孟婆的〖忘魂〗失去过技能，则令其恢复该技能；此牌进入弃牌堆后，会被销毁。",
	honghuangzhili: "洪荒之力",
	honghuangzhili_cbg: "洪",
	honghuangzhili_info: "若该角色的势力是神，你获得其一张牌，其〖神裔〗无效直到其下家的回合（这个下家是动态变化的，会随着一个人的死或者复活而变化）开始；若该角色的势力不是神，其翻面。",

	boss_qingmushilian: "春之试炼",
	boss_qinglong: "青龙",
	boss_mushengoumang: "木神勾芒",
	boss_shujing: "树精",
	boss_taihao: "太昊",

	boss_baimangshilian: "秋之试炼",
	boss_baihu: "白虎",
	boss_jinshenrushou: "金神蓐收",
	boss_mingxingzhu: "明刑柱",
	boss_shaohao: "少昊",

	boss_xuanlinshilian: "冬之试炼",
	boss_xuanwu: "玄武",
	boss_shuishenxuanming: "水神玄冥",
	boss_shuishengonggong: "水神共工",
	boss_zhuanxu: "颛顼",

	boss_lingqu: "灵躯",
	boss_lingqu_info: "锁定技，当你受到伤害后，你摸一张牌，然后手牌上限+1；防止你受到的大于1点的伤害。",
	boss_zirun: "滋润",
	boss_zirun_info: "锁定技，准备阶段开始时，你令所有角色摸一张牌，若其装备区内有牌，则其额外摸一张牌。",
	boss_juehong: "决洪",
	boss_juehong_info: "锁定技，准备阶段开始时，你令所有敌方角色自己弃置自己的装备区内的所有牌，若其装备区内没有牌，则改为你弃置其一张手牌。",
	boss_zaoyi: "皂仪",
	boss_zaoyi_info: "锁定技，只要水神玄冥存活，你不会成为敌方角色使用锦囊牌的目标，只要水神共工存活，你不会成为敌方角色使用基本牌的目标。水神玄冥和水神共工均死亡后，你摸四张牌，然后从下回合开始，每个回合开始时使体力值最少的敌方角色失去所有体力。",
	boss_baiyi: "白仪",
	boss_baiyi_info: "锁定技，每名敌方角色的摸牌阶段，若当前轮数小于3，其少摸一张牌；第五轮开始时，每名敌方角色弃置两张牌；当己方角色受到的雷电伤害时，若当前轮数小于7，其防止此伤害。",
	boss_qingzhu: "擎柱",
	boss_qingzhu_info: "锁定技，你跳过弃牌阶段，若你没有〖殛顶〗，你于出牌阶段不能使用【杀】。",
	boss_jiazu: "枷足",
	boss_jiazu_info: "锁定技，回合开始时，弃置你上家和下家的敌方角色的装备区内的坐骑牌。",
	boss_jiding: "殛顶",
	boss_jiding_info: "锁定技，其他己方角色受到伤害后，若伤害来源为敌方角色，则你视为对伤害来源使用雷【杀】，若此【杀】造成伤害，蓐收回复1点体力。然后你失去此技能（只有发动了才会失去，没发动不会失去）。",
	boss_xingqiu: "刑秋",
	boss_xingqiu_info: "锁定技，每两轮的出牌阶段开始时，你横置所有敌方角色，然后使明刑柱获得〖殛顶〗。",
	boss_kuangxiao: "狂啸",
	boss_kuangxiao_info: "锁定技，你的回合内，你使用【杀】没有距离限制，且指定所有敌方角色为目标。",
	boss_shenyi: "神裔",
	boss_shenyi_info: "锁定技，你的武将牌始终正面向上，你的判定区内的牌效果反转。",
	boss_shenen: "神恩",
	boss_shenen_info: "锁定技，所有己方角色使用牌无距离限制；所有敌方角色摸牌阶段多摸一张牌且手牌上限+1。",
	boss_fentian: "焚天",
	boss_fentian_info: "锁定技，你造成的伤害视为火焰伤害；你使用红色牌无距离和次数限制，且不可被其他角色使用【闪】或【无懈可击】响应。",
	boss_fentian2: "焚天",
	boss_xingxia: "行夏",
	boss_xingxia_info: "每两轮限一次，出牌阶段，你可以对焰灵造成2点火焰伤害，然后令每名敌方角色选择一项：1.弃置一张红色牌；2.你对其造成1点火焰伤害。",
	boss_huihuo: "回火",
	boss_huihuo_info: "锁定技，当你死亡时，你对所有敌方角色各造成3点火焰伤害；出牌阶段，你可以多使用一张【杀】。",
	boss_furan: "复燃",
	boss_furan2: "复燃",
	boss_furan_info: "当你濒死时，所有敌方角色视为可以将红色牌当【桃】对你使用。",
	boss_chiyi: "赤仪",
	boss_chiyi2: "赤仪",
	boss_chiyi_info: "锁定技，从第三轮开始，敌方角色受到的伤害+1；第五轮开始时，你对所有角色各造成1点火焰伤害；第七轮开始时，你对焰灵造成5点火焰伤害。",
	boss_buchun: "布春",
	boss_buchun_info: "每两轮限一次，出牌阶段，若场上有死亡的树精，你可以失去1点体力，复活所有树精，使其回复体力至1点，补充手牌至两张；若场上没有死亡的树精，你可以为一名己方角色回复2点体力。",
	boss_cuidu: "淬毒",
	boss_cuidu_info: "锁定技，你对敌方角色造成伤害后，若其没有“中毒”，你令其获得“中毒”，然后令木神勾芒摸一张牌。",
	boss_zhongdu: "中毒",
	boss_zhongdu_bg: "毒",
	boss_zhongdu_info: "锁定技，回合开始时，你进行判定，若结果不为红桃，你受到1点无来源的伤害，若结果不为黑桃，你失去此技能。",
	boss_qingyi: "青仪",
	boss_qingyi_info: "锁定技，第三轮开始时，己方角色各回复1点体力；第五轮开始时，敌方角色各失去1点体力；第七轮开始时，复活木神勾芒和树精，使其各摸三张牌，各+1体力上限，然后各回复3点体力。",

	boss_guimou: "鬼谋",
	boss_guimou_info: "结束阶段，你可以令一名随机的其他角色进入混乱状态直到其下一回合结束。",
	boss_yuance: "远策",
	boss_yuance_info: "每当一名角色受到其他角色的伤害，你可以选择一项并进行一次判定：1. 若结果为黑色，受伤害角色失去1点体力，否则伤害来源失去1点体力；2. 若结果为红色，受伤害角色回复1点体力，否则伤害来源回复1点体力。",
	boss_qizuo: "奇佐",
	boss_qizuo_info: "你可以令你的普通锦囊牌额外结算一次。",
	boss_guixin: "归心",
	boss_guixin_info: "锁定技，其他角色摸牌时，若摸牌数不少于2，须将摸到的牌中的一张交给你。",
	xiongcai: "雄才",
	xiongcai_info: "锁定技，你在回合结束后随机获得一个魏势力角色的所有技能。",
	xiaoxiong: "枭雄",
	xiaoxiong_info: "锁定技，每当一名其他角色使用一张基本牌或锦囊牌，你获得一张与之同名的牌；在一名其他角色的结束阶段，若其本回合没有使用牌，你对其造成1点伤害。",
	boss_zhangwu: "章武",
	boss_zhangwu_info: "每当你受到一次伤害，你可以弃置任意张牌并令伤害来源选择一项：弃置等量的牌，或受到等量的伤害。",
	xiangxing: "禳星",
	xiangxing_info: "锁定技，游戏开始时，你获得7枚星；每当你累计扣减7点体力，你失去一枚星，并造成7点雷属性伤害，随机分配给其他角色；当你失去全部星后，你的体力上限变为3。",
	yueyin: "月隐",
	yueyin_info: "锁定技，你的每一枚星对应的一个特定条件，当你失去星时，若满足此条件，则不造成伤害。",
	xiangxing7_info: "你没有手牌",
	xiangxing6_info: "此次受到的是火属性伤害",
	xiangxing5_info: "此次受到的是雷属性伤害",
	xiangxing4_info: "此次为失去体力",
	xiangxing3_info: "一名其他角色有至少4件装备",
	xiangxing2_info: "你的判定区内至少有两张牌",
	xiangxing1_info: "场上只有2名存活角色",
	gaiming: "改命",
	gaiming_info: "锁定技，在你的判定牌生效前，你观看牌堆顶的七张牌并选择一张作为判定结果，此结果不可更改。",
	fengqi: "风起",
	fengqi_info: "准备阶段和结束阶段，你可以视为使用任意一张普通锦囊牌。",

	jiaoxia: "皎霞",
	jiaoxia_info: "每当你成为红色牌的目标，你可以摸一张牌。",
	lingbo: "凌波",
	lingbo_info: "每当你使用或打出一张【闪】，你可以摸两张牌。",
	tiandao: "天道",
	tiandao_info: "任意一名角色的判定生效前，你可以打出一张牌替换之。",
	yunshen: "云身",
	yunshen2: "云身",
	yunshen_info: "每当你使用或打出一张【闪】时，你可以令你的防御距离+1；准备阶段，你将累计的防御距离清零，然后摸等量的牌。",
	lianji: "连计",
	lianji_info: "出牌阶段限一次，你可以选择一张手牌并指定两名角色进行拼点，拼点赢的角色获得此牌，并对没赢的角色造成1点伤害。",
	mazui: "麻醉",
	mazui2: "麻醉",
	mazui_info: "出牌阶段限一次，你可以将一张黑色手牌置于一名角色的武将牌上，该角色造成的下一次伤害-1，然后获得此牌。",

	boss_nbianshen: "变形",
	boss_nbianshenx: "变形",
	boss_nbianshenx_info: "你从第二轮开始，每一轮幻化为警觉、任性、睿智、暴怒四种随机状态中的一种。",
	boss_mengtai: "萌态",
	boss_mengtai_info: "锁定技，若你的出牌阶段被跳过，你跳过本回合的弃牌阶段；若你的摸牌阶段被跳过，结束阶段开始时，你摸三张牌。",
	boss_ruizhi: "睿智",
	boss_ruizhi_info: "锁定技，其他角色的准备阶段开始时，其选择一张手牌和一张装备区里的牌，然后弃置其余的牌。",
	boss_jingjue: "警觉",
	boss_jingjue_info: "每当你于回合外失去牌时，你可以进行一次判定，若结果为红色，你回复1点体力。",
	boss_renxing: "任性",
	boss_renxing_info: "锁定技，你的回合外，一名角色受到1点伤害后或回复1点体力时，你摸一张牌。",
	boss_nbaonu: "暴怒",
	boss_nbaonu_info: "锁定技，摸牌阶段，你改为摸X张牌（X为4到你体力值间的随机数）；若你的体力值小于5，则你使用【杀】造成的伤害+1且无次数限制。",
	boss_shouyi: "兽裔",
	boss_shouyi_info: "锁定技，你使用牌无距离限制。",

	boss_nianrui: "年瑞",
	boss_nianrui_info: "锁定技，摸牌阶段，你额外摸两张牌。",
	boss_qixiang: "祺祥",
	boss_qixiang1: "祺祥",
	boss_qixiang2: "祺祥",
	boss_qixiang_info: "乐不思蜀判定时，你的方块判定牌视为红桃；兵粮寸断判定时，你的黑桃判定牌视为草花。",

	qiwu: "栖梧",
	qiwu_info: "锁定技。每当你使用一张梅花牌，你回复1点体力。",
	jizhen: "激阵",
	jizhen_info: "结束阶段，你可以令所至多两名已受伤角色摸一张牌。",

	boss_yushou: "驭兽",
	boss_yushou_info: "出牌阶段开始时，你可以对所有敌方角色使用一张【南蛮入侵】。",
	boss_moyany: "魔炎",
	boss_moyany_info: "每当你于回合外失去牌时，你可以进行一次判定，若结果为红色，你对一名其他角色造成2点火焰伤害。",
	boss_modao: "魔道",
	boss_modao_info: "锁定技，准备阶段，你摸两张牌。",
	boss_mojian: "魔箭",
	boss_mojian_info: "出牌阶段开始时，你可以对所有敌方角色使用一张【万箭齐发】。",
	boss_danshu: "丹术",
	boss_danshu_info: "每当你于回合外失去牌时，你可以进行一次判定，若结果为红色，你回复1点体力。",

	boss_zuijiu: "醉酒",
	boss_zuijiu_info: "锁定技，你因【杀】造成伤害时，此伤害+1。",
	boss_taiping: "太平",
	boss_taiping_info: "锁定技，摸牌阶段摸牌时，你的摸牌数量+2。",
	boss_suoming: "索命",
	boss_suoming_info: "结束阶段，将任意名未被横置的其他角色的武将牌横置。",
	boss_xixing: "吸星",
	boss_xixing_info: "准备阶段，对任意一名横置的其他角色造成1点雷电伤害，然后回复1点体力。",

	boss_baolian: "暴敛",
	boss_baolian_info: "锁定技，结束阶段，你摸两张牌。",
	boss_manjia: "蛮甲",
	boss_manjia_info: "锁定技，若你的装备区内没有防具牌，则你视为装备了【藤甲】。",
	boss_xiaoshou: "枭首",
	boss_xiaoshou_info: "结束阶段，对体力不小于你的一名其他角色造成3点伤害。",
	boss_guiji: "诡计",
	boss_guiji_info: "锁定技，准备阶段结束时，若你的判定区内有牌，你随机弃置其中一张牌。",
	boss_lianyu: "炼狱",
	boss_lianyu_info: "结束阶段，你可以对所有敌方角色造成1点火焰伤害。",

	boss_guihuo: "鬼火",
	boss_guihuo_info: "结束阶段，你可以对一名其他角色造成1点火焰伤害。",
	boss_minbao: "冥爆",
	boss_minbao_info: "锁定技，当你死亡时，对场上所有其他角色造成1点火焰伤害。",
	boss_luolei: "落雷",
	boss_luolei_info: "准备阶段，你可以对一名其他角色造成1点雷电伤害。",
	boss_beiming: "悲鸣",
	boss_beiming_info: "锁定技，当你死亡时，你令杀死你的角色弃置所有手牌。",
	boss_guimei: "鬼魅",
	boss_guimei_info: "锁定技，你不能成为延时类锦囊的目标。",
	boss_didong: "地动",
	boss_didong_info: "结束阶段，你可以选择一名敌方角色将其武将牌翻面。",
	boss_shanbeng: "山崩",
	boss_shanbeng_info: "锁定技，当你死亡时，你令所有其他角色弃置其装备区内的所有牌。",

	boss_chiyan_intro1: "&nbsp;第一关",
	boss_chiyan_intro1_info: "挑战朱雀",
	boss_chiyan_intro2: "&nbsp;第二关",
	boss_chiyan_intro2_info: "挑战火神祝融、焰灵",
	boss_chiyan_intro3: "&nbsp;第三关",
	boss_chiyan_intro3_info: "挑战炎帝、火神祝融、焰灵",
	boss_chiyan_intro3_append: "每通过一关，游戏轮数清零，阵亡角色复活，所有角色重置武将和区域内的牌，并获得4-X张起始手牌，X为阵亡角色数。",

	boss_qingmu_intro1: "&nbsp;第一关",
	boss_qingmu_intro1_info: "挑战青龙",
	boss_qingmu_intro2: "&nbsp;第二关",
	boss_qingmu_intro2_info: "挑战木神勾芒、树精",
	boss_qingmu_intro3: "&nbsp;第三关",
	boss_qingmu_intro3_info: "挑战太昊、木神勾芒、树精",
	boss_qingmu_intro3_append: "每通过一关，游戏轮数清零，阵亡角色复活，所有角色重置武将和区域内的牌，并获得4-X张起始手牌，X为阵亡角色数。",

	boss_xuanlin_intro1: "&nbsp;第一关",
	boss_xuanlin_intro1_info: "挑战玄武",
	boss_xuanlin_intro2: "&nbsp;第二关",
	boss_xuanlin_intro2_info: "挑战水神玄冥、水神共工",
	boss_xuanlin_intro3: "&nbsp;第三关",
	boss_xuanlin_intro3_info: "挑战颛顼、水神玄冥、水神共工",
	boss_xuanlin_intro3_append: "每通过一关，游戏轮数清零，阵亡角色复活，所有角色重置武将和区域内的牌，并获得4-X张起始手牌，X为阵亡角色数。",

	boss_baimang_intro1: "&nbsp;第一关",
	boss_baimang_intro1_info: "挑战白虎",
	boss_baimang_intro2: "&nbsp;第二关",
	boss_baimang_intro2_info: "挑战金神蓐收、明刑柱",
	boss_baimang_intro3: "&nbsp;第三关",
	boss_baimang_intro3_info: "挑战少昊、金神蓐收、明刑柱",
	boss_baimang_intro3_append: "每通过一关，游戏轮数清零，阵亡角色复活，所有角色重置武将和区域内的牌，并获得4-X张起始手牌，X为阵亡角色数。",

	boss_bianshen_intro1: "&nbsp;第一关",
	boss_bianshen_intro1_info: "挑战魑、魅、魍、魉中的随机一个",
	boss_bianshen_intro2: "&nbsp;第二关",
	boss_bianshen_intro2_info: "挑战牛头、马面中的随机一个",
	boss_bianshen_intro3: "&nbsp;第三关",
	boss_bianshen_intro3_info: "挑战白无常、黑无常中的随机一个",
	boss_bianshen_intro4: "&nbsp;第四关",
	boss_bianshen_intro4_info: "挑战罗刹、夜叉中的随机一个",
	// boss_bianshen2:'后援',
	// boss_bianshen2_info:'你死亡后，随机召唤牛头、马面中的一个。',
	// boss_bianshen3:'后援',
	// boss_bianshen3_info:'你死亡后，随机召唤白无常、黑无常中的一个。',
	// boss_bianshen4:'后援',
	// boss_bianshen4_info:'你死亡后，随机召唤罗刹、夜叉中的一个。',

	boss_qiangzheng: "强征",
	boss_qiangzheng_info: "锁定技，结束阶段，你获得每个敌方角色的一张手牌。",
	boss_baolin: "暴凌",
	guizhen: "归真",
	guizhen_info: "每当你失去最后一张手牌，你可以所有敌人失去全部手牌，没有手牌的角色失去1点体力（不触发技能）。",
	boss_shengshou: "圣手",
	boss_shengshou_info: "每当你使用一张牌，你可以进行一次判定，若为红色，你回复1点体力。",
	wuqin: "五禽戏",
	wuqin_info: "结束阶段，若你没有手牌，可以摸三张牌。",

	boss_konghun: "控心",
	boss_konghun_info: "结束阶段，你可以指定一名敌人令其进入混乱状态（不受对方控制，并将队友视为敌人）直到下一回合开始。",
	yuehun: "月魂",
	yuehun_info: "结束阶段，你可以回复1点体力并摸两张牌。",
	fengwu: "风舞",
	fengwu_info: "出牌阶段限一次，可令除你外的所有角色依次对与其距离最近的另一名角色使用一张【杀】，无法如此做者失去1点体力。",
	boss_wange: "笙歌",

	huanhua: "幻化",
	huanhua_info: "锁定技，游戏开始时，你获得其他角色的所有技能，体力上限变为其他角色之和；其他角色于摸牌阶段摸牌时，你摸等量的牌；其他角色于弃牌阶段弃牌时，你弃置等量的手牌。",

	boss_leiji: "雷击",
	boss_leiji_info: "每当你使用或打出一张【闪】，可令任意一名角色进行一次判定，若结果为黑色，其受到1点雷电伤害，然后你摸一张牌。",
	jidian: "亟电",
	jidian_info: "每当你造成一次伤害，可以指定距离受伤害角色1以内的一名其他角色进行判定，若结果为黑色，该角色受到1点雷电伤害。",

	tinqin: "听琴",
	boss_guihan: "归汉",
	boss_guihan_info: "限定技，濒死阶段，你可以将体力回复至体力上限，摸四张牌，令所有敌人的技能恢复，失去技能〖悲歌〗和〖胡笳〗，并获得技能〖听琴〗、〖蕙质〗。",
	boss_huixin: "蕙质",
	boss_huixin_info: "每当你于回合外失去牌，可以进行一次判定，若为黑色，当前回合角色失去1点体力，否则你回复1点体力并摸一张牌。",
	boss_hujia: "胡笳",
	boss_hujia_info: "结束阶段，若你已受伤，可以弃置一张牌令一名其他角色的所有技能失效，若其所有技能已失效，改为令其减少1点体力上限。",
	boss_honglian: "红莲",
	boss_honglian_info: "锁定技，结束阶段，你摸两张牌，并对所有敌人造成1点火焰伤害。",
	huoshen: "火神",
	huoshen_info: "锁定技，你防止即将受到的火焰伤害，改为回复1点体力。",
	boss_xianyin: "仙音",
	boss_xianyin_info: "每当你于回合外失去牌，你可以进行一次判定，若为红色，你令一名敌人失去1点体力。",

	boss_yuhuo: "浴火",
	boss_yuhuo_info: "觉醒技，在你涅槃后，你获得技能〖神威〗、〖朱羽〗。",
	boss_tianyu: "天狱",
	boss_tianyu_info: "锁定技，结束阶段，你解除横置状态，除你之外的所有角色进入横置状态。",

	boss_jizhi: "集智",
	boss_jizhi_info: "每当你使用一张非转化的非基本牌，你可以摸一张牌并展示之。",
	boss_guiyin: "归隐",
	boss_guiyin_info: "锁定技，体力值比你多的角色无法在回合内对你使用卡牌。",
	boss_gongshen: "工神",
	boss_gongshen_info: "锁定技，除你之外的角色没有装备区；你不能成为其他角色的延时锦囊牌的目标。",

	fanghua: "芳华",
	fanghua_info: "结束阶段，你可以令所有已翻面角色失去1点体力。",
	tashui: "踏水",
	tashui_info: "每当你使用或打出一张黑色牌，你可以令一名其他角色翻面。",

	boss_wuxin: "无心",
	boss_wuxin_info: "锁定技，你防止即将受到的伤害，改为失去1点体力；你不能成为其他角色的延时锦囊的目标。",
	shangshix: "伤逝",
	shangshix2: "伤逝",
	shangshix_info: "锁定技，你的手牌数至少为4，结束阶段，若你的体力值大于1，你令场上所有角色失去1点体力。",

	boss_baonu: "暴怒",
	boss_baonu_info: "锁定技，当你的体力值降至4或更低时，你变身为暴怒战神或神鬼无前，并立即开始你的回合。",
	shenwei: "神威",
	shenwei_info: "锁定技，摸牌阶段，你额外摸X张牌，你的手牌上限+X（X为场上其他角色的数目且至多为3）。",
	xiuluo: "修罗",
	xiuluo_info: "准备阶段，你可以弃置一张牌，然后弃置你判定区内一张同花色的牌，然后你可以重复此流程。",
	shenqu: "神躯",
	shenqu_info: "每名角色的准备阶段，若你的手牌数少于或等于你的体力上限数，你可以摸两张牌；当你受到伤害后，你可以使用一张【桃】。",
	jiwu: "极武",
	jiwu_info: "出牌阶段，你可以弃置一张牌，然后获得获得以下一项技能直到回合结束：〖强袭〗、〖铁骑〗、〖旋风〗、〖完杀〗。",

	boss_jingjia: "精甲",
	boss_jingjia_info: "锁定技，游戏开始时，将本局游戏中加入的装备随机置入你的装备区。",
	boss_aozhan: "鏖战",
	boss_aozhan_info: "锁定技，若你装备区内有：武器牌，你可以多使用一张【杀】；防具牌，防止你受到的超过1点的伤害；坐骑牌，摸牌阶段多摸一张牌；宝物牌，跳过你的判定阶段。",

	boss_qinguangwang_ab: "秦广王",
	boss_qinguangwang: "秦广王·蒋子文",
	boss_panguan: "判官",
	boss_panguan_info: "锁定技，你不能成为延时类锦囊的目标。",
	boss_juhun: "拘魂",
	boss_juhun_info: "锁定技，结束阶段，你令随机一名其他角色的武将牌翻面或横置。",
	boss_wangxiang: "望乡",
	boss_wangxiang_info: "锁定技，当你死亡时，你令所有其他角色弃置其装备区内的所有牌。",
	boss_chujiangwang_ab: "楚江王",
	boss_chujiangwang: "楚江王·厉温",
	boss_bingfeng: "冰封",
	boss_bingfeng_info: "锁定技，你死亡时，若杀死你的角色武将牌是正面朝上， 你令其翻面。",
	boss_songdiwang_ab: "宋帝王",
	boss_songdiwang: "宋帝王·余懃",
	boss_heisheng: "黑绳",
	boss_heisheng_info: "锁定技，你死亡时，横置所有场上角色。",
	boss_shengfu: "绳缚",
	boss_shengfu_info: "锁定技，你的回合结束时，随机弃置一张场上其他角色的坐骑牌。",
	boss_wuguanwang_ab: "五官王",
	boss_wuguanwang: "五官王·吕岱",
	boss_zhiwang: "治妄",
	boss_zhiwang_info: "锁定技，当其他角色于摸牌阶段外得到牌时，你随机弃置其一张手牌。",
	boss_zhiwang_planetarian: "注意事项",
	boss_zhiwang_planetarian_info: "若触发〖治妄〗的角色因〖治妄〗触发的其他的技能（如〖伤逝〗〖连营〗等）继续得到了牌，则该角色将其武将牌变更为孙策。",
	boss_gongzheng: "公正",
	boss_gongzheng_info: "锁定技，准备阶段，若你判定区有牌，你随机弃置一张你判定区的牌。",
	boss_xuechi: "血池",
	boss_xuechi_info: "锁定技，你的回合结束时，令随机一名其他角色失去2点体力。",
	boss_yanluowang_ab: "阎罗王",
	boss_yanluowang: "阎罗王·包拯",
	boss_tiemian: "铁面",
	boss_tiemian_info: "锁定技，你的防具区没有牌时，视为你装备【仁王盾】。",
	boss_zhadao: "铡刀",
	boss_zhadao_info: "锁定技，你使用【杀】指定目标后，你令目标角色防具无效。",
	boss_zhuxin: "诛心",
	boss_zhuxin_info: "锁定技，你死亡时，你令场上血量最少的一名其他角色受到2点伤害。",
	boss_bianchengwang_ab: "卞城王",
	boss_bianchengwang: "卞城王·毕元宾",
	boss_leizhou: "雷咒",
	boss_leizhou_info: "锁定技，准备阶段，你对随机一名其他角色造成1点雷属性伤害。",
	boss_leifu: "雷缚",
	boss_leifu_info: "锁定技，你的回合结束时，随机横置一名其他角色。",
	boss_leizhu: "雷诛",
	boss_leizhu_info: "锁定技，你死亡时，对所有其他角色造成依次造成1点雷属性伤害。",
	boss_taishanwang_ab: "泰山王",
	boss_taishanwang: "泰山王·董和",
	boss_fudu: "服毒",
	boss_fudu_info: "锁定技，其他角色使用【桃】时，你令随机另一名其他角色失去1点体力。",
	boss_kujiu: "苦酒",
	boss_kujiu_info: "锁定技，其他角色准备阶段，你令其失去1点体力，然后该角色视为使用一张【酒】。",
	boss_renao: "热恼",
	boss_renao_info: "锁定技，你死亡时，你令随机一名其他角色受到3点火属性伤害。",
	boss_dushiwang_ab: "都市王",
	boss_dushiwang: "都市王·黄中庸",
	boss_remen: "热闷",
	boss_remen_info: "锁定技，若你的装备区内没有防具牌，则【南蛮入侵】、【万箭齐发】和普通【杀】对你无效。",
	boss_zhifen: "炙焚",
	boss_zhifen_info: "锁定技，准备阶段，你随机选择一名其他角色，获得其一张手牌（没有则不获得），并对其造成1点火属性伤害。",
	boss_huoxing: "火刑",
	boss_huoxing_info: "锁定技，你死亡时，你对所有其他角色造成1点火属性伤害。",
	boss_pingdengwang_ab: "平等王",
	boss_pingdengwang: "平等王·陆游",
	boss_suozu: "锁足",
	boss_suozu_info: "锁定技，准备阶段，你令所有其他角色横置。",
	boss_abi: "阿鼻",
	boss_abi_info: "锁定技，锁定技，你受到伤害时，你对伤害来源造成伤害的角色造成1点随机属性伤害（雷或火随机）。",
	boss_pingdeng: "平等",
	boss_pingdeng_info: "锁定技，你死亡时，你对体力最多的一名其他角色造成2点随机属性伤害（属性随机），然后再对一名体力最多的其他角色造成1点随机属性伤害（属性随机）。",
	boss_zhuanlunwang_ab: "转轮王",
	boss_zhuanlunwang: "转轮王·薛礼",
	boss_lunhui: "轮回",
	boss_lunhui_info: "锁定技，准备阶段，若你的体力小于等于2，则你与场上除你以外体力最高且大于2的角色交换体力值。",
	boss_wangsheng: "往生",
	boss_wangsheng_info: "锁定技，你的出牌阶段开始时，视为你随机使用一张【南蛮入侵】或【万箭齐发】。",
	boss_zlfanshi: "反噬",
	boss_zlfanshi_info: "锁定技，每个回合你受到第一次伤害后，若再次受到伤害，则对随机一名其他角色造成1点伤害。",
	boss_shikieiki_ab: "四季映姬",
	boss_shikieiki: "四季映姬·夜魔仙那度",
	boss_yingzhong: "映冢",
	boss_yingzhong_info: "锁定技。你登场后的第一个回合开始时，你随机获得两个“阴间武将”的全部技能。",
	boss_yingzhong_append: '<span style="font-family:yuanli">四季映姬到阴曹地府<br>——阴(映)到家了！</span>',
	//孟婆:
	boss_mengpo: "孟婆",
	boss_shiyou: "拾忧",
	boss_shiyou_info: "其他角色于弃牌阶段弃置的牌进入弃牌堆前，你可以选择其中任意张花色各不相同的牌获得之。",
	boss_wanghun: "忘魂",
	boss_wanghun_info: "锁定技，你死亡时，令随机两名敌方角色各随机失去一个技能（主公技除外），并在牌堆中加入2张回魂。(回魂只能在挑战模式出现)",
	boss_wangshi: "往事",
	boss_wangshi_info: "锁定技，你存活时，敌方角色的回合开始时，令其于本回合不能使用或打出随机一种类型的牌（基本、锦囊、装备）。",
	boss_wangshi2: "往事",
	boss_wangshi2_info: "",
	//地藏王:
	boss_dizangwang: "地藏王",
	boss_bufo: "不佛",
	boss_bufo_info: "锁定技，你的回合开始时，你对所有距离为1的其他角色造成1点火焰伤害；你受到大于等于2的伤害时，令此伤害-1。",
	boss_wuliang: "无量",
	boss_wuliang_info: "锁定技，你登场时额外摸三张牌；结束阶段开始时，你摸两张牌；你的回合开始时，若你当前体力小于3，则回复至3。",
	boss_dayuan: "大愿",
	boss_dayuan_info: " 当一名角色判定牌最终生效前，你可以指定该判定牌的点数和花色。",
	boss_diting: "谛听",
	boss_diting_info: "锁定技，你的坐骑区被废除，你与别人计算距离时-1，别人与你计算距离时+1；你的坐骑牌均用于重铸。",
	/*
	//等阶
	"boss_sdyl_playerlevel1":"一阶",
	"boss_sdyl_playerlevel1_info":"",
	"boss_sdyl_playerlevel2":"二阶",
	"boss_sdyl_playerlevel2_info":"开局随机使用一张装备牌，起始手牌+1。",
	"boss_sdyl_playerlevel3":"三阶",
	"boss_sdyl_playerlevel3_info":"出杀次数+1，体力上限+1。",
	"boss_sdyl_playerlevel4":"四阶",
	"boss_sdyl_playerlevel4_info":"摸牌阶段多摸一张牌，起始手牌+1。",
	"boss_sdyl_playerlevel5":"重生",
	"boss_sdyl_playerlevel5_info":"限定技，当你处于濒死状态时，你可以弃置所有判定区牌，然后复原你的武将牌，将手牌补充至手牌体力上限（至多为5），将体力回复至体力上限。",

	"boss_sdyl_bosslevel1":"一阶",
	"boss_sdyl_bosslevel1_info":"",
	"boss_sdyl_bosslevel2":"二阶",
	"boss_sdyl_bosslevel2_info":"登场时随机使用一张装备牌。",
	"boss_sdyl_bosslevel3":"三阶",
	"boss_sdyl_bosslevel3_info":"出杀次数+1，回合开始获得一张【杀】，体力上限+1，起始手牌+1。",
	"boss_sdyl_bosslevel4":"四阶",
	"boss_sdyl_bosslevel4_info":"摸牌阶段多摸一张牌，手牌上限+1。",
	"boss_sdyl_bosslevel5":"五阶",
	"boss_sdyl_bosslevel5_info":"登场时视为使用一张【南蛮入侵】且此【南蛮入侵】伤害+1。体力上限+1，起始手牌+1。",
	*/
	boss_sunce: "那个男人",
	boss_hunzi: "魂姿",
	boss_hunzi_info: "觉醒技，准备阶段，若你的体力值为1，你减1点体力上限，失去技能〖魂佑〗并获得技能〖英姿〗和〖英魂〗。",
	boss_jiang: "激昂",
	boss_jiang_info: "①锁定技，〖激昂〗不会无效。②每当你使用或打出红色牌时，你可以摸一张牌。若你是因响应其他角色使用或打出的牌，则你获得对方使用或打出的牌。③当有其他角色使用或打出红色牌指定你为目标或响应你后，你可以摸一张牌并获得这些牌。",
	boss_hunyou: "魂佑",
	boss_hunyou_info: "锁定技，你的体力值变化和体力上限变化无效。",
	boss_taoni: "讨逆",
	boss_taoni_info: "锁定技，游戏开始时，每名角色回合开始时或你死亡时，你检查存活角色的合法性。若有角色存在非法行为，则你终止本局游戏。",

	boss_xhuanren: "关卡说明",
	boss_xhuanren_info: "",
	boss_xhuanren_info_boss: "第一关：挑战秦广王<br>第二关：挑战楚江王，宋帝王，五官王，阎罗王中的一个<br>第三关：挑战卞城王，泰山王，都市王，平等王中的一个<br>第四关：挑战转轮王",

	boss_newhuanren: "关卡说明",
	boss_newhuanren_info: "",
	boss_newhuanren_info_boss: "第一关：挑战秦广王<br>第二关：挑战楚江王，宋帝王，五官王，阎罗王中的一个<br>第三关：挑战卞城王，泰山王，都市王，平等王中的一个<br>第四关：挑战转轮王<br>注：孟婆将在每局前三个阶段随机一个阶段登场<br>地藏王登场规则为，50回合内通过第三关，并且在前三关中成功击杀孟婆。<br>选用的武将越阴间、占比越高，四季映姬登场概率就越大。<li>选陆逊左慈张春华于吉蒋费孔融自动变孙笨",
	lingsheji: "灵蛇髻",
	lingsheji2: "灵蛇髻",
	shanrangzhaoshu: "禅让诏书",
	xingtianpojunfu: "刑天破军斧",
	noda_axe: "刑天破军斧",
	noda_axe2: "刑天破军斧",
	jinwuluorigong: "金乌落日弓",
	iwasawa_crowbow: "金乌落日弓",
	lingsheji_info: "出牌阶段结束时，你可选择：1.摸一张牌。2.将一张牌置于武将牌上，并于回合结束后获得此牌。",
	shanrangzhaoshu_info: "其他角色于回合外得到牌后，若是其本回合内第一次得到牌，则你可以选择一项：交给其一张牌，或令其交给你一张牌。",
	xingtianpojunfu_info: "当你于出牌阶段内使用牌指定唯一目标后，你可弃置两张牌。若如此做，其本回合内不能使用或打出牌且其防具技能无效。",
	jinwuluorigong_info: "当你于出牌阶段内一次性失去了两张以上的手牌后，你可以弃置一名其他角色等量的牌。",
	TheDayIBecomeAGod: "神杀",
	thedayibecomeagod: "传承",
	thedayibecomeagod_info: "选择一名其他己方角色。若其势力非神，则改为神势力；若其势力为神，则将武将牌翻至正面，回复体力至体力上限，并将手牌摸至5。",
	gubuzifeng: "故步自封",
	gubuzifeng_disable: "故步自封",
	gubuzifeng_info: "出牌阶段，对一名其他角色使用。其的一个随机技能失效直到其下个回合结束。",
	goujiangdesidai: "篝酱的丝带",
	goujiangdesidai_info: "锁定技，若你未拥有技能〖纵丝〗，则你视为拥有技能〖纵丝〗；若你拥有技能〖纵丝〗，则你将此技能改为「出牌阶段限两次」。",
	goujiangdesidai_skill: "纵丝",
	niaobaidaowenha: "鸟白岛文蛤",
	niaobaidaowenha_skill: "鸟白岛文蛤",
	niaobaidaowenha_info: "当你减少1点体力上限后，你可令一名其他角色增加1点体力上限并回复1点体力。",
	niaobaidaowenha_skill_info: "当你减少1点体力上限后，你可令一名其他角色增加1点体力上限并回复1点体力。",
	shenzhixiunvfu: "神之修女服",
	shenzhixiunvfu_info: "没什么实际作用的衣服，仅仅是显得像个神而已。",

	mode_boss_card_config: "挑战卡牌",
	mode_boss_character_config: "挑战武将",

	// 台词部分
	"#boss_modao": "魔道影阵，助我法力。",
	"#boss_lunhui": "轮回反复，此法无解。",
	"#boss_wangsheng": "前生今世，不过皆苦。",
	"#boss_zlfanshi": "敢忤逆我，你是不知道真正的代价！",
	"#boss_zhuanlunwang:die": "你居然走到了最后！",
	"#boss_tiemian": "铁面无私，刚正不阿！",
	"#boss_zhadao": "铡刀之下，皆是恶徒！",
	"#boss_zhuxin": "诛人心魄，灭人心智。",
	"#boss_zhiwang": "罔顾伦常，必受其害！",
	"#boss_gongzheng": "公正以待，显其威法。",
	"#boss_xuechi": "炼狱血池，需要你的奉献。",
	"#boss_wuguanwang:die": "我的法阵，居然被破了！",
	"#boss_fudu": "服药止血，反被毒伤。",
	"#boss_kujiu": "此酒虽苦，酒效不减。",
	"#boss_renao": "惹恼我的代价，你可承受不起！",
	"#boss_heisheng": "想跑？痴人说梦！",
	"#boss_shengfu": "此绳索，是你无法逃脱的噩梦。",
	"#boss_songdiwang_enyuan": "有恩有惠，有伤有报。",
	"#boss_panguan": "世俗杂事，吾皆可判。",
	"#boss_juhun": "勾魂索命，拘魄入狱。",
	"#boss_wangxiang": "还是别望他乡了！",
	"#boss_suozu": "困其身，锁其足。",
	"#boss_abi": "阿鼻地狱，雷火皆来。",
	"#boss_pingdeng": "众生平等，你也难逃此罚！",
	"#boss_shiyou": "忧愁可拾，烦苦可消。",
	"#boss_wanghun": "忘情断爱，心魂可劫。",
	"#boss_wangshi": "红尘往事，再无牵挂。",
	"#boss_remen": "这燥热，真让人烦闷！",
	"#boss_zhifen": "焚身燃躯，日炙火烧！",
	"#boss_huoxing": "火海炼狱，普世之刑！",
	"#boss_bufo": "地狱未空，誓不成佛。",
	"#boss_wuliang": "无量劫难，众生度尽。",
	"#boss_dayuan": "地狱众生，发愿救度。",
	"#boss_diting": "静虑深密，犹如秘藏。",
	"#boss_chujiangwang_weimu": "暗涌掩身，查无踪迹。",
	"#boss_chujiangwang_fankui": "伤我，可是要有付出的！",
	"#boss_bingfeng": "接受这寒冰的封冻吧！",
	"#boss_leifu": "想出此阵，不要妄想！",
	"#boss_leizhou": "术法诅咒，显灵加威。",
	"#boss_leizhu": "你们皆要受到诛连罪行！",
	"#xiuluo1": "准备受死吧！",
	"#xiuluo2": "鼠辈！螳臂当车！",
	"#shenwei1": "萤烛之火，也敢与日月争辉？",
	"#shenwei2": "我不会输给任何人！",
	"#shenji1": "杂鱼们！都去死吧！",
	"#shenji2": "竟想赢我？痴人说梦！",
	"#boss_lvbu2:die": "虎牢关，失守了……",
	"#shenqu1": "别心怀侥幸了，你们不可能赢！",
	"#shenqu2": "虎牢关，我一人镇守足矣！",
	"#jiwu1": "我，是不可战胜的！",
	"#jiwu2": "今天，就让你们感受一下真正的绝望！",
	"#qiangxi_boss_lvbu31": "这么想死，那我就成全你！",
	"#qiangxi_boss_lvbu32": "项上人头，待我来取！",
	"#retieji_boss_lvbu31": "哈哈哈，破绽百出！",
	"#retieji_boss_lvbu32": "我要让这虎牢关下，血流成河！",
	"#xuanfeng_boss_lvbu31": "千钧之势，力贯苍穹！",
	"#xuanfeng_boss_lvbu32": "横扫六合，威震八荒！",
	"#wansha_boss_lvbu31": "蝼蚁，怎容偷生？",
	"#wansha_boss_lvbu32": "沉沦吧，在这无边的恐惧！",
	"#boss_lvbu3:die": "你们的项上人头，我改日再取！",

}