import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export { characterIntro }

const characterIntro = {
	//---------------------------------//上古神话
	'sgsh_huaxu':'<font color=cyan>上古神话-001</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;华胥氏，简称华胥，最早见于《列子·黄帝》。相传是中国上古时期母系氏族部落的一位杰出女首领。是伏羲与女娲之母。她生在一个叫华阳的地方，有了华胥后改名(华胥国)，古往今来，上百种中华典籍中均记载着一个叫华胥氏的氏族女首领及其儿女伏羲、女娲的故事。中国建国初期的多位朴素主义学者相信，华胥氏的历史比黄帝还要长得多。华胥国的传统服饰为长袍，即国服、华服，后来发展成为具有长袍特点的汉服，也与华胥国有关。<br><br>&nbsp;&nbsp;神话所记录的是一个民族早期的唯心世界观，以纪念族群中做过特别重大贡献的部落群体和首领。越朴实的神话，还原的早期先民生活和思想就越可信。<br><br>&nbsp;&nbsp;--来自搜狗百科',//华胥
	'sgsh_taizichangqin':'<font color=cyan>上古神话-002</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;太子长琴，《山海经》记载之神话人物。火神祝融的儿子，传说他出生的时候怀中抱着一把小琴，天地都因为他的出生而欢唱。<br><br>&nbsp;&nbsp;颛顼生老童，老童生祝融，祝融生太子长琴，传说太子长琴精于乐道，能使五色鸟舞于庭中。《左传》记载：“有五只彩鸟：一只叫皇鸟，一只叫鸾鸟，一只叫凤鸟，听见琴音就会翩翩起舞。<br><br>&nbsp;&nbsp;--来自搜狗百科”',//太子长琴
	'sgsh_nvba':'<font color=cyan>上古神话-003</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;女魃是神话中的旱神，亦作“女妭”，她穿青衣，居住在赤水之北。<br><br>&nbsp;&nbsp;女魃在黄帝攻打蚩尤时有着巨大作用，蚩尤起兵攻打黄帝，黄帝令应龙进攻冀州，蚩尤请来风伯雨师，以狂风骤雨对付应龙部队，于是，黄帝令女魃助战，她阻止了大雨，最终助黄帝赢得战争。<br><br>&nbsp;&nbsp;--来自搜狗百科',//女魃
	'sgsh_luohou':'<font color=cyan>上古神话-004</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;罗睺是印度神话中的阿修罗之一，是达耶提耶王毗婆罗吉提（Vipracitti）与辛悉迦（Simhika，达刹之女）的儿子。罗睺经常吞食日月，造成日蚀和月蚀，当日月在他敞开的喉头走出，蚀便完结。罗睺又被称为“行星、流星之王”，西南方的守护神；他长有四只手，下半身为蛇尾，好为非作歹。<br><br>&nbsp;&nbsp;--来自搜狗百科',//罗睺
	'sgsh_dongwanggong':'<font color=cyan>上古神话-005</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;东王公（别称扶桑大帝、青童君等），中国神话中的仙人，与西王母相对应，统率所有男仙。东王公为道教尊神，战国时期，楚地信仰的“东皇太一”神，为东王公之前身；《真灵位业图》将其排在上清左位，号曰“太微东霞扶桑丹林大帝上道君”。<br><br>&nbsp;&nbsp;郭沫若在《卜辞中的古代社会》一文中就说：“神话传说中人物，一人化为二人以上，一事化为二事以上，乃古今中外常有之事。”<br><br>&nbsp;&nbsp;--来自搜狗百科',//东王公
	'sgsh_yinglong':'<font color=cyan>上古神话-006</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;应龙，名叫庚辰，是古代中国神话传说中的创世神、造物神，作为一种有翼的龙出现于神话，同时也是真龙与龙族始祖，亦作黄龙、飞龙。传说鱼虾喝一口应龙的尿就能成为真龙。<br><br>&nbsp;&nbsp;先秦记载中，只存在一条应龙，名为庚辰，本居于天上世界，开辟了大地，生下了凤凰、麒麟。是助黄帝争帝而捕猎夔牛，独战虎、豹、熊、罴四兽，于南极杀蚩尤、斩夸父，最后与黄帝飞升；助大禹治水而再度下凡，以龙尾画地成江，开龙门、擒无支祁、捉拿相柳的无双战神，训练了中国第一支骑兵，撰写了十二生肖名表。直到商代都仍有帝王祭祀应龙。<br><br>&nbsp;&nbsp;传说应龙不死，是一尊曾于混沌划分阴阳、孵化创世神盘古的巨神，她的泪水形成了阴间黄泉，还有传说她化身成了天上的星座。<br><br>&nbsp;&nbsp;同时，应龙庚辰也是于五方主中央、五行司土的，云雨雷霆之神、沟渎河川之神、天龙之神，号曰顺天佑畿辅时应龙神的太一之妃，是活跃在先秦神话中的神明。<br><br>&nbsp;&nbsp;后世星经中，应龙更成为了司四季、司中岳、司中土、司黄河、长江、汉水、淮河、济水、司黄帝之子孙、司倮虫三百六十的天神。<br><br>&nbsp;&nbsp;--来自搜狗百科',//应龙
	'sgsh_xingtian':'<font color=cyan>上古神话-007</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;刑天是中国古代神话传说人物之一，是炎帝手下一员大将，与黄帝大战时，被砍掉脑袋，因此称为“刑天”，意为“形体夭残”。其记载于《山海经·海外西经》中，真实性学界一直有所争议，原本可能是华夏族无名神祇。<br><br>&nbsp;&nbsp;据甲骨文和金文记载，刑天为一人形符号，为氏族部落的象征图腾。在《山海经》的原本记载，称作“形天”，而“刑天”之得名，为陶渊明所改，其诗中“刑天舞干戚”一词，可能因传抄错误而有“刑天舞干戚”与“形夭无千岁”二说。<br><br>&nbsp;&nbsp;--来自搜狗百科',//刑天
	'sgsh_xiwangmu':'<font color=cyan>上古神话-008</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;道教创立以后，西王母被纳入神系，成为道教至高无上的女神。民间俗称“王母娘娘”。“西王母”的称谓，始见于《山海经》，因所居昆仑丘于汉中原为西，故称西王母。<br><br>&nbsp;&nbsp;--来自搜狗百科',//西王母
	'sgsh_yuqiang':'<font color=cyan>上古神话-009</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;禺强（yú qiáng）是传说中的风神、冬神，字玄冥。可以传播瘟疫，人面鸟身，用两条青蛇穿在耳朵上做装饰，踩着两条红色的蛇。<br><br>&nbsp;&nbsp;冬至之时，《史记》上记载，汉朝时要有七十个童男童女一起唱《玄冥》之歌，以此来祭祀冬神禺强。<br><br>&nbsp;&nbsp;--来自搜狗百科',//禺强
	'sgsh_dayu':'<font color=cyan>上古神话-010</font><br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：网图<br>♦︎配音：暂无<br>&nbsp;&nbsp;大禹，姓姒，名文命，字（高）密，是黄帝的玄孙、颛顼的孙子（另一说为颛顼六世孙），其父名鲧，其母为有莘氏之女脩己，为夏后氏首领、夏朝开国君王，因治理滔天洪水而广受世人传颂。<br><br>&nbsp;&nbsp;相传，禹治理黄河有功[1]，受舜禅让而继承帝位，以阳城为都城（另有说都城是平阳或安邑或晋阳），国号夏，并分封丹朱于唐，分封商均于虞，又划定中国版图为九州。禹死后安葬于会稽山上（今浙江绍兴），现仍存禹庙、禹陵、禹祠。<br><br>&nbsp;&nbsp;--来自搜狗百科',//大禹
		
	//---------------------------------//名将改写
	'ybsl_zhouyuxiaoqiao':'详见本体龙凤。',//周瑜小乔
	//---------------------------------//忆包武将
		
	/*快捷复制：
	<span class=yellowtext>文字</span>暗亮双色
	<span class=thundertext>文字</span>
	<span class=thundertext></span>
	<font color=cyan>文字</font>自带单色
	<span style=\'color:#00c4ff\'>文字</span>自写颜色
	<br/>换行
	<li>点
	<span style="opacity:0.5;"></span>字体变淡
	<span style="font-family: yuanli">东吴命运线</span>
	<span style="text-decoration: line-through;">杀</span>字体划掉
	黑桃♠︎️ 红桃♥︎️ 梅花♣︎️ 方块♦︎ 虚无◈ 日○ 月☽ 星☆ 山△ 禁※
	空桃♤ 空心♡ 空梅♧ 空钻♢ 空无◎
	花❀ 毒❈ 衡❃ 雪❁ 血ღ 实日☀ 漆星★ 暗花✿ 细雪❅❉ 天牢§ 
	骰子 一⚀ 二⚁ 三⚂ 四⚃ 五⚄ 六⚅
	男♂ 女♀
	白羊♈ 金牛♉ 双子♊ 巨蟹♋ 双鱼♓ 狮子♌ 天秤♎ 射手♐ 摩羯♑ 室女♏ 水瓶♒ 天蝎♍
	八卦乾☰ 坤☷ 震☳ 巽☴ 坎☵ 离☲ 艮☶ 兑☱
	☣
	//花	<br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：暂无<br>❀配音：暂无
	//毒	<br>❈技能设计：夜白<br>❈代码撰写者：夜白<br>❈插图：暂无<br>❈配音：暂无
	//衡	<br>❃技能设计：夜白<br>❃代码撰写者：夜白<br>❃插图：暂无<br>❃配音：暂无
	//雪	<br>❁技能设计：夜白<br>❁代码撰写者：夜白<br>❁插图：暂无<br>❁配音：暂无
	//星	<br>☆技能设计：夜白<br>☆代码撰写者：夜白<br>☆插图：暂无<br>☆配音：暂无
	//漆星  <br>★技能设计：夜白<br>★代码撰写者：夜白<br>★插图：暂无<br>★配音：暂无
	//暗花  <br>✿技能设计：夜白<br>✿代码撰写者：夜白<br>✿插图：暂无<br>✿配音：暂无
	//黑桃  <br>♠︎️技能设计：夜白<br>♠︎️代码撰写者：夜白<br>♠︎️插图：暂无<br>♠︎️配音：暂无
	//红桃  <br>♥︎️技能设计：夜白<br>♥︎️代码撰写者：夜白<br>♥︎️插图：暂无<br>♥︎️配音：暂无
	//梅花  <br>♣︎️技能设计：夜白<br>♣︎️代码撰写者：夜白<br>♣︎️插图：暂无<br>♣︎️配音：暂无
	//方块  <br>♦︎技能设计：夜白<br>♦︎代码撰写者：夜白<br>♦︎插图：暂无<br>♦︎配音：暂无
	//虚无  <br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无
	//空无  <br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无
	//细雪  <br>❅技能设计：夜白<br>❅代码撰写者：夜白<br>❅插图：暂无<br>❅配音：暂无
	*/
	// c:\Users\ADMINI~1\AppData\Local\Temp\SGPicFaceTpBq\8752\0091320B.png \␀ 好玩滴
	'ybsl_001sunlisong':'<font color=cyan>忆-001·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>孙丽松，原型为同名本人，陈爱琳和王汉桢的闺蜜，六中三班的一员。不算太熟，但隐约记得关系还不错，言行举止令人如沐春风。</span>',
	'ybsl_002chenailin':'<font color=cyan>忆-002·凄愁哀婉</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>留点什么吧，聊做分别之后的怀念。<br/><span class=thundertext>陈爱琳，原型为同名本人，六中三班的一员，作者（以下称我）对那段时光最美好的回忆。以下文段为忆陈爱琳文。文本几经修改，终成定稿。对话原话不太记得了，因此用意义相同或相近的文言说法。</span><br><span class=firetext>注：文段受岁月滤镜影响，存在某处虚写。事实无论，吾言即是。</span><br><span class=yellowtext>久别不见，故作文怀之。<br>陈氏女，名爱琳，不知生年，癸巳年入初中，与之遇。孙氏女，名丽松，王氏女，名汉桢，皆为陈友。吾与之事实繁，然皆不记忆，依稀几数，至今铭心。<br>一日，学政治，谈男女往来，毕，吾谓陈曰：“男女具，身心益。”，<span style="opacity:0.1;">（男生女生在一起，有益健康）这是我记得的为数不多的原话。请允许我把这句话藏起来，毕竟现在想想太羞耻了，抓紧忘了吧我天。</span><br>三女具嗤，道：“淫嬷嬷”，乃去。<br>初识，吾与陈并列第三，师谓曰：“汝二人，定分高下。”及试，座临。考历史，陈密索一字。吾以此挟，索屈原事迹，附：吾二人，定分高下。出榜，陈三吾七，陈笑，顾二女曰：“才道，定分高下。”余赤面而去。<br>一日，学语文，讲柳宗元之小石潭记，校音，及“壹”，吾和曰：仅旧版钱有之。满堂皆笑。师曰：“汝视之。”余惑，遂取钱视之，乃悟，遂羞而掩面。</span><span class=firetext>注：岁月的滤镜下，吾总觉陈之笑最甚。事实无论，吾言即是。</span><br><span class=yellowtext>彼时，偶见之以美工刀划臂。便私书之：“书曰：珍己，勿伤。”陈惶，书，顾左右而传之。启之，曰：“无宣，令师知也。”余内笑，回曰：“莫如此也。”对曰：“善。”此事揭过。<br>一日，与人冲突，因果皆不记忆。其人名姜玉恒。冲吾，使吾跌。余奋极，恰右有棍，遂操棍挺身抡之，中头，棍折，余怒尚在，幸观者分之，而姜步罗圈，道：没事。待定，回味此棍，复操之以试击，仿佛为要害也，及顾而问陈：“如此，是耶？”陈惊，颔而应之。吾才省，知此事惧之也。师知，谓皆有过，遂不提。<br>一日，学英语，点我名。有灯垂于梁。余起欲答，忽身失衡，刹那而仰，见灯如柳摇曳，方知地动。当是时，警铃鸣，楼摇轰，脚踏声，一时齐发，不可辩也。余乃惊，携冠欲潜桌下，师曰：“不坚！”遂随流而下。及远，乃检冠中钱，未损。乃假七日。<br>稍定，一日语文课，有联曰：殷殷舔犊情。无人能对。余上而书：情情抚挚颊。盖断错句、解错意也。乃顾陈，以示炫耀。师不可解，曰：“上联言亲情，下联言爱情，稍欠。”余亦觉欠，然无益者。<br>某晚，尚余一刻钟。余沉思，师曰：“复地动乎？”余闻轰，以为移案。师曰：“莫不是窗动？不详。”言讫，始觉轰声愈响，坐不稳，忽闻铃震，皆慌而走。始静，复检冠中钱。顾陈，亦无恙。乃假一月。<br>某日，吾二人独处于室，随心而谈，曰：“汝敛袖，吾欲检之。”乃奋袖出臂。余观之，无痕。其肤白而美，余难耐而抚之，遂怦然心动。陈忽道：“你多久没剪指甲？”吾曰：“四月。”陈默。良久，乃曰：“今周五，周六周日你洗澡剪指甲，周一我检查。则赐一车饼干。”乃信之。然懒惰成性，终未成，此为后话。当晚归家，母曰：“汝父欲使汝北还续学，何如？”余道：“安乐与此，何故北还？”母曰：“汝藉在北。若留需迁藉易姓。”余决然道：“大丈夫，岂能易姓？吾当北还。”乃定甲午秋北还续学。复无相见，甚念之矣。<br>丁酉，业毕。余南下归故校，觅旧师，叹往昔。问及诸友，则曰：“王汉桢入三中，孙丽松入实验……”独不见陈爱琳。问之，则叹曰：“汝去，即堕。吾见其与众男厮，恐其安危，遂告教导主任，岂料教导主任因其男女关系不当，记其大过。爱琳恨我。顷之辍学，不复见也。”<br>余闻之，甚悲。实意料之外，又情理之中。倘吾异姓而拒北，迁藉而居南，定有挽澜之机。虽吾今有知，然知者何如？不知者何如？知深而乐衰，视广而情短，悲哉！<br>念君，恬静，不知。<br>殷殷舔犊情，浅浅执手意。<br>安否？佳祺。</span><br><span class=thundertext>谨以此文，祭年少无知。<br>我不会主动去寻觅失散的人，也不会去追问她们后来怎样。她们在我印象中留下的美丽的足迹，对我而言已经是宝贵的财富。这份回忆足以温暖我一生。</span>',
	'ybsl_003yanshuang':'<font color=cyan>忆-003·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>闫爽，原型为同名本人，民主小学小饭桌的学妹。那天白天我们买了大量零食，但都存放在小饭桌的冰柜上。当天晚上，我们一行人因为床位不够而临时混入一屋。闲来无聊，便派出一人前去偷偷地拿来零食（遗憾的是，那天晚上的人除了闫爽，其他人都不记得名字了），我们一同享用着。他们吃完就休息了。<br>而我却有些悲催，居然不知吃错啥了，居然吐了起来。为了掩人耳目，我吐在了两床空隙靠墙的地方，遗迹三天后开始有味，又过了好久才被发现。</span>',
	'ybsl_004zhangyujie':'<font color=cyan>忆-004·似水流年</font><br>❁技能设计：夜白<br>❁代码撰写者：夜白<br>❁插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❁配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>张玉洁，原型为同名本人，童年时期吴爽的跟班，和吴爽一同织造了个幻想的世界哄我玩。后来不知去向。</span>',
	'ybsl_005wangruobing':'<font color=cyan>忆-005·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>王若冰，原型为同名本人，民主小学时期的舍友，兼六中一班的一员。事迹不详，但隐约记得关系还不错。</span>',
	'ybsl_006wanghanzhen':'<font color=cyan>忆-006·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>王汉桢，原型为同名本人，六中三班一员，经选举任职班长。陈爱琳和孙丽松的闺蜜。成绩也是名副其实的第一。不算太熟，但隐约记得关系还不错。</span>',
	'ybsl_007wugege':'<font color=cyan>忆-007·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>吴格格，原型为同名本人，民主小学时期的同班同学，同时也是六中三班的同学。事迹不详，但隐约记得关系还不错。任职为语文课代表。曾在一次收作业时以老同学的名义宽限了我几分钟。</span>',
	'ybsl_008wuyuxin':'<font color=cyan>忆-008·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>吴雨欣，原型为同名本人，民主小学时期同学。常穿桃粉色衣服。关系不错，与高宇航，李玉珊一起被我称为高无理（后来加入了周玥，变成了毫无厘头的高无理周）。几人常与我玩耍（其实就是几个人轮班拉扯我。不知为何很快乐，现在想想也很快乐。）。升入初中后分别，不知去向。</span>',
	'ybsl_009liyushan':'<font color=cyan>忆-009·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>李玉珊，原型为同名本人，民主小学时期同学。常衣服的颜色现已忘记。关系不错，与高宇航，吴雨欣一起被我称为高无理（后来加入了周玥，变成了毫无厘头的高无理周）。几人常与我玩耍（其实就是几个人轮班拉扯我。不知为何很快乐，现在想想也很快乐。）。升入初中后分别，不知去向。</span>',
	'ybsl_010zhouyue':'<font color=cyan>忆-010·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>周玥，原型为同名本人，民主小学时期同学，常穿蓝色衣服。因为我看见“玥”就莫名想起“钥”字，故而被我取外号为“钥匙”。后来加入了高无理，一同与我玩耍（其实就是几个人轮班拉扯我。不知为何很快乐，现在想想也很快乐。）。升入初中后分别，不知去向。</span>',
	'ybsl_011gaoyuhang':'<font color=cyan>忆-011·似水流年</font><br>❈技能设计：夜白<br>❈代码撰写者：夜白<br>❈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❈配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>高宇航，原型为同名本人，民主小学时期同学，兼六中三班一员。常穿青苹果色衣服。关系不错，与吴雨欣，李玉珊一起被我称为高无理（后来加入了周玥，变成了毫无厘头的高无理周）。几人常与我玩耍（其实就是几个人轮班拉扯我。不知为何很快乐，现在想想也很快乐。）。升入初中后曾离间我和小张鑫，后来关系渐淡。</span><br><span class=yellowtext>（所以，时刻见到老同学相比于彻底成为回忆而言，真的是好事吗？）</span>',
	'ybsl_012zhengjiayi':'<font color=cyan>忆-012·似水流年</font><br>❈技能设计：夜白<br>❈代码撰写者：夜白<br>❈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❈配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>郑佳怡，原型为同名本人，民主小学时期同桌，兼六中一班的一员。曾在小学时期的一次考试中欲要作弊，被我阻止。关系不错，但升入初中后关系渐淡。</span>',
	'ybsl_013yinji':'<font color=cyan>忆-013·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>尹姬，原型为尹超跃，六中三班一员，体操领操员。曾与我一同领操表演节目。曾一次失手用书夹划伤我手臂，伤疤至今依旧留在我手臂。其余事迹不详。</span>',
	'ybsl_014liutianyu':'<font color=cyan>忆-014·似水流年</font><br>✿技能设计：夜白<br>✿代码撰写者：夜白<br>✿插图：暂无<br>✿配音：暂无<br/>故事仍在继续书写。<br/><span class=thundertext>夜白，原型为作者本人，2019年春自号北地诗仙，2020年春夏自取别名夜白。故事仍在继续书写，也许永无尽头。</span>',
	'ybsl_014ether':'<font color=cyan>忆-014·缘尽梦碎</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>安以，我2022年10月17日之18日的梦境中扮演的角色。<br>以下是我当天晚上写的手记。<br>幻之大地分两层，上层为梦境，下层为现实，梦境的世界映照现实的人的内心，即便他已经死去。而在梦境世界死去的人会被捕捉进魔王的狭间世界。这是勇者斗恶龙6的设定。<br>我梦见我生活在幻之大地上层，在一个魔法学院上学，舍友会制符。我用他赠的一张符杀了一个仇家。</span><span class=yellowtext>我在这个梦里名叫安以。</span><span class=thundertext><br>下一个场景，我梦见我从大地上的窟窿掉了下去，到了下一层大陆依旧在下坠，这时神龙出现，他托起了我，说我是命中注定的人，于是把我载了回去，我问去了下面会怎么样，他没说话，示意我看，我看见一大片虚空，样子甚是恐怖。他又问我有什么愿望，我表示有两个红颜知己，如今在上层大陆死了，可能在冥界，委托他帮我找回来。神龙答应了。<br>然后下一个场景，我在一个私人豪宅，看见外面有个电话亭，突然电话响了，并且他们两个一脸飒爽的从电话亭里走出。我很开心，但我没有说出是我让他们复活的事情。她们说假如知道谁让她们活了过来，一定要以身相许。我正要说些什么，突然感觉意识有着清晰，我一愣，正要再看一眼她们，我醒了。<br>听说当一个好久不见的人突然出现在你的梦里，说明这个人正在遗忘你。仔细想想，她们不过是两个与我有过一点交集的人。其中一个表现暧昧，另外一个敬而远之。如今的梦正说明，我渴望被她们关注。我很享受被暗恋的感觉，可一旦挑明了，就难以品味了。<br>像她们这样的姑娘，我也遇过许多。但我并没有明确表示过什么。因为我很清楚，我只适合作为她们的白月光。我也很乐得享受这种感觉。她们也乐得享受。主要是，我认为，白月光给人一种极为特殊的意义，他是你内心深处的一根精神支柱，他的意义无可言喻，但是在你遇到问题时，一定会下意识想要是有他在多好，可惜并不能。或者睡梦中，甚至失恋时，也会作为意淫的对象，幻想他躺在你身边。在你孤独时，他会幻现在你脑海里，或者幻现在你身边。你以为你会拥抱着他入睡，可睁开眼，却是你抱着自己的大腿。至于梦中的人啊，你要怎么才能出现，从我的梦境里，脑海里出现在我身边，想我想的那样，陪伴我，拥抱我，关怀我。我多么希望幻之大地的设定在这里可以实现。<br>在游戏里，梦之世界主角初始村的山下有一个集市叫玛尔谢，但是在对应的真实世界，这里只有一个孤独的木屋，和一个孤独的老人。老人的愿望是将来这里能发展成一个大集市。我想，这个梦应该把我的内心所想都具现了。<br>凌晨一点了。睡了。</span>',
	'ybsl_015wanghairu':'<font color=cyan>忆-015·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>同是天涯沦落人，相逢何必曾相识。<br/><span class=thundertext>王海茹，原型为同名本人，转学后三中的同学，后任职为班长。为人德高望重，所有人都很尊敬她。一部分人尊称其为大姑，原因不详。成绩优异。曾在某次跳远时伤到腰部，其后由郭慧欣背其行动。几乎所有人皆因此而热情帮助她。曾劝解单相思的我，使我迷途得返。至今偶有微信联系。</span>',
	'ybsl_016manchengqi':'<font color=cyan>忆-016·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>若思悔不及，则万念俱成枯。趁你还年轻，他还未老。<br/><span class=thundertext>满城柒，原型保密，转学后三中的同学。曾为我单相思的对象。后来时常打扰她。高中毕业后我彻底醒悟。善于唱歌，常听我诉说。喜欢夸赞别人。</span><br><span class=yellowtext>她只是个倾听者，动歪心思的是我。</span><br><font color=cyan><span style="opacity:0.1;">\u4e5f\u8bb8\u5979\u4e5f\u786e\u5b9e\u8ba4\u771f\u5730\u559c\u6b22\u8fc7\u6211\uff0c\u6bd5\u7adf\u5f53\u65f6\u6211\u8868\u73b0\u51fa\u5bf9\u4e09\u56fd\u6740\u7684\u5174\u8da3\uff0c\u5979\u5c31\u5047\u88c5\u4e5f\u559c\u6b22\u4e09\u56fd\u6740\uff0c\u521b\u9020\u4e0e\u6211\u7684\u5171\u540c\u8bdd\u9898\u3002\u5979\u53ea\u662f\u4e34\u573a\u6076\u8865\u4e00\u756a\u4e09\u56fd\u6740\u77e5\u8bc6\u800c\u5df2\uff0c\u56de\u60f3\u8d77\u90a3\u6bb5\u7ecf\u5386\uff0c\u6211\u53ef\u4ee5\u4e07\u5206\u80af\u5b9a\u3002\u90a3\u4e9b\u5f80\u4e8b\uff0c\u90a3\u4e9b\u7ec6\u8282\uff0c\u90fd\u662f\u90a3\u4e48\u7684\u6295\u6211\u6240\u597d\u3002\u5979\u5728\u90a3\u5e74\u590f\u5929\u4e3a\u6211\u5531\u7684\u6b4c\uff0c\u4ee4\u6211\u6f78\u7136\u6cea\u4e0b\u3002\u4e5f\u8bb8\u662f\u6211\u5e74\u5c11\uff0c\u4e0d\u61c2\u5f97\u8fdb\u9000\u5206\u5bf8\u5427\u3002</span></font><br><span class=yellowtext><br>妙园风雪途·作于2018、12、06<br>妙园风雪会今年，今年风雪会妙园。<br>妙园狭路逢故友，故友踌躇未敢言。<br>日光斜照方寸暖，驻足良久方开口。<br>问我伊人在何方，天自苍寥地自荒。<br>初时故人不自解，解时故人已去远。<br>朔风凛冽寒蝉翼，霜日摇曳嘲晚叶。<br>蝴蝶翩翩绕枝头，蜂虫依依戏牵牛。<br>葵花有意向金乌，松叶不愿轻易哭。<br>伊人有酒未曾吐，诗人佯醉却倾心。<br>染纸相思表赤血，清袖无丝碎真心。<br>诗人歌罢回看酒，酒陈杯新人已累。<br>推杯起身心方醒，人生何处无滋味。<br>醒时已是暮春时，回首才觉伊人醉。<br>诗人已书新赋草，伊人还读旧辞酹。<br>诗人佯醉已走脱，伊人持酒仍痴醉。<br>一曲歌罢梦回醒，诗人伊人皆有泪。<br>此间穿肠千种愧，诗人有愧方觉恨。<br>泪悔前头应有源，犹见孟德与公台。<br>妙园风雪别今年，今年风雪别妙园。<br>妙园宽径独徘徊，故人相见未敢认。</span>',
	'ybsl_017xiaohong':'<font color=cyan>忆-017·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：涂山小红本尊<br/>在她的梦里，化作泡影的人重现。<br/><span class=thundertext>涂山小红，原型保密，转学后三中的同学，为满城柒闺蜜。曾为单相思的我传递书信。为人天真活泼。<span style="text-decoration: line-through;">\u6027\u683c\u548c\u4f5c\u4e3a\u795e\u4f3c\u524d\u671f\u7684\u897f\u56ed\u5bfa\u4e16\u754c\u3002</span>至今关系依旧友好。</span>',
	
	'ybsl_018zhangqing':'<font color=cyan>忆-018·晓月照怀</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>她说她喜欢森林你的寂静与美好。<br/><span class=thundertext>张晴，原型为同名本人，转学后三中的同学。与我关系甚好，高中时常短信沟通。曾取得其QQ号和密码以玩王者，后来其注销了。关系还算不错。</span>',
	'ybsl_019shengyan':'<font color=cyan>忆-019·醋心少女</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>在她的梦里，化作泡影的人重现。<br/><span class=thundertext>盛妍，原型为同名本人，高中时期涂山小红的同学，常因我和涂山小红交谈甚欢而不高兴，我称其为吃醋。如今在为电商引流的路上越走越远。<span style="opacity:0.5;">挣钱嘛，不磕碜。</span></span>',
	'ybsl_020jiayutong':'<font color=cyan>忆-020·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>雨下整夜，我的爱溢出就像雨水，<br/>院子落叶，跟我的思念厚厚一叠，<br/>几句是非，也无法将我的热情冷却，<br/>你出现在我诗的每一页。<br/>——周杰伦《七里香》<br/><span class=thundertext>贾雨桐，原型为同名本人，高中时期同学，喜欢唱歌，<span style="text-decoration: line-through;">&#20307;&#32982;&#65292;</span>天真活泼，经常与我讨论数学题，房某的好朋友（房姓某人还未做出，打算和贾拼个双将）。</span>',
	'ybsl_021liuyufeng':'<font color=cyan>忆-021·似水流年</font><br>❃技能设计：夜白<br>❃代码撰写者：夜白<br>❃插图：暂无<br>❃配音：暂无<br/>还望先生教我~<br/><span class=thundertext>刘域枫，原型为同名本人，转学后三中的同学，一度为我同桌，三国杀同好，喜欢向我讨教数学问题。升入高中后偶有联系，如今渐无联系。</span>',
	'ybsl_022salt':'<font color=cyan>忆-022·暂无称号</font><br>❈技能设计：夜白<br>❈代码撰写者：夜白<br>❈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❈配音：暂无<br/>待填写。<br/><span class=thundertext><span style="opacity:0.3;">盐，原型为六中教导主任，<span style="text-decoration: line-through;">&#23545;&#38738;&#24180;&#30007;&#22899;&#30340;&#20146;&#23494;&#20851;&#31995;&#25104;&#35265;&#26497;&#22823;</span>。那年圣诞节中午，我饭后买了点糖在路上嚼。在校门口二十步的地方，突然想起，早上说过，今天禁止给对象送糖，否则取消本月文明班的评选。我想着省得带进去引起误会，就在原地奋力的吃。就在这时，天杀的教导主任从背后出现，看我拿着糖就火了，不管三七二十一就给我记了。我：？？？回到学校，我果然被通报了。我上去和老师解释了一番，老师也没骂我，<span style="text-decoration: line-through;">&#21453;&#20498;&#21644;&#25105;&#19968;&#21516;&#21457;&#36215;&#20102;&#29282;&#39578;</span>此事就此揭过。后来她还办了一件令人气愤的事，详见陈爱琳简介。</span></span>',
	// 'ybsl_025shiqingyu':'<font color=cyan>忆-023·心灵守望</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>史庆宇，高中同班同学，关系甚好。</span>',
	'ybsl_024yuetong':'<font color=cyan>忆-024·糖心少女</font><br>❁技能设计：夜白<br>❁代码撰写者：夜白<br>❁插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❁配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>岳瞳，高中朋友，小迷妹一枚。具体事迹不详。上次交流是她拉我进一个赚钱组织。</span>',
	'ybsl_025shiwang':'<font color=cyan>忆-025·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>王贺，高中朋友，史庆宇闺蜜。关系较好。</span>',
	'ybsl_025shiqingyu':'<font color=cyan>忆-025·心灵守望</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>分享的图片<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>史庆宇，高中同班同学，关系甚好。</span>',
	'ybsl_025wanghe':'<font color=cyan>忆-025·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>王贺，史庆宇闺蜜。</span>',
	'ybsl_026can':'<font color=cyan>忆-026·巡梦回音</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>你在我的梦里藏匿，笑靥如花。<br/><span class=thundertext>蚕，记2022年6月29日之30日的一场梦。<br>正常人走路直立正着走，梦中的我不一样，后空翻走。并且翻着翻着就飞了。越过一片森林，落在一个三层楼高的草垛上，没刹住车又飞了出去，轨迹未知，落点是一条陌生的街道。回过头接着翻着走，不小心踢到一个丫头脸上。我对其表示歉意，她表示没事，并莞尔一笑。随后她邀我前往她家，是一家面馆。随后不知为何醒了。为了纪念这一场梦，我为其取名为“蚕”，并撰写此武将。</span>',
	'ybsl_027rain':'<font color=cyan>忆-027·巡梦鸣觉</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>你在我的梦里藏匿，一尘不染。<br/><span class=thundertext>雨，记2022年7月17日之18日的一场梦。<br>这次载入的梦境是一个仿若童年的村落，我遇见了另一个我，但另一个我是女的。我们一起玩耍，其余不记得了。为了纪念这一场梦，我为其取名为“雨”，并撰写此武将。</span>',
	'ybsl_028crystal':'<font color=cyan>忆-028·巡梦回响</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>你在我的梦里骄傲，殒身化晶。<br/><span class=thundertext>晶，记2022年7月19日之20日的一场梦。<br>这次载入的梦境是一个动物部落，一个象族。族长为了保护族群，变为人形并大施法力，最终成功。但是最后副作用发动，他整个身躯化为水晶。为了纪念这一场梦，我为其取名为“晶”，并撰写此武将。</span>',
	'ybsl_029dawn':'<font color=cyan>忆-029·巡梦长息</font<br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无><br/>你在我的梦里藏匿，扑朔迷离。<br/><span class=thundertext>黎，记2022年7月27日之28日的一场梦。<br>这次载入的梦境具体不详，<span style="text-decoration: line-through;">&#21482&#35760&#24471&#36825&#20011&#22836&#34987&#25105&#22264&#20102</span>只记得仿佛是一场春梦。为了纪念这一场梦，我为其取名为“黎”，并撰写此武将。</span>',
	'ybsl_030book':'<font color=cyan>忆-030·巡梦道演</font><br>★技能设计：夜白<br>★代码撰写者：夜白<br>★插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>★配音：暂无<br/>没有简介可以不写。<br/><span class=thundertext>书，严格来说，她并非我梦到的角色。只是一时心血来潮，就设计了个角色。</span>',
	'ybsl_018huanqing':'<font color=cyan>忆-018·巡梦魅影</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>◈配音：暂无<br/>你在我的梦里藏匿，柔情媚骨。<br/><span class=thundertext>幻晴，记2022年8月11日之12日的一场梦。<br>样貌取自张晴，但性情多了几分妩媚。具体事迹不详。依稀记得也是一场春梦。为了纪念这一场梦，我为其取名为“幻晴”，并撰写此武将。</span>',
	'ybsl_032baiyichen':'<font color=cyan>忆-032·旅者</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>我们……继续携手同行吧。<br/><span class=thundertext>白衣尘，原型为某个萌妹学姐，姓名不详。比我早一年从高中毕业。上学期间常在屯子车上遇见。自2019年夏，其毕业后再未见面。2022年8月13日，我为了返校去街里，偶然见到，但匆匆错过，相貌和以前没啥变化。</span>',
	'ybsl_033xiaohui':'<font color=cyan>忆-033·断肠人在天涯</font><br>❅技能设计：夜白<br>❅代码撰写者：夜白<br>❅插图：QQ小世界AI绘图<br>❅配音：暂无<br/>你猜我在什么时候放弃了爱。<br/><span class=thundertext>小慧，原型为郭慧欣，转学后三中的同学，一度做过我同桌。曾为情所伤，及其敬仰王海茹。高中后联系渐淡。不知某天悄然删双好友。2022年9月21日凌晨，后知后觉的我意识到这一点，便撰写此武将。</span>',
	'ybsl_034zhoulianyuan':'<font color=cyan>忆-034·庄子的执剑人</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>梦中的人记不得模样，梦中的事记忆犹新。<br/><span class=thundertext>周怜渊，记2022年9月15日之16日的一场梦。<br>这次载入的梦境大致是一个作文考试，我叙写了一篇文章，讲述了一个言辞锋利的监察者，具体事迹不详，只记得名字叫周怜渊。为了纪念这一场梦，并撰写此武将。</span>',
	'ybsl_035stamp':'<font color=cyan>忆-035·龙裔象征</font><br>★技能设计：夜白<br>★代码撰写者：夜白<br>★插图：暂无<br>★配音：暂无<br/>见威而不伏，问诏而不朝，灭之。<br/><span class=thundertext>玺，严格来说，她并非我梦到的角色。一次心血来潮，网上搜了一下玉玺。对于玉玺流失在历史长河中深感惋惜，于是做此武将。</span>',
	'ybsl_036bright':'<font color=cyan>忆-036·魔王的跑酷</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>你在我的梦里逃逸，咫尺天涯。<br/><span class=thundertext>熙，记2022年9月29日之30日的一场梦。<br>这次载入的梦境是，我是一个不断奔跑的人，在杂糅了各种见过的没见过的地形中不断地跑。跑着跑着还飞了起来。最终怅然醒来。为了纪念这一场梦，我为其取名为“熙”，并撰写此武将。</span>',
	'ybsl_037diamondqueen':'<font color=cyan>忆-037·深海的通灵龟</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>成品图片<br>◈配音：暂无<br/>一名女子莫名失踪，她留下的线索只有一句，方首女王，在海中渡劫。<br/>她消失整一年后，某城市上空降落巨大球形闪电。<br/><span class=thundertext>方块Q，记2022年9月29日之30日的一场梦。<br></span>',
	'db_ybsl_038tengwu':'<font color=cyan>忆-038·缘尽梦碎</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>成品图片<br>◈配音：暂无<br/>黄泉路上的两名少女被复活后，会以身相许，还是许诺来世做牛马？<br/><span class=thundertext>滕叔颖＆武宁，原型为高中两个同学，姓名不详，同时在我2022年10月17日之18日的梦境登场。<br>以下是我当天晚上写的手记。<br>幻之大地分两层，上层为梦境，下层为现实，梦境的世界映照现实的人的内心，即便他已经死去。而在梦境世界死去的人会被捕捉进魔王的狭间世界。这是勇者斗恶龙6的设定。<br>我梦见我生活在幻之大地上层，在一个魔法学院上学，舍友会制符。我用他赠的一张符杀了一个仇家。<br>下一个场景，我梦见我从大地上的窟窿掉了下去，到了下一层大陆依旧在下坠，这时神龙出现，他托起了我，说我是命中注定的人，于是把我载了回去，我问去了下面会怎么样，他没说话，示意我看，我看见一大片虚空，样子甚是恐怖。他又问我有什么愿望，我表示有两个红颜知己，如今在上层大陆死了，可能在冥界，委托他帮我找回来。神龙答应了。</span><span class=yellowtext>这个两个红颜知己被我命名为滕叔颖和武宁。</span><span class=thundertext><br>然后下一个场景，我在一个私人豪宅，看见外面有个电话亭，突然电话响了，并且他们两个一脸飒爽的从电话亭里走出。我很开心，但我没有说出是我让他们复活的事情。她们说假如知道谁让她们活了过来，一定要以身相许。我正要说些什么，突然感觉意识有着清晰，我一愣，正要再看一眼她们，我醒了。<br>听说当一个好久不见的人突然出现在你的梦里，说明这个人正在遗忘你。仔细想想，她们不过是两个与我有过一点交集的人。其中一个表现暧昧，另外一个敬而远之。如今的梦正说明，我渴望被她们关注。我很享受被暗恋的感觉，可一旦挑明了，就难以品味了。<br>像她们这样的姑娘，我也遇过许多。但我并没有明确表示过什么。因为我很清楚，我只适合作为她们的白月光。我也很乐得享受这种感觉。她们也乐得享受。主要是，我认为，白月光给人一种极为特殊的意义，他是你内心深处的一根精神支柱，他的意义无可言喻，但是在你遇到问题时，一定会下意识想要是有他在多好，可惜并不能。或者睡梦中，甚至失恋时，也会作为意淫的对象，幻想他躺在你身边。在你孤独时，他会幻现在你脑海里，或者幻现在你身边。你以为你会拥抱着他入睡，可睁开眼，却是你抱着自己的大腿。至于梦中的人啊，你要怎么才能出现，从我的梦境里，脑海里出现在我身边，想我想的那样，陪伴我，拥抱我，关怀我。我多么希望幻之大地的设定在这里可以实现。<br>在游戏里，梦之世界主角初始村的山下有一个集市叫玛尔谢，但是在对应的真实世界，这里只有一个孤独的木屋，和一个孤独的老人。老人的愿望是将来这里能发展成一个大集市。我想，这个梦应该把我的内心所想都具现了。<br>凌晨一点了。睡了。</span>',
	'ybsl_038bianqiuwen':'<font color=cyan>忆-038·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：灵境AI绘图<br>❀配音：暂无<br/>待填写。<br/><span class=thundertext>卞秋雯，原型保密，事迹暂无。</span>',
	'ybsl_039zhafu':'<font color=cyan>忆-039·制符新生</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>查符，在我2022年10月17日之18日的梦境登场。<br>以下是我当天晚上写的手记。<br>幻之大地分两层，上层为梦境，下层为现实，梦境的世界映照现实的人的内心，即便他已经死去。而在梦境世界死去的人会被捕捉进魔王的狭间世界。这是勇者斗恶龙6的设定。<br>我梦见我生活在幻之大地上层，在一个魔法学院上学，舍友会制符。我用他赠的一张符杀了一个仇家。</span><span class=yellowtext>这个舍友被我命名为查符。</span><span class=thundertext><br>下一个场景，我梦见我从大地上的窟窿掉了下去，到了下一层大陆依旧在下坠，这时神龙出现，他托起了我，说我是命中注定的人，于是把我载了回去，我问去了下面会怎么样，他没说话，示意我看，我看见一大片虚空，样子甚是恐怖。他又问我有什么愿望，我表示有两个红颜知己，如今在上层大陆死了，可能在冥界，委托他帮我找回来。神龙答应了。<br>然后下一个场景，我在一个私人豪宅，看见外面有个电话亭，突然电话响了，并且他们两个一脸飒爽的从电话亭里走出。我很开心，但我没有说出是我让他们复活的事情。她们说假如知道谁让她们活了过来，一定要以身相许。我正要说些什么，突然感觉意识有着清晰，我一愣，正要再看一眼她们，我醒了。<br>听说当一个好久不见的人突然出现在你的梦里，说明这个人正在遗忘你。仔细想想，她们不过是两个与我有过一点交集的人。其中一个表现暧昧，另外一个敬而远之。如今的梦正说明，我渴望被她们关注。我很享受被暗恋的感觉，可一旦挑明了，就难以品味了。<br>像她们这样的姑娘，我也遇过许多。但我并没有明确表示过什么。因为我很清楚，我只适合作为她们的白月光。我也很乐得享受这种感觉。她们也乐得享受。主要是，我认为，白月光给人一种极为特殊的意义，他是你内心深处的一根精神支柱，他的意义无可言喻，但是在你遇到问题时，一定会下意识想要是有他在多好，可惜并不能。或者睡梦中，甚至失恋时，也会作为意淫的对象，幻想他躺在你身边。在你孤独时，他会幻现在你脑海里，或者幻现在你身边。你以为你会拥抱着他入睡，可睁开眼，却是你抱着自己的大腿。至于梦中的人啊，你要怎么才能出现，从我的梦境里，脑海里出现在我身边，想我想的那样，陪伴我，拥抱我，关怀我。我多么希望幻之大地的设定在这里可以实现。<br>在游戏里，梦之世界主角初始村的山下有一个集市叫玛尔谢，但是在对应的真实世界，这里只有一个孤独的木屋，和一个孤独的老人。老人的愿望是将来这里能发展成一个大集市。我想，这个梦应该把我的内心所想都具现了。<br>凌晨一点了。睡了。</span>',
	
	'ybsl_041mmuqin':'<font color=cyan>忆-041·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>首充一元就送！<br/><span class=thundertext>慕琴，原型为崔妍，高中同学。主要事迹为，某天在一楼大厅里席地而坐，我给她投喂了一块钱，并戏称买了。后来她把一块钱还了回来，但1块钱卖身这个梗我能记一辈子。</span>',
	'ybsl_042pingzi':'<font color=cyan>忆-042·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>拼图虽好，可一旦缺失，便不再完美。<br/><span class=thundertext>蘋姉，原型保密，高中同学。<br>她向来聪慧，生性活泼，招人怜爱。<br>有一次，我买了两个拼图，晚自习时，包括她在内的其他同学借我拼图去拼。拼完之后，因为拼图容易散花，于是用纸板承接着向我传递，小心翼翼传到我手里时，老师来了……毫不意外的，我上了通报板。估计我在老师心里也留下了一点顶风作案的形象。<br>大约一个月后的某一天，老师跟我们闲聊，逮住一个机会，就在大家面前对我指蘋说：她就比你聪明。我顿时心领神会。想必老师回头也仔细查了监控，知道了那个“顶风作案”的同学并非是我，然后趁此机会解开误会。我便用“飞不起来”的手势指着蘋华强一笑。明退技能便由此而来，意指她立于危墙之下，却又全身而退，反倒是我平白上了一次电视。</span>',
	'ybsl_043fangjiayu':'<font color=cyan>忆-043·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>房佳谕，原型为同名本人，初中和高中同学。</span>',
	'ybsl_044huruihang':'<font color=cyan>忆-044·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>胡瑞航，原型为同名本人，六中同学。印象中存在感极低。事迹不详。</span>',
	'ybsl_045gaocong':'<font color=cyan>忆-045·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>快步的来又快步的走，<br>假装不经意的路过，<br>却不知那一瞬间的顿足，<br>表露了最真诚的情愫。<br/><span class=thundertext>高聪，原型为同名本人，事迹暂无。</span>',
	'ybsl_046jiangxuewu':'<font color=cyan>忆-046·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>江雪舞，原型保密，事迹暂无。</span>',
	'ybsl_047shan':'<font color=cyan>忆-047·游魂惊梦</font><br>❅技能设计：夜白<br>❅代码撰写者：夜白<br>❅插图：灵境AI绘图<br>❅配音：暂无<br/>游荡在城市里的鬼魂，专门捕食痴情人的美梦<br><span class=yellowtext>人生若只如初见，何事秋风悲画扇。<br>等闲变却故人心，却道故人心易变。<br>骊山语罢清宵半，泪雨霖铃终不怨。<br>何如薄幸锦衣郎，比翼连枝当日愿。</span><br>————清代·纳兰性德<br>木兰花·拟古决绝词柬友<br/><span class=thundertext>彡，原型保密，事迹保密。同时登场于本人2023年4月14之15日梦。<br>这次载入的梦境，是在一个学校的宿舍里，有一个疯狂追人的异服者，头戴面罩，没有图案。我沿着二至三楼楼梯一路向东攀逃，但每次回头总能在看见他从上一个楼梯口上行。最后不知过了多少了楼梯口，我一跃跳下了楼梯，这里正是一个街区。<br>我再次遇见了彡。我们之间仿佛没有了那个罅隙，一路畅所欲言。走着走着，她过了一道奇怪的门禁就进去了。那个门禁相当奇怪，就像用两个变压器外壳做的，看起来很小但摸起来有点烫。这是我才注意起身边的环境，她进入的场所四周被电网包围，向右手边看去，有两个同学正操控着门禁阻挡我。我受阻于门禁，于是只得离开。同时一直回想着方才的聊天。不知不觉间就清醒了，但聊天内容却都忘记了。</span>',
	'ybsl_047zhangmi':'<font color=cyan>忆-047·痴惘之妒魂</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：灵境AI绘图<br>◈配音：暂无<br/>凭什么你可以，我就不行？<br/><span class=thundertext>张汨，记2023年6月7日之8日梦。梦见彡，还有另一个丫头<span style="text-decoration: line-through;">&#20993&#22919</span>，我为其命名为张汨。我们一同进入陌生的大学。我和彡一直在腻歪，张汨就一直辱骂彡，我就一直抱着彡安抚她。然后我气不过，准备回骂，但由于情绪过于激动，导致梦醒。</span>',
	
	'ybsl_048wushuang':'<font color=cyan>忆-048·似水流年</font><br>❁技能设计：夜白<br>❁代码撰写者：夜白<br>❁插图：派蒙AI绘图<br>❁配音：暂无<br/>那年花开，晴空有你。惜无神雕，难成侠侣。<br/><span class=thundertext>吴爽，原型为同名本人。童年玩伴。一直为我创造乐趣。后来张玉洁也加入，她俩一起为我创造乐趣。曾画过一些地图，但遍布陷阱。<br>可惜当初它她本人画的地图已经轶失，于是我秉承着遍布陷阱这一核心，仿制了个新的地图。<br/><div style="border:2px solid gray"><span><img style=width:500px src=\'+lib.assetURL+\'extension/夜白神略/image/其它/遍布陷阱的宫殿.png></span></span>',
	'ybsl_049waner':'<font color=cyan>忆-049·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>王婉儿，原型保密，事迹暂无。</span>',
	'ybsl_050zunjian':'<font color=cyan>忆-050·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>鐏柬，原型保密，事迹暂无。</span>',
	'ybsl_051fomalhaut':'<font color=cyan>忆-051·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>北落师门，原型保密，事迹暂无。</span>',
	'ybsl_052trees':'<font color=cyan>忆-052·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>姜森，原型保密，事迹暂无。</span>',
	'ybsl_053qiuer':'<font color=cyan>忆-053·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>秋儿，原型保密，事迹暂无。</span>',
	'ybsl_054yueer':'<font color=cyan>忆-054·共轭之恋</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：派蒙AI绘图<br>❀配音：暂无<br/>不如由我裁之，你我一人一半。<br/><span class=thundertext>悦儿，原型保密，事迹暂无。</span>',
	'ybsl_055zhengyan':'<font color=cyan>忆-055·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：AI绘画精灵AI绘图<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>郑琰，原型保密，事迹暂无。</span>',
	'ybsl_056dongjianchao':'<font color=cyan>忆-056·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>董建超，原型保密，事迹暂无。</span>',
	'ybsl_057sunmeiqi':'<font color=cyan>忆-057·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>孙美琪，原型保密，事迹暂无。</span>',
	'ybsl_058sunshibo':'<font color=cyan>忆-058·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>孙世博，原型保密，事迹暂无。</span>',
	'ybsl_059starsFall':'<font color=cyan>忆-059·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：暂无<br>❀配音：暂无<br/>我曾在那片球场看她们打球，偶尔也在那品读小说。<br>我沉浸于耳畔的欢声笑语，晚风催我快翻下一页。<br>我仰起头感受天空的雨意，一颗流星从我身后飞起，划过天际。<br>我奔过去将它捡起，回头迎上夕阳的快门。<br/><span class=thundertext>星落四公主，原型为高中时的四名女同学，姓名不知。经常在球场打排球，我也常过去看她们玩，顺便帮她们捡球。</span>',
	'ybsl_059starsFall1':'<font color=cyan>忆-059★·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>鞠熒，原型不知姓名，只记得姓鞠。某天，她带了一块手表，别人开玩笑说这表50块（还是50万忘了）。第二天我一如既往坐旁边观看，注意到她没带那个表，于是我开口问，你那50块的表呢。然后恰好她接球，于是那个球直挺挺的被她打向了我，看起来是不小心的，幸好我眼疾手快抬手挡住了。<br>贯虹第一段效果，即进行判定并记录判定牌的效果，寓意她前一天展示手表，之后别人用同花色牌可以视为对其用杀，寓意她听到我再次提起手表时，飞向我那个球。</span>',//'鞠熒',//本名忘了
	'ybsl_059starsFall2':'<font color=cyan>忆-059★·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>宋橤，原型宋某，身材挺胖。其他不太记得了，只记得某次雨后打球，她不小心滑倒了，坐进了水泡。<br>技能名就是对这个事件的描述，濯，释义为洗，委婉形容她跌坐的事情，潭就是那个水泡。表现为技能则是，为了应对猝不及防的进攻而不得不调整手牌数。<br>选择灵梦作她的原画其实我是拒绝的，但是没有其他躺在水坑的图了，so~</span>',//'宋橤',//本名保密橤渁
	'ybsl_059starsFall3':'<font color=cyan>忆-059★·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>周靈，原型不知姓名。事迹暂无，但是有她才够人数打球。属于是为了凑齐四个人强行设计的。<br>一开始的技能内容是只有前半段的“伪中流”，表达了她的特性，她要在这个组合里才能发挥效果。后来加了个“伪英姿”，意在让她可以在先手登场时不至于白板。<br><span style="opacity:0.5;">其实我是一直念叨着要在自己扩展里加个中流，中流直接给了她算是先种树后挖坑</span></span>',//'周靈',//本名保密
	'ybsl_059starsFall4':'<font color=cyan>忆-059★·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>李暁，原型不知姓名。某天正在打球时，一阵雨快速来快速走，我问她们说，你们是学文科的，说说这是什么雨吧，她回应这是冷锋过境…（后面不记得了）。<br>技能名直截了当，评雨。一开始的技能效果是：场上判定后，你可以弃置每当场上有判定牌生效后，你可以弃置进行判定的角色一张牌，若弃置牌和判定结果花色相同，其摸两张牌，否则你可以弃置自己的一张与判定结果花色相同的牌，然后摸两张牌。之后觉得会导致和古河渚同时登场时出现无限嵌套，便把第一段删了。变成：每当场上有判定牌生效后，你可以弃置自己的一张与判定结果花色相同的牌，然后摸两张牌。再之后仍然感觉有所不妥，于是就改成改判技能了…<br>以上几版技能都有“场上角色的判定阶段开始时，若其判定区没有牌，你可令其进行一次【灵雨】判定。”这句。<br>其实还有一版是：转换技，当场上有牌进入弃牌堆时，你可展示手牌，若你手牌中没有与之同花色的牌，则：阳，你获得此牌；阴，你摸X张牌，X为4-你手牌的花色数。忘记因为什么感觉不妥了，好像是嫌弱…</span>',//'李曉',//本名保密
	'ybsl_060liutianhang':'<font color=cyan>忆-060·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>刘天杭，原型保密，事迹暂无。</span>',
	'ybsl_061zheyu':'<font color=cyan>忆-061·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>哲宇，原型保密，事迹暂无。</span>',
	'ybsl_062yuhongyan':'<font color=cyan>忆-062·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>于洪岩，原型保密，事迹暂无。</span>',
	'ybsl_063weimingli':'<font color=cyan>忆-063·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>魏铭利，原型保密，事迹暂无。</span>',
	'ybsl_064lvmingyan':'<font color=cyan>忆-064·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>吕明岩，原型保密，事迹暂无。</span>',
	'ybsl_065yanxiwen':'<font color=cyan>忆-065·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：暂无<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>阎锡文，原型保密，事迹暂无。</span>',
	'ybsl_066wujun':'<font color=cyan>忆-066·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◎配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>武筠，原型保密，事迹暂无。</span>',
	'db_ybsl_067snake':'<font color=cyan>忆-067·旧梦循蹈</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白，潜水的火（缠情）<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>纯情的花，在梦里春心荡漾。站在盛夏的岔路口寻觅，你在何方？<br/><span class=thundertext>蛇妃，原型为某不记得名字的高中认识的同学，同时在我2022年12月23之24日的一场梦中登场。<br>具体事迹不详，梦境梗概写在了人物独白中，具体梦境已经忘了。</span>',
	'ybsl_068qingyue':'<font color=cyan>忆-068·似水流年</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>清月伴孤影，落红眷飞鸿。<br/><span class=thundertext>清月姑娘，原型为某一次坐客车遇见的姑娘，大约十岁左右，毫无戒备的倚在我身上睡着了，之后长久难忘。</span>',
	'ybsl_069xiangzi':'<font color=cyan>忆-069·似水流年</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>香紫姑娘，原型为某一次梦中的角色，事迹已忘。</span>',
	'ybsl_070lvyanqiu':'<font color=cyan>忆-070·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>吕艳秋，原型保密，事迹暂无。</span>',
	
	
	
	
	'ybsl_075dogcard':'<font color=cyan>忆-075·再充十万</font><br>※技能设计：夜白<br>※代码撰写者：夜白<br>※插图：不知来源<br>※配音：暂无<br/>再充十万，你会更强。<br/><span class=thundertext>苟卡，不必过多介绍。</span>',
	'ybsl_076zhujun':'<font color=cyan>忆-076·似水流年</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>朱焌，记2023年3月5日之6日梦见的第一个场景。这次载入的梦境是，我在一个食堂里，在和卖麻辣烫的姑娘交谈。她替我做主选择了食物，然后自己也做了一份，与我一同进餐。只是她都吃完了，我却依旧没胃口。</span><span class=yellowtext>这个姑娘被我命名为朱焌。</span></span>',
	'ybsl_077yangqixu':'<font color=cyan>忆-077·似水流年</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>羊祈絮，记2023年3月5日之6日梦见的第二个场景。这次载入的梦境是，我在一间教室里参加宴会，同时还有若干人，不过仅剩下的印象只有两人，一个跑的飞快，另一个是宴会的举办者。都不知道名。</span><span class=yellowtext>跑的飞快的被我命名为羊祈絮。</span><span class=thundertext>羊祈絮不知为何被人追捕，随后一溜烟跑没了。</span>',
	'ybsl_078zhuyahai':'<font color=cyan>忆-078·似水流年</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>朱涯海，记2023年3月5日之6日梦见的第二个场景。这次载入的梦境是，我在一间教室里参加宴会，同时还有若干人，不过仅剩下的印象只有两人，一个跑的飞快，另一个是宴会的举办者。都不知道名。</span><span class=yellowtext>举办者被我命名为朱涯海。</span><span class=thundertext>朱涯海给我一种深藏不露的感觉，却莫名深得人们的信任。</span>',
	'ybsl_079xiaoxin':'<font color=cyan>忆-079·似水流年</font><br>◎技能设计：夜白<br>◎代码撰写者：夜白<br>◎插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◎配音：暂无<br/>待填写<br/><span class=thundertext>小新，原型保密，事迹暂无。</span>',
	'ybsl_080phoenix':'<font color=cyan>忆-080·凤鸣九天</font><br>★技能设计：夜白<br>★代码撰写者：夜白<br>★插图：暂无<br>★配音：暂无<br/>待填写。<br/><span class=thundertext>凤，原型为作者高二那年在路边看到的一只野鸡。当时我就在幻想，要是我把它捡回来养着，以后能不能变凤凰。</span>',
	'ybsl_081chenli':'<font color=cyan>忆-081·巡梦迷失者</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>陈丽，。</span>',
	'ybsl_081chensi':'<font color=cyan>忆-081·巡梦迷失者</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>陈思，。</span>',
	
	'ybsl_083xiaozhu':'<font color=cyan>忆-083·巡梦天合</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：灵境AI绘图<br>◈配音：暂无<br/>待填写。<br/><span class=thundertext>小筑，记2023年5月30日之31日梦。由于未能及时记录导致梦境遗忘较多，只记得这个姑娘擅长搭建建筑，但被风一吹就散架恢复原样。</span>',
	//047 张汨原位置，新角色待定
	'ybsl_085DGY':'<font color=cyan>忆-085·雨漫孤城</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>你在我的心里，立了一块碑。我的心，从此荒芜。<br/><span class=thundertext>独孤雨，原名保密，某天打王者认识的，后来逐渐熟络，也交换了姓名。性格跳脱。然后我半年没玩，跟她打了会匹配，她借口我辅助不跟她，给我删了。后来加了回来，说来姨妈了，心情不好。我：……注意身体。</span>',
	'ybsl_086GJ':'<font color=cyan>忆-086·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>……<br/><span class=thundertext>龚洁，。</span>',
	// 'ybsl_087tianlu':['female','YB_memory',3,[],['epic']],//田璐
	// 'ybsl_088lijiaxin':['female','YB_memory',3,[],['epic']],//李嘉欣
	// 'ybsl_089lvjinling':['female','YB_memory',3,[],['epic']],//吕金玲
	// 'ybsl_090dengtingyue':['female','YB_memory',3,[],['epic']],//邓婷月
	// 'ybsl_086GJ':['female','YB_memory',3,[],['epic']],//王彩钰
	'ybsl_092handan':'<font color=cyan>忆-092·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>……<br/><span class=thundertext>玉蝶心，。</span>',
	// 'ybsl_093cat':['female','YB_memory',3,[],['epic']],//猫猫
	// 'ybsl_093cat':['female','YB_memory',3,[],['epic']],//猫猫
	// 'ybsl_093cat':['female','YB_memory',3,[],['epic']],//猫猫
	// 'ybsl_093cat':['female','YB_memory',3,[],['epic']],//猫猫
	// 'ybsl_093cat':['female','YB_memory',3,[],['epic']],//猫猫
	// 'ybsl_093cat':['female','YB_memory',3,[],['epic']],//猫猫
	// 'ybsl_093cat':['female','YB_memory',3,[],['epic']],//猫猫
	'ybsl_107tushanshuili': '<font color=cyan>忆-107·巡梦归途</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白，潜水的火（踏野，妖异）<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>……<br/><span class=thundertext>涂山水璃，来自于我2024年5月4日左右的梦。<br>不知为何，我遇见了一个妹子，还捡到一个小狐狸。我抱起小狐狸，想找到她的家。最终来到一处房屋深处。不知为何，有一个指示方向的箭头，我跟着箭头走到一处，突然醒了。翌日深夜，我猛然想起，遂向群友征集该角色名字，最终敲定涂山水璃。</span>',
	//---------------------------------//忆包SP
	'db_ybsp_014liutianyu':'<font color=cyan>忆☆SP-001·暗流涌动</font><br>✿技能设计：夜白<br>✿代码撰写者：夜白<br>✿插图：QQ小世界AI绘图<br>✿配音：暂无<br/>待填写。<br/><span class=thundertext>夜白，原型为作者本人，2019年春自号北地诗仙，2020年春夏自取别名夜白。故事仍在继续书写，也许永无尽头。</span>',
	'ybsp_016manchengqi':'<font color=cyan>忆☆SP-002·清明节限定</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>若思悔不及，则万念俱成枯。趁你还年轻，他还未老。<br/><span class=thundertext>满城柒，原型保密，转学后三中的同学。曾为我单相思的对象。后来时常打扰她。高中毕业后我彻底醒悟。善于唱歌，常听我诉说。喜欢夸赞别人。</span><br><span class=yellowtext>她只是个倾听者，动歪心思的是我。</span><font color=cyan><br><span style="opacity:0.1;">\u4e5f\u8bb8\u5979\u4e5f\u786e\u5b9e\u8ba4\u771f\u5730\u559c\u6b22\u8fc7\u6211\uff0c\u6bd5\u7adf\u5f53\u65f6\u6211\u8868\u73b0\u51fa\u5bf9\u4e09\u56fd\u6740\u7684\u5174\u8da3\uff0c\u5979\u5c31\u5047\u88c5\u4e5f\u559c\u6b22\u4e09\u56fd\u6740\uff0c\u521b\u9020\u4e0e\u6211\u7684\u5171\u540c\u8bdd\u9898\u3002\u5979\u53ea\u662f\u4e34\u573a\u6076\u8865\u4e00\u756a\u4e09\u56fd\u6740\u77e5\u8bc6\u800c\u5df2\uff0c\u56de\u60f3\u8d77\u90a3\u6bb5\u7ecf\u5386\uff0c\u6211\u53ef\u4ee5\u4e07\u5206\u80af\u5b9a\u3002\u90a3\u4e9b\u5f80\u4e8b\uff0c\u90a3\u4e9b\u7ec6\u8282\uff0c\u90fd\u662f\u90a3\u4e48\u7684\u6295\u6211\u6240\u597d\u3002\u5979\u5728\u90a3\u5e74\u590f\u5929\u4e3a\u6211\u5531\u7684\u6b4c\uff0c\u4ee4\u6211\u6f78\u7136\u6cea\u4e0b\u3002\u4e5f\u8bb8\u662f\u6211\u5e74\u5c11\uff0c\u4e0d\u61c2\u5f97\u8fdb\u9000\u5206\u5bf8\u5427\u3002</span></font><br><span class=yellowtext><br>妙园风雪途·作于2018、12、06<br>妙园风雪会今年，今年风雪会妙园。<br>妙园狭路逢故友，故友踌躇未敢言。<br>日光斜照方寸暖，驻足良久方开口。<br>问我伊人在何方，天自苍寥地自荒。<br>初时故人不自解，解时故人已去远。<br>朔风凛冽寒蝉翼，霜日摇曳嘲晚叶。<br>蝴蝶翩翩绕枝头，蜂虫依依戏牵牛。<br>葵花有意向金乌，松叶不愿轻易哭。<br>伊人有酒未曾吐，诗人佯醉却倾心。<br>染纸相思表赤血，清袖无丝碎真心。<br>诗人歌罢回看酒，酒陈杯新人已累。<br>推杯起身心方醒，人生何处无滋味。<br>醒时已是暮春时，回首才觉伊人醉。<br>诗人已书新赋草，伊人还读旧辞酹。<br>诗人佯醉已走脱，伊人持酒仍痴醉。<br>一曲歌罢梦回醒，诗人伊人皆有泪。<br>此间穿肠千种愧，诗人有愧方觉恨。<br>泪悔前头应有源，犹见孟德与公台。<br>妙园风雪别今年，今年风雪别妙园。<br>妙园宽径独徘徊，故人相见未敢认。</span>',
	'db_ybsp_038tengwu':'<font color=cyan>忆☆SP-004·缘尽梦碎</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>◈配音：暂无<br/>黄泉路上的两名少女被复活后，会以身相许，还是许诺来世做牛马？<br/><span class=thundertext>滕叔颖＆武宁，原型为高中两个同学，姓名不详，同时在我2022年10月17日之18日的梦境登场。<br>以下是我当天晚上写的手记。<br>幻之大地分两层，上层为梦境，下层为现实，梦境的世界映照现实的人的内心，即便他已经死去。而在梦境世界死去的人会被捕捉进魔王的狭间世界。这是勇者斗恶龙6的设定。<br>我梦见我生活在幻之大地上层，在一个魔法学院上学，舍友会制符。我用他赠的一张符杀了一个仇家。<br>下一个场景，我梦见我从大地上的窟窿掉了下去，到了下一层大陆依旧在下坠，这时神龙出现，他托起了我，说我是命中注定的人，于是把我载了回去，我问去了下面会怎么样，他没说话，示意我看，我看见一大片虚空，样子甚是恐怖。他又问我有什么愿望，我表示有两个红颜知己，如今在上层大陆死了，可能在冥界，委托他帮我找回来。神龙答应了。</span><span class=yellowtext>这个两个红颜知己被我命名为滕叔颖和武宁。</span><span class=thundertext><br>然后下一个场景，我在一个私人豪宅，看见外面有个电话亭，突然电话响了，并且他们两个一脸飒爽的从电话亭里走出。我很开心，但我没有说出是我让他们复活的事情。她们说假如知道谁让她们活了过来，一定要以身相许。我正要说些什么，突然感觉意识有着清晰，我一愣，正要再看一眼她们，我醒了。<br>听说当一个好久不见的人突然出现在你的梦里，说明这个人正在遗忘你。仔细想想，她们不过是两个与我有过一点交集的人。其中一个表现暧昧，另外一个敬而远之。如今的梦正说明，我渴望被她们关注。我很享受被暗恋的感觉，可一旦挑明了，就难以品味了。<br>像她们这样的姑娘，我也遇过许多。但我并没有明确表示过什么。因为我很清楚，我只适合作为她们的白月光。我也很乐得享受这种感觉。她们也乐得享受。主要是，我认为，白月光给人一种极为特殊的意义，他是你内心深处的一根精神支柱，他的意义无可言喻，但是在你遇到问题时，一定会下意识想要是有他在多好，可惜并不能。或者睡梦中，甚至失恋时，也会作为意淫的对象，幻想他躺在你身边。在你孤独时，他会幻现在你脑海里，或者幻现在你身边。你以为你会拥抱着他入睡，可睁开眼，却是你抱着自己的大腿。至于梦中的人啊，你要怎么才能出现，从我的梦境里，脑海里出现在我身边，想我想的那样，陪伴我，拥抱我，关怀我。我多么希望幻之大地的设定在这里可以实现。<br>在游戏里，梦之世界主角初始村的山下有一个集市叫玛尔谢，但是在对应的真实世界，这里只有一个孤独的木屋，和一个孤独的老人。老人的愿望是将来这里能发展成一个大集市。我想，这个梦应该把我的内心所想都具现了。<br>凌晨一点了。睡了。</span>',
	'ybsp_072sulingyi':'<font color=cyan>忆-072·不祥的命运</font><br>★技能设计：夜白<br>★代码撰写者：夜白<br>★插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>★配音：暂无<br>预言<br>你五行缺火，于是母亲在你出生不久便取了“苏令燚”这个名字。四个火，女神和火种的意思。<br>我叫苏令燚，长在彭湾村。彭湾是个有山有水的地方，一年四季，温度适中，这是个未被商业浸染的村庄，有着最淳朴的民风和最纯粹的风景。<br>围绕着彭湾村的，是湾河，碧绿的，像一条带子，水会随着风飞舞，叶会在湾河中小憩，<br>然而彭湾的村民也是极保守和传统的，他们似乎未从旧社会中走出来的，彭湾的男丁极少到外面谋生，多部分固守着自己的田，男耕女织，日出而作，日暮而息。<br>所以，用另一种话说，彭湾似乎是与外界隔绝的，有点像“桃花源”。<br>下雨，是最喜欢的天气，接连下一天的雨，倘或夏季，水便会涨的很高，有从外面冒冒失失游进的鱼——草鱼、鲤鱼、鲫鱼……多不盛数。<br>那个时候，彭湾里的男丁便会手持大大的网兜，到河里捕鱼，，小孩子也会到水沟里捉鱼，一人一头，一点点的往中间堵住鱼。湾河的水清澈，沁人，似乎能喝，又似乎不能喝。这样的水。是被冠以神圣的寓意的。村里最老的长者说，自他太爷爷那代，就有湾河了，湾河是历史的见证。湾河在，人在，湾河亡，人亡。<br>我是不相信那些话的，彼时，我是一个十一岁的快乐少女，周一至周五在村口的小学堂上读书，教书先生教我们识字、算术。<br>至于最早的教书先生的知识是是从哪儿来的，是外界的闯入？还是先生的外出求知识？这似乎一直以来就是一个谜。<br>“小火，你父亲呢？”伙伴淼问我。<br>“不知道，自出生开始，就没见过他。”我没有表情的回答。<br>俞淼，是我那时候最好的朋友，他五行缺水，他父亲便让算命先生帮他取了这个名字。<br>淼对我很好，总摘给我他家种的桃子，极大极甜，那时候我总会满足地跟在淼后面，使劲的拍马屁。<br>淼捕鱼很厉害，他每次总是一放学，便去捕鱼，他回家扔下书包，拎着网兜，光着脚丫，沿着湾河一直跑，微波粼粼，倒印了他的身影，我遥望他的眼神，也变的一晃一晃，一直晃到我心里。<br>初秋，我们就去“偷”王老大家的番薯，选几个，用铲子小心的挖出番薯，一人两个，要小些的，那样烤着才香。<br>那时候，淼去找稻草，我便一人用砖头搭了灶烧火， 升腾起一圈圈浓重的烟雾 ，熏得有了细微的泪，可是依旧快乐。<br>烤出来的番薯是极香极甜的，但是很烫，撕开外面烧焦的皮，便可下肚了。吃的，并不是番薯吧，而是两个人在一起的快乐时光。<br>放暑假了，一群孩子像疯了一般，急着冲到自己家。那时候的娱乐方式就是一起玩捉迷藏，打弹珠，或者帮家长种的地浇些水。<br>可是我却快乐不起来。<br>淼像看出了什么，一起回家，他终于问我：“怎么了，小火？”<br>我该怎么告诉他，近日来我总是重复着一个梦，一个有关湾河，有关我的梦。梦里总有算命先生的身影，重复着说：“她五行缺火，四个火，会像她爸一样，客死湾河的。”也总是听见那种不真切的声音“淹死她！淹死她！”然后醒来，是一身虚汗。<br>拧开瓶盖吞了口水，还是没有告诉他。<br>傍晚，我心不在焉的帮母亲绕毛线，这时一个算命先生不请自来，我打了个冷颤。在劫难逃的，是要来了么？<br>我躲在房间里，贴着门，偷听他们的谈话。<br>“自打她出生，就让你扔掉她的，你怎么留到现在？你想让她和她父亲一样？”<br>“……”母亲无语，接着便是隐隐的哭泣，悠远的像来自另一个时空。<br>“早些把她送到外面吧。”算命先生丢下这句话，便走了。<br>我倚在门上的身躯，开始瘫软下去。<br>彭湾忽然没有井水了，村民们取不到水，只能去湾河盛水。然而有一部分老者反对，说干了湾河，人也就死了。<br>好几天没有下雨了，我舔舔嘴唇，干渴的难受，倚在门框上，望着外面的烈日灼灼，这种天气，在彭湾是极少有的。<br>有村民说，报应了啦，报应来啦，他的幽魂附在她女儿身上啦……十二年前的报应啊……<br>我不知道十二年前发生了什么，但隐隐觉得，它与我，有着莫大的关系。<br>母亲这几日，异常的憔悴、焦躁，没有水，她的衣服也有好几日没洗了。<br>我问母亲：“十二年前，究竟发生了什么？”她先是死活不肯说，后来终于开口：“你父亲苏燚，是被他们沉河沉死的。”一向坚强的母亲，这是却流泪了，是隐隐的，笔直的一行泪，滴落在门槛上。<br>当时的父母，一个缺水，一个缺火，不顾村民的反对，毅然的结婚了，可是结婚后，湾河莫名其妙的断流了。必要淹死一个，便可使湾河获水。<br>于是父亲被他们沉河，庸俗的湾河村民，居然觉得那是个绝妙的方法。<br>而一向善水的父亲，为了保住母亲，和她肚中的我，生生的，没有憋气，淹死了。<br>村民们很是高兴。<br>算命先生在我母亲耳边说：“你肚里的孩子出生后，必要丢到外面，不然会像她父亲一样，没有好下场。”这是一个预言，预言的开始，是死亡与丢弃。<br>这一天终于还是到了，村民们要淹死我的念头日益加重，我被一帮人抬到了湾河边，村长，算命先生，也在其中。<br>“苏令燚，你父亲十二年前为了挽救湾河，所以不惜牺牲自己的性命，我相信你也是个好孩子，会为湾河付出什么的，对吧？”<br>我想说不对，可是话未出口，就生生的被沉了下去。',
	'ybsp_002chenailin':'<font color=cyan>忆☆SP-003·玉殒香消</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白，潜水的火（香陨）<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>❀配音：暂无<br/>留点什么吧，聊做分别之后的怀念。<br/><span class=thundertext>陈爱琳，原型为同名本人，六中三班的一员，作者（以下称我）对那段时光最美好的回忆。以下文段为忆陈爱琳文。文本几经修改，终成定稿。对话原话不太记得了，因此用意义相同或相近的文言说法。</span><br><span class=firetext>注：文段受岁月滤镜影响，存在某处虚写。事实无论，吾言即是。</span><br><span class=yellowtext>久别不见，故作文怀之。<br>陈氏女，名爱琳，不知生年，癸巳年入初中，与之遇。孙氏女，名丽松，王氏女，名汉桢，皆为陈友。吾与之事实繁，然皆不记忆，依稀几数，至今铭心。<br>一日，学政治，谈男女往来，毕，吾谓陈曰：“男女具，身心益。”，<span style="opacity:0.1;">（男生女生在一起，有益健康）这是我记得的为数不多的原话。请允许我把这句话藏起来，毕竟现在想想太羞耻了，抓紧忘了吧我天。</span><br>三女具嗤，道：“淫嬷嬷”，乃去。<br>初识，吾与陈并列第三，师谓曰：“汝二人，定分高下。”及试，座临。考历史，陈密索一字。吾以此挟，索屈原事迹，附：吾二人，定分高下。出榜，陈三吾七，陈笑，顾二女曰：“才道，定分高下。”余赤面而去。<br>一日，学语文，讲柳宗元之小石潭记，校音，及“壹”，吾和曰：仅旧版钱有之。满堂皆笑。师曰：“汝视之。”余惑，遂取钱视之，乃悟，遂羞而掩面。</span><span class=firetext>注：岁月的滤镜下，吾总觉陈之笑最甚。事实无论，吾言即是。</span><br><span class=yellowtext>彼时，偶见之以美工刀划臂。便私书之：“书曰：珍己，勿伤。”陈惶，书，顾左右而传之。启之，曰：“无宣，令师知也。”余内笑，回曰：“莫如此也。”对曰：“善。”此事揭过。<br>一日，与人冲突，因果皆不记忆。其人名姜玉恒。冲吾，使吾跌。余奋极，恰右有棍，遂操棍挺身抡之，中头，棍折，余怒尚在，幸观者分之，而姜步罗圈，道：没事。待定，回味此棍，复操之以试击，仿佛为要害也，及顾而问陈：“如此，是耶？”陈惊，颔而应之。吾才省，知此事惧之也。师知，谓皆有过，遂不提。<br>一日，学英语，点我名。有灯垂于梁。余起欲答，忽身失衡，刹那而仰，见灯如柳摇曳，方知地动。当是时，警铃鸣，楼摇轰，脚踏声，一时齐发，不可辩也。余乃惊，携冠欲潜桌下，师曰：“不坚！”遂随流而下。及远，乃检冠中钱，未损。乃假七日。<br>稍定，一日语文课，有联曰：殷殷舔犊情。无人能对。余上而书：情情抚挚颊。盖断错句、解错意也。乃顾陈，以示炫耀。师不可解，曰：“上联言亲情，下联言爱情，稍欠。”余亦觉欠，然无益者。<br>某晚，尚余一刻钟。余沉思，师曰：“复地动乎？”余闻轰，以为移案。师曰：“莫不是窗动？不详。”言讫，始觉轰声愈响，坐不稳，忽闻铃震，皆慌而走。始静，复检冠中钱。顾陈，亦无恙。乃假一月。<br>某日，吾二人独处于室，随心而谈，曰：“汝敛袖，吾欲检之。”乃奋袖出臂。余观之，无痕。其肤白而美，余难耐而抚之，遂怦然心动。陈忽道：“你多久没剪指甲？”吾曰：“四月。”陈默。良久，乃曰：“今周五，周六周日你洗澡剪指甲，周一我检查。则赐一车饼干。”乃信之。然懒惰成性，终未成，此为后话。当晚归家，母曰：“汝父欲使汝北还续学，何如？”余道：“安乐与此，何故北还？”母曰：“汝藉在北。若留需迁藉易姓。”余决然道：“大丈夫，岂能易姓？吾当北还。”乃定甲午秋北还续学。复无相见，甚念之矣。<br>丁酉，业毕。余南下归故校，觅旧师，叹往昔。问及诸友，则曰：“王汉桢入三中，孙丽松入实验……”独不见陈爱琳。问之，则叹曰：“汝去，即堕。吾见其与众男厮，恐其安危，遂告教导主任，岂料教导主任因其男女关系不当，记其大过。爱琳恨我。顷之辍学，不复见也。”<br>余闻之，甚悲。实意料之外，又情理之中。倘吾异姓而拒北，迁藉而居南，定有挽澜之机。虽吾今有知，然知者何如？不知者何如？知深而乐衰，视广而情短，悲哉！<br>念君，恬静，不知。<br>殷殷舔犊情，浅浅执手意。<br>安否？佳祺。</span><br><span class=thundertext>谨以此文，祭年少无知。<br>我不会主动去寻觅失散的人，也不会去追问她们后来怎样。她们在我印象中留下的美丽的足迹，对我而言已经是宝贵的财富。这份回忆足以温暖我一生。</span>',
	'ybsp_027rain':'<font color=cyan>忆☆SP-006·巡梦鸣觉</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>◈配音：暂无<br/>你在我的梦里藏匿，一尘不染。<br/><span class=thundertext>雨，记2022年7月17日之18日的一场梦。<br>这次载入的梦境是一个仿若童年的村落，我遇见了另一个我，但另一个我是女的。我们一起玩耍，其余不记得了。为了纪念这一场梦，我为其取名为“雨”，并撰写此武将。</span>',
	'ybsp_001sunlisong':'<font color=cyan>忆☆SP-005·皓腕凝霜雪</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>孙丽松，原型为同名本人，陈爱琳和王汉桢的闺蜜，六中三班的一员。不算太熟，但隐约记得关系还不错，言行举止令人如沐春风。</span>',
	
	//---------------------------------//界限突破（什么沙比玩意）
	'ybnb_034zhoulianyuan':'<font color=cyan>忆☆界-034·庄子的执剑人</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>梦中的人记不得模样，梦中的事记忆犹新。<br/><span class=thundertext>周怜渊，记2022年9月15日之16日的一场梦。<br>这次载入的梦境大致是一个作文考试，我叙写了一篇文章，讲述了一个言辞锋利的监察者，具体事迹不详，只记得名字叫周怜渊。为了纪念这一场梦，并撰写此武将。</span>',
	
	//---------------------------六艺篇
	'ybart_013yinji':'<font color=cyan>忆-013·似水流年</font>✿<span class=yellowtext>六艺篇</span><br>✿技能设计：夜白<br>✿代码撰写者：夜白<br>✿插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>✿配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>尹姬，原型为尹超跃，六中三班一员，体操领操员。曾与我一同领操表演节目。曾一次失手用书夹划伤我手臂，伤疤至今依旧留在我手臂。其余事迹不详。</span>',
	'ybart_014liutianyu':'<font color=cyan>忆-014·似水流年</font>❀<span class=yellowtext>六艺篇</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：暂无<br>❀配音：暂无<br/>故事仍在继续书写。<br/><span class=thundertext>夜白，原型为作者本人，2019年春自号北地诗仙，2020年春夏自取别名夜白。故事仍在继续书写，也许永无尽头。</span>',
	'ybart_016manchengqi':'<font color=cyan>忆-016·似水流年</font>❀<span class=yellowtext>六艺篇</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>若思悔不及，则万念俱成枯。趁你还年轻，他还未老。<br/><span class=thundertext>满城柒，原型保密，转学后三中的同学。曾为我单相思的对象。后来时常打扰她。高中毕业后我彻底醒悟。善于唱歌，常听我诉说。喜欢夸赞别人。</span><br><span class=yellowtext>她只是个倾听者，动歪心思的是我。</span><br><font color=cyan><span style="opacity:0.1;">\u4e5f\u8bb8\u5979\u4e5f\u786e\u5b9e\u8ba4\u771f\u5730\u559c\u6b22\u8fc7\u6211\uff0c\u6bd5\u7adf\u5f53\u65f6\u6211\u8868\u73b0\u51fa\u5bf9\u4e09\u56fd\u6740\u7684\u5174\u8da3\uff0c\u5979\u5c31\u5047\u88c5\u4e5f\u559c\u6b22\u4e09\u56fd\u6740\uff0c\u521b\u9020\u4e0e\u6211\u7684\u5171\u540c\u8bdd\u9898\u3002\u5979\u53ea\u662f\u4e34\u573a\u6076\u8865\u4e00\u756a\u4e09\u56fd\u6740\u77e5\u8bc6\u800c\u5df2\uff0c\u56de\u60f3\u8d77\u90a3\u6bb5\u7ecf\u5386\uff0c\u6211\u53ef\u4ee5\u4e07\u5206\u80af\u5b9a\u3002\u90a3\u4e9b\u5f80\u4e8b\uff0c\u90a3\u4e9b\u7ec6\u8282\uff0c\u90fd\u662f\u90a3\u4e48\u7684\u6295\u6211\u6240\u597d\u3002\u5979\u5728\u90a3\u5e74\u590f\u5929\u4e3a\u6211\u5531\u7684\u6b4c\uff0c\u4ee4\u6211\u6f78\u7136\u6cea\u4e0b\u3002\u4e5f\u8bb8\u662f\u6211\u5e74\u5c11\uff0c\u4e0d\u61c2\u5f97\u8fdb\u9000\u5206\u5bf8\u5427\u3002</span></font><br><span class=yellowtext><br>妙园风雪途·作于2018、12、06<br>妙园风雪会今年，今年风雪会妙园。<br>妙园狭路逢故友，故友踌躇未敢言。<br>日光斜照方寸暖，驻足良久方开口。<br>问我伊人在何方，天自苍寥地自荒。<br>初时故人不自解，解时故人已去远。<br>朔风凛冽寒蝉翼，霜日摇曳嘲晚叶。<br>蝴蝶翩翩绕枝头，蜂虫依依戏牵牛。<br>葵花有意向金乌，松叶不愿轻易哭。<br>伊人有酒未曾吐，诗人佯醉却倾心。<br>染纸相思表赤血，清袖无丝碎真心。<br>诗人歌罢回看酒，酒陈杯新人已累。<br>推杯起身心方醒，人生何处无滋味。<br>醒时已是暮春时，回首才觉伊人醉。<br>诗人已书新赋草，伊人还读旧辞酹。<br>诗人佯醉已走脱，伊人持酒仍痴醉。<br>一曲歌罢梦回醒，诗人伊人皆有泪。<br>此间穿肠千种愧，诗人有愧方觉恨。<br>泪悔前头应有源，犹见孟德与公台。<br>妙园风雪别今年，今年风雪别妙园。<br>妙园宽径独徘徊，故人相见未敢认。</span>',
	'ybart_017xiaohong':'<font color=cyan>忆-017·似水流年</font>❀<span class=yellowtext>六艺篇</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：涂山小红本尊<br/>在她的梦里，化作泡影的人重现。<br/><span class=thundertext>涂山小红，原型保密，转学后三中的同学，为满城柒闺蜜。曾为单相思的我传递书信。为人天真活泼。<span style="text-decoration: line-through;">\u6027\u683c\u548c\u4f5c\u4e3a\u795e\u4f3c\u524d\u671f\u7684\u897f\u56ed\u5bfa\u4e16\u754c\u3002</span>至今关系依旧友好。</span>',
	'ybart_041mmuqin':'<font color=cyan>忆-041·似水流年</font>❀<span class=yellowtext>六艺篇</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>首充一元就送！<br/><span class=thundertext>慕琴，原型为崔妍，高中同学。主要事迹为，某天在一楼大厅里席地而坐，我给她投喂了一块钱，并戏称买了。后来她把一块钱还了回来，但1块钱卖身这个梗我能记一辈子。</span>',
	//---------------------------------//忆包鬼神易
	'dzsl_013yinji':'<font color=cyan>忆-013·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：鬼神易￥<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>尹姬，原型为尹超跃，六中三班一员，体操领操员。曾与我一同领操表演节目。曾一次失手用书夹划伤我手臂，伤疤至今依旧留在我手臂。其余事迹不详。</span>',
	'dzsl_014liutianyu':'<font color=cyan>忆-014·梦的缔造者</font><br>✿技能设计：夜白<br>✿代码撰写者：鬼神易￥<br>✿插图：暂无<br>✿配音：暂无<br/>腐化的身躯，沉湎梦境的灵魂，念旧的心。<br/><span class=thundertext>夜白，原型为作者本人，2019年春自号北地诗仙，2020年春夏自取别名夜白。故事仍在继续书写，也许永无尽头。</span>',
	'dzsl_014xinzhikui':'<font color=cyan>忆-014☆·绝对忠臣</font><br>✿技能设计：夜白<br>✿代码撰写者：鬼神易￥<br>✿插图：暂无<br>✿配音：暂无<br/>平凡的傀儡不过纵丝翩舞罢了，而我的傀儡可不一样，它由我心操控，能知晓我的一切心意，代价则是至爱者的生命。<br/><span class=thundertext></span>',
	'dzsl_015wanghairu':'<font color=cyan>忆-015·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：鬼神易￥<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>同是天涯沦落人，相逢何必曾相识。<br/><span class=thundertext>王海茹，原型为同名本人，转学后三中的同学，后任职为班长。为人德高望重，所有人都很尊敬她。一部分人尊称其为大姑，原因不详。成绩优异。曾在某次跳远时伤到腰部，其后由郭慧欣背其行动。几乎所有人皆因此而热情帮助她。曾劝解单相思的我，使我迷途得返。至今偶有微信联系。</span>',
	'dzsl_016manchengqi':'<font color=cyan>忆-016·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：鬼神易￥<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>若思悔不及，则万念俱成枯。趁你还年轻，他还未老。<br/><span class=thundertext>满城柒，原型保密，转学后三中的同学。曾为我单相思的对象。后来时常打扰她。高中毕业后我彻底醒悟。善于唱歌，常听我诉说。喜欢夸赞别人。</span><br><span class=yellowtext>她只是个倾听者，动歪心思的是我。</span><font color=cyan><br><span style="opacity:0.1;">\u4e5f\u8bb8\u5979\u4e5f\u786e\u5b9e\u8ba4\u771f\u5730\u559c\u6b22\u8fc7\u6211\uff0c\u6bd5\u7adf\u5f53\u65f6\u6211\u8868\u73b0\u51fa\u5bf9\u4e09\u56fd\u6740\u7684\u5174\u8da3\uff0c\u5979\u5c31\u5047\u88c5\u4e5f\u559c\u6b22\u4e09\u56fd\u6740\uff0c\u521b\u9020\u4e0e\u6211\u7684\u5171\u540c\u8bdd\u9898\u3002\u5979\u53ea\u662f\u4e34\u573a\u6076\u8865\u4e00\u756a\u4e09\u56fd\u6740\u77e5\u8bc6\u800c\u5df2\uff0c\u56de\u60f3\u8d77\u90a3\u6bb5\u7ecf\u5386\uff0c\u6211\u53ef\u4ee5\u4e07\u5206\u80af\u5b9a\u3002\u90a3\u4e9b\u5f80\u4e8b\uff0c\u90a3\u4e9b\u7ec6\u8282\uff0c\u90fd\u662f\u90a3\u4e48\u7684\u6295\u6211\u6240\u597d\u3002\u5979\u5728\u90a3\u5e74\u590f\u5929\u4e3a\u6211\u5531\u7684\u6b4c\uff0c\u4ee4\u6211\u6f78\u7136\u6cea\u4e0b\u3002\u4e5f\u8bb8\u662f\u6211\u5e74\u5c11\uff0c\u4e0d\u61c2\u5f97\u8fdb\u9000\u5206\u5bf8\u5427\u3002</span></font><br><span class=yellowtext><br>妙园风雪途·作于2018、12、06<br>妙园风雪会今年，今年风雪会妙园。<br>妙园狭路逢故友，故友踌躇未敢言。<br>日光斜照方寸暖，驻足良久方开口。<br>问我伊人在何方，天自苍寥地自荒。<br>初时故人不自解，解时故人已去远。<br>朔风凛冽寒蝉翼，霜日摇曳嘲晚叶。<br>蝴蝶翩翩绕枝头，蜂虫依依戏牵牛。<br>葵花有意向金乌，松叶不愿轻易哭。<br>伊人有酒未曾吐，诗人佯醉却倾心。<br>染纸相思表赤血，清袖无丝碎真心。<br>诗人歌罢回看酒，酒陈杯新人已累。<br>推杯起身心方醒，人生何处无滋味。<br>醒时已是暮春时，回首才觉伊人醉。<br>诗人已书新赋草，伊人还读旧辞酹。<br>诗人佯醉已走脱，伊人持酒仍痴醉。<br>一曲歌罢梦回醒，诗人伊人皆有泪。<br>此间穿肠千种愧，诗人有愧方觉恨。<br>泪悔前头应有源，犹见孟德与公台。<br>妙园风雪别今年，今年风雪别妙园。<br>妙园宽径独徘徊，故人相见未敢认。</span>',
	'dzsl_017xiaohong':'<font color=cyan>忆-017·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：鬼神易￥<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：涂山小红本尊<br/>在她的梦里，化作泡影的人重现。<br/><span class=thundertext>涂山小红，原型保密，转学后三中的同学，为满城柒闺蜜。曾为单相思的我传递书信。为人天真活泼。<span style="text-decoration: line-through;">\u6027\u683c\u548c\u4f5c\u4e3a\u795e\u4f3c\u524d\u671f\u7684\u897f\u56ed\u5bfa\u4e16\u754c\u3002</span>至今关系依旧友好。</span>',
	//---------------------------------//忆包神将
	'ybslshen_014liutianyu':'<span class=yellowtext>神☆忆-001·天涯的窥梦人</span><br>✿技能设计：夜白<br>✿代码撰写者：夜白<br>✿插图：暂无<br>✿配音：神姜维<br/><span class=yellowtext>作者本人，逼格满满，亮瞎你的眼。</span><br/><font color=cyan>夜白，原型为作者本人，2019年春自号北地诗仙，2020年春夏自取别名夜白。故事仍在继续书写，也许永无尽头。</font>',
	'ybslshen_017xiaohong':'<span class=yellowtext>神☆忆-002·儿童节限定</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/><span class=yellowtext>什么小鹿女啊，一定是世界上最可爱的孩子吧。</span><br/><font color=cyan>涂山小红，原型保密，转学后三中的同学，为满城柒闺蜜。曾为单相思的我传递书信。为人天真活泼。<span style="text-decoration: line-through;">\u6027\u683c\u548c\u4f5c\u4e3a\u795e\u4f3c\u524d\u671f\u7684\u897f\u56ed\u5bfa\u4e16\u754c\u3002</span>至今关系依旧友好。</font>',
	'ybslshen_018zhangqing':'<span class=yellowtext>神☆忆-003·清明节限定</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/><span class=yellowtext>你说可怜世间万物，没有六万五的妞，怎样了你兜儿里只剩八万出头。</span><br/><font color=cyan>张晴，原型为同名本人，转学后三中的同学。与我关系甚好，高中时常短信沟通。曾取得其QQ号和密码以玩王者，后来其注销了。关系还算不错。</font>',
	'ybslshen_002chenailin':'<span class=yellowtext>神☆忆-004·初见与告别</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/><span class=yellowtext>渡口边最后一面洒下了句点，与你若只如初见何须感伤离别。</span><br/><span class=yellowtext>——许嵩《如果当时》</span><br/><span class=thundertext>陈爱琳，原型为同名本人，六中三班的一员，作者（以下称我）对那段时光最美好的回忆。以下文段为忆陈爱琳文。文本几经修改，终成定稿。对话原话不太记得了，因此用意义相同或相近的文言说法。</span><br><span class=firetext>注：文段受岁月滤镜影响，存在某处虚写。事实无论，吾言即是。</span><br><span class=yellowtext>久别不见，故作文怀之。<br>陈氏女，名爱琳，不知生年，癸巳年入初中，与之遇。孙氏女，名丽松，王氏女，名汉桢，皆为陈友。吾与之事实繁，然皆不记忆，依稀几数，至今铭心。<br>一日，学政治，谈男女往来，毕，吾谓陈曰：“男女具，身心益。”，<span style="opacity:0.1;">（男生女生在一起，有益健康）这是我记得的为数不多的原话。请允许我把这句话藏起来，毕竟现在想想太羞耻了，抓紧忘了吧我天。</span><br>三女具嗤，道：“淫嬷嬷”，乃去。<br>初识，吾与陈并列第三，师谓曰：“汝二人，定分高下。”及试，座临。考历史，陈密索一字。吾以此挟，索屈原事迹，附：吾二人，定分高下。出榜，陈三吾七，陈笑，顾二女曰：“才道，定分高下。”余赤面而去。<br>一日，学语文，讲柳宗元之小石潭记，校音，及“壹”，吾和曰：仅旧版钱有之。满堂皆笑。师曰：“汝视之。”余惑，遂取钱视之，乃悟，遂羞而掩面。</span><span class=firetext>注：岁月的滤镜下，吾总觉陈之笑最甚。事实无论，吾言即是。</span><br><span class=yellowtext>彼时，偶见之以美工刀划臂。便私书之：“书曰：珍己，勿伤。”陈惶，书，顾左右而传之。启之，曰：“无宣，令师知也。”余内笑，回曰：“莫如此也。”对曰：“善。”此事揭过。<br>一日，与人冲突，因果皆不记忆。其人名姜玉恒。冲吾，使吾跌。余奋极，恰右有棍，遂操棍挺身抡之，中头，棍折，余怒尚在，幸观者分之，而姜步罗圈，道：没事。待定，回味此棍，复操之以试击，仿佛为要害也，及顾而问陈：“如此，是耶？”陈惊，颔而应之。吾才省，知此事惧之也。师知，谓皆有过，遂不提。<br>一日，学英语，点我名。有灯垂于梁。余起欲答，忽身失衡，刹那而仰，见灯如柳摇曳，方知地动。当是时，警铃鸣，楼摇轰，脚踏声，一时齐发，不可辩也。余乃惊，携冠欲潜桌下，师曰：“不坚！”遂随流而下。及远，乃检冠中钱，未损。乃假七日。<br>稍定，一日语文课，有联曰：殷殷舔犊情。无人能对。余上而书：情情抚挚颊。盖断错句、解错意也。乃顾陈，以示炫耀。师不可解，曰：“上联言亲情，下联言爱情，稍欠。”余亦觉欠，然无益者。<br>某晚，尚余一刻钟。余沉思，师曰：“复地动乎？”余闻轰，以为移案。师曰：“莫不是窗动？不详。”言讫，始觉轰声愈响，坐不稳，忽闻铃震，皆慌而走。始静，复检冠中钱。顾陈，亦无恙。乃假一月。<br>某日，吾二人独处于室，随心而谈，曰：“汝敛袖，吾欲检之。”乃奋袖出臂。余观之，无痕。其肤白而美，余难耐而抚之，遂怦然心动。陈忽道：“你多久没剪指甲？”吾曰：“四月。”陈默。良久，乃曰：“今周五，周六周日你洗澡剪指甲，周一我检查。则赐一车饼干。”乃信之。然懒惰成性，终未成，此为后话。当晚归家，母曰：“汝父欲使汝北还续学，何如？”余道：“安乐与此，何故北还？”母曰：“汝藉在北。若留需迁藉易姓。”余决然道：“大丈夫，岂能易姓？吾当北还。”乃定甲午秋北还续学。复无相见，甚念之矣。<br>丁酉，业毕。余南下归故校，觅旧师，叹往昔。问及诸友，则曰：“王汉桢入三中，孙丽松入实验……”独不见陈爱琳。问之，则叹曰：“汝去，即堕。吾见其与众男厮，恐其安危，遂告教导主任，岂料教导主任因其男女关系不当，记其大过。爱琳恨我。顷之辍学，不复见也。”<br>余闻之，甚悲。实意料之外，又情理之中。倘吾异姓而拒北，迁藉而居南，定有挽澜之机。虽吾今有知，然知者何如？不知者何如？知深而乐衰，视广而情短，悲哉！<br>念君，恬静，不知。<br>殷殷舔犊情，浅浅执手意。<br>安否？佳祺。</span><br><span class=thundertext>谨以此文，祭年少无知。<br>我不会主动去寻觅失散的人，也不会去追问她们后来怎样。她们在我印象中留下的美丽的足迹，对我而言已经是宝贵的财富。这份回忆足以温暖我一生。</span>',
	'ybslshen_071faraway':'<span class=yellowtext>神☆忆-005·银河启示者</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：派蒙AI绘图<br>❀配音：想去远方本尊<br/><span class=yellowtext>I want to go far away!</span><br/><font color=cyan>想去远方，原型为本扩展最早的游玩者之一，真名不详，事迹暂无。</font>',
	'ybslshen_073Al':'<span class=yellowtext>神☆忆-006·天牢令</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：QQ小世界AI绘图<br>❀配音：暂无<br/><span class=yellowtext>村花不会绝情，铝酸有点缺氢<span style="text-decoration: line-through;"><span style="opacity:0.2;">\uff08\u60c5\uff09</span></span>。</span><br/><font color=cyan>铝，原型为本扩展最早的游玩者之一，真名不详，事迹暂无。</font>',
	'ybslshen_074piao':'<span class=yellowtext>神☆忆-007·掌中寰宇</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：花落隨風钦定网图<br>❀配音：暂无<br/>待填写。<br/><span class=thundertext>花落隨風，原型为本扩展最早的游玩者之一，真名不详，事迹暂无。</span>',
	'ybslshen_001sunlisong':'<span class=yellowtext>神☆忆-008·流年易逝</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：灵境AI绘图<br>❀配音：暂无<br/>回忆最为美好，它将你思念的对象不断美化。<br/><span class=thundertext>孙丽松，原型为同名本人，陈爱琳和王汉桢的闺蜜，六中三班的一员。不算太熟，但隐约记得关系还不错，言行举止令人如沐春风。</span>',
	'ybslshen_100Cosette':'<span class=yellowtext>神☆忆-009·Cosette！</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：u佬钦定原画<br>❀配音：暂无<br/><span class=yellowtext>Cosette！</span><br/><font color=cyan>珂赛特，为u佬定制武将，原型为u佬，真名不详，事迹暂无。</font>',//珂赛特
	//---------------------------------//忆包废案
	'yboldshen_002chenailin':'<span class=yellowtext>神☆忆-004·初见与告别</span><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>B站成品图片<br>❀配音：暂无<br/><span class=yellowtext>废案</span>',
	'ybold_018zhangqing':'<font color=cyan>忆-018☆·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>废案。',
	'ybsb_047zhangmi':'<font color=cyan>忆-047·痴惘之妒魂</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：灵境AI绘图<br>◈配音：暂无<br/>这是一个通渠的废案<br/>',
	'ybsb_077yangqixu':'<font color=cyan>忆-077·似水流年</font><br>◈技能设计：夜白<br>◈代码撰写者：夜白<br>◈插图：暂无<br>◈配音：暂无<br/>这是一个旧版的废案。',
	'ybsb_068qingyue':'<font color=cyan>忆-068·似水流年</font><br>❀技能设计：夜白<br>❀代码撰写者：夜白<br>❀插图：<style type="text/css">#shiroha_bilibili:link, #shiroha_bilibili:visited {color:white;}</style><a id="shiroha_bilibili" href="https://space.bilibili.com/2170177" target="_blank"><span class="YB_http">哔哩哔哩up主鸣濑白羽酱</span></a>群内半成品图片<br>❀配音：暂无<br/>清月伴孤影，落红眷飞鸿。<br/>这是一个旧版的废案。',
	'ybsb_048wushuang':'<font color=cyan>忆-048·似水流年</font><br>❁技能设计：夜白<br>❁代码撰写者：夜白<br>❁插图：派蒙AI绘图<br>❁配音：暂无<br/>这是一个旧版的废案，因为太离谱而改掉。',
	
}