import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export { list }

const list = [
	['spade', 1, 'ybsl_feijingsanjian'],
	['spade', 2, 'ybsl_zhongkai'],
	['spade', 3, 'sha','YB_wind|thunder'],
	['spade', 4, 'shunshou'],
	['spade', 5, 'shuiyanqijunx'],
	['spade', 6, 'sha','thunder|YB_wind'],
	['spade', 7, 'sha','thunder|YB_wind'],
	['spade', 8, 'sha','YB_wind|thunder',['yingbian_fujia','yingbian_add']],
	['spade', 9, 'sha','YB_wind|thunder',['yingbian_fujia','yingbian_add']],
	['spade', 10, 'tiesuo'],
	['spade', 11, 'wuxie'],
	['spade', 12, 'ybsl_frostnova','ice',['yingbian_fujia','yingbian_luLi']],
	['spade', 13, 'ybsl_frostnova','ice',['yingbian_fujia','yingbian_luLi']],

	['heart', 1, 'ybsl_windstorm','YB_wind',['yingbian_fujia','yingbian_luLi']],
	['heart', 2, 'sha','YB_wind'],
	['heart', 3, 'shan'],
	['heart', 4, 'shan'],
	['heart', 5, 'tao'],
	['heart', 6, 'sha','YB_wind'],
	['heart', 7, 'shan'],
	['heart', 8, 'shan'],
	['heart', 9, 'shan'],
	['heart', 10, 'sha','YB_wind'],
	['heart', 11, 'sha','YB_wind'],
	['heart', 12, 'tao'],
	['heart', 13, 'wuxie'],

	['club', 1, 'ybsl_qingfengshan'],
	['club', 2, 'ybsl_zhijizhibi'],
	['club', 3, 'ybsl_zhijizhibi'],
	['club', 4, 'jiu'],
	['club', 5, 'sha','YB_wind|ice'],
	['club', 6, 'tiesuo'],
	['club', 7, 'tiesuo'],
	['club', 8, 'sha','YB_wind|ice'],
	['club', 9, 'sha','YB_wind|ice',['yingbian_zhuzhan','yingbian_add']],
	['club', 10, 'jiu'],
	['club', 11, 'tiesuo'],
	['club', 12, 'tiesuo',null,['yingbian_fujia','yingbian_add']],
	['club', 13, 'tiesuo',null,['yingbian_fujia','yingbian_add']],

	['diamond', 1, 'ybsl_windstorm'],
	['diamond', 2, 'shan'],
	['diamond', 3, 'sha','YB_wind|fire',['yingbian_canqu','yingbian_add']],
	['diamond', 4, 'sha','fire|YB_wind'],
	['diamond', 5, 'ybsl_jinyinrukai'],
	['diamond', 6, 'sha','YB_wind|fire'],
	['diamond', 7, 'shan'],
	['diamond', 8, 'shan'],
	['diamond', 9, 'jiu'],
	['diamond', 10, 'tao'],
	['diamond', 11, 'shan'],
	['diamond', 12, 'sha','YB_wind|fire'],
	['diamond', 13, 'ybsl_jizhiguan'],

	//转换卡
	['spade', 1, 'ybsl_ji'],
	['spade', 2, 'ybsl_yi'],
	['spade', 3, 'ybsl_cai'],
	['spade', 4, 'ybsl_xiang'],
	['spade', 5, 'ybsl_hua'],
	['spade', 6, 'ybsl_ji'],
	['spade', 7, 'ybsl_yi'],
	['spade', 8, 'ybsl_cai'],
	['spade', 9, 'ybsl_xiang'],
	['spade', 10, 'ybsl_hua'],
	['spade', 11, 'ybsl_ji'],
	['spade', 12, 'ybsl_yi'],
	['spade', 13, 'ybsl_cai'],

	['heart', 1, 'ybsl_xiang'],
	['heart', 2, 'ybsl_hua'],
	['heart', 3, 'ybsl_ji'],
	['heart', 4, 'ybsl_yi'],
	['heart', 5, 'ybsl_cai'],
	['heart', 6, 'ybsl_xiang'],
	['heart', 7, 'ybsl_hua'],
	['heart', 8, 'ybsl_ji'],
	['heart', 9, 'ybsl_yi'],
	['heart', 10, 'ybsl_cai'],
	['heart', 11, 'ybsl_xiang'],
	['heart', 12, 'ybsl_hua'],
	['heart', 13, 'ybsl_ji'],

	['club', 1, 'ybsl_yi'],
	['club', 2, 'ybsl_cai'],
	['club', 3, 'ybsl_xiang'],
	['club', 4, 'ybsl_hua'],
	['club', 5, 'ybsl_ji'],
	['club', 6, 'ybsl_yi'],
	['club', 7, 'ybsl_cai'],
	['club', 8, 'ybsl_xiang'],
	['club', 9, 'ybsl_hua'],
	['club', 10, 'ybsl_ji'],
	['club', 11, 'ybsl_yi'],
	['club', 12, 'ybsl_cai'],
	['club', 13, 'ybsl_xiang'],

	['diamond', 1, 'ybsl_hua'],
	['diamond', 2, 'ybsl_ji'],
	['diamond', 3, 'ybsl_yi'],
	['diamond', 4, 'ybsl_cai'],
	['diamond', 5, 'ybsl_xiang'],
	['diamond', 6, 'ybsl_hua'],
	['diamond', 7, 'ybsl_ji'],
	['diamond', 8, 'ybsl_yi'],
	['diamond', 9, 'ybsl_cai'],
	['diamond', 10, 'ybsl_xiang'],
	['diamond', 11, 'ybsl_hua'],
	['diamond', 12, 'ybsl_ji'],
	['diamond', 13, 'ybsl_yi'],
]
