import { lib, game, ui, get, ai, _status } from '../../../../../../noname.js';
export { character };

/** @type { importCharacterConfig['character'] } */
const character = {


	sgsxjxfzmnl_re_xusheng: ['male', 'wu', 4, ['sgsxjxfzmnl_pojun'], ['rankAdd:legend', 'rankS:ap', 'linkTo:re_xusheng', 'YB_mjz:re_xusheng', 'tempname:re_xusheng']],
	sgsxjxfzmnl_sb_huangzhong: ['male', 'shu', 4, ['sgsxjxfzmnl_sbliegong'], ['rankAdd:legend', 'rankS:s', 'linkTo:sb_huangzhong', 'YB_mjz:sb_huangzhong', 'tempname:sb_huangzhong']],
	sgsxjxfzmnl_shen_sunce: ['male', 'shen', '1/6', ['sgsxjxfzmnl_yingba', 'sgsxjxfzmnl_scfuhai', 'pinghe'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_sunce', 'YB_mjz:shen_sunce', 'tempname:shen_sunce', 'wu']],
	sgsxjxfzmnl_sb_xiahoushi: ['female', 'shu', 3, ['sgsxjxfzmnl_sbyanyu', 'sgsxjxfzmnl_sbqiaoshi'], ['rankAdd:legend', 'rankS:s', 'linkTo:sb_xiahoushi', 'YB_mjz:sb_xiahoushi', 'tempname:sb_xiahoushi']],
	sgsxjxfzmnl_mo_diaochan: ['female', 'devil', 3, ['sgsxjxfzmnl_meihuo', 'sgsxjxfzmnl_biyue'], ['rankAdd:rare', 'rankS:am', 'linkTo:diaochan', 'YB_mjz:diaochan', 'tempname:diaochan', 'qun']],
	sgsxjxfzmnl_miheng: ['male', 'qun', 3, ['sgsxjxfzmnl_kuangcai', 'sgsxjxfzmnl_shejian'], ['rankAdd:legend', 'rankS:s', 'linkTo:miheng', 'YB_mjz:miheng', 'tempname:miheng']],
	sgsxjxfzmnl_wangyuanji: ['female', 'wei', 3, ['sgsxjxfzmnl_qianchong', 'sgsxjxfzmnl_shangjian'], ['rankAdd:legend', 'rankS:s', 'linkTo:wangyuanji', 'YB_mjz:wangyuanji', 'tempname:wangyuanji']],
	sgsxjxfzmnl_shen_guojia: ['male', 'shen', 3, ['sgsxjxfzmnl_reshuishi', 'stianyi', 'resghuishi'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_guojia', 'YB_mjz:shen_guojia', 'tempname:shen_guojia', 'wei']],
	sgsxjxfzmnl_wenyang: ['male', 'wei', 4, ['sgsxjxfzmnl_quedi', 'sgsxjxfzmnl_chuifeng', 'sgsxjxfzmnl_chongjian', 'dbchoujue'], ['rankAdd:legend', 'rankS:s', 'linkTo:db_wenyang', 'YB_mjz:db_wenyang', 'tempname:db_wenyang', 'doublegroup:wei:wu']],
	sgsxjxfzmnl_re_jushou: ['male', 'qun', '2/3/3', ['sgsxjxfzmnl_rejianying', 'sgsxjxfzmnl_reshibei'], ['rankAdd:legend', 'rankS:s', 'linkTo:xin_jushou', 'YB_mjz:xin_jushou', 'tempname:xin_jushou']],
	sgsxjxfzmnl_shen_ganning: ['male', 'shen', '3/6', ['sgsxjxfzmnl_drltpoxi', 'sgsxjxfzmnl_drltjieying'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_ganning', 'YB_mjz:shen_ganning', 'tempname:shen_ganning', 'wu']],
	sgsxjxfzmnl_shichangshi: {
		sex: 'male',
		group: 'qun',
		hp: 1,
		skills: ['sgsxjxfzmnl_mbdanggu', 'sgsxjxfzmnl_mbmowang'],
		trashBin: ['sex:male_castrated'],
		names: '张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望',
		linkTo: 'shichangshi',
		YB_mjz: 'shichangshi',
		tempname: ['shichangshi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_scs_zhangrang: ['male', 'qun', 0, ['sgsxjxfzmnl_scstaoluan'], ['unseen', 'sex:male_castrated', 'tempname:scs_zhangrang', 'linkTo:scs_zhangrang', 'name:张|让', 'YB_mjz:scs_zhangrang']],
	sgsxjxfzmnl_scs_zhaozhong: ['male', 'qun', 0, ['sgsxjxfzmnl_scschiyan'], ['unseen', 'sex:male_castrated', 'tempname:scs_zhaozhong', 'linkTo:scs_zhaozhong', 'name:赵|忠', 'YB_mjz:scs_zhaozhong']],
	sgsxjxfzmnl_scs_sunzhang: ['male', 'qun', 0, ['sgsxjxfzmnl_scszimou'], ['unseen', 'sex:male_castrated', 'tempname:scs_sunzhang', 'linkTo:scs_sunzhang', 'name:孙|璋', 'YB_mjz:scs_sunzhang']],
	sgsxjxfzmnl_scs_bilan: ['male', 'qun', 0, ['sgsxjxfzmnl_scspicai'], ['unseen', 'sex:male_castrated', 'tempname:scs_bilan', 'linkTo:scs_bilan', 'name:毕|岚', 'YB_mjz:scs_bilan']],
	sgsxjxfzmnl_scs_xiayun: ['male', 'qun', 0, ['sgsxjxfzmnl_scsyaozhuo'], ['unseen', 'sex:male_castrated', 'tempname:scs_xiayun', 'linkTo:scs_xiayun', 'name:夏|恽', 'YB_mjz:scs_xiayun']],
	sgsxjxfzmnl_scs_hankui: ['male', 'qun', 0, ['sgsxjxfzmnl_scsxiaolu'], ['unseen', 'sex:male_castrated', 'tempname:scs_hankui', 'linkTo:scs_hankui', 'name:韩|悝', 'YB_mjz:scs_hankui']],
	sgsxjxfzmnl_scs_lisong: ['male', 'qun', 0, ['sgsxjxfzmnl_scskuiji'], ['unseen', 'sex:male_castrated', 'tempname:scs_lisong', 'linkTo:scs_lisong', 'name:栗|嵩', 'YB_mjz:scs_lisong']],
	sgsxjxfzmnl_scs_duangui: ['male', 'qun', 0, ['sgsxjxfzmnl_scschihe'], ['unseen', 'sex:male_castrated', 'tempname:scs_duangui', 'linkTo:scs_duangui', 'name:段|珪', 'YB_mjz:scs_duangui']],
	sgsxjxfzmnl_scs_guosheng: ['male', 'qun', 0, ['sgsxjxfzmnl_scsniqu'], ['unseen', 'sex:male_castrated', 'tempname:scs_guosheng', 'linkTo:scs_guosheng', 'name:郭|胜', 'YB_mjz:scs_guosheng']],
	sgsxjxfzmnl_scs_gaowang: ['male', 'qun', 0, ['sgsxjxfzmnl_scsmiaoyu'], ['unseen', 'sex:male_castrated', 'tempname:scs_gaowang', 'linkTo:scs_gaowang', 'name:高|望', 'YB_mjz:scs_gaowang']],

	// sgsxjxfzmnl_shichangshi_dead:{
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 1,
	// 	skills: ["sgsxjxfzmnl_mbdanggu", "sgsxjxfzmnl_mbmowang"],
	// 	trashBin: ["sex:male_castrated"],
	// 	names: "张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望",
	// 	linkTo:'shichangshi',
	// 	rankAdd:'legend',
	// 	rankS:'s',
	// 	isUnseen:true,
	// },
	// sgsxjxfzmnl_scs_zhangrang_dead:['male','qun',0,['sgsxjxfzmnl_scstaoluan'],['unseen','sex:male_castrated','tempname:scs_zhangrang','linkTo:scs_zhangrang','name:张|让']],
	// sgsxjxfzmnl_scs_zhaozhong_dead:['male','qun',0,['sgsxjxfzmnl_scschiyan'],['unseen','sex:male_castrated','tempname:scs_zhaozhong','linkTo:scs_zhaozhong','name:赵|忠']],
	// sgsxjxfzmnl_scs_sunzhang_dead:['male','qun',0,['sgsxjxfzmnl_scszimou'],['unseen','sex:male_castrated','tempname:scs_sunzhang','linkTo:scs_sunzhang','name:孙|璋']],
	// sgsxjxfzmnl_scs_bilan_dead:['male','qun',0,['sgsxjxfzmnl_scspicai'],['unseen','sex:male_castrated','tempname:scs_bilan','linkTo:scs_bilan','name:毕|岚']],
	// sgsxjxfzmnl_scs_xiayun_dead:['male','qun',0,['sgsxjxfzmnl_scsyaozhuo'],['unseen','sex:male_castrated','tempname:scs_xiayun','linkTo:scs_xiayun','name:夏|恽']],
	// sgsxjxfzmnl_scs_hankui_dead:['male','qun',0,['sgsxjxfzmnl_scsxiaolu'],['unseen','sex:male_castrated','tempname:scs_hankui','linkTo:scs_hankui','name:韩|悝']],
	// sgsxjxfzmnl_scs_lisong_dead:['male','qun',0,['sgsxjxfzmnl_scskuiji'],['unseen','sex:male_castrated','tempname:scs_lisong','linkTo:scs_lisong','name:栗|嵩']],
	// sgsxjxfzmnl_scs_duangui_dead:['male','qun',0,['sgsxjxfzmnl_scschihe'],['unseen','sex:male_castrated','tempname:scs_duangui','linkTo:scs_duangui','name:段|珪']],
	// sgsxjxfzmnl_scs_guosheng_dead:['male','qun',0,['sgsxjxfzmnl_scsniqu'],['unseen','sex:male_castrated','tempname:scs_guosheng','linkTo:scs_guosheng','name:郭|胜']],
	// sgsxjxfzmnl_scs_gaowang_dead:['male','qun',0,['sgsxjxfzmnl_scsmiaoyu'],['unseen','sex:male_castrated','tempname:scs_gaowang','linkTo:scs_gaowang','name:高|望']],

	sgsxjxfzmnl_yue_caiwenji: ['female', 'qun', 3, ['sgsxjxfzmnl_dcshuangjia', 'sgsxjxfzmnl_dcbeifen'], ['rankAdd:legend', 'rankS:s', 'linkTo:yue_caiwenji', 'YB_mjz:yue_caiwenji', 'tempname:yue_caiwenji', 'name:蔡|琰']],
	sgsxjxfzmnl_liuyan: ['male', 'qun', 3, ['sgsxjxfzmnl_tushe', 'sgsxjxfzmnl_limu'], ['rankAdd:legend', 'rankS:s', 'linkTo:liuyan', 'YB_mjz:liuyan', 'tempname:liuyan']],
	sgsxjxfzmnl_shen_xunyu: ['male', 'shen', 3, ['sgsxjxfzmnl_tianzuo', 'sgsxjxfzmnl_lingce', 'sgsxjxfzmnl_dinghan'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_xunyu', 'YB_mjz:shen_xunyu', 'tempname:shen_xunyu', 'wei', 'clan:颍川荀氏']],
	sgsxjxfzmnl_shen_zhangfei: ['male', 'shen', 4, ['sgsxjxfzmnl_shencai', 'sgsxjxfzmnl_xunshi'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_zhangfei', 'YB_mjz:shen_zhangfei', 'tempname:shen_zhangfei', 'shu']],
	sgsxjxfzmnl_wu_zhugeliang: ['male', 'shu', '4/7', ['sgsxjxfzmnl_dcjincui', 'sgsxjxfzmnl_dcqingshi', 'sgsxjxfzmnl_dczhizhe'], ['rankAdd:legend', 'rankS:s', 'linkTo:wu_zhugeliang', 'YB_mjz:wu_zhugeliang', 'tempname:wu_zhugeliang', 'name:诸葛|亮']],
	sgsxjxfzmnl_sb_caopi: ['male', 'wei', 3, ['sgsxjxfzmnl_sbxingshang', 'sgsxjxfzmnl_sbfangzhu', 'sgsxjxfzmnl_sbsongwei'], ['rankAdd:legend', 'rankS:s', 'linkTo:sb_caopi', 'YB_mjz:sb_caopi', 'tempname:sb_caopi', 'zhu']],
	sgsxjxfzmnl_boss_zhaoyun: ['male', 'shen', 1, ['sgsxjxfzmnl_boss_juejing', 'sgsxjxfzmnl_xinlonghun', 'sgsxjxfzmnl_zhanjiang'], ['rankAdd:legend', 'rankS:s', 'linkTo:boss_zhaoyun', 'YB_mjz:boss_zhaoyun', 'tempname:boss_zhaoyun', 'shu']],
	sgsxjxfzmnl_nanhualaoxian: ['male', 'qun', 3, ['sgsxjxfzmnl_yufeng', 'sgsxjxfzmnl_tianshu'], ['rankAdd:legend', 'rankS:s', 'linkTo:nanhualaoxian', 'YB_mjz:nanhualaoxian', 'tempname:nanhualaoxian', 'name:庄|周']],
	sgsxjxfzmnl_mo_lvbu: ['male', 'devil', 6, ['mashu', 'sgsxjxfzmnl_jielve', 'sgsxjxfzmnl_zhenhuo', 'sgsxjxfzmnl_wuqian', 'wushuang'], ['rankAdd:rare', 'rankS:am', 'linkTo:lvbu', 'YB_mjz:lvbu', 'tempname:lvbu', 'qun']],
	sgsxjxfzmnl_zhangxuan: ['female', 'wu', 4, ['sgsxjxfzmnl_tongli', 'sgsxjxfzmnl_shezang'], ['rankAdd:legend', 'rankS:s', 'linkTo:zhangxuan', 'YB_mjz:zhangxuan', 'tempname:zhangxuan']],
	sgsxjxfzmnl_caojinyu: ['female', 'wei', 3, ['sgsxjxfzmnl_yuqi', 'sgsxjxfzmnl_shanshen', 'sgsxjxfzmnl_xianjing'], ['rankAdd:legend', 'rankS:s', 'linkTo:caojinyu', 'YB_mjz:caojinyu', 'tempname:caojinyu']],
	sgsxjxfzmnl_shen_machao: ['male', 'shen', 4, ['sgsxjxfzmnl_shouli', 'sgsxjxfzmnl_hengwu'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_machao', 'YB_mjz:shen_machao', 'tempname:shen_machao', 'shu']],
	sgsxjxfzmnl_sunhanhua: ['female', 'wu', 3, ['sgsxjxfzmnl_chongxu', 'sgsxjxfzmnl_miaojian', 'sgsxjxfzmnl_shhlianhua'], ['rankAdd:legend', 'rankS:s', 'linkTo:sunhanhua', 'YB_mjz:sunhanhua', 'tempname:sunhanhua']],
	sgsxjxfzmnl_xin_guozhao: {
		sex: 'female',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_yichong', 'sgsxjxfzmnl_wufei'],
		YB_mjz: 'xin_guozhao',
		linkTo: 'xin_guozhao',
		tempname: ['xin_guozhao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_sb_guanyu: {
		sex: 'male',
		group: 'shu',
		hp: 4,
		skills: ['sgsxjxfzmnl_sbwusheng', 'sgsxjxfzmnl_sbyijue'],
		YB_mjz: 'sb_guanyu',
		linkTo: 'sb_guanyu',
		tempname: ['sb_guanyu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_sb_huanggai: {
		sex: 'male',
		group: 'wu',
		hp: 4,
		skills: ['sgsxjxfzmnl_sbkurou', 'sgsxjxfzmnl_sbzhaxiang'],
		YB_mjz: 'sb_huanggai',
		linkTo: 'sb_huanggai',
		tempname: ['sb_huanggai'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_zhouxuān: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcwumei', 'sgsxjxfzmnl_dczhanmeng'],
		YB_mjz: 'dc_zhouxuān',
		linkTo: 'dc_zhouxuān',
		tempname: ['dc_zhouxuān'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_sunlingluan: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['sgsxjxfzmnl_dclingyue', 'sgsxjxfzmnl_dcpandi'],
		YB_mjz: 'sunlingluan',
		linkTo: 'sunlingluan',
		tempname: ['sunlingluan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_xushao: {
		sex: 'male',
		group: 'qun',
		hp: 4,
		skills: ['sgsxjxfzmnl_pingjian'],
		YB_mjz: 'xushao',
		linkTo: 'xushao',
		tempname: ['xushao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_sp_huaman: {
		sex: 'female',
		group: 'shu',
		hp: 4,
		skills: ['sgsxjxfzmnl_spxiangzhen', 'sgsxjxfzmnl_spfangzong', 'sgsxjxfzmnl_spxizhan'],
		names: '孟|null',
		YB_mjz: 'sp_huaman',
		linkTo: 'sp_huaman',
		tempname: ['sp_huaman'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_quyi: {
		sex: 'male',
		group: 'qun',
		hp: 4,
		skills: ['sgsxjxfzmnl_fuqi', 'sgsxjxfzmnl_jiaozi'],
		YB_mjz: 'quyi',
		linkTo: 'quyi',
		tempname: ['quyi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_shen_jiangwei: {
		sex: 'male',
		group: 'shen',
		hp: 4,
		skills: ['sgsxjxfzmnl_tianren', 'sgsxjxfzmnl_jiufa', 'sgsxjxfzmnl_pingxiang'],
		groupInGuozhan: 'shu',
		YB_mjz: 'shen_jiangwei',
		linkTo: 'shen_jiangwei',
		tempname: ['shen_jiangwei'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_liuye: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcpoyuan', 'sgsxjxfzmnl_dchuace'],
		YB_mjz: 'dc_liuye',
		linkTo: 'dc_liuye',
		tempname: ['dc_liuye'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_peixiu: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['xingtu', 'sgsxjxfzmnl_juezhi'],
		groupBorder: 'jin',
		YB_mjz: 'peixiu',
		linkTo: 'peixiu',
		tempname: ['peixiu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_wu_luxun: {
		sex: 'male',
		group: 'wu',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcxiongmu', 'dczhangcai', 'sgsxjxfzmnl_dcruxian'],
		clans: ['吴郡陆氏'],
		YB_mjz: 'wu_luxun',
		linkTo: 'wu_luxun',
		tempname: ['wu_luxun'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mb_caomao: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_mbqianlong', 'sgsxjxfzmnl_mbweitong'],
		isZhugong: true,
		YB_mjz: 'mb_caomao',
		linkTo: 'mb_caomao',
		tempname: ['mb_caomao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_puyuan: {
		sex: 'male',
		group: 'shu',
		hp: 4,
		skills: ['sgsxjxfzmnl_pytianjiang', 'sgsxjxfzmnl_pyzhuren'],
		YB_mjz: 'puyuan',
		linkTo: 'puyuan',
		tempname: ['puyuan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_shen_huatuo: {
		sex: 'male',
		group: 'shen',
		hp: 3,
		skills: ['sgsxjxfzmnl_jingyu', 'sgsxjxfzmnl_lvxin', 'sgsxjxfzmnl_huandao'],
		groupInGuozhan: 'qun',
		YB_mjz: 'dc_shen_huatuo',
		linkTo: 'dc_shen_huatuo',
		tempname: ['dc_shen_huatuo'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_xujing: {
		sex: 'male',
		group: 'shu',
		hp: 3,
		skills: ['dcshangyu', 'sgsxjxfzmnl_dccaixia'],
		YB_mjz: 'dc_xujing',
		linkTo: 'dc_xujing',
		tempname: ['dc_xujing'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_shen_zhangjiao: ['male', 'shen', 3, ['sgsxjxfzmnl_yizhao', 'sgsxjxfzmnl_sijun', 'sgsxjxfzmnl_sanshou', 'sgsxjxfzmnl_tianjie'], ['rankAdd:legend', 'rankS:s', 'linkTo:shen_zhangjiao', 'YB_mjz:shen_zhangjiao', 'qun']],
	sgsxjxfzmnl_xizhicai: ['male', 'wei', 3, ['sgsxjxfzmnl_xianfu', 'tiandu', 'sgsxjxfzmnl_chouce'], ['rankAdd:legend', 'rankS:ap', 'linkTo:xizhicai', 'YB_mjz:xizhicai', 'tempname:xizhicai']],
	sgsxjxfzmnl_sb_sp_zhugeliang: {
		sex: 'male',
		group: 'shu',
		hp: 3,
		skills: ['sgsxjxfzmnl_sbhuoji', 'sgsxjxfzmnl_sbkanpo'],
		names: '诸葛|亮',
		YB_mjz: 'sb_sp_zhugeliang',
		linkTo: 'sb_sp_zhugeliang',
		tempname: ['sb_sp_zhugeliang'],
		rankAdd: 'legend',
		rankS: 's',
	},

	sgsxjxfzmnl_dc_qinghegongzhu: {
		sex: 'female',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_dczhangji', 'sgsxjxfzmnl_dczengou'],
		names: '曹|null',
		YB_mjz: 'dc_qinghegongzhu',
		linkTo: 'dc_qinghegongzhu',
		tempname: ['dc_qinghegongzhu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_bianxi: {
		sex: 'male',
		group: 'wei',
		hp: 4,
		skills: ['sgsxjxfzmnl_dunxi'],
		YB_mjz: 'bianxi',
		linkTo: 'bianxi',
		tempname: ['bianxi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_shen_sunquan: {
		sex: 'male',
		group: 'shen',
		hp: 4,
		skills: ['sgsxjxfzmnl_junkyuheng', 'sgsxjxfzmnl_junkdili'],
		groupInGuozhan: 'wu',
		YB_mjz: 'shen_sunquan',
		linkTo: 'shen_sunquan',
		tempname: ['shen_sunquan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_panshu: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['sgsxjxfzmnl_weiyi', 'sgsxjxfzmnl_jinzhi'],
		YB_mjz: 'panshu',
		linkTo: 'panshu',
		tempname: ['panshu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_haozhao: {
		sex: 'male',
		group: 'wei',
		hp: 4,
		skills: ['sgsxjxfzmnl_drlt_zhengu'],
		YB_mjz: 'haozhao',
		linkTo: 'haozhao',
		tempname: ['haozhao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mo_caopi: {
		sex: 'male',
		group: 'devil',
		hp: 3,
		skills: ['xingshang', 'fangzhu', 'songwei', 'sgsxjxfzmnl_cpcuandi'],
		isZhugong: true,
		YB_mjz: 'caopi',
		linkTo: 'caopi',
		tempname: ['caopi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_fuqian: {
		sex: 'male',
		group: 'shu',
		hp: 4,
		skills: ['sgsxjxfzmnl_jueyong', 'sgsxjxfzmnl_poxiang'],
		YB_mjz: 'fuqian',
		linkTo: 'fuqian',
		tempname: ['fuqian'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_sb_caoren: {
		sex: 'male',
		group: 'wei',
		hp: 4,
		maxHp: 4,
		hujia: 2,
		skills: ['sgsxjxfzmnl_sbjushou', 'sgsxjxfzmnl_sbjiewei'],
		YB_mjz: 'sb_caoren',
		linkTo: 'sb_caoren',
		tempname: ['sb_caoren'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_yue_miheng: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcjigu', 'sgsxjxfzmnl_dcsirui'],
		YB_mjz: 'yue_miheng',
		linkTo: 'yue_miheng',
		tempname: ['yue_miheng'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_zhujianping: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcxiangmian', 'sgsxjxfzmnl_dctianji'],
		YB_mjz: 'zhujianping',
		linkTo: 'zhujianping',
		tempname: ['zhujianping'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_shen_huangzhong: {
		sex: 'male',
		group: 'shen',
		hp: 4,
		skills: ['sgsxjxfzmnl_new_dclieqiong', 'sgsxjxfzmnl_dczhanjue'],
		groupInGuozhan: 'shu',
		YB_mjz: 'shen_huangzhong',
		linkTo: 'shen_huangzhong',
		tempname: ['shen_huangzhong'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_tengfanglan: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcluochong', 'sgsxjxfzmnl_dcaichen'],
		YB_mjz: 'dc_tengfanglan',
		linkTo: 'dc_tengfanglan',
		tempname: ['dc_tengfanglan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_sb_diaochan: {
		sex: 'female',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_sblijian', 'sgsxjxfzmnl_sbbiyue'],
		names: 'null|null',
		YB_mjz: 'sb_diaochan',
		linkTo: 'sb_diaochan',
		tempname: ['sb_diaochan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_re_zuoci: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_rehuashen', 'sgsxjxfzmnl_rexinsheng'],
		YB_mjz: 're_zuoci',
		linkTo: 're_zuoci',
		tempname: ['re_zuoci'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_chengui: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcyingtu', 'sgsxjxfzmnl_dccongshi'],
		YB_mjz: 'chengui',
		linkTo: 'chengui',
		tempname: ['chengui'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_sunru: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['sgsxjxfzmnl_xiecui', 'sgsxjxfzmnl_youxu'],
		YB_mjz: 'dc_sunru',
		linkTo: 'dc_sunru',
		tempname: ['dc_sunru'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_yue_xiaoqiao: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcqiqin', 'sgsxjxfzmnl_dcweiwan'],
		names: '桥|null',
		YB_mjz: 'yue_xiaoqiao',
		linkTo: 'yue_xiaoqiao',
		tempname: ['yue_xiaoqiao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_sb_simayi: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcsbquanmou', 'sgsxjxfzmnl_dcsbpingliao'],
		names: '司马|懿',
		YB_mjz: 'dc_sb_simayi',
		linkTo: 'dc_sb_simayi',
		tempname: ['dc_sb_simayi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mb_zhangfen: {
		sex: 'male',
		group: 'wu',
		hp: 4,
		skills: ['sgsxjxfzmnl_mbquchong', 'sgsxjxfzmnl_mbxunjie'],
		YB_mjz: 'mb_zhangfen',
		linkTo: 'mb_zhangfen',
		tempname: ['mb_zhangfen'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_liuzan: {
		sex: 'male',
		group: 'wu',
		hp: 4,
		skills: ['sgsxjxfzmnl_fenyin'],
		YB_mjz: 'liuzan',
		linkTo: 'liuzan',
		tempname: ['liuzan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_xurong: {
		sex: 'male',
		group: 'qun',
		hp: 4,
		skills: ['sgsxjxfzmnl_xinfu_xionghuo', 'sgsxjxfzmnl_xinfu_shajue'],
		YB_mjz: 'xurong',
		linkTo: 'xurong',
		tempname: ['xurong'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_sb_huanggai: {
		sex: 'male',
		group: 'wu',
		hp: 4,
		skills: ['sgsxjxfzmnl_dcsblieji', 'sgsxjxfzmnl_dcsbquzhou'],
		YB_mjz: 'dc_sb_huanggai',
		linkTo: 'dc_sb_huanggai',
		tempname: ['dc_sb_huanggai'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_yuanyin: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcmoshou', 'dcyunjiu'],
		YB_mjz: 'yuanyin',
		linkTo: 'yuanyin',
		tempname: ['yuanyin'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_v_zhangliao: {
		sex: 'male',
		group: 'qun',
		hp: 4,
		skills: ['sgsxjxfzmnl_dcyuxi', 'sgsxjxfzmnl_dcporong'],
		YB_mjz: 'v_zhangliao',
		linkTo: 'v_zhangliao',
		tempname: ['v_zhangliao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_ol_nanhualaoxian: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_olqingshu', 'sgsxjxfzmnl_olshoushu', 'sgsxjxfzmnl_olhedao'],
		names: '庄|周',
		YB_mjz: 'ol_nanhualaoxian',
		linkTo: 'ol_nanhualaoxian',
		tempname: ['ol_nanhualaoxian'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mo_guanyu: {
		sex: 'male',
		group: 'devil',
		hp: 5,
		skills: ['sgsxjxfzmnl_mo_yijue', 'sgsxjxfzmnl_mo_boming', 'sgsxjxfzmnl_mo_fuchou'],
		// YB_mjz: 'jsp_guanyu',
		linkTo: 'guanyu',
		tempname: ['guanyu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mo_re_diaochan: {
		sex: 'female',
		group: 'devil',
		hp: 3,
		skills: ['sgsxjxfzmnl_meihuo', 'sgsxjxfzmnl_biyue', 'sgsxjxfzmnl_yaoyan'],
		YB_mjz: 're_diaochan',
		linkTo: 're_diaochan',
		tempname: ['re_diaochan'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mo_zhangfei: {
		sex: 'male',
		group: 'devil',
		hp: 4,
		skills: ['sgsxjxfzmnl_new_repaoxiao', 'sgsxjxfzmnl_liyong'],
		YB_mjz: 'zhangfei',
		linkTo: 'zhangfei',
		tempname: ['zhangfei'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_sb_zhouyu: {
		sex: 'male',
		group: 'wu',
		hp: 4,
		skills: ['sgsxjxfzmnl_dcsbronghuo', 'sgsxjxfzmnl_dcsbyingmou'],
		YB_mjz: 'dc_sb_zhouyu',
		linkTo: 'dc_sb_zhouyu',
		tempname: ['dc_sb_zhouyu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_dc_simashi: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_dcsanshi', 'sgsxjxfzmnl_dczhenrao', 'sgsxjxfzmnl_dcchenlve'],
		names: '司马|师',
		groupBorder: 'jin',
		YB_mjz: 'dc_simashi',
		linkTo: 'dc_simashi',
		tempname: ['dc_simashi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_xuelingyun: {
		sex: 'female',
		group: 'wei',
		hp: 3,
		skills: ['dcxialei', 'sgsxjxfzmnl_dcanzhi'],
		YB_mjz: 'xuelingyun',
		linkTo: 'xuelingyun',
		tempname: ['xuelingyun'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_yangbiao: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_zhaohan', 'rangjie', 'sgsxjxfzmnl_yizheng'],
		clans: ['弘农杨氏'],
		YB_mjz: 'yangbiao',
		linkTo: 'yangbiao',
		tempname: ['yangbiao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mb_simazhao: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['sgsxjxfzmnl_mbxiezheng', 'mbqiantun', 'sgsxjxfzmnl_mbweisi', 'sgsxjxfzmnl_mbzhaoxiong'],
		names: '司马|昭',
		groupBorder: 'jin',
		YB_mjz: 'jsrg_simazhao',
		linkTo: 'jsrg_simazhao',
		tempname: ['mb_simazhao'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_caoying: {
		sex: 'female',
		group: 'wei',
		hp: 4,
		skills: ['sgsxjxfzmnl_xinfu_lingren', 'sgsxjxfzmnl_fujian'],
		YB_mjz: 'caoying',
		linkTo: 'caoying',
		tempname: ['caoying'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mo_jiaxu: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['sgsxjxfzmnl_luanwu', 'sgsxjxfzmnl_wansha', 'sgsxjxfzmnl_weimu'],
		YB_mjz: 'jiaxu',
		linkTo: 'jiaxu',
		tempname: ['jiaxu'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mo_guosi: {
		sex: 'male',
		group: 'qun',
		hp: 4,
		skills: ['sgsxjxfzmnl_gzxiongsuan', 'sgsxjxfzmnl_xinfu_sidao'],
		YB_mjz: 'guosi',
		linkTo: 'guosi',
		tempname: ['guosi'],
		rankAdd: 'legend',
		rankS: 's',
	},
	sgsxjxfzmnl_mo_zhangji: {
		sex: 'male',
		group: 'qun',
		hp: 4,
		skills: ['sgsxjxfzmnl_xinfu_lveming', 'xinfu_tunjun'],
		YB_mjz: 'zhangji',
		linkTo: 'zhangji',
		tempname: ['zhangji'],
		rankAdd: 'legend',
		rankS: 's',
	},
};
