import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export { YBSL_destiny }
/**
 * 校花梦工厂缘分搭配
 */
const YBSL_destiny = function(){
	{//校花梦工厂缘分搭配
		lib.translate.xh_shisu='世俗界'
		lib.translate.xh_linyi='林逸'
		lib.translate.xh_chumengyao='楚梦瑶'
		lib.translate.xh_tangyun='唐韵'
		lib.translate.xh_yangming='杨明'
		lib.translate.xh_luanxiaoru='栾小茹'
		lib.translate.xh_turanran='土冉冉'
		lib.translate.xh_fengxiaoxiao='冯笑笑'
		lib.translate.xh_yuning='雨凝'
		lib.translate.xh_guanxin='关馨'
		lib.translate.xh_yingziyu='应子鱼'
		lib.translate.xh_jiaoyazi='焦牙子'
		lib.translate.xh_yangqiqi='杨七七'
		lib.translate.xh_chenyushu='陈雨舒'
		lib.translate.xh_songlingshan='宋凌珊'
		lib.translate.xh_xushihan='许诗涵'
		lib.translate.xh_yuxiaoke='郁小可'
		lib.translate.xh_sunjingyi='孙静怡'
		lib.translate.xh_zhongpinliang='钟品亮'
		lib.translate.xh_zhangnaipao='张乃炮'
		lib.translate.xh_xueli='雪梨'
		lib.translate.xh_ergoudan='二狗蛋'
		lib.translate.xh_anjianwen='安建文'
		lib.translate.xh_bingtang='冰糖'
	
	
		lib.translate.xh_tianjie='天阶岛'
		lib.translate.xh_zhangliju='章力钜'
		lib.translate.xh_shangguanlaner='上官岚儿'
		lib.translate.xh_wangxinyan='王心妍'
		lib.translate.xh_duanmuyu='端木玉'
		lib.translate.xh_lengleng='冷冷'
		lib.translate.xh_hanjingjing='韩静静'
		lib.translate.xh_ningxuefei='宁雪菲'
		lib.translate.xh_tianchan='天婵'
		lib.translate.xh_donghaishenni='东海神尼'
		lib.translate.xh_huangxiaotao='黄小桃'
		lib.translate.xh_ningshangling='宁尚菱'
		lib.translate.xh_gongyangjie='公羊杰'
		lib.translate.xh_shangguantianhua='上官天华'
		lib.translate.xh_guidongxi='鬼东西'
		lib.translate.xh_huoyudie='霍雨蝶'
		lib.translate.xh_nicaiyue='倪彩月'
		lib.translate.xh_chenxi='陈曦'
		lib.translate.xh_xishanlaozong='西山老宗'
		lib.translate.xh_kangzhaoming='康照明'
		lib.translate.xh_chengyiyi='程依依'
		lib.translate.xh_xulingchong='徐灵冲'
		lib.translate.xh_xinrenqinglong='新任青龙'
		lib.translate.xh_liuziyu='柳子玉'
		_status.xhmgcCharacter={
			xh_linyi:['male','qun',4,[],[]],
			xh_chumengyao:['female','qun',4,[],[]],
			xh_tangyun:['female','qun',4,[],[]],
			xh_yangming:['male','qun',4,[],[]],
			xh_luanxiaoru:['female','qun',4,[],[]],
			xh_turanran:['female','qun',4,[],[]],
			xh_fengxiaoxiao:['female','qun',4,[],[]],
			xh_yuning:['female','qun',4,[],[]],
			xh_guanxin:['female','qun',4,[],[]],
			xh_yingziyu:['female','qun',4,[],[]],
			xh_jiaoyazi:['male','qun',4,[],[]],
			xh_yangqiqi:['female','qun',4,[],[]],
			xh_chenyushu:['female','qun',4,[],[]],
			xh_songlingshan:['female','qun',4,[],[]],
			xh_xushihan:['female','qun',4,[],[]],
			xh_yuxiaoke:['female','qun',4,[],[]],
			xh_sunjingyi:['female','qun',4,[],[]],
			xh_zhongpinliang:['male','qun',4,[],[]],
			xh_zhangnaipao:['male','qun',4,[],[]],
			xh_xueli:['female','qun',4,[],[]],
			xh_ergoudan:['male','qun',4,[],[]],
			xh_anjianwen:['male','qun',4,[],[]],
			xh_bingtang:['female','qun',4,[],[]],

			xh_zhangliju:['male','qun',4,[],[]],
			xh_shangguanlaner:['female','qun',4,[],[]],
			xh_wangxinyan:['female','qun',4,[],[]],
			xh_duanmuyu:['female','qun',4,[],[]],
			xh_lengleng:['female','qun',4,[],[]],
			xh_hanjingjing:['female','qun',4,[],[]],
			xh_ningxuefei:['female','qun',4,[],[]],
			xh_tianchan:['female','qun',4,[],[]],
			xh_donghaishenni:['female','qun',4,[],[]],
			xh_huangxiaotao:['female','qun',4,[],[]],
			xh_ningshangling:['female','qun',4,[],[]],
			xh_gongyangjie:['male','qun',4,[],[]],
			xh_shangguantianhua:['male','qun',4,[],[]],
			xh_guidongxi:['male','qun',4,[],[]],
			xh_huoyudie:['female','qun',4,[],[]],
			xh_nicaiyue:['female','qun',4,[],[]],
			xh_chenxi:['female','qun',4,[],[]],
			xh_xishanlaozong:['male','qun',4,[],[]],
			xh_kangzhaoming:['male','qun',4,[],[]],
			xh_chengyiyi:['female','qun',4,[],[]],
			xh_xulingchong:['male','qun',4,[],[]],
			xh_xinrenqinglong:['male','qun',4,[],[]],
			xh_liuziyu:['female','qun',4,[],[]],
		}
		for(var i in _status.xhmgcCharacter){
			lib.character[i]=_status.xhmgcCharacter[i];
		}
		lib.YB_chooseYuanfen = {
			xh_linyi:{
				huhuashizhe:{
					name:'护花使者',
					order:22,
					list:['xh_chumengyao'],
				},
				danshenchuancheng:{
					name:'丹神传承',
					order:21,
					list:['xh_zhangliju'],
				},
				qingshenyizhong:{
					name:'情深意重',
					order:53,
					list:['xh_turanran','xh_fengxiaoxiao','xh_yuning','xh_yuxiaoke'],
				},
				shashouzhiwang:{
					name:'杀手之王',
					order:32,
					list:['xh_yangming'],
				},
			},
			xh_chumengyao:{
				huhuashizhe:{
					name:'护花使者',
					order:29,
					list:['xh_linyi'],
				},
				jueseshuangshu:{
					name:'绝色双姝',
					order:31,
					list:['xh_chenyushu'],
				},
				qinglituosu:{
					name:'清丽脱俗',
					order:32,
					list:['xh_tangyun','xh_sunjingyi'],
				},
				zhengxiezhidao:{
					name:'正邪之道',
					order:40,
					list:['xh_yangming','xh_luanxiaoru'],
				},
			},
			xh_tangyun:{
				chiqingyuxin:{
					name:'痴情于心',
					order:21,
					list:['xh_guanxin'],
				},
				pingminxiaohua:{
					name:'平民校花',
					order:22,
					list:['xh_yingziyu'],
				},
				qinglituosu:{
					name:'清丽脱俗',
					order:29,
					list:['xh_chumengyao','xh_sunjingyi'],
				},
				gangrouzhifen:{
					name:'刚柔之分',
					order:32,
					list:['xh_yangming'],
				},
			},
			xh_yangming:{
				shashouzhiwang:{
					name:'杀手之王',
					order:22,
					list:['xh_linyi'],
				},
				gangrouzhifen:{
					name:'刚柔之分',
					order:21,
					list:['xh_tangyun'],
				},
				yinyizhike:{
					name:'隐逸之客',
					order:27,
					list:['xh_luanxiaoru'],
				},
				linglongjiaofeng:{
					name:'灵龙姣凤',
					order:48,
					list:['xh_linyi','xh_chumengyao','xh_tangyun'],
				},
			},
			xh_luanxiaoru:{
				fengwuhuangyin:{
					name:'凤舞凰音',
					order:21,
					list:['xh_chumengyao'],
				},
				xingqingjiongyi:{
					name:'性情迥异',
					order:24,
					list:['xh_turanran','xh_fengxiaoxiao'],
				},
				yinyizhike:{
					name:'隐逸之客',
					order:28,
					list:['xh_yangming'],
				},
				shisutianjiao:{
					name:'世俗天骄',
					order:48,
					list:['xh_linyi','xh_chumengyao','xh_tangyun'],
				},
			},
			xh_turanran:{
				tongbingxianglian:{
					name:'同病相怜',
					order:20,
					list:['xh_fengxiaoxiao'],
				},
				xianneizhizhu:{
					name:'贤内之助',
					order:21,
					list:['xh_songlingshan'],
				},
				qingshenyizhong:{
					name:'情深意重',
					order:53,
					list:['xh_linyi','xh_fengxiaoxiao','xh_yuning','xh_yuxiaoke'],
				},
			},
			xh_fengxiaoxiao:{
				tongbingxianglian:{
					name:'同病相怜',
					order:21,
					list:['xh_turanran'],
				},
				jinglingguguai:{
					name:'精灵古怪',
					order:20,
					list:['xh_jiaoyazi'],
				},
				qingshenyizhong:{
					name:'情深意重',
					order:53,
					list:['xh_linyi','xh_turanran','xh_yuning','xh_yuxiaoke'],
				},
			},
			xh_yuning:{
				jiaoqielinglian:{
					name:'娇怯令怜',
					order:21,
					list:['xh_guanxin'],
				},
				shuiyuexingguang:{
					name:'水月星光',
					order:20,
					list:['xh_xushihan'],
				},
				qingshenyizhong:{
					name:'情深意重',
					order:53,
					list:['xh_linyi','xh_turanran','xh_fengxiaoxiao','xh_yuxiaoke'],
				},
			},
			xh_guanxin:{
				jiaoqielinglian:{
					name:'娇怯令怜',
					order:20,
					list:['xh_yuning'],
				},
				aomeixiuhe:{
					name:'傲梅羞荷',
					order:21,
					list:['xh_yangqiqi'],
				},
				chiqingyuxin:{
					name:'痴情于心',
					order:26,
					list:['xh_tangyun'],
				},
			},
			xh_yingziyu:{
				xiaoyuanyiba:{
					name:'校园一霸',
					order:20,
					list:['xh_zhongpinliang'],
				},
				pingminxiaohua:{
					name:'平民校花',
					order:22,
					list:['xh_tangyun'],
				},
				xinyouqianban:{
					name:'心有牵绊',
					order:27,
					list:['xh_jiaoyazi','xh_yangqiqi'],
				},
			},
			xh_jiaoyazi:{
				shourensuotuo:{
					name:'受人所托',
					order:19,
					list:['xh_zhangnaipao'],
				},
				jinglingguguai:{
					name:'精灵古怪',
					order:20,
					list:['xh_fengxiaoxiao'],
				},
				xinyouqianban:{
					name:'心有牵绊',
					order:28,
					list:['xh_yingziyu','xh_yangqiqi'],
				},
			},
			xh_yangqiqi:{
				linghanaoxue:{
					name:'凌寒傲雪',
					order:26,
					list:['xh_xueli'],
				},
				aomeixiuhe:{
					name:'傲梅羞荷',
					order:29,
					list:['xh_guanxin'],
				},
				xinyouqianban:{
					name:'心有牵绊',
					order:31,
					list:['xh_yingziyu','xh_jiaoyazi'],
				},
			},
			xh_chenyushu:{
				yihanyixia:{
					name:'一憨一黠',
					order:20,
					list:['xh_ergoudan'],
				},
				jueseshuangshu:{
					name:'绝色双姝',
					order:20,
					list:['xh_chumengyao'],
				},
				yejiezhihua:{
					name:'业界之花',
					order:27,
					list:['xh_songlingshan','xh_xushihan'],
				},
			},
			xh_songlingshan:{
				mingzhengandou:{
					name:'明争暗斗',
					order:20,
					list:['xh_anjianwen'],
				},
				xianneizhizhu:{
					name:'贤内之助',
					order:20,
					list:['xh_turanran'],
				},
				yejiezhihua:{
					name:'业界之花',
					order:27,
					list:['xh_chenyushu','xh_xushihan'],
				},
			},
			xh_xushihan:{
				shuiyuexingguang:{
					name:'水月星光',
					order:27,
					list:['xh_yuning'],
				},
				shenshikanke:{
					name:'身世坎坷',
					order:28,
					list:['xh_bingtang'],
				},
				yejiezhihua:{
					name:'业界之花',
					order:31,
					list:['xh_chenyushu','xh_songlingshan'],
				},
			},
			xh_yuxiaoke:{
				pangmenzuodao:{
					name:'旁门左道',
					order:15,
					list:['xh_zhongpinliang'],
				},
				yumenzhiyou:{
					name:'郁闷之友',
					order:16,
					list:['xh_xulingchong'],
				},
				qingshenyizhong:{
					name:'情深意重',
					order:53,
					list:['xh_linyi','xh_turanran','xh_fengxiaoxiao','xh_yuning'],
				},
			},
			xh_sunjingyi:{
				kujinganlai:{
					name:'苦尽甘来',
					order:15,
					list:['xh_xueli'],
				},
				bingqingyujie:{
					name:'冰清玉洁',
					order:16,
					list:['xh_bingtang'],
				},
				qinglituosu:{
					name:'清丽脱俗',
					order:23,
					list:['xh_chumengyao','xh_tangyun'],
				},
			},
			xh_zhongpinliang:{
				xiaoyuanyiba:{
					name:'校园一霸',
					order:17,
					list:['xh_yingziyu'],
				},
				pangmenzuodao:{
					name:'旁门左道',
					order:15,
					list:['xh_yuxiaoke'],
				},
				qigongyifa:{
					name:'奇功异法',
					order:20,
					list:['xh_zhangnaipao','xh_xueli'],
				},
			},
			xh_zhangnaipao:{
				shourensuotuo:{
					name:'受人所托',
					order:22,
					list:['xh_jiaoyazi'],
				},
				menghuelang:{
					name:'猛虎恶狼',
					order:22,
					list:['xh_anjianwen'],
				},
				qigongyifa:{
					name:'奇功异法',
					order:23,
					list:['xh_xueli','xh_zhongpinliang'],
				},
			},
			xh_xueli:{
				linghanaoxue:{
					name:'凌寒傲雪',
					order:16,
					list:['xh_yangqiqi'],
				},
				kujinganlai:{
					name:'苦尽甘来',
					order:16,
					list:['xh_sunjingyi'],
				},
				qigongyifa:{
					name:'奇功异法',
					order:21,
					list:['xh_zhangnaipao','xh_zhongpinliang'],
				},
			},
			xh_ergoudan:{
				yihanyixia:{
					name:'一憨一黠',
					order:22,
					list:['xh_chenyushu'],
				},
				yanhanyumeng:{
					name:'言憨语萌',
					order:22,
					list:['xh_nicaiyue'],
				},
				gejuyifang:{
					name:'各据一方',
					order:23,
					list:['xh_anjianwen','xh_bingtang'],
				},
			},
			xh_anjianwen:{
				menghuelang:{
					name:'猛虎恶狼',
					order:16,
					list:['xh_zhangnaipao'],
				},
				mingzhengandou:{
					name:'明争暗斗',
					order:16,
					list:['xh_songlingshan'],
				},
				gejuyifang:{
					name:'各据一方',
					order:20,
					list:['xh_ergoudan','xh_bingtang'],
				},
			},
			xh_bingtang:{
				bingxueyuzhu:{
					name:'冰雪玉珠',
					order:15,
					list:['xh_sunjingyi'],
				},
				shenshikanke:{
					name:'身世坎坷',
					order:17,
					list:['xh_xushihan'],
				},
				gejuyifang:{
					name:'各据一方',
					order:21,
					list:['xh_ergoudan','xh_anjianwen'],
				},
			},

			xh_zhangliju:{
				yuanyuanfeiqian:{
					name:'渊源匪浅',
					order:22,
					list:['xh_shangguanlaner'],
				},
				danshenchuancheng:{
					name:'丹神传承',
					order:21,
					list:['xh_linyi'],
				},
				tiandaozhitu:{
					name:'天道之途',
					order:53,
					list:['xh_hanjingjing','xh_ningxuefei','xh_tianchan','xh_nicaiyue'],
				},
				yuanyuanchuancheng:{
					name:'渊源传承',
					order:32,
					list:['xh_duanmuyu'],
				},
				
			},
			xh_shangguanlaner:{
				yuanyuanfeiqian:{
					name:'渊源匪浅',
					order:22,
					list:['xh_zhangliju'],
				},
				hehubeizhi:{
					name:'呵护备至',
					order:21,
					list:['xh_shangguantianhua'],
				},
				biyuexiuhua:{
					name:'闭月羞花',
					order:28,
					list:['xh_wangxinyan','xh_chenxi'],
				},
				yidaitiannv:{
					name:'一代天女',
					order:40,
					list:['xh_duanmuyu','xh_lengleng'],
				},
			},
			xh_wangxinyan:{
				shienqingzhong:{
					name:'师恩情重',
					order:21,
					list:['xh_donghaishenni'],
				},
				tongmenjiemei:{
					name:'同门姐妹',
					order:22,
					list:['xh_huangxiaotao'],
				},
				biyuexiuhua:{
					name:'闭月羞花',
					order:29,
					list:['xh_shangguanlaner','xh_chenxi'],
				},
				huixinlingxing:{
					name:'慧心灵性',
					order:32,
					list:['xh_duanmuyu'],
				},
			},
			xh_duanmuyu:{
				yuanyuanchuancheng:{
					name:'渊源传承',
					order:22,
					list:['xh_zhangliju'],
				},
				huixinlingxing:{
					name:'慧心灵性',
					order:21,
					list:['xh_wangxinyan'],
				},
				tianzhijiaonv:{
					name:'天之骄女',
					order:27,
					list:['xh_lengleng'],
				},
				zongmentianjiao:{
					name:'宗门天骄',
					order:48,
					list:['xh_zhangliju','xh_shangguanlaner','xh_wangxinyan'],
				},
			},
			xh_lengleng:{
				jiaoxiaruochi:{
					name:'娇黠若痴',
					order:21,
					list:['xh_shangguanlaner'],
				},
				lingxinhuichi:{
					name:'灵心慧齿',
					order:24,
					list:['xh_hanjingjing','xh_ningxuefei'],
				},
				tianzhijiaonv:{
					name:'天之骄女',
					order:28,
					list:['xh_duanmuyu'],
				},
				tiandaojiaozi:{
					name:'天道娇子',
					order:48,
					list:['xh_zhangliju','xh_shangguanlaner','xh_wangxinyan'],
				},
			},
			xh_hanjingjing:{
				kejixiudao:{
					name:'科技修道',
					order:20,
					list:['xh_ningxuefei'],
				},
				daozhixiangzuo:{
					name:'道之相左',
					order:21,
					list:['xh_guidongxi'],
				},
				tiandaozhitu:{
					name:'天道之途',
					order:53,
					list:['xh_zhangliju','xh_ningxuefei','xh_tianchan','xh_nicaiyue'],
				},
			},
			xh_ningxuefei:{
				kejixiudao:{
					name:'科技修道',
					order:27,
					list:['xh_hanjingjing'],
				},
				xidaonvhuang:{
					name:'西岛女皇',
					order:29,
					list:['xh_ningshangling'],
				},
				tiandaozhitu:{
					name:'天道之途',
					order:53,
					list:['xh_zhangliju','xh_hanjingjing','xh_tianchan','xh_nicaiyue'],
				},
			},
			xh_tianchan:{
				cuoshigaotu:{
					name:'错失高徒',
					order:21,
					list:['xh_donghaishenni'],
				},
				qingyishuangxin:{
					name:'情义双馨',
					order:20,
					list:['xh_huoyudie'],
				},
				tiandaozhitu:{
					name:'天道之途',
					order:53,
					list:['xh_zhangliju','xh_hanjingjing','xh_ningxuefei','xh_nicaiyue'],
				},
			},
			xh_donghaishenni:{
				cuoshigaotu:{
					name:'错失高徒',
					order:20,
					list:['xh_tianchan'],
				},
				weizunquanzhong:{
					name:'位尊权重',
					order:21,
					list:['xh_gongyangjie'],
				},
				shienqingzhong:{
					name:'师恩情重',
					order:26,
					list:['xh_wangxinyan'],
				},
			},
			xh_huangxiaotao:{
				buweijianxie:{
					name:'不畏奸邪',
					order:20,
					list:['xh_xishanlaozong'],
				},
				tongmenjiemei:{
					name:'同门姐妹',
					order:22,
					list:['xh_wangxinyan'],
				},
				yunnizhibie:{
					name:'云泥之别',
					order:27,
					list:['xh_ningshangling','xh_gongyangjie'],
				},
			},
			xh_ningshangling:{
				wumingzhihuo:{
					name:'无名之火',
					order:20,
					list:['xh_kangzhaoming'],
				},
				xidaonvhuang:{
					name:'西岛女皇',
					order:20,
					list:['xh_ningxuefei'],
				},
				yunnizhibie:{
					name:'云泥之别',
					order:27,
					list:['xh_huangxiaotao','xh_gongyangjie'],
				},
			},
			xh_gongyangjie:{
				baolilengku:{
					name:'暴戾冷酷',
					order:26,
					list:['xh_chengyiyi'],
				},
				weizunquanzhong:{
					name:'位尊权重',
					order:29,
					list:['xh_donghaishenni'],
				},
				yunnizhibie:{
					name:'云泥之别',
					order:31,
					list:['xh_huangxiaotao','xh_ningshangling'],
				},
			},
			xh_shangguantianhua:{
				xincishouruan:{
					name:'心慈手软',
					order:19,
					list:['xulingchong'],
				},
				hehubeizhi:{
					name:'呵护备至',
					order:21,
					list:['xh_shangguanlaner'],
				},
				rencaibeichu:{
					name:'人才辈出',
					order:28,
					list:['xh_guidongxi','xh_huoyudie'],
				},
			},
			xh_guidongxi:{
				cuannizhichou:{
					name:'篡逆之仇',
					order:20,
					list:['xh_xinrenqinglong'],
				},
				daozhixiangzuo:{
					name:'道之相左',
					order:20,
					list:['xh_hanjingjing'],
				},
				rencaibeichu:{
					name:'人才辈出',
					order:27,
					list:['xh_shangguantianhua','xh_huoyudie'],
				},
			},
			xh_huoyudie:{
				qingyishuangxin:{
					name:'情义双馨',
					order:21,
					list:['xh_tianchan'],
				},
				qingyixiangcheng:{
					name:'情义相承',
					order:19,
					list:['xh_liuziyu'],
				},
				rencaibeichu:{
					name:'人才辈出',
					order:27,
					list:['xh_shangguantianhua','xh_guidongxi'],
				},
			},
			xh_nicaiyue:{
				mingwanbuling:{
					name:'冥顽不灵',
					order:15,
					list:['xh_xishanlaozong'],
				},
				yanhanyumeng:{
					name:'言憨语萌',
					order:16,
					list:['xh_ergoudan'],
				},
				tiandaozhitu:{
					name:'天道之途',
					order:53,
					list:['xh_zhangliju','xh_hanjingjing','xh_ningxuefei','xh_tianchan'],
				},
			},
			xh_chenxi:{
				fengcanhuajiao:{
					name:'风残花娇',
					order:15,
					list:['xh_chengyiyi'],
				},
				gangzhenjiaorou:{
					name:'刚贞娇柔',
					order:16,
					list:['xh_liuziyu'],
				},
				biyuexiuhua:{
					name:'闭月羞花',
					order:23,
					list:['xh_shangguanlaner','xh_wangxinyan'],
				},
			},
			xh_xishanlaozong:{
				buweijianxie:{
					name:'不畏奸邪',
					order:16,
					list:['xh_huangxiaotao'],
				},
				mingwanbuling:{
					name:'冥顽不灵',
					order:16,
					list:['xh_nicaiyue'],
				},
				ningezhitu:{
					name:'佞恶之徒',
					order:21,
					list:['xh_kangzhaoming','xh_chengyiyi'],
				},
			},
			xh_kangzhaoming:{
				wumingzhihuo:{
					name:'无名之火',
					order:17,
					list:['xh_ningshangling'],
				},
				renxingqinshou:{
					name:'人形禽兽',
					order:15,
					list:['xh_xinrenqinglong'],
				},
				ningezhitu:{
					name:'佞恶之徒',
					order:20,
					list:['xh_chengyiyi','xh_xishanlaozong'],
				},
			},
			xh_chengyiyi:{
				yidaijiaozi:{
					name:'一代骄子',
					order:22,
					list:['xh_gongyangjie'],
				},
				yinfuqizi:{
					name:'隐伏棋子',
					order:22,
					list:['xh_chenxi'],
				},
				geyoushouduan:{
					name:'各有手段',
					order:23,
					list:['xh_kangzhaoming','xh_xishanlaozong'],
				},
			},
			xh_xulingchong:{
				xincishouruan:{
					name:'心慈手软',
					order:22,
					list:['xh_shangguantianhua'],
				},
				yumenzhiyou:{
					name:'郁闷之友',
					order:22,
					list:['xh_yuxiaoke'],
				},
				geweiqizhu:{
					name:'各为其主',
					order:23,
					list:['xh_xinrenqinglong','xh_liuziyu'],
				},
			},
			xh_xinrenqinglong:{
				renxingqinshou:{
					name:'人形禽兽',
					order:15,
					list:['xh_kangzhaoming'],
				},
				cuannizhichou:{
					name:'篡逆之仇',
					order:17,
					list:['xh_guidongxi'],
				},
				geweiqizhu:{
					name:'各为其主',
					order:21,
					list:['xulingchong','xh_liuziyu'],
				},
			},
			xh_liuziyu:{
				gangzhenjiaorou:{
					name:'刚贞娇柔',
					order:15,
					list:['xh_chenxi'],
				},
				qingyixiangcheng:{
					name:'情义相承',
					order:17,
					list:['xh_huoyudie'],
				},
				geweiqizhu:{
					name:'各为其主',
					order:21,
					list:['xulingchong','xh_xinrenqinglong'],
				},
			},
		}
		// game.addMode('YB_chooseYuanfen',{
		// 	start:function(){
		// 		'step 0'
		// 		var dialog = ui.create.dialog('请选择至多五名武将组合出缘分');
		// 		var characters=_status.xhmgcCharacter;
		// 		var list = Object.keys(characters);
		// 		dialog.addSmall([list,'character']);

		// 	},
		// },{
		// 	translate: '缘分组合模拟器',
		// })
		lib.translate.YB_chooseYuanfen='组合缘分';

	}
}