import { lib, game, ui, get, ai, _status } from '../../../../noname.js';
export default cardData = function () {
	return (game.sgczkCardData = {
		character: {
			caocao: {},
			simayi: {},
			xiahoudun: {},
			zhangliao: {},
			xuchu: {},
			guojia: {},
			zhenji: {},
			dianwei: {},
			caopi: {},
			xuhuang: {},
			xunyu: {},
			xiahouyuan: {},
			zhanghe: {},
			caoren: {},
			dengai: {},

			liubei: {},
			guanyu: {},
			zhangfei: {},
			zhugeliang: {},
			zhaoyun: {},
			machao: {},
			huangyueying: {},
			huangzhong: {},
			weiyan: {},
			pangtong: {},
			liushan: {},
			menghuo: {},
			zhurong: {},
			jiangwei: {},

			sunquan: {},
			ganning: {},
			lvmeng: {},
			huanggai: {},
			zhouyu: {},
			daqiao: {},
			luxun: {},
			sunshangxiang: {},
			sunjian: {},
			sunce: {},
			xiaoqiao: {},
			zhoutai: {},
			taishici: {},
			lusu: {},
			zhangzhao: {},
			zhanghong: {},

			huatuo: {},
			lvbu: {},
			diaochan: {},
			zhangjiao: {},
			yuji: {},
			yuanshao: {},
			yanliang: {},
			wenchou: {},
			dongzhuo: {},
			jiaxu: {},
			pangde: {},
			caiwenji: {},
			zuoci: {},

			shen_guanyu: {},
			shen_lvmeng: {},
			shen_zhugeliang: {},
			shen_zhouyu: {},
			shen_caocao: {},
			shen_lvbu: {},
			shen_zhaoyun: {},
			shen_simayi: {},
		},
		card: {},
	});
};
