import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export {translate}

const translate = {  
	ybmjz_standard:'标包名将',
	ybmjz_caocao:'名将曹操',
	ybmjz_caocao_prefix:'名将',
	'ybmjz_jianxiong':'奸雄',
	'ybmjz_jianxiong_info':'当你受到伤害后，你可以获得对你造成伤害的牌并摸X张牌（X为本次伤害值且至少为一）。每局游戏限一次，当你以此法获得牌时，你可以展示并记录这些牌点数（重复点数不记录），然后若已记录点数不少于9个，你依次执行：①增加一点体力上限；②获得你武将牌上未生效的主公技；③修改【奸雄】。',
	'ybmjz_jianxiong_gai':'奸雄·改',
	'ybmjz_jianxiong_gai_info':'当你受到伤害后，你可以获得对你造成伤害的牌并摸X张牌（X为已损体力值且至少为一）。',
	'ybmjz_zhishuo':'执槊',
	'ybmjz_zhishuo_info':'主公技，以魏势力角色为来源弃置的牌进入弃牌堆时，其可以将之置于你的武将牌上成为“短歌行”；当魏势力角色使用或打出牌时，若“短歌行”中有与此牌花色相同的牌，你可以将所有与之花色相同的“短歌行”当做无次数限制的【杀】使用，且你令此【杀】伤害基数为此【杀】的实体牌数，此【杀】造成伤害后，你可令其回复本次伤害值的体力值；当你获得此技能时，你装备【衠钢槊】。',
	'ybmjz_hujia':'护驾',
	'ybmjz_hujia_info':'主公技，以魏势力角色为来源弃置的牌进入弃牌堆时，其可以将之置于你的武将牌上成为“短歌行”；当魏势力角色使用或打出牌时，若“短歌行”中有与此牌花色相同的牌，你可以将一张与之花色相同的“短歌行”交给其并摸一张牌；当你需要使用或打出一张【闪】时，你可以令其他魏势力角色选择是否打出一张【闪】。若有角色响应，则你视为使用或打出了一张【闪】。',
	ybmjz_simayi:'名将司马懿', 
	ybmjz_simayi_prefix:'名将', 
	'ybmjz_fankuix':'反馈',
	'ybmjz_fankuix_info':'每当你受到伤害一点后，你可以获得一名其他角色的一张牌，然后若选择的不是伤害来源，你弃置一张牌。',
	'ybmjz_fankui':'反馈',
	'ybmjz_fankui_info':'当你受到一点伤害后，你可以获得伤害来源一张牌，然后若来源手牌数大于你，你可再获得其一张牌。',
	'ybmjz_guicai':'鬼才',
	'ybmjz_guicai_info':'在任意角色的判定牌生效前，你可以打出一张牌代替之；每回合每种花色限一次，当你的手牌进入弃牌堆时，你可以摸一张牌。',//，然后此次判定结果不能再被修改
	ybmjz_xiahoudun:'名将夏侯惇', 
	ybmjz_xiahoudun_prefix:'名将', 
	'ybmjz_ganglie':'刚烈',
	'ybmjz_ganglie_info':'当你受到1点伤害后，你可进行判定，若结果为：红色，你对伤害来源造成1点伤害；黑色，你弃置伤害来源一张牌。然后你可以弃置一张与判定牌同颜色的牌再执行一次。',
	'ybmjz_gangliex':'刚烈',
	'ybmjz_gangliex_info':'当你受到1点伤害后，你可进行判定，若结果为：红色，你对伤害来源造成1点伤害；黑色，你弃置伤害来源一张牌。然后你可将判定牌置于其武将牌上。（当你弃置其牌后，若其武将牌上有红色刚烈牌，你弃置其中一张红色刚烈牌，对其造成一点伤害；当你对其造成伤害后，若其武将牌上有黑色刚烈牌，你弃置其中一张黑色刚烈牌，然后弃置其一张牌）。',
	'ybmjz_gangliey':'刚烈',
	'ybmjz_gangliey_info':'当你受到1点伤害后，你可进行判定，若结果为：红色，你对伤害来源造成1点伤害；黑色，你弃置伤害来源一张牌。然后你可将判定牌置于其武将牌上。然后若其武将牌上刚烈牌集齐黑红两种颜色，你获得其一黑一红两张刚烈牌对其造成两点伤害。每个回合结束时，你获得当前回合角色的刚烈牌，然后回复其中红色牌数的体力，摸其中黑色牌数的牌。',
	'ybmjz_qingjian':'清俭',
	'ybmjz_qingjian_info':'',
	ybmjz_zhangliao:'名将张辽', 
	ybmjz_zhangliao_prefix:'名将', 
	'ybmjz_tuxi':'突袭',
	'ybmjz_tuxi_info':'出牌阶段开始时，你可以弃置一张牌，并选择等量有手牌的其他角色，展示并获得他们各一张牌，若你弃置的牌花色包含此牌花色，你对其造成一点伤害。',
	ybmjz_xuzhu:'名将许褚', 
	ybmjz_xuzhu_prefix:'名将',
	'ybmjz_luoyi':'裸衣',
	'ybmjz_luoyi_info':'出牌阶段开始时，你可以弃置一张牌，然后摸两张牌并展示之，若你弃置的牌或摸到的牌包含：装备牌，直到下回合开始，你使用【杀】或【决斗】造成的伤害+1；基本牌：本回合使用【杀】次数+1；锦囊牌，本回合使用【杀】无距离限制。',
	ybmjz_guojia:'名将郭嘉', 
	ybmjz_guojia_prefix:'名将', 
	ybmjz_zhenji:'名将甄姬', 
	ybmjz_zhenji_prefix:'名将', 

	ybmjz_liubei:'名将刘备', 
	ybmjz_liubei_prefix:'名将', 
	ybmjz_guanyu:'名将关羽',
	ybmjz_guanyu_prefix:'名将',
	ybmjz_zhangfei:'名将张飞',
	ybmjz_zhangfei_prefix:'名将',
	ybmjz_zhugeliang:'名将诸葛亮',
	ybmjz_zhugeliang_prefix:'名将',
	ybmjz_zhaoyun:'名将赵云',
	ybmjz_zhaoyun_prefix:'名将',
	ybmjz_machao:'名将马超',
	ybmjz_machao_prefix:'名将',
	ybmjz_huangyueying:'名将黄月英',
	ybmjz_huangyueying_prefix:'名将',

	ybmjz_sunquan:'名将孙权',
	ybmjz_sunquan_prefix:'名将',
	ybmjz_ganning:'名将甘宁',
	ybmjz_ganning_prefix:'名将',
	ybmjz_lvmeng:'名将吕蒙',
	ybmjz_lvmeng_prefix:'名将',
	ybmjz_huanggai:'名将黄盖',
	ybmjz_huanggai_prefix:'名将',
	ybmjz_zhouyu:'名将周瑜',
	ybmjz_zhouyu_prefix:'名将',
	ybmjz_daqiao:'名将大乔',
	ybmjz_daqiao_prefix:'名将',
	ybmjz_luxun:'名将陆逊',
	ybmjz_luxun_prefix:'名将',
	ybmjz_sunshangxiang:'名将孙尚香',
	ybmjz_sunshangxiang_prefix:'名将',

	ybmjz_huatuo:'名将华佗',
	ybmjz_huatuo_prefix:'名将',
	ybmjz_lvbu:'名将吕布',
	ybmjz_lvbu_prefix:'名将',
	ybmjz_diaochan:'名将貂蝉',
	ybmjz_diaochan_prefix:'名将',
	//----------------------装备及其他


	
	ybmjz_zhangqiying:'名将张琪瑛',
	ybmjz_zhangqiying_prefix:'名将',
	ybmjz_shen_zhugeliang:'名将神诸葛亮',
	ybmjz_shen_zhugeliang_prefix:'名将神',
	ybmjz_hina:'名将佐藤雏',
	ybmjz_hina_prefix:'名将',
	ybmjz_kotori:'名将神户小鸟',
	ybmjz_kotori_prefix:'名将',
	ybmjz_kagari:'名将篝',
	ybmjz_kagari_prefix:'名将',
	ybmjz_majun:'名将马钧',
	ybmjz_majun_prefix:'名将',
	ybmjz_youta:'名将成神阳太',
	ybmjz_youta_prefix:'名将',
	'ybmjz_fengshen':'逢神',
	'ybmjz_fengshen_info':'锁定技，游戏开始时，若你没有副将，且佐藤雏不在场上，你失去一点体力上限并将佐藤雏作为自己的副将。',
	'ybmjz_yingshen':'应神',
	'ybmjz_yingshen_info':'你可以助战自己；当有角色询问助战应变时，你可以交换主副将，视为响应之。（若已发动唤神，则不交换主副将）',
	'ybmjz_huanshen':'唤神',
	'ybmjz_huanshen_info':'神势力技，限定技，当有角色于回合外进入濒死状态时，你可以交换主副将，令其回复体力至1。',
	// 'ybmjz_yingshen':'应神',
	// 'ybmjz_yingshen_info':'当有角色询问助战应变时，你可以将势力改为神，视为响应之。（若已发动唤神，则不更改势力）',
	// 'ybmjz_huanshen':'唤神',
	// 'ybmjz_huanshen_info':'神势力技，限定技，当有角色于回合外进入濒死状态时，你可以交换主副将（若没有副将，则武将牌改为成神阳太），令其回复体力至1。',
}